
<script>
$(document).ready(function(){

    $(".close-modal").on('click',function(){
       location.reload();
    });

    $("#form-edit").validate({     
            rules:{
                // year:{
                // required:true
                // },
                // name:{
                // required:true
                // }
            },
            errorClass: "help-inline",
            errorElement: "span",
            highlight:function(element, errorClass, validClass) {
                $(element).parents('.control-group').addClass('error');
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').removeClass('error');
                $(element).parents('.control-group').addClass('success');
            },
            messages: {
                //cus_cellphone: "Vui lòng nhập số điện thoại !",
                // cus_identity_card: "Vui lòng nhập số CMND !",
                // year: "Vui lòng nhập năm !",
                // name: "Vui lòng nhập tên phí !",
            },
            submitHandler: function(form,e) {
                console.log('Form submitted');
                $.ajax({
                      type: "POST",
                      url: "<?php echo $this->BaseUrl?>/default/organization/update/",
                      data: $('#form-edit').serialize() ,
                      cache: false,
                      success: function(html)
                      {   
                        $("#form-edit").html('');
                        $("#message").html("Cập nhật thành công"); 
                        
                        //$(".close-modal").hide();  
                                                                               
                      }
                });
                return false;                       
            }
        });
});  

</script>


<form id="form-edit" class="form-horizontal">
<p id="message"></p>
<input type="hidden" name="organ_detail_id" id="organ_detail_id" value="<?php echo $this->organdetail['organ_detail_id']; ?>" />

<div class="control-group">
    <label class="control-label">Tên TCHN:</label>
    <div class="controls">
        <input type="text" name="organ_name" id="organ_name" class="span3" value="<?php echo $this->organdetail['organ_name']; ?>">
    </div>
</div> 

<div class="control-group">        
    <label class="control-label">Số CNHN:</label>
    <div class="controls">
    <input type="text" name="organ_certification" id="organ_certification" value="<?php echo $this->organdetail['organ_certification']; ?>" class="span3" placeholder="Vui lòng nhập số CNHN" />
    </div>
</div>

<div class="control-group">        
    <label class="control-label">Số điện thoại:</label>
    <div class="controls">
    <input type="text" name="organ_mobile" id="organ_mobile" value="<?php echo $this->organdetail['organ_mobile']; ?>" class="span3" placeholder="Vui lòng nhập số điện thoại" />
    </div>
</div>

<div class="control-group">        
    <label class="control-label">Địa chỉ VP:</label>
    <div class="controls">
    <textarea rows="5" name="law_organ_address" id="law_organ_address" class="span3" placeholder="Vui lòng nhập địa chỉ VP" ><?php echo $this->organdetail['law_organ_address']; ?></textarea>
    </div>
</div>

<div class="control-group">        
    <label class="control-label">Địa chỉ HKTT:</label>
    <div class="controls">
    <textarea rows="5" name="law_organ_address_hktt" id="law_organ_address_hktt" class="span3" placeholder="Vui lòng nhập địa chỉ VP"><?php echo $this->organdetail['law_organ_address_hktt']; ?></textarea>
    </div>
</div>

<div class="control-group">        
    <label class="control-label">Thông tin thay đổi:</label>
    <div class="controls">
    <textarea rows="5" name="thongtin_thaydoi" id="thongtin_thaydoi" class="span3" placeholder="Vui lòng nhập thông tin thay đổi" ><?php echo $this->organdetail['thongtin_thaydoi']; ?></textarea>
    </div>
</div>
<div class="control-group">        
    <label class="control-label">Ngày cập nhật:</label>
    <div class="controls">
    <textarea rows="5" name="ngaycapnhat" id="ngaycapnhat" class="span3" placeholder="Vui lòng nhập thông tin thay đổi" ><?php echo $this->organdetail['ngaycapnhat']; ?></textarea>
    </div>
</div>
<!-- <div class="control-group">        
<label class="control-label">Ngày đóng phí:</label>
<div class="controls">
<input type="text" name="baseondocument" id="baseondocument" value="<?php echo $this->categoryfee['baseondocument']; ?>" class="span3" placeholder="Vui lòng nhập số văn bản" />
</div>
</div>    -->

<!-- <label class="control-label">Trạng thái phí</label>
<div class="controls">
    <div class="row-fluid">
        <div class="span3">
        <label>                            
            <input type="radio" name="status" value="1" <?php echo ($this->categoryfee['status'] == 1) ? 'checked' :'' ?>/>
    Hoạt động</label>
        </div>
        <div class="span6">
            <label>
            <input type="radio" name="status" value="0" <?php echo ($this->categoryfee['status'] == 0) ? 'checked' :'' ?>/>
            Ngưng hoạt động</label> 
        </div>
    </div>                                               
</div>  -->



<!-- <div class="form-actions"> -->
<button style="float: right;" type="submit" class="btn">Lưu</button>
<!-- </div> -->
</form>
         


