<script>
$(document).ready(function(){
    
	$('input[type=checkbox],input[type=radio],input[type=file]').uniform();
  
  $('select').select2();
    var date = new Date();
    var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());

    $('.datepicker').datepicker(   
      'setValue', today
    );

      $("#search").hide();
  $(".searchfield").hide();
    
    $(".message-success").hide();

    $("#model-warning").modal('hide');

   $("#customer_form").validate({     
          rules:{
            law_name:{
              required:true
            },
            law_birthday:{
              required:true
            },
            organ_law_id:{
              required:true
            },
            law_nation:{
              required:true
            },
            law_certification:{
              required:true
            },
            law_certification_date:{
              required:true
            },
            law_joining_organ_date:{
              required:true
            }
          },
          errorClass: "help-inline",
          errorElement: "span",
          highlight:function(element, errorClass, validClass) {
            $(element).parents('.control-group').addClass('error');
          },
          unhighlight: function(element, errorClass, validClass) {
            $(element).parents('.control-group').removeClass('error');
            $(element).parents('.control-group').addClass('success');
          },
          messages: {
            law_name: "Nhập tên LS !",
            law_nation: "Nhập quốc tịch!",
            law_certification: "Nhập số chứng chỉ LS !"          
          },
          submitHandler: function(form,e) {
             console.log('Form submitted');
              $.ajax({
                  type: "POST",
                  url: "<?php echo $this->BaseUrl?>/default/organization/addlawyer/",
                  data: $('#customer_form').serialize() ,
                  cache: false,
                  success: function(html)
                  {   
                    //alert(html);
                    $("#message").html(html);
                    $("#model-warning").modal("show");
                    $(".message-success").show();
                                
                  }
            });
            return false;                       
        }
	});

    $("#cus_cellphone").keyup(function() {
           //alert($("#cus_cellphone").val()); 
           $(".message-success").hide();  
          
           if($("#cus_cellphone").val() != '' && $("#cus_cellphone").val() != null && $("#cus_cellphone").val() != undefined && isNumber($("#cus_cellphone").val())){
            if($.trim($("#cus_cellphone").val()) != '' && $.trim($("#cus_cellphone").val()) != null){
   
                var dataString = '?type='+ 'phone' +'&data='+$.trim($("#cus_cellphone").val());
                $.ajax({
                      type: "GET",
                      url: "<?php echo $this->BaseUrl?>/default/customers/validate"+dataString ,
                      dataType: 'json',
                      cache: false,
                      success: function(data)
                      {         
                        if(data != null){
                          //alert("Số điện thoại đã tồn tại. Vui lòng nhập số khác");
                          // $("#message").html("Số điện thoại đã tồn tại. Vui lòng nhập số khác");
                          // $("#model-warning").modal("show");    
                          // $("#cus_cellphone").val(''); 
                        }                       
                                 
                      }, error: function(msg){ 
                        
                      }           
                });
              // }
            }   
           }                 
    });

    $("form input[type=submit]").click(function() {
        $("input[type=submit]", $(this).parents("form")).removeAttr("clicked");
        $(this).attr("clicked", "true");
    });

    $("#cus_username").keyup(function() {
                      
            if($("#cus_username").val() != '' && $.trim($("#cus_username").val()) != null){
   
                var dataString = '?type='+ 'username' +'&data='+$.trim($("#cus_username").val());
                $.ajax({
                      type: "GET",
                      url: "<?php echo $this->BaseUrl?>/default/customers/validate"+dataString ,
                      dataType: 'json',
                      cache: false,
                      success: function(data)
                      {        
                        
                        if(data != null && data >0){
                          // $("#message").html("Tên đăng nhập đã tồn tại. Vui lòng nhập tên đăng nhập khác");
                          // $("#model-warning").modal("show");
                          // $("#cus_username").val(''); 
                        }                         
                                 
                      }, error: function(msg){ 
                        
                      }           
                });
              // }
            }   
                            
    });

  function isNumber(n) {
    return !isNaN(parseFloat(n)) && isFinite(n);
  }

  $(function () {
    $(":file").change(function () {
        if (this.files && this.files[0]) {
            var reader = new FileReader();
            reader.onload = imageIsLoaded;
            reader.readAsDataURL(this.files[0]);
        }
    });
});

function imageIsLoaded(e) {
    $('#image-review').attr('src', e.target.result);
};

});

   

</script>

<div id="model-warning" class="modal fade"  data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <p id="message">Trong hệ thống đã tồn tại luật sư,hệ thống sẽ tải thông tin để bạn đăng kí tập sự.</p>
          
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>

<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i></a> <a href="#" class="current">Thêm mới thông tin tổ chức và hoạt động</a> </div>
    <!-- <h1>Quản lý luật sư</h1> -->
  </div>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="alert alert-success alert-dismissible message-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Thông báo</strong> Bạn đã tạo thành công tổ chức và hoạt động.
      </div>	
    </div>  	 

    <div class="row-fluid">	  	
      <div class="span12">		 
        <div class="widget-box">
            <div class="widget-title">
              <span class="icon">
                <i class="icon-th-list"></i>
              </span>
              <h5>Thông tin quản lý tổ chức hoạt động luật sư</h5>
            </div>
            
            <div class="widget-content nopadding"> 
            <!-- <p>test code </p> -->
            <form id="customer_form" method="post" novalidate="novalidate">
              <div class="row-fluid form-horizontal">
                
                    
                    <div class="span6">
                        <!-- <input type="hidden" id="submittype" name="submittype" /> -->
                        
                        <div class="control-group">
                              <label class="control-label">Chọn tổ chức luật sư *:</label>
                                <div class="controls">                                
                                  <select class="span8" id="organ_detail_id" name="organ_detail_id">
                                  <?php  
                                      foreach ($this->organizations as $org) {
                                          echo '<option value="'.$org['organ_detail_id'].'" class="span8">'.$org['organ_name'].'</option>';
                                      }
                                      ?>    
                                  </select>
                              </div>
                        </div>                 
                        
                        <div class="control-group">
                          <label class="control-label">Tên LS * :</label>
                          <div class="controls">
                            <input type="text" name="law_name" id="law_name" class="span8" placeholder="Nhập tên LS" />
                          </div>
                        </div>

                       <div class="control-group">
                        <label class="control-label">Ngày cấp số chứng chỉ LS * :</label>
                        <div class="controls">
                            <!-- <input type="text" class="span8" id="cus_identity_date" name="cus_identity_date" placeholder="Company name" /> -->
                            <div  data-date="12-02-2012" class="input-append date datepicker">
                              <input type="text" id="law_birthday" name="law_birthday" data-date-format="dd-mm-yyyy" class="span11" placeholder="Vui lòng chọn ngày cấp" >
                              <span class="add-on"><i class="icon-th"></i></span> 
                            </div>
                        </div>
                      </div>  

                      
                        <div class="control-group">
                          <label class="control-label">Quốc tịch * :</label>
                          <div class="controls">
                            <input type="text" name="law_nation" id="law_nation" class="span8" placeholder="Nhập quốc tịch" />
                          </div>
                        </div>

                                            

                    </div>  
                    <div class="span6">

                      <div class="control-group">
                          <label class="control-label">Số chứng chỉ LS * :</label>
                          <div class="controls">
                            <input type="number" name="law_certification" id="law_certification" class="span6" placeholder="Nhập số chứng chỉ LS" />
                          </div>
                        </div>   
                        
                        <div class="control-group">
                        <label class="control-label">Ngày cấp số chứng chỉ LS * :</label>
                        <div class="controls">
                            <!-- <input type="text" class="span8" id="cus_identity_date" name="cus_identity_date" placeholder="Company name" /> -->
                            <div  data-date="12-02-2012" class="input-append date datepicker">
                              <input type="text" id="law_certification_date" name="law_certification_date" data-date-format="dd-mm-yyyy" class="span11" placeholder="Vui lòng chọn ngày cấp" >
                              <span class="add-on"><i class="icon-th"></i></span> 
                            </div>
                        </div>
                      </div>  

                        <div class="control-group">
                        <label class="control-label">Ngày gia nhập tổ chức luật sư * :</label>
                        <div class="controls">
                            <!-- <input type="text" class="span8" id="cus_identity_date" name="cus_identity_date" placeholder="Company name" /> -->
                            <div  data-date="12-02-2012" class="input-append date datepicker">
                              <input type="text" id="law_joining_organ_date" name="law_joining_organ_date" data-date-format="dd-mm-yyyy" class="span11" placeholder="Vui lòng chọn ngày cấp" >
                              <span class="add-on"><i class="icon-th"></i></span> 
                            </div>
                        </div>
                      </div>               
                       
                    </div>  
               	  
              </div>
              <div class="row-fluid">
                    <div class="form-actions">
                              <div class="span4" >
                              </div>
                              <div class="span6">	       
                                  <button type="submit" id="sumit" class="btn ">Thêm mới</button>                           
                              </div>
                              <div class="span2" >
                              </div>
                            </div>  
                    </div>
              </div>  
              </form>
            </div>
        </div>
        
    </div>
  </div>  
</div>
