<script>
    $(document).ready(function(){
    //   $("#search").hide();
      $("#model-warning").modal("hide");
      $(".message-success").hide(); 
      $('.datepicker').datepicker(
        {
          orientation: 'bottom',
          autoclose : true,
          //format : 'yy-mm-dd'
        } 
      );

    //   $("#notification").html("Thông báo : Số tiền bạn đóng phí thành viên là ")

      var regis_date = '';

      $('#dp5').datepicker()
      .on('changeDate', function(ev){
        console.log("tesst code");
          console.log(ev.date.valueOf());
          console.log($("#dp5").val());
          regis_date = ev.date.valueOf();        
      });    


    $("#search-global").keyup(function() {        
        $("#cus_id").val('');
        var searchbox = $(this).val();
        var dataString = 'searchword='+ searchbox + '&searchfield='+$("#search-field").val();
        
        if(searchbox ==''){
            $("#display-content-search-global").html('');
        } else
        {
            $.ajax({
                type: "POST",
                url: "<?php echo $this->BaseUrl?>/default/customers/search/",
                data: dataString,
                cache: false,
                success: function(html)
                {   
                  //$("#display-content-search-global").html('');
                  $("#display-content-search-global").html(html);                  
                }
            });
        }
        return false;    
    });  

     $("#form-edit").validate({     
            rules:{
                currentPass:{
                  required:true
                },
                password:{
                  required:true
                },
                password2: {
                  equalTo: "#password"
                }
            },
            errorClass: "help-inline",
            errorElement: "span",
            highlight:function(element, errorClass, validClass) {
                $(element).parents('.control-group').addClass('error');
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').removeClass('error');
                $(element).parents('.control-group').addClass('success');
            },
            messages: {
                currentPass: "Vui lòng nhập mật khẩu hiện tại",
                password: "Vui lòng nhập mật khẩu mới",
				        password2: { equalTo: "Mật khẩu không khớp" },
            },
            submitHandler: function(form,e) {
                console.log('Form submitted');
                $.ajax({
                      type: "POST",
                      url: "<?php echo $this->BaseUrl?>/default/customers/updatepasswordcustomer/",
                      data: $('#form-edit').serialize() ,
                      cache: false,
                      success: function(html)
                      {   
                        //alert(html);
                        $("#notify").html(html);
                        $("#model-warning").modal('show');
                        //$("#message").html("Đổi mật khẩu thành công"); 
                        //$(".close-modal").hide();  
                                                                               
                      }
                });
                return false;                       
            }
        });

     $('#display-content-search-global').on('click', function(event) {
      console.log("action event");
      var id = $(event.target).attr('id');
      var value = $("#"+id).val();
      var dataString = '?searchword='+ id;
       $.ajax({
            type: "GET",
            url: "<?php echo $this->BaseUrl?>/default/customers/detail"+dataString ,
            //data: dataString+'?format=html',
            dataType: 'json',
            cache: false,
            success: function(data)
            {   
 
              if(data.cus_id != null && data.cus_id != undefined){
                     $("#cus_id").val(data.cus_id);                     
                     $('#display-content-search-global').html('');
                     //$("#search-global").val(data.cus_identity_card);
                     if($("#search-field").val() != null && $("#search-field").val() == "name"){
                      $("#search-global").val(data.cus_fullname);
                     }else if($("#search-field").val() != null && $("#search-field").val() == "lawyer_number"){
                      $("#search-global").val(data.cus_lawyer_number);
                     }else if($("#search-field").val() != null && $("#search-field").val() == "identity_card"){
                      $("#search-global").val(data.cus_identity_card);
                     }else{
                      $("#search-global").val(data.cus_cellphone);
                     }

                     $("#cus_cellphone").val(data.cus_cellphone);
                     $("#cus_firstname").val(data.cus_firstname);
                     $("#cus_lastname").val(data.cus_lastname);
                     $("#cus_identity_card").val(data.cus_identity_card);
                     $("#cus_username").val(data.cus_username);
                     $("#cus_birthday").val(data.cus_birthday);
                     $("#cus_country").val(data.cus_country);
                     $("#passwordold").val(data.cus_password);
                     
              
              }
              //console.log(data);             
            }, error: function(msg){               
            }           
            });
    });
    

 });

  function isNumber(n) {
    return !isNaN(parseFloat(n)) && isFinite(n);
  }

//   function loadDataForTab($cus_id,$div_content,$typetab){ 
//         var dataString = '?cus_id='+ $cus_id;        
//         if(cus_id =='' || cus_id == undefined){
//             $("#table-lawyer").html('');
//         } else
//         {
//             var url = "<?php echo $this->BaseUrl?>/default/fee/list"+dataString;

//             $.ajax({
//                 type: "GET",
//                 url: url,
//                 //data: dataString,
//                 //dataType: 'json',
//                 cache: false,
//                 success: function(html)
//                 {   
//                   //alert(html);
//                   $($div_content).html(html);                  
//                 }
//             });
//         }
//  return false;   
// }

  // function updatePass($id,$pass){  
  //     $("#user_id").val($id);
  //     $("#passwordold").val($pass);
  //     $("#model-warning").modal('show');     
  // }

</script>


 <div id="content">
    <div id="content-header">
      <div id="breadcrumb"> <a href="" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i></a> <a href="#" class="current">Đổi mật khẩu luật sư</a> </div>
      <!-- <h1>Quản lý luật sư</h1> -->
    </div>
   <div class="container-fluid"> 
   <div class="row-fluid">
      <div class="alert alert-success alert-dismissible message-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <strong>Thông báo</strong> Bạn đã cập nhật mật khẩu thành công.
        </div>
    </div>   
    <!-- <h4>Thêm mới luật sư tập sự</h4> -->
    <div class="row-fluid">     
        <!-- open div general information-->
        <div class="span12">          
          <div class="widget-box">
            <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
              <h5>Thông tin chung</h5>
            </div>
            <div class="widget-content nopadding" id="detail-information">
            <!--start form-->              
                <div class="row-fluid form-horizontal">
                  <div class="span6">
                      <label class="control-label">Họ và lót :</label>
                        <div class="controls">
                          <input type="text" disabled id="cus_firstname"  name="cus_firstname" class="span8" placeholder="Họ của luật sư" />
                        </div>  
                        <label class="control-label">Tên :</label>
                        <div class="controls">
                          <input type="text" disabled id="cus_lastname"  name="cus_lastname" class="span8" placeholder="Tên của luật sư" />
                        </div>   
                        <label class="control-label">Ngày sinh :</label>
                        <div class="controls">
                          <input type="text" disabled id="cus_birthday"  name="cus_birthday" class="span8" placeholder="Ngày sinh" />
                        </div>  
                      
                      <!-- <label class="control-label">Tên đăng nhập:</label>
                        <div class="controls">
                          <input type="text" id="cus_username"  name="cus_username" class="span8" placeholder="Nhập số điện thoại để tìm luật sư" />
                      </div>                                      -->
                  </div>  
                  <div class="span6">
                    <label class="control-label">Số điện thoại :</label>
                      <div class="controls">
                        <input type="text" disabled id="cus_cellphone"  name="cus_cellphone" class="span8" placeholder="Số điện thoại" />
                      </div> 
                      <label class="control-label">Số chứng minh nhân dân :</label>
                      <div class="controls">
                        <input type="text" disabled id="cus_identity_card"  name="cus_identity_card" class="span8" placeholder="Số chứng minh nhân dân" />
                      </div>  
                      <!-- <label class="control-label">Tỉnh thành :</label>
                      <div class="controls">
                        <input type="text" id="cus_country"  name="cus_country" class="span8" placeholder="Tỉnh thành" />
                      </div>                   -->
                  </div>                  
                </div>            
              <!-- end form -->
            </div>          
          </div>
        </div>   
      </div> 


    <div class="row-fluid">     
        <!-- open div general information-->
        <div class="span12">          
          <div class="widget-box">
            <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
              <h5>Đổi mật khẩu</h5>
            </div>
            <div class="widget-content nopadding" id="detail-information">
            <!--start form-->              
                <div class="row-fluid form-horizontal">
                <form id="form-edit" class="form-horizontal">
                    <p id="message"><?php echo $this->parError; ?></p>
                    <input type="hidden" name="cus_id" id="cus_id"/> 
                    <input type="hidden" name="passwordold" id="passwordold" /> 
               
                    <div class="control-group">
                          <label class="control-label">Nhập mật khẩu hiện tại:</label>
                          <div class="controls">
                              <input type="password" id="currentPass" name="currentPass">
                          </div>
                    </div>

                    <div class="control-group">        
                          <label class="control-label">Nhập mật khẩu mới:</label>
                          <div class="controls">
                            <input id="password" type="password" name="password" />
                          </div>
                      </div> 

                    <div class="control-group">        
                        <label class="control-label">Nhập mật khẩu mới:</label>
                        <div class="controls">
                        <input id="password2" type="password" name="password2" />
                        </div>
                    </div> 
                              
                    <div class="form-actions">
                      <button style="float: right;" type="submit" class="btn">Lưu</button>
                    </div>
                  </form>
                </div>            
              <!-- end form -->
            </div>          
          </div>
        </div>   
      </div>            
      </div>     
    </div>    
    </div>
      <!--end div-->   
      <!--open div--> 
   
    </div>  
  </div>
  
 
<!-- </div> -->

<!-- Modal -->
<div id="model-warning" class="modal fade" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p id="notify"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button>  -->
      </div>
    </div>
  </div>
</div>