
<script>
$(document).ready(function(){

    $(".close-modal").on('click',function(){
       location.reload();
    });

    $("#form-edit").validate({     
            rules:{
                // law_code:{
                // required:true
                // },
                // law_certfication_no:{
                // required:true
                // }
            },
            errorClass: "help-inline",
            errorElement: "span",
            highlight:function(element, errorClass, validClass) {
                $(element).parents('.control-group').addClass('error');
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').removeClass('error');
                $(element).parents('.control-group').addClass('success');
            },
            messages: {
                //cus_cellphone: "Vui lòng nhập số điện thoại !",
                // cus_identity_card: "Vui lòng nhập số CMND !",
                law_code: "Vui lòng nhập mã luật sư !",
                law_certfication_no: "Vui lòng nhập số chứng chỉ !",
            },
            submitHandler: function(form,e) {
                console.log('Form submitted');
                $.ajax({
                      type: "POST",
                      url: "<?php echo $this->BaseUrl?>/default/customers/updaterewarddiscipline/",
                      data: $('#form-edit').serialize() ,
                      cache: false,
                      success: function(html)
                      {   
                        $("#message").html("Chỉnh sửa thông tin khen thưởng kỉ luật thành công"); 
                        //$(".close-modal").hide();  
                                                                               
                      }
                });
                return false;                       
            }
        });
});  

</script>


<form id="form-edit" class="form-horizontal">
             <h4> Chỉnh sửa khen thưởng kỉ luật </h3>
              <p id="message"></p>
              <!-- <input type="hidden" name="startedmonth" id="startedmonth" value="<?php echo $this->paymentlawyerofflinedata['startedmonth']; ?>" />
              <input type="hidden" name="endmonth" id="endmonth" value="<?php echo $this->paymentlawyerofflinedata['endmonth']; ?>" />
              <input type="hidden" name="cus_id" id="cus_id" value="<?php echo $this->paymentlawyerofflinedata['cus_id']; ?>" />
              <input type="hidden" name="payment_lawyer_off_id" value="<?php echo $this->paymentlawyerofflinedata['payment_lawyer_off_id']; ?>" />  -->
              <input type="hidden" name="id" id="id" value="<?php echo $this->data['id']; ?>" />
              <input type="hidden" name="type" id="type" value="<?php echo $this->data['type']; ?>" />
              <?php if($this->data['type'] == "khenthuong"): ?>
                <div class="control-group">
                        <label class="control-label">Tên luật sư: </label>
                        <div class="controls">
                            <input type="text" disabled class="span2" value="<?php echo $this->data['cus_firstname']." ".$this->data['cus_lastname']; ?>">
                        </div>
                </div> 

                <div class="control-group">        
                    <label class="control-label">Loại :</label>
                    <div class="controls">
                    <input type="text" disabled value="Khen thưởng" class="span3" placeholder="" />
                    </div>
                </div>

                <div class="control-group">        
                    <label class="control-label">Lý do:</label>
                    <div class="controls">
                    <input type="text" name="reward_reason" value="<?php echo $this->data['reward_reason']; ?>" class="span3" placeholder="Vui lòng nhập lý do" />
                    </div>
                </div>

                <div class="control-group">        
                    <label class="control-label">Năm :</label>
                    <div class="controls">
                    <input type="text" name="year"  value="<?php echo $this->data['year']; ?>" class="span3" placeholder="Vui lòng nhập số năm" />
                    </div>
                </div>   

                <div class="control-group">        
                    <label class="control-label">Văn bản:</label>
                    <div class="controls">
                    <input type="text" name="cus_reward_document" value="<?php echo $this->data['cus_reward_document']; ?>" class="span3" placeholder="Vui lòng nhập văn bản" />
                    </div>
                </div>         
               
              <?php else:  ?>     
                    <div class="control-group">
                            <label class="control-label">Tên luật sư: </label>
                            <div class="controls">
                                <input type="text" disabled class="span2" value="<?php echo $this->data['cus_firstname']." ".$this->data['cus_lastname']; ?>">
                            </div>
                    </div> 

                    <div class="control-group">        
                        <label class="control-label">Loại :</label>
                        <div class="controls">
                        <input type="text" disabled value="Kỉ luật" class="span3" placeholder="" />
                        </div>
                    </div>

                    <div class="control-group">        
                        <label class="control-label">Lý do:</label>
                        <div class="controls">
                        <input type="text" name="discipline_reason" value="<?php echo $this->data['discipline_reason']; ?>" class="span3" placeholder="Vui lòng nhập lý do" />
                        </div>
                    </div>

                    <div class="control-group">        
                        <label class="control-label">Năm :</label>
                        <div class="controls">
                        <input type="text" name="year"  value="<?php echo $this->data['year']; ?>" class="span3" placeholder="Vui lòng nhập số năm" />
                        </div>
                    </div>   

                    <div class="control-group">        
                        <label class="control-label">Văn bản:</label>
                        <div class="controls">
                        <input type="text" name="cus_reward_discipline_document" value="<?php echo $this->data['cus_reward_discipline_document']; ?>" class="span3" placeholder="Vui lòng nhập văn bản" />
                        </div>
                    </div>  

                    <div class="control-group">        
                        <label class="control-label">Người khiếu nại :</label>
                        <div class="controls">
                        <input type="text" name="people_problem"  value="<?php echo $this->data['people_problem']; ?>" class="span3" placeholder="Vui lòng nhập người khiếu nại" />
                        </div>
                    </div>   

                    <div class="control-group">        
                        <label class="control-label">Người thụ lý:</label>
                        <div class="controls">
                        <input type="text" name="law_help" value="<?php echo $this->data['law_help']; ?>" class="span3" placeholder="Vui lòng nhập người thụ lý" />
                        </div>
                    </div>     
            
                   

              <?php endif;  ?>      
              <!-- <div class="form-actions"> -->
                <button style="float: right;" type="submit" class="btn">Lưu</button>
              <!-- </div> -->
            </form>
         


