
<script>
$(document).ready(function(){

    $(".close-modal").on('click',function(){
       location.reload();
    });

    $("#form-edit").validate({     
            rules:{
                // law_code:{
                // required:true
                // },
                // law_certfication_no:{
                // required:true
                // }
            },
            errorClass: "help-inline",
            errorElement: "span",
            highlight:function(element, errorClass, validClass) {
                $(element).parents('.control-group').addClass('error');
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').removeClass('error');
                $(element).parents('.control-group').addClass('success');
            },
            messages: {
                //cus_cellphone: "Vui lòng nhập số điện thoại !",
                // cus_identity_card: "Vui lòng nhập số CMND !",
                law_code: "Vui lòng nhập mã luật sư !",
                law_certfication_no: "Vui lòng nhập số chứng chỉ !",
            },
            submitHandler: function(form,e) {
                console.log('Form submitted');
                $.ajax({
                      type: "POST",
                      url: "<?php echo $this->BaseUrl?>/default/customers/updatecustomerssupport/",
                      data: $('#form-edit').serialize() ,
                      cache: false,
                      success: function(html)
                      {   
                        $("#message").html("Chỉnh sửa thông tin trợ giúp pháp lý thành công"); 
                        //$(".close-modal").hide();  
                                                                               
                      }
                });
                return false;                       
            }
        });
});  

</script>


<form id="form-edit" class="form-horizontal">
    <h4> Chỉnh sửa trợ giúp pháp lý </h3>
    <p id="message"></p>
    <input type="hidden" name="support_id" id="support_id" value="<?php echo $this->data['support_id']; ?>" />
       
    <div class="control-group">
            <label class="control-label">Tên luật sư: </label>
            <div class="controls">
                <input type="text" disabled class="span2" value="<?php echo $this->data['cus_firstname']." ".$this->data['cus_lastname']; ?>">
            </div>
    </div> 

    <div class="control-group">        
        <label class="control-label">Số giờ :</label>
        <div class="controls">
        <input type="text" name="hours" value="<?php echo $this->data['hours']; ?>" class="span3" placeholder="" />
        </div>
    </div>
    
    <div class="control-group">        
        <label class="control-label">Năm :</label>
        <div class="controls">
        <input type="text" name="year"  value="<?php echo $this->data['year']; ?>" class="span3" placeholder="Vui lòng nhập số năm" />
        </div>
    </div> 

    <div class="control-group">        
        <label class="control-label">Nội dung:</label>
        <div class="controls">
        <input type="text" name="reason" value="<?php echo $this->data['reason']; ?>" class="span3" placeholder="Vui lòng nhập lý do" />
        </div>
    </div>
  
    <!-- <div class="form-actions"> -->
    <button style="float: right;" type="submit" class="btn">Lưu</button>
    <!-- </div> -->
</form>
         


