<script>
$(document).ready(function(){
    
	$('input[type=checkbox],input[type=radio],input[type=file]').uniform();
  $('select').select2();
    var date = new Date();
    var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());

    $("#year").val(date.getFullYear());
    //cmnd
    $('.datepicker-cmnd').datepicker({ format: 'dd/mm/yyyy' }); // format to show
    //$('.datepicker-cmnd').datepicker('setValue', today);

    //bithday
    $('.datepicker-birthday').datepicker({ format: 'dd/mm/yyyy' });
    //$('.datepicker-birthday').datepicker(   
    //  'setValue', today
    //);

    //passport
    $('.datepicker-passport').datepicker({ format: 'dd/mm/yyyy' });
    //$('.datepicker-passport').datepicker(   
    //  'setValue', today
    //);

    $(".datepicker-joining-communist-prepare").datepicker({ format: 'dd/mm/yyyy' });

    $(".datepicker-cus-joining-communist").datepicker({ format: 'dd/mm/yyyy' });

    // $('.datepicker-lawyernumber-date').datepicker({ format: 'dd/mm/yyyy' });
    // $('.datepicker-lawyernumber-date').datepicker(   
    //   'setValue', today
    // );

    

    $(".message-success").hide();

    $("#model-warning").modal('hide');

    $(".kyluattype").show();
 
    //search global
    $("#search-global").keyup(function(e) {        
        $("#cus_id").val('');
        var key = e.keyCode;

        if (key == 40 || key == 38 || key == 13) {
          return false;
        }   
        var searchbox = $(this).val();
        var dataString = 'searchword='+ searchbox + '&searchfield='+$("#search-field").val();
        searchData(searchbox,dataString); 
       
    });  

    $('#search').on("keydown", "#search-global", function (e) {
        console.log("event key down");
        var $listItems = $('.display-box-search-result li');
        //console.log($listItems);
        var key = e.keyCode,
        $selected = $listItems.filter('.hovered'),$current;

        var $scrollable = $("#display-content-search-global");
		    var scrollTop = $scrollable.scrollTop();

        //console.log(scrollTop);

        if (key != 40 && key != 38 && key != 13)
            return;

        //$listItems.removeClass('selected');

        if (key == 40) // Down key
        {
            $listItems.removeClass('hovered');
            if (!$selected.length || $selected.is(':last-child')) {
                $current = $listItems.eq(0);
            } else {
                $current = $selected.next();
            }
            $current.addClass('hovered');
            //console.log("Current : "+$current);
            //console.log($current);
            //$scrollable.scrollTop(scrollTop + 10);
        } 
        else if (key == 38) // Up key
        {
            $listItems.removeClass('hovered');
            if (!$selected.length || $selected.is(':first-child')) {
                $current = $listItems.last();
            } else {
                $current = $selected.prev();
            }       
            $current.addClass('hovered');
            //console.log($('.display-box-search-result li').length);
            //$scrollable.scrollTop(scrollTop - 10);

        } 
        else if (key == 13) // Enter key
        {
            $current = $listItems.filter('.hovered');
            $current.trigger('click');
            return false;
        }

        $("#display-content-search-global").scrollTop(0);//set to top
        $("#display-content-search-global").scrollTop($('.hovered:first').offset().top-$("#display-content-search-global").height());       
        
    });

    //clicked on event search
    $('#display-content-search-global').on('click', function(event) {
      var id = $(event.target).attr('id');
      var value = $("#"+id).val();    
      var dataString = '?searchword='+ id;
       $.ajax({
            type: "GET",
            url: "<?php echo $this->BaseUrl?>/default/customers/detail"+dataString ,
            dataType: 'json',
            cache: false,
            success: function(data)
            {   
 
              if(data.cus_id != null && data.cus_id != undefined){
                     $("#cus_id2").val(data.cus_id);
                     $("#cus_firstname2").val(data.cus_firstname);
                     $("#cus_lastname2").val(data.cus_lastname);
                     $("#cus_birthday2").val(data.cus_birthday);
                     $("#cus_country2").val(data.cus_country);
                     $("#cus_cellphone2").val(data.cus_cellphone);
                     $("#cus_identity_card2").val(data.cus_identity_card);

                     $('#display-content-search-global').html('');
                     //$("#search-global").val(data.cus_identity_card); 
                     if($("#search-field").val() != null && $("#search-field").val() == "name"){
                      $("#search-global").val(data.cus_fullname);
                     }else if($("#search-field").val() != null && $("#search-field").val() == "lawyer_number"){
                      $("#search-global").val(data.cus_lawyer_number);
                     }else if($("#search-field").val() != null && $("#search-field").val() == "identity_card"){
                      $("#search-global").val(data.cus_identity_card);
                     }else{
                      $("#search-global").val(data.cus_cellphone);
                     }

                     $("#cus_id3").val(data.cus_id);
                     $("#cus_firstname3").val(data.cus_firstname);
                     $("#cus_lastname3").val(data.cus_lastname);
                     $("#cus_birthday3").val(data.cus_birthday);
                     $("#cus_country3").val(data.cus_country);
                     $("#cus_cellphone3").val(data.cus_cellphone);
                     $("#cus_identity_card3").val(data.cus_identity_card);
              }        
            }, error: function(msg){               
            }           
            });
    });
    

   //var typeSubmit = '';     

   $("#sumit-intership").on("click",function(){
     console.log("submit intership");
     $("#submittype").val('intership');
   });

   $("#sumit-joining").on("click",function(){
     console.log("submit joining");
     $("#submittype").val('joining');
   });
   
   $("#sumit-normal").on("click",function(){
     console.log("submit normal");
     $("#submittype").val('normal');
   });

   $('#cus_reward_discipline_type').select2();

  //$("#cus_reward_discipline_type").attr("disabled",true);
  $("#cus_reward_discipline_document").attr("disabled",false);
  $("#month").attr("disabled",false);
  $("#cus_reward_document").attr("disabled",true); 
  $("#law_help").attr("disabled",false);
  $("#people_problem").attr("disabled",false);
  $("#inline_content input[name='cus_reward_discipline']").click(function(){
    if($('input:radio[name=cus_reward_discipline]:checked').val() == "kyluat"){
      //$("#cus_reward_discipline_type").attr("disabled",false);
      $("#cus_reward_discipline_document").attr("disabled",false);
      $("#month").attr("disabled",false);   
      $("#cus_reward_document").attr("disabled",true);  
      $("#law_help").attr("disabled",false);
      $("#people_problem").attr("disabled",false);
      //$('#cus_reward_discipline_type').trigger("change"); 
      $("#cus_reward_discipline_type").empty();
      $(".kyluattype").show();
      for(var i=0;i<1;i++){
        $("#cus_reward_discipline_type").append('<option id="canhcao" value="canhcao">Cảnh cáo</option>');
        $("#cus_reward_discipline_type").append('<option id="khientrach" value="khientrach">Khiển trách</option>');
        //$("#cus_reward_discipline_type").append('<option value="'+data[i].service_id+'">'+data[i].service_name+'</option>');
        //$("#cus_reward_discipline_type").append('<option value="'+data[i].service_id+'">'+data[i].service_name+'</option>');
      }
    }else{
      //$("#cus_reward_discipline_type").attr("disabled",true);
      $("#cus_reward_discipline_document").attr("disabled",true);
      $("#month").attr("disabled",true);
      $("#law_help").attr("disabled",true);
      $("#people_problem").attr("disabled",true); 
      $("#cus_reward_document").attr("disabled",false);       
      $('#cus_reward_discipline_type').empty().trigger("change");    
      $(".kyluattype").hide();             
    }
  });

   $("#form-internship").validate({
          rules:{
            cus_reason:{
              required:true
            }
          },
          errorClass: "help-inline",
          errorElement: "span",
          highlight:function(element, errorClass, validClass) {
            $(element).parents('.control-group').addClass('error');
          },
          unhighlight: function(element, errorClass, validClass) {
            $(element).parents('.control-group').removeClass('error');
            $(element).parents('.control-group').addClass('success');
          },
          messages: {
            cus_reason: "Vui lòng nhập lý do !!!"          
          },
          submitHandler: function(form,e) {
            console.log('Form submitted');
            var data = {
              cus_id : $("#cus_id2").val(),   
              cus_reward_discipline: $('input[name=cus_reward_discipline]:checked').val(), 
              cus_reward_document :$("#cus_reward_document").val(),    
              cus_reason: $("#cus_reason").val(),
              law_help : $("#law_help").val(),
              people_problem : $("#people_problem").val(),
              year:$("#year").val(),
              cus_reward_discipline_type : $("#cus_reward_discipline_type").val(),
              cus_reward_discipline_document :$("#cus_reward_discipline_document").val(),
              cus_reward_discipline_month : $("#month").val()  
            }
            $.ajax({
                  type: "POST",
                  url: "<?php echo $this->BaseUrl?>/default/customers/createrewarddiscipline/",
                  data: data ,
                  cache: false,
                  success: function(html)
                  {   
                    $("#message").html(html);
                    $("#model-warning").modal("show");                              
                  }
            });
            return false;                       
        }
	});


//Trợ giúp pháp lý
  $("#form-support").validate({
          rules:{
            reason:{
              required:true
            },
            hours:{
              required:true
            },
            year3:{
              required:true
            }
          },
          errorClass: "help-inline",
          errorElement: "span",
          highlight:function(element, errorClass, validClass) {
            $(element).parents('.control-group').addClass('error');
          },
          unhighlight: function(element, errorClass, validClass) {
            $(element).parents('.control-group').removeClass('error');
            $(element).parents('.control-group').addClass('success');
          },
          messages: {
            reason: "Vui lòng nhập nội dung !!!",
            year3: "Vui lòng nhập năm !!!" , 
            hours: "Vui lòng nhập số giờ !!!"          
          },
          submitHandler: function(form,e) {
            console.log('Form submitted');
            var data = {
              cus_id : $("#cus_id3").val(),             
              reason: $("#reason").val(),
              hours :$("#hours").val(),
              year:$("#year3").val()

            }
            $.ajax({
                  type: "POST",
                  url: "<?php echo $this->BaseUrl?>/default/customers/createsupport/",
                  data: data ,
                  cache: false,
                  success: function(html)
                  {   
                    $("#message").html(html);
                    $("#model-warning").modal("show");                              
                  }
            });
            return false;                       
        }
	});   
   
   
   
   $("#customer_form").validate({     
          rules:{
            // cus_cellphone:{
            //   required:true
            // },
            cus_identity_card:{
              required:true
            },
            cus_firstname:{
              required:true
            },
            cus_lastname:{
              required:true
            }
            // cus_birthday:{
            //   required:true
            // },
            // cus_lawyer_number:{
            //   required:true
            // },
            // cus_identity_place:{
            //   required:true
            // },
            // cus_identity_date:{
            //   required:true
            // },
            // cus_address_resident:{
            //   required:true
            // },
            // cus_address_resident_now:{
            //   required:true
            // },           
            // // cus_lawyer_certification:{
            // //   required:true 
            // // },
            // cus_religion:{
            //   required:true 
            // },
            // cus_username:{
            //   required:true              
            // },
            // cus_password:{
            //   required:true  
            // },
            // city_id:{
            //   required:true 
            // },
            // cus_email:{
            //   required:true,
            //   email: true
            // }
          },
          errorClass: "help-inline",
          errorElement: "span",
          highlight:function(element, errorClass, validClass) {
            $(element).parents('.control-group').addClass('error');
          },
          unhighlight: function(element, errorClass, validClass) {
            $(element).parents('.control-group').removeClass('error');
            $(element).parents('.control-group').addClass('success');
          },
          messages: {
            cus_cellphone: "Vui lòng nhập số điện thoại !",
            cus_identity_card: "Vui lòng nhập số CMND !",
            cus_firstname: "Vui lòng nhập họ !",
            cus_lastname: "Vui lòng nhập tên !",
            cus_identity_place : "Vui lòng nhập nơi cấp CMND!",
            cus_identity_date :" Vui lòng chọn ngày cấp CMND!",
            cus_birthday: "Vui lòng chọn ngày sinh!",
            cus_birthplace:"Vui lòng nhập nơi sinh!",
            // cus_country:"Vui lòng nhập tỉnh thành!",
            cus_nation:"Vui lòng nhập quốc tịch!",
            cus_address_resident:"Vui lòng nhập địa chỉ cư trú!",
            cus_homephone: " Vui lòng nhập số điện thoại nhà riêng",
            //cus_username : " Vui lòng nhập tên đăng nhập",
            //cus_password : "Vui lòng nhập mật khẩu",
            cus_email: "Vui lòng nhập email !",
            cus_lawyer_number:"Vui lòng nhập số thẻ LS ",
            cus_lawyer_certification:" Vui lòng nhập số chứng chỉ hành nghề LS",
            cus_religion: "Vui lòng nhập tôn giáo"
          },
          submitHandler: function(form,e) {
             console.log('Form submitted');
             var formData = new FormData(form); 
            $.ajax({
                  type: "POST",
                  url: "<?php echo $this->BaseUrl?>/default/customers/create/",
                  data: formData ,
                  cache: false,
                  contentType: false,
                  processData: false,
                  success: function(html)
                  {   
                    console.log(html);
                    var obj = JSON.parse(html);
                    //console.log(obj.error);
                    //if(obj.type == 'normal'){
                      if(obj.error != ''){
                        $("#message").html(obj.error);
                        $("#model-warning").modal("show");
                      }else{
                        if(obj.id != ''){
                          if(obj.type == 'intership'){
                            window.location.href = '<?php echo $this->BaseUrl?>/intership/add?cus_id='+obj.id;
                          }else if(obj.type == 'joining'){
                            window.location.href = '<?php echo $this->BaseUrl?>/lawyer/index?cus_id='+obj.id;
                          }else{
                            $("#message").html('Bạn đã thêm mới thành công');
                            $("#model-warning").modal("show");
                          }
                        }
                        
                      }
                    //}
                   // window.location.href = 'http://localhost:8081/zf2/customers/test/';
                    //alert(html);
                    // $("#message").html(html);
                    // $("#model-warning").modal("show");
                    // $(".message-success").show();
                                
                  }
            });
            return false;                       
        }
	});

    $("form input[type=submit]").click(function() {
        $("input[type=submit]", $(this).parents("form")).removeAttr("clicked");
        $(this).attr("clicked", "true");
    });

  function isNumber(n) {
    return !isNaN(parseFloat(n)) && isFinite(n);
  }

  function searchData(searchbox,dataString){
    if(searchbox ==''){
            $("#display-content-search-global").html('');
            //load = true;
        } else
        {
            $.ajax({
                type: "POST",
                url: "<?php echo $this->BaseUrl?>/default/customers/search/",
                data: dataString,
                cache: false,
                success: function(html)
                {   
                  //$("#display-content-search-global").html('');
                  //console.log(html.length);
                  $("#display-content-search-global").html(html);                  
                }
            });
            //load = true
        }
  } 

  $(function () {
    $(":file").change(function () {
        if(this.id == "image"){
          if (this.files && this.files[0]) {
            var reader = new FileReader();
            reader.onload = imageIsLoaded;
            reader.readAsDataURL(this.files[0]);
          }
        }        
    });
});

function imageIsLoaded(e) {
    $('#image-review').attr('src', e.target.result);
};

});

function updateCustomerRewardDiscipline(id){    
    //alert("member status");
    var dataString = '?id='+ id ;
    $.ajax({
        type: "GET",
        url: "<?php echo $this->BaseUrl?>/default/customers/detailrewarddescipline"+dataString ,
        cache: false,
        success: function(html)
        { 
          //alert(html);
          $("#message").html(html);
          $("#model-warning").modal('show');
        }
    });
  };

  function updateCustomerSupport(id){
    var dataString = '?id='+ id ;
    $.ajax({
        type: "GET",
        url: "<?php echo $this->BaseUrl?>/default/customers/detailcustomerssupport"+dataString ,
        cache: false,
        success: function(html)
        { 
          //alert(html);
          $("#message").html(html);
          $("#model-warning").modal('show');
        }
    });
  }

  function deleteCustomerSupport(id){
    var dataString = '?id='+ id ;
    $.ajax({
        type: "GET",
        url: "<?php echo $this->BaseUrl?>/default/customers/deletecustomersupport"+dataString ,
        cache: false,
        success: function(html)
        { 
          //alert(html);
          $("#message").html(html);
          $("#model-warning").modal('show');
        }
    });
  }

  function deleteCustomerRewardDiscipline(id){    
    //alert("member status");
    var dataString = '?id='+ id ;
    $.ajax({
        type: "GET",
        url: "<?php echo $this->BaseUrl?>/default/customers/deleterewarddescipline"+dataString ,
        cache: false,
        success: function(html)
        { 
          //alert(html);
          $("#message").html(html);
          $("#model-warning").modal('show');
        }
    });
  };
   

</script>

<div id="model-warning" class="modal fade"  data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <p id="message">Trong hệ thống đã tồn tại luật sư,hệ thống sẽ tải thông tin để bạn đăng kí tập sự.</p>
          
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>

<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i></a> <a href="#" class="current">Thêm mới danh sách</a> </div>
    <!-- <h1>Quản lý luật sư</h1> -->
  </div>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="alert alert-success alert-dismissible message-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Thông báo</strong> Bạn đã tạo thành công một luật sư trong danh sách.
      </div>	
    </div>  	

    <div class="widget-box">
        <div class="widget-title">
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#tab1">Thêm mới danh sách</a></li>
                <li><a data-toggle="tab" href="#tab2">Thêm mới khen thưởng kỷ luật</a></li>
                <li><a data-toggle="tab" href="#tab3">Thêm trợ giúp pháp lý </a></li>
                <li><a data-toggle="tab" href="#tab4">Chỉnh sửa khen thưởng kỷ luật</a></li>
                <li><a data-toggle="tab" href="#tab5">Chỉnh sửa trợ giúp pháp lý </a></li>
            </ul>
        </div>
        <div class="widget-content tab-content">
            <div id="tab1" class="tab-pane active">  
                <div class="row-fluid">	  	
                  <div class="span12">		 
                    <div class="widget-box">
                        <div class="widget-title">
                          <span class="icon">
                            <i class="icon-th-list"></i>
                          </span>
                          <h5>Thông tin chung luật sư</h5>
                        </div>
                        
                        <div class="widget-content nopadding">  
                          <form id="customer_form" method="post" enctype="multipart/form-data" novalidate="novalidate">
                            <div class="row-fluid form-horizontal">                      
                                  
                                  <div class="span6">
                                      <input type="hidden" id="submittype" name="submittype" />

                                       <div class="control-group">
                                        <label class="control-label">Họ tên lót  :</label>
                                        <div class="controls">
                                          <input type="text" name="cus_firstname" id="cus_firstname" class="span8" placeholder="Vui lòng nhập họ luật sư" />
                                        </div>
                                      </div>

                                      <div class="control-group">
                                        <label class="control-label">Tên  :</label>
                                        <div class="controls">
                                          <input type="text" name="cus_lastname" id="cus_lastname" class="span8" placeholder="Vui lòng nhập tên luật sư" />
                                        </div>
                                      </div>                                      
                                     
                                      <div class="control-group">
                                          <label class="control-label">Ngày sinh  :</label>
                                          <div class="controls">
                                            <!-- <input type="text" id="cus_birthday" name="cus_birthday"  class="span8" placeholder="Enter Password"  /> -->
                                            
                                            <div  data-date="12-02-2012" class="input-append date datepicker-birthday">
                                              <input type="text" id="cus_birthday" name="cus_birthday" data-date-format="dd-mm-yyyy" class="span11" >
                                              <span class="add-on"><i class="icon-th"></i></span> 
                                            </div>                            
                                          </div> 
                                      </div>   

                                       <!-- <div class="control-group">  
                                          <label class="control-label">Nơi sinh (phường, xã, huyện) *</label>
                                          <div class="controls">
                                            <input type="text" id="cus_birthplace" name="cus_birthplace"  class="span8" placeholder="Vui lòng nhập nơi sinh ."  />
                                          </div>
                                      </div>     -->
                                      
                                      <div class="control-group">
                                            <label class="control-label"> Nơi sinh (tỉnh thành)  :</label>
                                            <div class="controls">
                                              <select class="span8" name="city_id">
                                              <?php  
                                                  foreach ($this->cities as $city) {
                                                      echo '<option value="'.$city['city_id'].'" class="span8">'.$city['city_name'].'</option>';
                                                  }
                                                  ?>    
                                              </select>
                                            </div>  
                                      </div>    

                                      <!-- <div class="control-group">
                                          <label class="control-label">Nguyên quán *:</label>
                                          <div class="controls">
                                            <input type="text" id="cus_country" name="cus_country"  class="span8" placeholder="Vui lòng nhập nguyên quán."  />
                                          </div>
                                      </div>     -->

                                      <div class="control-group">
                                        <label class="control-label">Số CMND/Passport  :</label>
                                        <div class="controls">
                                          <input type="text" name="cus_identity_card" id="cus_identity_card" class="span8" placeholder="Vui lòng nhập số CMND" />
                                        </div>
                                      </div>

                                      <div class="control-group">
                                        <label class="control-label">Ngày cấp CMND :</label>
                                        <div class="controls">
                                            <!-- <input type="text" class="span8" id="cus_identity_date" name="cus_identity_date" placeholder="Company name" /> -->
                                            <div  data-date="12-02-2012" class="input-append date datepicker-cmnd">
                                              <input type="text" id="cus_identity_date" name="cus_identity_date" data-date-format="dd-mm-yyyy" class="span11" placeholder="Vui lòng chọn ngày cấp CMND" >
                                              <span class="add-on"><i class="icon-th"></i></span> 
                                            </div>
                                        </div>
                                      </div>

                                      <div class="control-group">
                                          <label class="control-label">Nơi cấp CMND :</label>
                                          <div class="controls">
                                            <input type="text" id="cus_identity_place" name="cus_identity_place" class="span8" placeholder="Vui lòng nhập nơi cấp CMND"/>
                                          </div>
                                      </div>                                      

                                      <div class="control-group">
                                        <label class="control-label">Hộ khẩu thường trú :</label>
                                        <div class="controls">
                                          <textarea id="cus_address_resident" name="cus_address_resident" class="span8" placeholder="Vui lòng nhập địa chỉ thường trú" ></textarea>
                                        </div>
                                      </div>

                                      <div class="control-group">
                                        <label class="control-label">Nơi ở hiện tại :</label>
                                        <div class="controls">
                                          <textarea id="cus_address_resident_now" name="cus_address_resident_now" class="span8" placeholder="Vui lòng nhập địa chỉ hiện tại" ></textarea>
                                        </div>
                                      </div>

                                      <div class="control-group">
                                        <label class="control-label">Số điện thoại(di động) :</label>
                                        <div class="controls">
                                            <input type="text" name="cus_cellphone" id="cus_cellphone" class="span8" placeholder="Vui lòng nhập số điện thoại" />
                                        </div>
                                      </div>

                                      <div class="control-group">
                                        <label class="control-label">Email :</label>
                                        <div class="controls">
                                          <input type="text" name="cus_email" id="cus_email" class="span8" placeholder="Vui lòng nhập email" />
                                        </div>
                                      </div>                                   

                                      <label class="control-label">Giới tính:</label>
                                      <div class="controls">
                                        <div class="row-fluid">
                                            <div class="span3">
                                              <label>
                                                  <input type="radio" name="cus_sex" value="nam" checked/>
                                          Nam</label>
                                            </div>
                                            <div class="span6">
                                                  <label>
                                                <input type="radio" name="cus_sex" value="nu"/>
                                                Nữ</label> 
                                            </div>
                                        </div>                                               
                                      </div>      

                                      <!-- <label class="control-label">Hiện tại</label>
                                      <div class="controls">
                                        <div class="row-fluid">
                                            <div class="span3">
                                              <label>
                                                  <input type="radio" name="in_laywer" value="yes" checked/>
                                            Luật sư tại Đoàn LS TP HCM</label>
                                            </div>
                                            <div class="span6">
                                                  <label>
                                                <input type="radio" name="in_laywer" value="no"/>
                                              Luật sư Đoàn khác</label> 
                                            </div>
                                        </div>                                               
                                      </div>   -->

                                      <!-- <div class="control-group">
                                          <label class="control-label">Số thẻ LS *:</label>
                                          <div class="controls">
                                            <input type="number" id="cus_lawyer_number" name="cus_lawyer_number"  class="span8" placeholder="Vui lòng nhập số thẻ LS."  />
                                          </div>
                                      </div>  -->

                                      <!-- <div class="control-group">
                                        <label class="control-label">Ngày cấp số thẻ LS *:</label>
                                        <div class="controls">
                                            <div  data-date="12-02-2012" class="input-append date datepicker-lawyernumber-date">
                                              <input type="text" id="cus_lawyernumber_date" name="cus_lawyernumber_date" data-date-format="dd-mm-yyyy" class="span11" placeholder="Vui lòng chọn ngày cấp thẻ LS" >
                                              <span class="add-on"><i class="icon-th"></i></span> 
                                            </div>
                                        </div>
                                      </div> -->

                                      <!-- <div class="control-group">
                                        <label class="control-label" >Chọn tổ chức hành nghề luật sư</label>                      
                                        <div class="controls">
                                              <select class="span8" id="cus_organization" name="cus_organization">
                                                <option value="" class="span8">Không tham gia TCHN</option>;
                                              <?php  
                                                  foreach ($this->organizations_data as $org) {
                                                      echo '<option value="'.$org['organ_detail_id'].'" class="span8">'.$org['organ_name'].'</option>';
                                                  }
                                                  ?>    
                                              </select>
                                        </div>  
                                      </div>    -->

                                      <!-- <div class="control-group">
                                          <label class="control-label">Số chứng chỉ hành nghề LS *:</label>
                                          <div class="controls">
                                            <input type="number" id="cus_lawyer_certification" name="cus_lawyer_certification"  class="span8" placeholder="Vui lòng nhập số chừng chỉ HNLS"  />
                                          </div>
                                      </div>                         -->

                                  </div>  
                                  <div class="span6">
                                      <div style="margin-left:33%;">                                  
                                        <img id="image-review" src="<?php echo $this->BaseUrl?>/files/images/photo.jpg" class="img-thumbnail img-responsive" width="120" height="336">
                                      </div>                                  

                                      <!-- <div class="control-group">
                                        <label class="control-label">Tên đăng nhập * :</label>
                                        <div class="controls">              
                                          <input type="text" id="cus_username" name="cus_username" class="span8" placeholder="Vui lòng nhập tên đăng nhập" />
                                        </div>
                                      </div>   -->

                                      <!-- <div class="control-group">
                                        <label class="control-label">Mật khẩu * :</label>
                                        <div class="controls">              
                                          <input type="password" id="cus_password" name="cus_password" class="span8" placeholder="Vui lòng nhập mật khẩu" />
                                        </div>
                                      </div>      -->

                                      <div class="control-group">
                                          <label class="control-label">Tôn giáo :</label>
                                          <div class="controls">
                                            <input type="text" id="cus_religion" name="cus_religion"  class="span8" placeholder="Vui lòng nhập tôn giáo."  />
                                          </div>
                                      </div>       

                                      <!-- <div class="control-group">
                                          <label class="control-label">Ngày vào đoàn TNCS HCM:</label>
                                          <div class="controls">                                            
                                            <div  data-date="12-02-2012" class="input-append date datepicker-birthday">
                                              <input type="text" id="cus_joining_communist_youth" name="cus_joining_communist_youth" data-date-format="dd-mm-yyyy" class="span11" >
                                              <span class="add-on"><i class="icon-th"></i></span> 
                                            </div>                            
                                          </div> 
                                      </div>    	 -->

                                      <div class="control-group">
                                          <label class="control-label">Ngày vào Đảng dự bị:</label>
                                          <div class="controls">
                                            <!-- <input type="text" id="cus_birthday" name="cus_birthday"  class="span8" placeholder="Enter Password"  /> -->
                                            
                                            <div  data-date="12-02-2012" class="input-append date datepicker-joining-communist-prepare">
                                              <input type="text" id="cus_joining_communist_prepare" name="cus_joining_communist_prepare" data-date-format="dd-mm-yyyy" class="span11" >
                                              <span class="add-on"><i class="icon-th"></i></span> 
                                            </div>                            
                                          </div> 
                                      </div>   

                                      <div class="control-group">
                                          <label class="control-label">Ngày vào Đảng chính thức:</label>
                                          <div class="controls">
                                            <!-- <input type="text" id="cus_birthday" name="cus_birthday"  class="span8" placeholder="Enter Password"  /> -->
                                            
                                            <div  data-date="12-02-2012" class="input-append date datepicker-cus-joining-communist">
                                              <input type="text" id="cus_joining_communist" name="cus_joining_communist" data-date-format="dd-mm-yyyy" class="span11" >
                                              <span class="add-on"><i class="icon-th"></i></span> 
                                            </div>                            
                                          </div> 
                                      </div>            			
                                          
                                      <!-- <label class="control-label">Số passport :</label>
                                      <div class="controls">
                                        <input type="text" id="cus_passport_card" name="cus_passport_card" class="span8" placeholder="Vui lòng nhập số passport" />
                                      </div>
                                      <label class="control-label">Nơi cấp passport:</label>
                                      <div class="controls">
                                        <input type="text" id="cus_passport_place" name="cus_passport_place" class="span8" placeholder="Vui lòng nhập nơi cấp passport" />
                                      </div>
                                      <label class="control-label">Ngày cấp passport</label>
                                      <div class="controls">                       
                                        <div  data-date="12-02-2012" class="input-append date datepicker-passport">
                                          <input type="text" id="cus_passport_date" name="cus_passport_date" data-date-format="dd-mm-yyyy" class="span11" placeholder="Vui lòng chọn ngày cấp">
                                          <span class="add-on"><i class="icon-th"></i></span> 
                                        </div>
                                      </div>  -->

                                      <label class="control-label">Trình độ học vấn:</label>
                                      <div class="controls">
                                        <input type="text" id="cus_educations" name="cus_educations" class="span8" placeholder="Vui lòng nhập trình độ học vấn" />
                                      </div>                                
                                         
                                      <div class="control-group"> 
                                        <label class="control-label">Trình độ tiếng anh:</label>                                      
                                        <div class="controls">
                                          <select class="span8" name="language_id">
                                                <?php  
                                                    foreach ($this->languages as $la) {
                                                        echo '<option value="'.$la['language_id'].'" class="span8">'.$la['language_name'].'</option>';
                                                    }
                                                    ?>    
                                          </select>
                                        </div>
                                      </div>

                                      <!-- <label class="control-label">Trình độ nghiệp vụ:</label>
                                      <div class="controls">
                                        <input type="text" id="cus_major" name="cus_major" class="span8" placeholder="Vui lòng nhập trình độ nghiệp vụ"/>
                                        
                                      </div>  -->
                                      
                                      <div class="control-group">
                                          <label class="control-label">Dân tộc :</label>
                                          <div class="controls">                                           
                                              <input type="text" id="cus_nation" name="cus_nation"  class="span4" placeholder="Nhập dân tộc."  /> 
                                          </div>
                                      </div>    

                                      <!-- <div class="control-group">                
                                          <label class="control-label">Số điện thoại (nhà riêng) * :</label>
                                          <div class="controls">
                                            <input type="text" id="cus_homephone" name="cus_homephone" class="span8" placeholder="Vui lòng nhập số điện thoại nhà riêng" />
                                          </div>
                                      </div>                               -->
                                    
                                      <label class="control-label"> Lý lịch 1 (hình ảnh 3x4)</label>
                                      <div class="controls">
                                      <input type="file" id="image" name="image" size="19" style="opacity: 0;">
                                      </div> 
                                      <label class="control-label">Lý lịch 2 (lý lịch pdf)</label>
                                      <div class="controls">
                                        <input name="attachment"  id="attachment" type="file" size="19" style="opacity: 0;">
                                      </div> 
                                      <!-- <label class="control-label">Lý lịch 2</label>
                                      <div class="controls">
                                      <input type="file" id="image2" name="image2" size="19" style="opacity: 0;">
                                      </div> -->
                                      <label class="control-label">Lý lịch 3(pdf)</label>
                                      <div class="controls">
                                        <input name="attachment2"  id="attachment2" type="file" size="19" style="opacity: 0;">
                                      </div>    
                                    
                                  </div>  
                                
                            </div>
                            <div class="row-fluid">
                                  <div class="form-actions">
                                      <div class="span4" >
                                      </div>
                                      <div class="span6">	       
                                          <button type="submit" id="sumit-normal" class="btn ">Thêm mới</button>      
                                          <button type="submit" id="sumit-intership" class="btn ">Thêm mới tập sự</button>	
                                          <button type="submit" id="sumit-joining" class="btn ">Thêm gia nhập mới</button>                                            
                                      </div>                               
                                  </div>
                            </div>  
                          </form>
                        </div>
                    </div>        
                  </div>
                </div>              
            </div>  
            <div id="tab2" class="tab-pane">                                         
              <div class="row-fluid">     
                <!-- open div general information-->
                <div class="span12">          
                  <div class="widget-box">
                    <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                      <h5>Thông tin chung</h5>
                    </div>
                    <div class="widget-content nopadding" id="detail-information">
                    <!--start form-->              
                        <div class="row-fluid form-horizontal">
                          <div class="span6">
                              <label class="control-label">Họ và lót :</label>
                                <div class="controls">
                                  <input type="text" disabled id="cus_firstname2"  name="cus_firstname" class="span8" placeholder="Họ của luật sư" />
                                </div>  
                                <label class="control-label">Tên :</label>
                                <div class="controls">
                                  <input type="text" disabled id="cus_lastname2"  name="cus_lastname" class="span8" placeholder="Tên của luật sư" />
                                </div>   
                                <label class="control-label">Ngày sinh :</label>
                                <div class="controls">
                                  <input type="text" disabled id="cus_birthday2"  name="cus_birthday" class="span8" placeholder="Ngày sinh" />
                                </div>  
                              
                              <!-- <label class="control-label">Tên đăng nhập:</label>
                                <div class="controls">
                                  <input type="text" id="cus_username"  name="cus_username" class="span8" placeholder="Nhập số điện thoại để tìm luật sư" />
                              </div>                                      -->
                          </div>  
                          <div class="span6">
                            <label class="control-label">Số điện thoại :</label>
                              <div class="controls">
                                <input type="text" disabled id="cus_cellphone2"  name="cus_cellphone" class="span8" placeholder="Số điện thoại" />
                              </div> 
                              <label class="control-label">Số chứng minh nhân dân :</label>
                              <div class="controls">
                                <input type="text" disabled id="cus_identity_card2"  name="cus_identity_card" class="span8" placeholder="Số chứng minh nhân dân" />
                              </div>  
                              <!-- <label class="control-label">Nguyên quán :</label>
                              <div class="controls">
                                <input type="text" id="cus_country2"  name="cus_country" class="span8" placeholder="Tỉnh thành" />
                              </div>                   -->
                          </div>                  
                        </div>            
                      <!-- end form -->
                    </div>          
                  </div>
                </div>   
              </div> 

              <div class="row-fluid">
                <!-- open div general information-->
                <div class="span12">          
                  <div class="widget-box">
                    <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                      <h5>Thêm mới khen thưởng kỉ luật</h5>
                    </div>
                    <div class="widget-content nopadding" id="detail-information">
                    <!--start form-->
                      <form id="form-internship" class="form-horizontal" novalidate="novalidate">
                        <input type="hidden" name="cus_id2" id="cus_id2" />
                        <div class="row-fluid">
                          <div class="span6">
                                <label class="control-label">Hình thức:</label>
                                <div class="controls">
                                  <div id="inline_content" class="row-fluid">
                                      <div class="span3">
                                        <label>
                                            <input type="radio" name="cus_reward_discipline" value="khenthuong" />
                                    Khen thưởng</label>
                                      </div>
                                      <div class="span6">
                                            <label>
                                          <input type="radio" name="cus_reward_discipline" value="kyluat" checked/>
                                          Kỉ luật</label> 
                                      </div>
                                  </div>                                               
                                </div> 

                                <div class="control-group kyluattype">
                                    <label class="control-label" >Chọn hình thức kỉ luật:</label>                      
                                    <div class="controls">
                                          <select class="span8" id="cus_reward_discipline_type" name="cus_reward_discipline_type">
                                              <option value="canhcao">Cảnh cáo</option>
                                              <option value="khientrach">Khiển trách</option>
                                              <!-- <option value="xoaten">Xóa tên</option>                                                   -->
                                          </select>
                                    </div>  
                                </div>

                                <div class="control-group">
                                    <label class="control-label" >Văn bản kỉ luật:</label>                      
                                    <div class="controls">
                                        <input type="text" disabled id="cus_reward_discipline_document"  name="cus_reward_discipline_document" class="span8" placeholder="Nhập tên văn bản kỉ luật." />
                                    </div>  
                                </div>  

                                <div class="control-group">        
                                    <label class="control-label">Số tháng kỷ luật:</label>
                                    <div class="controls">
                                    <input type="number" id="month"  name="month"  class="span8"  />
                                    </div>
                                </div>   

                                <div class="control-group">        
                                    <label class="control-label">Năm khen thưởng hoặc kỷ luật:</label>
                                    <div class="controls">
                                    <input type="number" id="year"  name="year"  class="span8"  />
                                    </div>
                                </div>    
                          </div>  
                          <div class="span6">  
                                <div class="control-group">
                                    <label class="control-label" >Văn bản khen thưởng:</label>                      
                                    <div class="controls">
                                        <input type="text" id="cus_reward_document"  name="cus_reward_document" class="span8" placeholder="Nhập tên văn bản khen thưởng." />
                                    </div>  
                                </div>                            
                                <div class="control-group">
                                  <label class="control-label">Lý do * :</label>
                                  <div class="controls">
                                    <textarea id="cus_reason" name="cus_reason" class="span11" placeholder="Vui lòng nhập lý do" ></textarea>
                                  </div>
                                </div> 

                                 <div class="control-group">
                                  <label class="control-label">Người khiếu nại * :</label>
                                  <div class="controls">
                                    <textarea id="people_problem" name="people_problem" class="span11" placeholder="Nhập người khiếu nại." ></textarea>
                                  </div>
                                </div> 

                                 <div class="control-group">
                                  <label class="control-label">Người thụ lý * :</label>
                                  <div class="controls">
                                  <input type="text" id="law_help"  name="law_help" class="span8" placeholder="Nhập người thụ lý." />
                                  </div>
                                </div>                             
                          </div>                

                        </div>             
                        <div class="row-fluid">
                            <div class="span2">
                            </div>
                            <div class="span10">
                                <p id="notification"></p>              
                            </div>
                            
                        </div>                       
                        <div class="form-actions">                  
                          <button type="submit" class="btn save-internship">Nhập</button>                  
                          <!-- <button class="btn">Hủy bỏ</button> -->
                        </div> 
                      </form>
                      <!-- end form -->
                    </div>                      
                  </div>                  
                </div> 
              </div>
            </div>
            <div id="tab3" class="tab-pane">
              <div class="row-fluid">     
                <!-- open div general information-->
                <div class="span12">          
                  <div class="widget-box">
                    <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                      <h5>Thông tin chung</h5>
                    </div>
                    <div class="widget-content nopadding" id="detail-information">
                    <!--start form-->              
                        <div class="row-fluid form-horizontal">
                          <div class="span6">
                              <label class="control-label">Họ và lót :</label>
                                <div class="controls">
                                  <input type="text" disabled id="cus_firstname3"  name="cus_firstname" class="span8" placeholder="Họ của luật sư" />
                                </div>  
                                <label class="control-label">Tên :</label>
                                <div class="controls">
                                  <input type="text" disabled id="cus_lastname3"  name="cus_lastname" class="span8" placeholder="Tên của luật sư" />
                                </div>   
                                <label class="control-label">Ngày sinh :</label>
                                <div class="controls">
                                  <input type="text" disabled id="cus_birthday3"  name="cus_birthday" class="span8" placeholder="Ngày sinh" />
                                </div>  
                              
                              <!-- <label class="control-label">Tên đăng nhập:</label>
                                <div class="controls">
                                  <input type="text" id="cus_username"  name="cus_username" class="span8" placeholder="Nhập số điện thoại để tìm luật sư" />
                              </div>                                      -->
                          </div>  
                          <div class="span6">
                            <label class="control-label">Số điện thoại :</label>
                              <div class="controls">
                                <input type="text" disabled id="cus_cellphone3"  name="cus_cellphone" class="span8" placeholder="Số điện thoại" />
                              </div> 
                              <label class="control-label">Số chứng minh nhân dân :</label>
                              <div class="controls">
                                <input type="text" disabled id="cus_identity_card3"  name="cus_identity_card" class="span8" placeholder="Số chứng minh nhân dân" />
                              </div>  
                              <!-- <label class="control-label">Nguyên quán :</label>
                              <div class="controls">
                                <input type="text" id="cus_country3"  name="cus_country" class="span8" placeholder="Tỉnh thành" />
                              </div>                   -->
                          </div>                  
                        </div>            
                      <!-- end form -->
                    </div>          
                  </div>
                </div>   
              </div> 

              <div class="row-fluid">
                <!-- open div general information-->
                <div class="span12">          
                  <div class="widget-box">
                    <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                      <h5>Thêm mới trợ giúp pháp lý</h5>
                    </div>
                    <div class="widget-content nopadding" id="detail-information">
                    <!--start form-->
                      <form id="form-support" class="form-horizontal" novalidate="novalidate">
                        <input type="hidden" name="cus_id2" id="cus_id3" />
                        <div class="row-fluid">
                          <div class="span6"> 

                                <div class="control-group">        
                                    <label class="control-label">Năm trợ giúp pháp lý:</label>
                                    <div class="controls">
                                    <input type="number" id="year3"  name="year3"  class="span8"  />
                                    </div>
                                </div>                              

                                <div class="control-group">        
                                    <label class="control-label">Số giờ trợ giúp pháp lý:</label>
                                    <div class="controls">
                                    <input type="number" id="hours"  name="hours"  class="span8"  />
                                    </div>
                                </div>    
                          </div>  
                          <div class="span6">                            
                                <div class="control-group">
                                  <label class="control-label">Nội dung * :</label>
                                  <div class="controls">
                                    <textarea id="reason" name="reason" class="span11" placeholder="Vui lòng nhập nội dung" ></textarea>
                                  </div>
                                </div>                                                        
                          </div>                

                        </div>             
                        <div class="row-fluid">
                            <div class="span2">
                            </div>
                            <div class="span10">
                                <p id="notification"></p>              
                            </div>
                            
                        </div>                       
                        <div class="form-actions">                  
                          <button type="submit" class="btn save-support">Nhập</button>                  
                          <!-- <button class="btn">Hủy bỏ</button> -->
                        </div> 
                      </form>
                      <!-- end form -->
                    </div>                      
                  </div>                  
                </div> 
              </div>
            </div>
            <div id="tab4" class="tab-pane">
              <div class="row-fluid">
                <div class="span12">
                  <div class="widget-box">
                      <div class="widget-title">
                        <span class="icon"><i class="icon-th"></i></span> 
                        <h5>Chỉnh sửa khen thưởng kỉ luật</h5>
                      </div>
                      <div class="widget-content nopadding">
                        <table class="table table-bordered data-table">
                          <thead>
                            <tr>
                                <th>Tên người khen thưởng hoặc kỉ luật </th>
                                <th>Số thẻ LS </th>
                                <th>Ngày cấp thẻ LS</th>
                                <th>Lý do khen thưởng hoặc kỉ luật</th>
                                <th>Ngày khen thưởng hoặc kỉ luật</th>
                                <th>Văn bản khen thưởng hoặc kỉ luật</th>
                                <th>Người khiếu nại</th>                                
                                <th>Người thụ lý</th>
                                <th>Thời gian kỉ luật (tháng)</th> 
                                <th>Năm</th>                                
                                <th>Loại</th>                                
                                <th>Thao tác</p>              
                            </tr>
                          </thead>
                          <tbody>       
                            <?php  
                                if($this->dataCustomersRewardDiscipline != null){
                                    foreach ($this->dataCustomersRewardDiscipline as $pay) {  
                                      
                                        $type = '';
                                        $reason = '';
                                        $ngay = '';
                                        $document = '';
                                        $nguoikhieunai = '';
                                        $nguoithuly = '';
                                        $thoigiankiluat = '';
                                        $nam = '';
                                        $chitiet = '';
                                        if($pay['type'] == 'khenthuong'){
                                          $type = '<td>Khen thưởng</td>';
                                          $reason = '<td>'.$pay['reward_reason'].'</td>';
                                          $ngay =  ($pay['reward_date'] != null && $pay['reward_date'] != ''
                                          && $pay['reward_date'] != '1900-01-01 00:00:00') ? date('d/m/Y', strtotime($pay['reward_date'])) : '';
                                          $document = '<td>'.$pay['cus_reward_document'].'</td>'; 
                                          $nguoikhieunai = '<td>'.'</td>';
                                          $nguoithuly = '<td>'.'</td>';
                                          $thoigiankiluat = '<td>'.'</td>'; 
                                          $nam = '<td>'.$pay['year'].'</td>'; 
                                          $chitiet =  '<td>Khen thưởng</td>';
                                        }else{
                                          $type = '<td>Kỉ luật</td>';
                                          $reason = '<td>'.$pay['discipline_reason'].'</td>';
                                          $ngay = ($pay['discipline_date'] != null && $pay['discipline_date'] != ''
                                          && $pay['discipline_date'] != '1900-01-01 00:00:00') ? date('d/m/Y', strtotime($pay['discipline_date'])) : '';
                                          $document = '<td>'.$pay['cus_reward_discipline_document'].'</td>';
                                          $nguoikhieunai = '<td>'.$pay['people_problem'].'</td>';
                                          $nguoithuly = '<td>'.$pay['law_help'].'</td>';
                                          $thoigiankiluat = '<td>'.$pay['cus_reward_discipline_month'].'</td>';
                                          $nam = '<td>'.$pay['year'].'</td>';
                                          if($pay['cus_reward_discipline_type'] == 'canhcao'){
                                            $chitiet =  '<td>Kỉ luật - Cảnh cáo</td>';
                                          }else{
                                            $chitiet =  '<td>Kỉ luật - Khiển trách</td>';
                                          }
                                          
                                        }
                                        
                                        $cus_date_lawyer_number =  ($pay['cus_date_lawyer_number'] != null && $pay['cus_date_lawyer_number'] != ''
                                        && $pay['cus_date_lawyer_number'] != '1900-01-01 00:00:00') ? date('d/m/Y', strtotime($pay['cus_date_lawyer_number'])) : '';    
                                        echo ' <tr class="gradeC">'.
                                        '<td>'.$pay['cus_firstname'].' '.$pay['cus_lastname'].'</td>'.
                                        '<td>'.$pay['cus_lawyer_number'].'</td>'.                                       
                                        '<td>'. $cus_date_lawyer_number .'</td>'.
                                         $reason.
                                         '<td>'.$ngay.'</td>'.
                                         $document.
                                         $nguoikhieunai.
                                         $nguoithuly.
                                         $thoigiankiluat.
                                         $nam.
                                         $chitiet.
                                         '<td class="center">'.
                                              '<button onClick="updateCustomerRewardDiscipline('.$pay['id'].');"><i class="icon-pencil"></i></button>'.' '.
                                               '<button onClick="deleteCustomerRewardDiscipline('.$pay['id'].');"><i class="icon-remove"></i></button>'.
                                              
                                    '</tr>';                            
                                    //} 
                                  }   
                                }

                            ?>
                          </tbody>
                        </table>
                      </div>
                    </div>        
                  </div>
                </div>                                 
            </div>
            <div id="tab5" class="tab-pane">
              <div class="row-fluid">
                <div class="span12">
                  <div class="widget-box">
                      <div class="widget-title">
                        <span class="icon"><i class="icon-th"></i></span> 
                        <h5>Chỉnh sửa trợ giúp pháp lý</h5>
                      </div>
                      <div class="widget-content nopadding">
                        <table class="table table-bordered data-table">
                          <thead>
                            <tr>
                                <th>Tên LS </th>
                                <th>Số chứng chỉ hành nghề </th>
                                <th>Ngày cấp chứng chỉ hành nghề</th>
                                <th>Số giờ trợ giúp</th>
                                <th>Năm </th>
                                <th>Nội dung</th>                                                             
                                <th>Thao tác</p>              
                            </tr>
                          </thead>
                          <tbody>       
                            <?php  
                                if($this->dataCustomersSupport != null){
                                    foreach ($this->dataCustomersSupport as $pay) { 
                                       
                                        $law_certification_createdate =  ($pay['law_certification_createdate'] != null && $pay['law_certification_createdate'] != ''
                                        && $pay['law_certification_createdate'] != '1900-01-01 00:00:00') ? date('d/m/Y', strtotime($pay['law_certification_createdate'])) : '';    
                                        echo ' <tr class="gradeC">'.
                                        '<td>'.$pay['cus_firstname'].' '.$pay['cus_lastname'].'</td>'.
                                        '<td>'.$pay['law_certfication_no'].'</td>'.                                       
                                        '<td>'. $law_certification_createdate .'</td>'.
                                        '<td>'.$pay['hours'].'</td>'.
                                        '<td>'.$pay['year'].'</td>'.
                                        '<td>'.$pay['reason'].'</td>'.  
                                         '<td class="center">'.
                                              '<button onClick="updateCustomerSupport('.$pay['support_id'].');"><i class="icon-pencil"></i></button>'.' '.
                                               '<button onClick="deleteCustomerSupport('.$pay['support_id'].');"><i class="icon-remove"></i></button>'.
                                              
                                    '</tr>';                            
                                    //} 
                                  }   
                                }

                            ?>
                          </tbody>
                        </table>
                      </div>
                    </div>        
                  </div>
                </div>                    
            </div>
        </div>                            
    </div>
  </div>    
</div>
