<div class="display-box-search-result" align-content="left">
<ul class="index-list">    
    <?php if( $this->resultSearch != null && sizeof($this->resultSearch)>0): ?>
        <?php foreach($this->resultSearch as $key=>$value): ?>       
                <li id="<?php echo $value["cus_identity_card"]; ?>" class="user-list-item" >
                    <a class="result-item" id="<?php echo $value["cus_identity_card"]; ?>"><?php echo $value["cus_fullname"].'_'.date('Y', strtotime($value["cus_birthday"])).'_'.$value["cus_identity_card"]; ?></a>
                </li>                    
        <?php endforeach; ?>        
    <?php endif; ?>  
</ul>
</div>