<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
<body>
  <br>
  <br>
  <br>
  <br>
    <form method="post" action="http://localhost:8081/zf2/customers/testupload" enctype="multipart/form-data">
        <input type="file" name="image"/>
        <!-- <input type="submit" name="uploadclick" value="Upload"/> -->
        <button type="submit"  id="save" class="btn ">Lưu</button>
    </form>   
</body>
</html>