<script>
    $(document).ready(function(){

      $('select').select2();

      $("#model-warning").modal("hide");
      $(".message-success").hide(); 
      var date = new Date();
      var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
      
      $('.datepicker-register').datepicker({ format: 'dd/mm/yyyy' }); 
      //$('.datepicker-register').datepicker('setValue', today);

      var inter_regis_date = '';

      // $('#dp5').datepicker()
      // .on('changeDate', function(ev){
      //   console.log("tesst code");
      //     console.log(ev.date.valueOf());
      //     console.log($("#dp5").val());
      //     inter_regis_date = ev.date.valueOf();        
      // });    


    $("#search-global").keyup(function(e) {        
        $("#cus_id").val('');
        var key = e.keyCode;

        if (key == 40 || key == 38 || key == 13) {
           return false;
        }   
        var searchbox = $(this).val();
        var dataString = 'searchword='+ searchbox + '&searchfield='+$("#search-field").val();
        searchData(searchbox,dataString);       
    });  

    $('#search').on("keydown", "#search-global", function (e) {
        console.log("event key down");
        var $listItems = $('.display-box-search-result li');
        //console.log($listItems);
        var key = e.keyCode,
        $selected = $listItems.filter('.hovered'),$current;

        var $scrollable = $("#display-content-search-global");
		    var scrollTop = $scrollable.scrollTop();

        //console.log(scrollTop);

        if (key != 40 && key != 38 && key != 13)
            return;

        //$listItems.removeClass('selected');

        if (key == 40) // Down key
        {
            $listItems.removeClass('hovered');
            if (!$selected.length || $selected.is(':last-child')) {
                $current = $listItems.eq(0);
            } else {
                $current = $selected.next();
            }
            $current.addClass('hovered');
            //console.log("Current : "+$current);
            //console.log($current);
            //$scrollable.scrollTop(scrollTop + 10);
        } 
        else if (key == 38) // Up key
        {
            $listItems.removeClass('hovered');
            if (!$selected.length || $selected.is(':first-child')) {
                $current = $listItems.last();
            } else {
                $current = $selected.prev();
            }       
            $current.addClass('hovered');
            //console.log($('.display-box-search-result li').length);
            //$scrollable.scrollTop(scrollTop - 10);

        } 
        else if (key == 13) // Enter key
        {
            $current = $listItems.filter('.hovered');
            $current.trigger('click');
            return false;
        }

        $("#display-content-search-global").scrollTop(0);//set to top
        $("#display-content-search-global").scrollTop($('.hovered:first').offset().top-$("#display-content-search-global").height());       
        
    });
       

    $("#form-internship").validate({
          rules:{
            inter_number_name:{
              required:true
            },
            lawyer_guide:{
              required:true
            },
            duration:{
              required:true
            }
            // ,
            // intership_address:{
            //   required:true
            // }
          },
          errorClass: "help-inline",
          errorElement: "span",
          highlight:function(element, errorClass, validClass) {
            $(element).parents('.control-group').addClass('error');
          },
          unhighlight: function(element, errorClass, validClass) {
            $(element).parents('.control-group').removeClass('error');
            $(element).parents('.control-group').addClass('success');
          },
          messages: {
            inter_number_name: "Nhập đợt tập sự !!!",
            lawyer_guide:"Chọn luật sư hướng dẫn",
            duration :" Chọn thời gian tập sự",
            intership_address : "Nhập ghi chú tập sự" 
          },
          submitHandler: function(form,e) {
            console.log('Form submitted');
            var data = {
              //cus_fullname : $("#cus_fullname").val(),       
              cus_id : $("#cus_id").val(),
              law_id : $("#law_id").val(),
              //inter_regis_date : inter_regis_date,
              //intership_number_id : $("#intership_number_id").val(),
              duration: $("#duration").val(),
              intership_address : $("#intership_address").val(),
              organ_detail_id : $("#organ_detail_id").val(),
              inter_number_name : $("#inter_number_name").val(),
              cus_member: $("#cus_member").val()           
            }
            $.ajax({
                  type: "POST",
                  url: "<?php echo $this->BaseUrl?>/default/intership/create/",
                  data: data ,
                  cache: false,
                  success: function(html)
                  {   
                    //$(".message-success").show();
                    //alert(html);
                    $("#message").html(html);
                    $("#model-warning").modal("show");
                    // $("#display-content-search").html('');
                    // $("#display-content-search").html(html);                  
                  }
            });
            return false;                       
        }
	  });

    $('#display-content-search-global').on('click', function(event) {
      console.log("action event");
      var id = $(event.target).attr('id');
      var value = $("#"+id).val();
      var dataString = '?searchword='+ id;
       $.ajax({
            type: "GET",
            url: "<?php echo $this->BaseUrl?>/default/customers/detail"+dataString ,
            //data: dataString+'?format=html',
            dataType: 'json',
            cache: false,
            success: function(data)
            {   
 
              if(data.cus_id != null && data.cus_id != undefined){
                     $("#cus_id").val(data.cus_id);
                     $('#display-content-search-global').html('');
                     //$("#search-global").val(data.cus_identity_card);
                     if($("#search-field").val() != null && $("#search-field").val() == "name"){
                      $("#search-global").val(data.cus_fullname);
                     }else if($("#search-field").val() != null && $("#search-field").val() == "lawyer_number"){
                      $("#search-global").val(data.cus_lawyer_number);
                     }else if($("#search-field").val() != null && $("#search-field").val() == "identity_card"){
                      $("#search-global").val(data.cus_identity_card);
                     }else{
                      $("#search-global").val(data.cus_cellphone);
                     }
                     $("#cus_cellphone").val(data.cus_cellphone);
                     $("#cus_firstname").val(data.cus_firstname);
                     $("#cus_lastname").val(data.cus_lastname);
                     $("#cus_identity_card").val(data.cus_identity_card);
                     $("#cus_username").val(data.cus_username);
                     $("#cus_birthday").val(data.cus_birthday);
                     $("#cus_country").val(data.cus_country);
                     $("#cus_lawyer_number").val(data.cus_lawyer_number);
                     $("#cus_member").val(data.cus_member);

              }
              //console.log(data);             
            }, error: function(msg){               
            }           
            });
    });

 });

 function searchData(searchbox,dataString){
    if(searchbox ==''){
            $("#display-content-search-global").html('');
            //load = true;
        } else
        {
            $.ajax({
                type: "POST",
                url: "<?php echo $this->BaseUrl?>/default/customers/search/",
                data: dataString,
                cache: false,
                success: function(html)
                {   
                  //$("#display-content-search-global").html('');
                  //console.log(html.length);
                  $("#display-content-search-global").html(html);                  
                }
            });
            //load = true
        }
  } 

  function isNumber(n) {
    return !isNaN(parseFloat(n)) && isFinite(n);
  }

</script>

 <div id="content">
    <div id="content-header">
      <div id="breadcrumb"> <a href="" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i></a> <a href="#" class="current">Thêm mới tập sự</a> </div>
      <!-- <h1>Quản lý luật sư</h1> -->
    </div>
   <div class="container-fluid"> 
   <div class="row-fluid">
      <div class="alert alert-success alert-dismissible message-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <strong>Thông báo</strong> Bạn đã tạo thành công một luật sư tập sự.
        </div>
    </div>   
    <!-- <h4>Thêm mới luật sư tập sự</h4> -->
    <div class="row-fluid">     
        <!-- open div general information-->
        <div class="span12">          
          <div class="widget-box">
            <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
              <h5>Thông tin chung</h5>
            </div>
            <div class="widget-content nopadding" id="detail-information">
            <!--start form-->  
            <?php if($this->cus_id != ''): ?>
                <div class="row-fluid form-horizontal">
                  <div class="span6">
                        <label class="control-label">Họ và lót:</label>
                        <div class="controls">
                          <input type="text" disabled id="cus_firstname" value="<?php echo $this->customerdata['cus_firstname'];?>"  name="cus_firstname" class="span8" placeholder="Họ của luật sư" />
                        </div>  
                        <label class="control-label">Tên :</label>
                        <div class="controls">
                          <input type="text" disabled id="cus_lastname" value="<?php echo $this->customerdata['cus_lastname'];?>" name="cus_lastname" class="span8" placeholder="Tên của luật sư" />
                        </div> 
                      
                      <label class="control-label">Ngày sinh :</label>
                      <div class="controls">
                        <input type="text" disabled id="cus_birthday" value="<?php echo $this->customerdata['cus_birthday'];?>" name="cus_birthday" class="span8" placeholder="Ngày sinh" />
                      </div>                     
                  </div>  
                  <div class="span6">
                      <label class="control-label">Số điện thoại :</label>
                      <div class="controls">
                        <input type="text" disabled id="cus_cellphone" value="<?php echo $this->customerdata['cus_cellphone'];?>" name="cus_cellphone" class="span8" placeholder="Số điện thoại" />
                      </div> 
                      <label class="control-label">Số chứng minh nhân dân :</label>
                      <div class="controls">
                        <input type="text" disabled id="cus_identity_card" value="<?php echo $this->customerdata['cus_identity_card'];?>"  name="cus_identity_card" class="span8" placeholder="Số chứng minh nhân dân" />
                      </div> 
                        
                      <!-- <label class="control-label">Số thẻ LS :</label>
                      <div class="controls">
                        <input type="text" id="cus_lawyer_number" value="<?php echo $this->customerdata['cus_lawyer_number'];?>"  name="cus_lawyer_number" class="span8" placeholder="Số thẻ LS" />
                      </div>  -->
                  </div>                  
                </div> 
            <?php else: ?>
                <div class="row-fluid form-horizontal">
                  <div class="span6">
                        <label class="control-label">Họ và lót:</label>
                        <div class="controls">
                          <input type="text" disabled id="cus_firstname"  name="cus_firstname" class="span8" placeholder="Họ của luật sư" />
                        </div>  
                        <label class="control-label">Tên :</label>
                        <div class="controls">
                          <input type="text" disabled id="cus_lastname" name="cus_lastname" class="span8" placeholder="Tên của luật sư" />
                        </div> 
                      
                      <label class="control-label">Ngày sinh :</label>
                      <div class="controls">
                        <input type="text" disabled id="cus_birthday"  name="cus_birthday" class="span8" placeholder="Ngày sinh" />
                      </div>                     
                  </div>  
                  <div class="span6">
                      <label class="control-label">Số điện thoại :</label>
                      <div class="controls">
                        <input type="text" disabled id="cus_cellphone"  name="cus_cellphone" class="span8" placeholder="Số điện thoại" />
                      </div> 
                      <label class="control-label">Số chứng minh nhân dân :</label>
                      <div class="controls">
                        <input type="text" disabled id="cus_identity_card"  name="cus_identity_card" class="span8" placeholder="Số chứng minh nhân dân" />
                      </div> 
                        

                  </div>                  
                </div> 
            <?php endif; ?>            
                          
              <!-- end form -->
            </div>          
          </div>
        </div>   
      </div> 

       <div class="row-fluid">
        <!-- open div general information-->
        <div class="span12">          
          <div class="widget-box">
            <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
              <h5>Thêm mới tập sự</h5>
            </div>
            <div class="widget-content nopadding" id="detail-information">
            <!--start form-->
              <form id="form-internship" class="form-horizontal" novalidate="novalidate">
                <input type="hidden" name="cus_id" id="cus_id" value="<?php echo $this->customerdata['cus_id'];?>" />
                <input type="hidden" name="cus_member" id="cus_member" value="<?php echo $this->customerdata['cus_member'];?>" />
                <div class="row-fluid">
                  <div class="span6">
                      <!-- <label class="control-label">Thông tin khóa học :</label>
                      <div class="controls">
                        <input type="text" id="cus_cellphone"  name="cus_cellphone" class="span8" placeholder="số điện thoại" />
                      </div>  -->
                      <!-- <div class="control-group">
                        <label class="control-label">Chọn ngày đăng ký tập sự</label>
                        <div class="controls">                  
                          <div data-date="12-02-2012" class="input-append date datepicker-register">                    
                            <input type="text" id="inter_regis_date" name="inter_regis_date" data-date-format="mm-dd-yyyy" class="span12" >
                            <span class="add-on"><i class="icon-th"></i></span> </div>
                        </div>
                      </div>  -->
                      <div class="control-group">
                              <label class="control-label">Chọn luật sư hướng dẫn:</label>
                                <div class="controls"> 
                                  <select class="span12" id="law_id" name="law_id">
                                  <?php  
                                      foreach ($this->lawyers as $law) {
                                          echo '<option value="'.$law['law_id'].'" class="span8">'.$law['cus_firstname'].' '.$law['cus_lastname'].' - '.$law['cus_identity_card'].'</option>';
                                      }
                                      ?>    
                                  </select>
                              </div>
                      </div> 
                      <div class="control-group">
                              <label class="control-label">Đợt tập sự:</label>
                                <div class="controls">      
                                  <input type="text" id="inter_number_name"  name="inter_number_name" class="span4" placeholder="Đợt tập sự" />                         
                                  <!-- <select class="span8" id="intership_number_id" name="intership_number_id">
                                  <?php  
                                      foreach ($this->internum as $inter) {
                                          echo '<option value="'.$inter['intership_number_id'].'" class="span8">'.$inter['intership_number_name'].'</option>';
                                      }
                                      ?>    
                                  </select>
                                  <a href="<?php echo $this->BaseUrl?>/default/intership/index">Thêm đợt tập sự</a> -->
                              </div>
                              
                        </div>              
                  </div>  
                  <div class="span6">

                        <div class="control-group">
                          <label class="control-label">Chọn tổ chức hành nghề *:</label>
                            <div class="controls">                                
                              <select class="span11" id="organ_detail_id" name="organ_detail_id">
                               <option value="0" class="span8">Không tập sự tại TCHN</option>
                              <?php  
                                  
                                  foreach ($this->organizations as $org) {
                                      echo '<option value="'.$org['organ_detail_id'].'" class="span11">'.$org['organ_name'].'</option>';
                                  }
                                  ?>    
                              </select>
                          </div>
                        </div>    
                        <div class="control-group">
                          <label class="control-label">Thời gian tập sự * :</label>
                          <div class="controls">
                                <select class="span8" id="duration" name="duration">
                                    <option value="0">0</option>
                                    <option value="6">6</option>
                                    <option value="12">12</option>
                                    <option value="18">18</option>
                                </select>          
                          </div>
                        </div> 

                        <div class="control-group">
                          <label class="control-label">Ghi chú. :</label>
                          <div class="controls">
                            <textarea rows="5" class="span12" type="text" name="intership_address" id="intership_address" class="span8" placeholder="Nhập ghi chú tập sự "></textarea>
                          </div>
                        </div>                
                  </div>                  
                </div>             
                                         
                 <div class="form-actions">                  
                  <button type="submit" class="btn save-internship">Nhập</button>                  
                  <button class="btn">Hủy bỏ</button>
                </div> 
              </form>
              <!-- end form -->
            </div>          
          </div>
        </div>   
      </div>     
    </div>    
    </div>
      <!--end div-->   
      <!--open div--> 
   
    </div>  
  </div>
  
 
<!-- </div> -->

<!-- Modal -->
<div id="model-warning" class="modal fade" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <p id="message">Trong hệ thống đã tồn tại luật sư,hệ thống sẽ tải thông tin để bạn đăng kí tập sự.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>