
<script>
$(document).ready(function(){

    $("#form-edit").validate({     
            rules:{
                // law_code:{
                // required:true
                // },
                // law_certfication_no:{
                // required:true
                // }
            },
            errorClass: "help-inline",
            errorElement: "span",
            highlight:function(element, errorClass, validClass) {
                $(element).parents('.control-group').addClass('error');
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').removeClass('error');
                $(element).parents('.control-group').addClass('success');
            },
            messages: {
                //cus_cellphone: "Vui lòng nhập số điện thoại !",
                // cus_identity_card: "Vui lòng nhập số CMND !",
                law_code: "Vui lòng nhập mã luật sư !",
                law_certfication_no: "Vui lòng nhập số chứng chỉ !",
            },
            submitHandler: function(form,e) {
                console.log('Form submitted');
                console.log($('#form-edit').serialize());
                $.ajax({
                      type: "POST",
                      url: "<?php echo $this->BaseUrl?>/default/intership/update/",
                      data: $('#form-edit').serialize() ,
                      cache: false,
                      success: function(html)
                      {   
                        //alert(html);
                        //alert("Cập nhật luật sư thành công");
                        //$(".message-success").show();
                        $("#message").html("Cập nhật thông tin đợt tập sự thành công");
                        // $("#model-warning").modal("show");                                    
                      }
                });
                return false;                       
            }
        });
});  

</script>
<form id="form-edit" class="form-horizontal">
    <p id="message"></p> 
    <input type="hidden" name="inter_id" value="<?php echo $this->intershipnumberdata['inter_id']; ?>" /> 
    <div class="control-group">
        <label class="control-label">Tên đợt tập sự: </label>
        <div class="controls">
            <input type="text" class="span3" name="inter_number_name" id="inter_number_name" value="<?php echo $this->intershipnumberdata['inter_number_name']; ?>">
        </div>
    </div> 
    <?php if($this->intershipnumberdata['payment_inter_status'] == 0 ): ?>   
        <label class="control-label">Trạng thái đợt tập sư:</label>
        <div class="controls">
            <div class="row-fluid">                        
                    <!-- <div class="span3">
                        <label>                            
                        <input type="radio" name="payment_inter_status" value="1" />
                        Tham gia đợt tập sự</label>
                    </div> -->
                    <div class="span6">
                        <label>
                        <input type="radio" name="payment_inter_status" value="2" />
                        Bỏ đợt tập sự</label> 
                    </div>              
            </div>                                               
        </div> 
    <?php else: ?>
        <!-- <label class="control-label">Trạng thái đợt tập sư:</label>
        <div class="controls">
            <div class="row-fluid">   
                   
                    <div class="span6">
                        <label>
                        <input type="radio" name="payment_inter_status" value="2" />
                        Bỏ đợt tập sự</label> 
                    </div>              
            </div>                                               
        </div>  -->
    <?php endif; ?>
    <div class="control-group">
        <label class="control-label">Ghi chú: </label>
        <div class="controls">
            <!-- <input type="text" class="span2" name="inter_note" id="inter_note" value="<?php echo $this->intershipnumberdata['inter_note']; ?>"> -->
            <textarea name="inter_note" id="inter_note" rows="4" cols="70"><?php echo $this->intershipnumberdata['inter_note']; ?></textarea>            
        </div>
    </div>           
    <!-- <div class="form-actions"> -->
    <button style="float: right;" type="submit" class="btn">Lưu</button>
    <!-- </div> -->
</form>
         