<script>
$(document).ready(function(){
    
	$('input[type=checkbox],input[type=radio],input[type=file]').uniform();

    $("#search").hide();
  $(".searchfield").hide();

    $(".message-success").hide();

    $("#model-warning").modal('hide');   

    $(".close-modal").on('click',function(){
      //location.reload();
    });

        
    $('input[type=checkbox],input[type=radio],input[type=file]').uniform();

    //$('.datepicker-startdate').datepicker();
    $('.datepicker-enddate').datepicker({ format: 'dd/mm/yyyy' });


    $(".close-modal").on('click',function(){
      location.reload();
    });

   $("#categorytranining_form").validate({     
          rules:{
            intership_number_name:{
              required:true
            }
          },
          errorClass: "help-inline",
          errorElement: "span",
          highlight:function(element, errorClass, validClass) {
            $(element).parents('.control-group').addClass('error');
          },
          unhighlight: function(element, errorClass, validClass) {
            $(element).parents('.control-group').removeClass('error');
            $(element).parents('.control-group').addClass('success');
          },
          messages: {            
            intership_number_name: "Vui lòng nhập tên đơt tập sự!"           
          },
          submitHandler: function(form,e) {
             console.log('Form submitted');
            $.ajax({
                  type: "POST",
                  url: "<?php echo $this->BaseUrl?>/default/intership/addintershipnumber/",
                  data: $('#categorytranining_form').serialize() ,
                  cache: false,
                  success: function(html)
                  {   
                    //alert(html);
                    $(".message-success").show();
                    $("#model-warning").modal("show");                                                   
                  }
            });
            return false;                       
        }
	});


  function isNumber(n) {
    return !isNaN(parseFloat(n)) && isFinite(n);
  }



});

  function approveIntershipNumber($id){
      var dataString = '?inter_number_id='+ $id;
       $.ajax({
            type: "GET",
            url: "<?php echo $this->BaseUrl?>/default/intership/approveintershipnumber"+dataString ,
            //data: dataString+'?format=html',
            //dataType: 'json',
            cache: false,
            success: function(html)
            { 
              //alert(html);
              $("#message").html(html);
              $("#model-warning").modal('show');
            }
       });       

  }

  function editIntershipNumber($id){
    // alert("test code law");
     //console.log($cat_id);

      var dataString = '?inter_number_id='+ $id;
       $.ajax({
            type: "GET",
            url: "<?php echo $this->BaseUrl?>/default/intership/detail"+dataString ,
            //data: dataString+'?format=html',
            //dataType: 'json',
            cache: false,
            success: function(html)
            { 
              //alert(html);
              $("#message").html(html);
              $("#model-warning").modal('show');
            }
       });  
  }

   

</script>

<div id="model-warning" class="modal fade"  data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
        
      </div>
        
        <div class="modal-body">
            <p id="message">Bạn đã tạo thành công đợt tập sự mới.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary close-modal" data-dismiss="modal">Đóng</button>
        </div>
      
    </div>
  </div>
</div>

<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i></a> <a href="#" class="current">Nhập mới đợt tập sự</a> </div>
    <!-- <h1>Quản lý luật sư</h1> -->
  </div>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="alert alert-success alert-dismissible message-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Thông báo</strong> Bạn đã tạo thành công đợt tập sự mới..
      </div>	
    </div>  	 

    <div class="row-fluid">	  	
      <div class="span12">		 
        <div class="widget-box">
            <div class="widget-title">
              <span class="icon">
                <i class="icon-th-list"></i>
              </span>
              <h5>Nhập mới đợt tập sự</h5>
            </div>
            
            <div class="widget-content nopadding"> 
            <!-- <p>test code </p> -->
              <div class="row-fluid form-horizontal">
                <form id="categorytranining_form" novalidate="novalidate">
                    <div class="span6">
                        <!-- <input type="hidden" id="cus_id" name="cus_id"/> -->
                        <!-- <div class="control-group">
                          <label class="control-label">Số giờ học :</label>
                          <div class="controls">
                              <input type="text" name="cat_train_quantity" id="cat_train_quantity" class="span8" placeholder="Số lượng học viên" />
                          </div>
                        </div> -->
                        <div class="control-group">
                          <label class="control-label">Tên đợt tập sự:</label>
                          <div class="controls">              
                            <input type="text" name="intership_number_name" id="intership_number_name" class="span8" placeholder="Tên đợt tập sự" />
                          </div>
                        </div>   
                        <!-- <div class="control-group">
                          <label class="control-label">Ngày bắt đầu:</label>
                          <div class="controls">
                            <div id="dpcmnd"  data-date="10/20/2018" class="input-append date datepicker-startdate">
                             
                              <input id="intership_number_startdate" name="intership_number_startdate" type="text" value="10/20/2018"  data-date-format="mm-dd-yyyy" class="span11" >
                              <span class="add-on"><i class="icon-th"></i></span>
                            </div>                           
                          </div>
                        </div>    -->

                    </div>  
                    <div class="span6">                       
                        
                        
                    <div class="control-group">
                          <label class="control-label">Ngày duyệt:</label>
                          <div class="controls">
                            <div id="dpcmnd"  data-date="10/20/2018" class="input-append date datepicker-enddate">
                             
                              <input id="intership_number_enddate" name="intership_number_enddate" type="text" data-date-format="mm-dd-yyyy" class="span11" >
                              <span class="add-on"><i class="icon-th"></i></span>
                            </div>                           
                          </div>
                        </div>                 
                    </div>  
               	  
              </div>
              <div class="row-fluid">
                    <div class="form-actions">
                              <div class="span4" >
                              </div>
                              <div class="span6">	             
                                  <button type="submit" class="btn ">Lưu</button>			
                                  <button type="button" class="btn ">Hủy</button>							 
                              </div>
                              <div class="span2" >
                              </div>
                            </div>  
                    </div>
              </div>  
              </form>
            </div>

            <!--tab-->
            <div class="widget-box">
                <div class="widget-title">
                    <ul class="nav nav-tabs">
                        <li class="active"><a id="internship" data-toggle="tab" href="#tab1">Danh sách đợt tập sự</a></li>
                                                
                    </ul>
                </div>
                <div class="widget-content tab-content">
                    <div id="tab1" class="tab-pane active">
                        <div class="row-fluid">
                          <div class="span12">    
                            <div class="widget-box">
                              <div class="widget-title">
                                <span class="icon"><i class="icon-th"></i></span> 
                                <h5>Danh sách đợt tập sự</h5>
                              </div>
                              <div class="widget-content nopadding">
                              <table class="table table-bordered data-table">
                                  <thead>
                                    <tr>
                                      <th>Tên đợt tập sự</th>
                                      <!-- <th>Ngày bắt đầu</th> -->
                                      <th>Ngày duyệt</th>                                                                    
                                      <th>Trạng thái</th>
                                      <th>Hành động</th>
                                    </tr>
                                  </thead>
                                  <tbody id="table-lawyer">   
                                  <?php  
                                        if($this->intershipnumberdata != null){
                                            foreach ($this->intershipnumberdata as $join) {                                           
                                                $text = ''; 
                                                $approved = '';
                                                if($join['intership_number_status'] == 1){
                                                    $text = '<td>Đã được duyệt ngày</td>';
                                                }else{
                                                    $text = '<td>Chưa được duyệt ngày</td>';  
                                                    $approved = '<button  data-toggle="tooltip" title="Duyệt đợt tập sự" onClick="approveIntershipNumber('.$join['intership_number_id'].');" ><i class="icon-ok"></i></button>';
                                                }    

                                                // $intership_number_startdate = ($join['intership_number_startdate'] != null && $join['intership_number_startdate'] != ''
                                                // && $join['intership_number_startdate'] != '1900-01-01 00:00:00') ? date('d/m/Y', strtotime($join['intership_number_startdate'])) : '';    
                                                

                                                
                                                
                                                $intership_number_enddate = ($join['intership_number_enddate'] != null && $join['intership_number_enddate'] != ''
                                                && $join['intership_number_enddate'] != '1900-01-01 00:00:00') ? date('d/m/Y', strtotime($join['intership_number_enddate'])) : '';

                                                echo ' <tr class="gradeC">'.
                                                '<td>'.$join['intership_number_name'].'</td>'.
                                                // '<td>'.$intership_number_startdate.'</td>'.
                                                '<td>'.$intership_number_enddate.'</td>'.
                                                $text.                                               
                                                '<td class="center">'.
                                                    '<button  data-toggle="tooltip" title="Chỉnh sửa tên đợt" onClick="editIntershipNumber('.$join['intership_number_id'].');" ><i class="icon-pencil"></i></button>'.' '.
                                                    $approved.
                                            '</tr>';                          
                                            }  
                                        }
                                    ?>                             
                            
                                  </tbody>
                                </table>                            
                              </div>
                            </div>
                                    
                          </div>          
                        </div>         
                    </div>                  
        
    </div>
  </div>  
</div>

