<?php  
    if($this->interships != null){
        foreach ($this->interships as $inter) {
            $edit = '<td class="center">'.
            '<input type="button" class=button value="Chỉnh sửa" onClick="updateInternship('.$inter['inter_id'].');" />'.
        '</td>';
            
            if($this->lawyerId  != null && $this->lawyerId != ''){
                // neu la luat su thi khong chinh sua
                $edit = '<td>Không chỉnh sửa. </th>';
            }else{
                if($inter['payment_inter_status'] == 1){
                    // neu la luat su thi khong chinh sua
                    $edit = '<td>Không chỉnh sửa.Bạn đã thanh toán tiền cho đợt tập sự </th>';
                }
            }           

            if($inter['payment_inter_status'] == 2){
                $edit = '<td>Không chỉnh sửa. Bạn đã hủy bỏ đợt tập sự</th>';
            }

            $inter_regis_date = ($inter['inter_regis_date'] != null && $inter['inter_regis_date'] != ''
                && $inter['inter_regis_date'] != '1900-01-01 00:00:00') ? date('d/m/Y', strtotime($inter['inter_regis_date'])) : '';    
        
            echo ' <tr class="gradeC">'.
            '<td>'.$inter_regis_date.'</td>'.
            '<td>'.$inter['inter_number_name'].'</td>'.            
            $edit.               
        '</tr>';                            
        }  
    }

?>   
                            
                               