<script>
$(document).ready(function(){
  
  $("#search").hide();
  $(".searchfield").hide();

  $('select').select2();

  // $('.datepicker-start').datepicker();

  // $('.datepicker-end').datepicker();

  var date = new Date();
  var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
  var today1 = new Date(date.getFullYear(), date.getMonth()-1, date.getDate());

  $('.datepicker-start1').datepicker({ format: 'dd/mm/yyyy' }); // format to show
  $('.datepicker-start1').datepicker('setValue', today1);

  $('.datepicker-end1').datepicker({ format: 'dd/mm/yyyy' }); // format to show
  $('.datepicker-end1').datepicker('setValue', today);

  var enddate = $("#enddate1").val();

  var startdate = $("#startdate1").val();

  var dataString = '?enddate='+ enddate+'&startdate='+ startdate;
//   $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/customersupport/reportlawyerfeeexportexcel"+dataString);
  var dataTable = $('#employee-grid').DataTable( {
    "language": {
            "lengthMenu": "Hiển thị _MENU_ dòng trên trang",
            "zeroRecords": "Không tìm thấy",
            "info": "Hiển thị trang _PAGE_ of _PAGES_",
            "infoEmpty": "Không có dữ liệu thích hợp",
            "infoFiltered": "(lọc từ _MAX_ tổng số kết quả)",
            "paginate": {
                "first":      "Đầu",
                "last":       "Cuối",
                "next":       "Tới",
                "previous":   "Sau"
            }
        },
		"processing": true,
    "serverSide": true,
    "searching": false,
    "aLengthMenu": [[10, 50, 75, -1], [10, 50, 75, "All"]],
        "iDisplayLength": 10,
    "ajax":{
      url :"<?php echo $this->BaseUrl?>/default/customersupport/listcustomersupportdatatable"+dataString, // json datasource
      type: "post",  // method  , by default get
      // done:function(){
      //   $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/categorytraining/listtest"+dataString);
      // },
      error: function(){  // error handling
        $(".employee-grid-error").html("");
        $("#employee-grid").append('<tbody class="employee-grid-error"><tr><th colspan="3">Không tìm thấy kết quả</th></tr></tbody>');
        $("#employee-grid_processing").css("display","none");
        
      }
    }
  } );

  $('#filtertable').on('submit', function(e){
      e.preventDefault();
      
      var enddate1 = $("#enddate1").val();

      var startdate1 = $("#startdate1").val();


       var dataString = '?enddate='+ enddate1+'&startdate='+ startdate1;
      //$("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/report/reportlawyerfeeexportexcel"+dataString);
      dataTable.ajax.url( '<?php echo $this->BaseUrl?>/default/customersupport/listcustomersupportdatatable'+dataString).load();
    
    });   
    
});
</script>


<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="#" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i> Trang chủ</a> <a href="#" class="current">Thống kê - Liệt kê LS trợ giúp pháp lý</a> </div>
    
  </div>
  
  <div class="container-fluid">
        <div class="widget-box">
            <div class="widget-title">
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#tab1">Danh sách LS trợ giúp pháp lý</a></li>
                   
                </ul>
            </div>
            <div class="widget-content tab-content">
                <div id="tab1" class="tab-pane active">
                    <h3>Danh LS trợ giúp pháp lý</h3>
                    <div  style="margin-bottom:4%;">  
                        <form method="post" id="filtertable" action=""> 
                          <table cellpadding="5" cellspacing="0">
                            <tbody><tr>
                                                       
                                        <td>													
                                        Thời gian từ ngày: 
                                        </td>
                                        <td>                      
                                            <div id="dpcmnd"  data-date="10/20/2018" class="input-append date datepicker-start1">
                                            
                                                <input id="startdate1" name="startdate1" type="text" data-date-format="mm-dd-yyyy" class="span2" >
                                                <span class="add-on"><i class="icon-th"></i></span>
                                            </div>                      
                                        </td>	
                                        <td>													
                                        Thời gian đến ngày: 
                                        </td>
                                        <td>					 
                     
                                            <div id="dpcmnd"  data-date="10/20/2018" class="input-append date datepicker-end1">
                                            
                                                <input id="enddate1" name="enddate1" type="text" data-date-format="mm-dd-yyyy" class="span2" >
                                                <span class="add-on"><i class="icon-th"></i></span>
                                            </div>  
                                        </td>													

                                      <!-- <td>   
                                          Thời gian (theo quý) : 
                                      </td>
                                      <td>   
                                          <select name="time" id="time" style="width: 150px">
                                              <option value="1">Quý 1</option>
                                              <option value="2">Quý 2</option>
                                              <option value="3">Quý 3</option>
                                              <option value="4">Quý 4</option>
                                          </select>	 
                                      </td>		
                                      <td>   
                                          Năm : 
                                      </td>
                                      <td>   
                                          <select name="year" id="year" style="width: 150px">                                            
                                              <option value="2019">2019</option>
                                              <option value="2018">2018</option>
                                              <option value="2017">2017</option>
                                              <option value="2016">2016</option>
                                          </select>	 
                                      </td>											 -->
                                      <td>
                                        <input type="submit" name="sbsearch" value="   Tìm   ">   
                                      </td>
                                    </tr>								    
                            </tbody>
                          </table>                 
                        </form>  
                        <br>
                        <br>

                        <!-- Xuất file : <a id="downloadUrl" href=""><img src="<?php echo $this->BaseUrl?>/files/images/ico_excel.gif" border="0"></a> -->

                    </div>
                    <div class="row-fluid">
                        <div class="span12">
                          <table id="employee-grid" class="table table-bordered"  cellpadding="0" cellspacing="0" border="0" class="display" width="100%">
                                <thead>
                                  <tr>
                                      <th>STT</th>
                                      <th>Họ Tên </th>
                                      <th>CMND </th>
                                      <th>Năm sinh</th>
                                      <th>Số thẻ LS</th>  
                                      <th>Ngày cấp thẻ LS</th> 
                                      <th>Địa chỉ thường trú</th>
                                      <th>Nơi ở hiện tại </th>                                    
                                      <th>Số giờ</th>  
                                      <th>Năm</th>
                                      <th>Lý do</th>              
                                  </tr>
                                </thead>
                          </table>
                        </div>
                    </div>  
                </div>
            </div>                            
        </div>


  
  </div>
</div>