<?php  
    if($this->customersupports != null){
        foreach ($this->customersupports as $cus) {
            $text = '';
           
            echo ' <tr class="gradeC">'.
            '<td>'.$cus['hours'].'</td>'. 
            '<td>'.$cus['year'].'</td>'. 
            '<td>'.$cus['reason'].'</td>'.
            // '<td class="center">'.
            //     '<input type="button" class=button value="Chỉnh sửa" onClick="updateSupport('.$cus['support_id'].');" />'.
            // '</td>'.              
        '</tr>';                            
        }  
    }

?>  