<script>
$(document).ready(function(){
  
    $("#search").hide();
  $(".searchfield").hide();

  $('select').select2();

  // $('.datepicker-start').datepicker();

  // $('.datepicker-end').datepicker();

  //tab1

  var searchText = $("#time").val();

  var year = $("#year").val();

  var type = $("#type").val();

  var dataString = '?search='+ searchText +'&year='+ year+'&type='+ type;
  $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/report/reportlawyerfeeexportexcel"+dataString);
  var dataTable = $('#employee-grid').DataTable( {
    "language": {
            "lengthMenu": "Hiển thị _MENU_ dòng trên trang",
            "zeroRecords": "Không tìm thấy",
            "info": "Hiển thị trang _PAGE_ of _PAGES_",
            "infoEmpty": "Không có dữ liệu thích hợp",
            "infoFiltered": "(lọc từ _MAX_ tổng số kết quả)",
            "paginate": {
                "first":      "Đầu",
                "last":       "Cuối",
                "next":       "Tới",
                "previous":   "Sau"
            }
        },
		"processing": true,
    "serverSide": true,
    "searching": false,
    "aLengthMenu": [[10, 50, 75, -1], [10, 50, 75, "All"]],
        "iDisplayLength": 10,
    "ajax":{
      url :"<?php echo $this->BaseUrl?>/default/report/reportlawyerfeedatatable"+dataString, // json datasource
      type: "post",  // method  , by default get
      // done:function(){
      //   $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/categorytraining/listtest"+dataString);
      // },
      error: function(){  // error handling
        $(".employee-grid-error").html("");
        $("#employee-grid").append('<tbody class="employee-grid-error"><tr><th colspan="3">Không tìm thấy kết quả</th></tr></tbody>');
        $("#employee-grid_processing").css("display","none");
        
      }
    }
  } );

  $('#filtertable').on('submit', function(e){
      e.preventDefault();
      
      var searchText = $("#time").val();

      var year = $("#year").val();

      var type = $("#type").val();

      var dataString = '?search='+ searchText +'&year='+ year+'&type='+ type;
      $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/report/reportlawyerfeeexportexcel"+dataString);
      dataTable.ajax.url( '<?php echo $this->BaseUrl?>/default/report/reportlawyerfeedatatable'+dataString).load();
    
    });   

//tab12

var searchText12 = $("#time12").val();

var year12 = $("#year12").val();

var type12 = $("#type12").val();

var dataString12 = '?search='+ searchText12 +'&year='+ year12+'&type='+ type12;
$("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/report/reportlawyerfeeexportexcel"+dataString12);
var dataTable12 = $('#employee-grid12').DataTable( {
  "language": {
          "lengthMenu": "Hiển thị _MENU_ dòng trên trang",
          "zeroRecords": "Không tìm thấy",
          "info": "Hiển thị trang _PAGE_ of _PAGES_",
          "infoEmpty": "Không có dữ liệu thích hợp",
          "infoFiltered": "(lọc từ _MAX_ tổng số kết quả)",
          "paginate": {
              "first":      "Đầu",
              "last":       "Cuối",
              "next":       "Tới",
              "previous":   "Sau"
          }
      },
  "processing": true,
  "serverSide": true,
  "searching": false,
  "aLengthMenu": [[10, 50, 75, -1], [10, 50, 75, "All"]],
      "iDisplayLength": 10,
  "ajax":{
    url :"<?php echo $this->BaseUrl?>/default/report/reportlawyerfeedatatable"+dataString12, // json datasource
    type: "post",  // method  , by default get
    // done:function(){
    //   $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/categorytraining/listtest"+dataString);
    // },
    error: function(){  // error handling
      $(".employee-grid-error").html("");
      $("#employee-grid").append('<tbody class="employee-grid-error"><tr><th colspan="3">Không tìm thấy kết quả</th></tr></tbody>');
      $("#employee-grid_processing").css("display","none");
      
    }
  }
} );

$('#filtertable12').on('submit', function(e){
    e.preventDefault();
    
    var searchText12 = $("#time12").val();

    var year12 = $("#year12").val();

    var type12 = $("#type12").val();

    var dataString12 = '?search='+ searchText12 +'&year='+ year12+'&type='+ type12;
    $("#downloadUrl12").attr("href", "<?php echo $this->BaseUrl?>/default/report/reportlawyerfeeeliendoanxportexcel"+dataString12);
    dataTable12.ajax.url( '<?php echo $this->BaseUrl?>/default/report/reportlawyerfeedatatable'+dataString12).load();
  
  });   

    //tab 2


      var searchText2 = $("#time2").val();

      var year2 = $("#year2").val();

      var dataString2 = '?search='+ searchText2 +'&year='+ year2;
      $("#downloadUrl2").attr("href", "<?php echo $this->BaseUrl?>/default/report/reportlawyerwithouttrainingexcel"+dataString2);
      var dataTable2 = $('#employee-grid2').DataTable( {
        "language": {
                "lengthMenu": "Hiển thị _MENU_ dòng trên trang",
                "zeroRecords": "Không tìm thấy",
                "info": "Hiển thị trang _PAGE_ of _PAGES_",
                "infoEmpty": "Không có dữ liệu thích hợp",
                "infoFiltered": "(lọc từ _MAX_ tổng số kết quả)",
                "paginate": {
                    "first":      "Đầu",
                    "last":       "Cuối",
                    "next":       "Tới",
                    "previous":   "Sau"
                }
            },
        "processing": true,
        "serverSide": true,
        "searching": false,
        "aLengthMenu": [[10, 50, 75, -1], [10, 50, 75, "All"]],
            "iDisplayLength": 10,
        "ajax":{
          url :"<?php echo $this->BaseUrl?>/default/report/reportlawyerwithouttrainingdatatable"+dataString2, // json datasource
          type: "post",  // method  , by default get
          // done:function(){
          //   $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/categorytraining/listtest"+dataString);
          // },
          error: function(){  // error handling
            $(".employee-grid-error2").html("");
            $("#employee-grid2").append('<tbody class="employee-grid-error2"><tr><th colspan="3">Không tìm thấy kết quả</th></tr></tbody>');
            $("#employee-grid_processing2").css("display","none");
            
          }
        }
      } );

    $('#filtertable2').on('submit', function(e){
        e.preventDefault();
        
        var searchText2 = $("#time2").val();

        var year2 = $("#year2").val();

        var dataString2 = '?search='+ searchText2 +'&year='+ year2;
        $("#downloadUrl2").attr("href", "<?php echo $this->BaseUrl?>/default/report/reportlawyerwithouttrainingexcel"+dataString2);
        dataTable2.ajax.url( '<?php echo $this->BaseUrl?>/default/report/reportlawyerwithouttrainingdatatable'+dataString2).load();
      
      });   


  //tab3

    //   var searchText3 = $("#time3").val();

      var year3 = $("#year3").val();

      var dataString3 = '?year='+ year3;
      //$("#downloadUrl3").attr("href", "<?php echo $this->BaseUrl?>/default/report/reportlawyerfeeexportexcel"+dataString);
      var dataTable3 = $('#employee-grid3').DataTable( {
        "language": {
                "lengthMenu": "Hiển thị _MENU_ dòng trên trang",
                "zeroRecords": "Không tìm thấy",
                "info": "Hiển thị trang _PAGE_ of _PAGES_",
                "infoEmpty": "Không có dữ liệu thích hợp",
                "infoFiltered": "(lọc từ _MAX_ tổng số kết quả)",
                "paginate": {
                    "first":      "Đầu",
                    "last":       "Cuối",
                    "next":       "Tới",
                    "previous":   "Sau"
                }
            },
        "processing": true,
        "serverSide": true,
        "searching": false,
        "aLengthMenu": [[10, 50, 75, -1], [10, 50, 75, "All"]],
            "iDisplayLength": 10,
        "ajax":{
          url :"<?php echo $this->BaseUrl?>/default/report/reportcustomersrewardtable"+dataString3, // json datasource
          type: "post",  // method  , by default get
          // done:function(){
          //   $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/categorytraining/listtest"+dataString);
          // },
          error: function(){  // error handling
            $(".employee-grid-error3").html("");
            $("#employee-grid3").append('<tbody class="employee-grid-error3"><tr><th colspan="3">Không tìm thấy kết quả</th></tr></tbody>');
            $("#employee-grid_processing3").css("display","none");
            
          }
        }
      } );

      $('#filtertable3').on('submit', function(e){
          e.preventDefault();
          
        //   var searchText3 = $("#time3").val();

          var year3 = $("#year3").val();

          var dataString3 = '?year='+ year3;
          //$("#downloadUrl3").attr("href", "<?php echo $this->BaseUrl?>/default/report/reportlawyerfeeexportexcel"+dataString3);
          dataTable3.ajax.url( '<?php echo $this->BaseUrl?>/default/report/reportcustomersrewardtable'+dataString3).load();
        
        });   
      
});
</script>


<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="#" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i> Trang chủ</a> <a href="#" class="current">Báo cáo</a> </div>
    
  </div>
  
  <div class="container-fluid">
        <div class="widget-box">
            <div class="widget-title">
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#tab1">Danh sách LS nộp phí thành viên</a></li>
                    <!--<li><a data-toggle="tab" href="#tab12">Danh sách LS nộp phí liên đoàn</a></li>-->
                    <li><a data-toggle="tab" href="#tab2">Danh sách chưa tham gia bồi dưỡng bồi dưỡng</a></li>
                    <li><a data-toggle="tab" href="#tab3">Danh sách hồ sơ khen thưởng kỷ luật</a></li>                    
                </ul>
            </div>
            <div class="widget-content tab-content">
                <div id="tab1" class="tab-pane active">
                    <h3>Danh luật sư trích nộp phí thành viên</h3>
                    <div  style="margin-bottom:4%;">  
                        <form method="post" id="filtertable" action=""> 
                          <table cellpadding="5" cellspacing="0">
                            <tbody><tr>
                                      <td>   
                                          Hình thức đóng phí : 
                                      </td>
                                      <td>   
                                          <select name="type" id="type" style="width: 150px">
                                              <option value="online">Đóng online</option>
                                              <option value="offline">Đóng tại đoàn</option>
                                              <option value="all">Tất cả</option>                                             
                                          </select>	 
                                      </td>	
                                      <td>   
                                          Thời gian (theo quý) : 
                                      </td>
                                      <td>   
                                          <select name="time" id="time" style="width: 150px">
                                              <option value="1">Quý 1</option>
                                              <option value="2">Quý 2</option>
                                              <option value="3">Quý 3</option>
                                              <option value="4">Quý 4</option>
                                              <option value="all">Nguyên năm</option>
                                          </select>	 
                                      </td>		
                                      <td>   
                                          Năm : 
                                      </td>
                                      <td>   
                                          <select name="year" id="year" style="width: 150px">                                            
                                              <option value="2019">2019</option>
                                              <option value="2018">2018</option>
                                              <option value="2017">2017</option>
                                              <option value="2016">2016</option>
                                          </select>	 
                                      </td>											
                                      <td>
                                        <input type="submit" name="sbsearch" value="   Tìm   ">   
                                      </td>
                                    </tr>								    
                            </tbody>
                          </table>                 
                        </form>  

                        Xuất file : <a id="downloadUrl" href=""><img src="<?php echo $this->BaseUrl?>/files/images/ico_excel.gif" border="0"></a>

                    </div>
                    <div class="row-fluid">
                        <div class="span12">
                          <table id="employee-grid" class="table table-bordered"  cellpadding="0" cellspacing="0" border="0" class="display" width="100%">
                                <thead>
                                  <tr>
                                      <th>STT</th>
                                      <th>Họ Tên </th>
                                      <th>Năm sinh</th>
                                      <th>Số thẻ LS</th>
                                      <th>Số tháng</th>
                                      <th>Tỷ lệ Trích nộp 50% Mức phí tháng</th>
                                      <th>Số tiền</th>
                                      <th>Từ </th> 
                                      <th>Đến</th>   
                                      <th>Hình thức đóng</th>                  
                                  </tr>
                                </thead>
                          </table>
                        </div>
                    </div>  
                </div>
                <div id="tab12" class="tab-pane">
                    <h3>Danh luật sư trích nộp phí liên đoàn</h3>
                    <div  style="margin-bottom:4%;">  
                        <form method="post" id="filtertable12" action=""> 
                          <table cellpadding="5" cellspacing="0">
                            <tbody><tr>
                                      <td>   
                                          Hình thức đóng phí : 
                                      </td>
                                      <td>   
                                          <select name="type12" id="type12" style="width: 150px">
                                              <option value="online">Đóng online</option>
                                              <option value="offline">Đóng tại đoàn</option>
                                              <option value="all">Tất cả</option>                                             
                                          </select>	 
                                      </td>	
                                      <td>   
                                          Thời gian (theo quý) : 
                                      </td>
                                      <td>   
                                          <select name="time12" id="time12" style="width: 150px">
                                              <option value="1">Quý 1</option>
                                              <option value="2">Quý 2</option>
                                              <option value="3">Quý 3</option>
                                              <option value="4">Quý 4</option>
                                              <option value="all">Nguyên năm</option>
                                          </select>	 
                                      </td>		
                                      <td>   
                                          Năm : 
                                      </td>
                                      <td>   
                                          <select name="year12" id="year12" style="width: 150px">                                            
                                              <option value="2019">2019</option>
                                              <option value="2018">2018</option>
                                              <option value="2017">2017</option>
                                              <option value="2016">2016</option>
                                          </select>	 
                                      </td>											
                                      <td>
                                        <input type="submit" name="sbsearch" value="   Tìm   ">   
                                      </td>
                                    </tr>								    
                            </tbody>
                          </table>                 
                        </form>  

                        Xuất file : <a id="downloadUrl12" href=""><img src="<?php echo $this->BaseUrl?>/files/images/ico_excel.gif" border="0"></a>

                    </div>
                    <div class="row-fluid">
                        <div class="span12">
                          <table id="employee-grid12" class="table table-bordered"  cellpadding="0" cellspacing="0" border="0" class="display" width="100%">
                                <thead>
                                  <tr>
                                      <th>STT</th>
                                      <th>Họ Tên </th>
                                      <th>Năm sinh</th>
                                      <th>Số thẻ LS</th>
                                      <th>Số tháng</th>
                                      <th>Tỷ lệ Trích nộp 50% Mức phí tháng</th>
                                      <th>Số tiền</th>
                                      <th>Từ </th> 
                                      <th>Đến</th>   
                                      <th>Hình thức đóng</th>                  
                                  </tr>
                                </thead>
                          </table>
                        </div>
                    </div>  
                </div>
                <div id="tab2" class="tab-pane">
                    <h3>Danh luật sư chưa tham gia bồi dưỡng bồi dưỡng</h3>
                    <div  style="margin-bottom:4%;">  
                        <form method="post" id="filtertable2" action=""> 
                          <table cellpadding="5" cellspacing="0">
                            <tbody><tr>
                                      <!-- <td>   
                                          Thời gian (theo quý) : 
                                      </td>
                                      <td>   
                                          <select name="time2" id="time2" style="width: 150px">
                                              <option value="1">Quý 1</option>
                                              <option value="2">Quý 2</option>
                                              <option value="3">Quý 3</option>
                                              <option value="4">Quý 4</option>
                                          </select>	 
                                      </td>		 -->
                                      <td>   
                                          Năm : 
                                      </td>
                                      <td>   
                                          <select name="year2" id="year2" style="width: 150px">                                            
                                              <option value="2019">2019</option>
                                              <option value="2018">2018</option>
                                              <option value="2017">2017</option>
                                              <option value="2016">2016</option>
                                          </select>	 
                                      </td>											
                                      <td>
                                        <input type="submit" name="sbsearch" value="   Tìm   ">   
                                      </td>
                                    </tr>								    
                            </tbody>
                          </table>                 
                        </form>  

                        Xuất file : <a id="downloadUrl2" href=""><img src="<?php echo $this->BaseUrl?>/files/images/ico_excel.gif" border="0"></a>

                    </div>
                    <div class="row-fluid">
                        <div class="span12">
                          <table id="employee-grid2" class="table table-bordered"  cellpadding="0" cellspacing="0" border="0" class="display" width="100%">
                                <thead>
                                  <tr>
                                      <th>STT</th>
                                      <th>Họ Tên </th>
                                      <th>Năm sinh</th>
                                      <th>CMND</th>
                                      <th>Đợt</th>
                                      <th>Ngày gia nhập</th>
                                      <th>Số ĐTDĐ</th>
                                      <th>CCHN</th>
                                      <th>Ngày cấp CCHN</th>
                                      <th>Số thẻ LS</th>
                                      <th>Ngày cấp thẻ LS</th>                                                      
                                  </tr>
                                </thead>
                          </table>
                        </div>
                    </div>  
                
                </div>
                <div id="tab3" class="tab-pane">
                <h3>Danh sách hồ sơ khen thưởng kỷ luật</h3>
                    <div  style="margin-bottom:4%;">  
                        <form method="post" id="filtertable3" action=""> 
                          <table cellpadding="5" cellspacing="0">
                            <tbody><tr>
                                      <!-- <td>   
                                          Thời gian (theo quý) : 
                                      </td>
                                      <td>   
                                          <select name="time3" id="time3" style="width: 150px">
                                              <option value="1">Quý 1</option>
                                              <option value="2">Quý 2</option>
                                              <option value="3">Quý 3</option>
                                              <option value="4">Quý 4</option>
                                          </select>	 
                                      </td>		 -->
                                      <td>   
                                          Năm : 
                                      </td>
                                      <td>   
                                          <select name="year3" id="year3" style="width: 150px">                                            
                                              <option value="2019">2019</option>
                                              <option value="2018">2018</option>
                                              <option value="2017">2017</option>
                                              <option value="2016">2016</option>
                                          </select>	 
                                      </td>											
                                      <td>
                                        <input type="submit" name="sbsearch" value="   Tìm   ">   
                                      </td>
                                    </tr>								    
                            </tbody>
                          </table>                 
                        </form>  

                        Xuất file : <a id="downloadUrl3" href=""><img src="<?php echo $this->BaseUrl?>/files/images/ico_excel.gif" border="0"></a>

                    </div>
                    <div class="row-fluid">
                        <div class="span12">
                          <table id="employee-grid3" class="table table-bordered"  cellpadding="0" cellspacing="0" border="0" class="display" width="100%">
                                <thead>
                                  <tr>
                                      <th>STT</th>
                                      <th>Người khiếu nại </th>
                                      <th>Ngày khiếu nại</th>
                                      <th>LS tổ chức bị khiếu nại</th>
                                      <th>Nội dung đề xuất</th>                                      
                                      <th>Người thụ lý</th>                     
                                  </tr>
                                </thead>
                          </table>
                        </div>
                    </div>  
  
                </div>
            </div>                            
        </div>


  
  </div>
</div>