<script>
$(document).ready(function(){
  
    $("#search").hide();
  $(".searchfield").hide();

  // $('.datepicker-start').datepicker();

  // $('.datepicker-end').datepicker();

  var searchText = $("#year").val();

  var dataString = '?year='+ searchText ;
  $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/report/reportfinalexcel"+dataString);
  var dataTable = $('#employee-grid').DataTable( {
    "language": {
            "lengthMenu": "Hiển thị _MENU_ dòng trên trang",
            "zeroRecords": "Không tìm thấy",
            "info": "Hiển thị trang _PAGE_ of _PAGES_",
            "infoEmpty": "Không có dữ liệu thích hợp",
            "infoFiltered": "(lọc từ _MAX_ tổng số kết quả)",
            "paginate": {
                "first":      "Đầu",
                "last":       "Cuối",
                "next":       "Tới",
                "previous":   "Sau"
            }
        },
		"processing": true,
    "serverSide": true,
    "searching": false,
    "aLengthMenu": [[10, 50, 75, -1], [10, 50, 75, "All"]],
        "iDisplayLength": 10,
    "ajax":{
      url :"<?php echo $this->BaseUrl?>/default/report/officedatatable"+dataString, // json datasource
      type: "post",  // method  , by default get
      // done:function(){
      //   $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/categorytraining/listtest"+dataString);
      // },
      error: function(){  // error handling
        $(".employee-grid-error").html("");
        $("#employee-grid").append('<tbody class="employee-grid-error"><tr><th colspan="3">Không tìm thấy kết quả</th></tr></tbody>');
        $("#employee-grid_processing").css("display","none");
        
      }
    }
  } );

  $('#filtertable').on('submit', function(e){
      e.preventDefault();
      
      var searchText = $("#year").val();

      var dataString = '?year='+ searchText;
      $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/report/reportfinalexcel"+dataString);
      //dataTable.ajax.url( '<?php echo $this->BaseUrl?>/default/report/officedatatable'+dataString).load();
    
    });   
     
      
});
</script>


<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="#" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i> Trang chủ</a> <a href="#" class="current">Báo cáo tổng hợp</a> </div>
    
  </div>
  
  <div class="container-fluid">
        <div class="widget-box">
            <div class="widget-title">
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#tab1">Báo cáo tổng hợp của Đoàn LS</a></li>
                    <!-- <li><a data-toggle="tab" href="#tab2">Danh sách chưa tham gia bồi dưỡng bồi dưỡng</a></li>
                    <li><a data-toggle="tab" href="#tab3">Danh sách hồ sơ khen thưởng kỷ luật</a></li> -->
                </ul>
            </div>
            <div class="widget-content tab-content">
                <div id="tab1" class="tab-pane active">
                    <h3>Báo cáo tổng hợp tình hình thu các loại phí</h3>
                    <div  style="margin-bottom:4%;">  
                        <form method="post" id="filtertable" action=""> 
                        <p> Vui lòng chọn năm trước khi xuất báo cáo</p>
                          <table cellpadding="5" cellspacing="0">
                            <tbody><tr>
                                      <td>   
                                          Năm : 
                                      </td>
                                      <td>   
                                          <select name="year" id="year" style="width: 150px">                                            
                                              <option value="2019">2019</option>
                                              <option value="2018">2018</option>
                                              <option value="2017">2017</option>
                                              <option value="2016">2016</option>
                                          </select>	 
                                      </td>										
                                      <!-- <td>
                                        <input type="submit" name="sbsearch" value="   Chọn năm   ">   
                                      </td> -->
                                    </tr>								    
                            </tbody>
                          </table>                 
                        </form>  

                        Xuất file : <a id="downloadUrl" href=""><img src="<?php echo $this->BaseUrl?>/files/images/ico_excel.gif" border="0"></a>

                    </div>
 
                </div>                
            </div>                            
        </div>


  
  </div>
</div>