<script>
$(document).ready(function(){
  window.prettyPrint && prettyPrint();

    $("#search").hide();
    $(".searchfield").hide();

    $('#multiselect1').multiselect();
    $('#multiselect2').multiselect();
    $('#multiselect3').multiselect();


    $("#grantaccess_form").validate({         
          rules:{
            role_name:{
              required:true
            },
            role_code:{
              required:true
            }
          },
          errorClass: "help-inline",
          errorElement: "span",
          highlight:function(element, errorClass, validClass) {
            $(element).parents('.control-group').addClass('error');
          },
          unhighlight: function(element, errorClass, validClass) {
            $(element).parents('.control-group').removeClass('error');
            $(element).parents('.control-group').addClass('success');
          },
          messages: {
            cat_train_quantity: "Vui lòng nhập số giờ giảng dạy của chủ đề",
            cat_train_name: "Vui lòng nhập tên chủ đề !"           
          },
          submitHandler: function(form,e) {
            console.log('Form submitted');
            console.log($('#grantaccess_form').serialize());
            $.ajax({
                  type: "POST",
                  url: "<?php echo $this->BaseUrl?>/admin/action/assign/",
                  data: $('#grantaccess_form').serialize() ,
                  //data:data,
                  cache: false,
                  success: function(html)
                  {   
                    alert(html);
                    //$("#message").html(html);
                    // $(".message-success").show();
                    // $("#model-warning").modal("show");                                                   
                  }
            });
            return false;                       
        }
	});



});

   

</script>

<div id="model-warning" class="modal fade"  data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
        
      </div>
        
        <div class="modal-body">
            <p id="message">Bạn đã gắn thành công vai trò cho tài khoản.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary close-modal" data-dismiss="modal">Đóng</button>
        </div>
      
    </div>
  </div>
</div>

<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i></a> <a href="#" class="current">Gắn vai trò cho tài khoản</a> </div>
    <!-- <h1>Quản lý luật sư</h1> -->
  </div>
  <div class="container-fluid">
    <!-- <div class="row-fluid">
      <div class="alert alert-success alert-dismissible message-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Thông báo</strong> Bạn đã tạo thành công chủ đề mới..
      </div>	
    </div>  	  -->


    <div class="row-fluid">	  	
      <div class="span12">		 
        <div class="widget-box">
            <div class="widget-title">
              <span class="icon">
                <i class="icon-th-list"></i>
              </span>
              <h5>Gắn vai trò cho tài khoản</h5>
            </div>
            
            <div class="widget-content nopadding"> 
            <!-- <p>test code </p> -->
              <div class="row-fluid form-horizontal">
                <form id="grantaccess_form" method="post" novalidate="novalidate">
                <input type="hidden" name="user_id" id="user_id" value="<?php echo $this->user_id; ?>"/>                                 
                  <div class="row-fluid">
                      <p> Danh sách vai trò</p>
                      <div class="span4">
                        <select id="multiselect1" class="form-control" size="8" multiple="multiple">
                          <?php  
                                if($this->roles != null){
                                    foreach ($this->roles as $act) {
                                        echo '<option value="'.$act['rl_id'].'">'.$act['rl_name'].'('.$act['rl_code'].')'.'</option>';                                    
                                    }  
                                }

                            ?>
                        </select>
                      </div>
                
                      <div class="span2">
                        <button type="button" id="multiselect1_rightAll" class="btn btn-block"><i class="icon-forward"></i></button>
                        <button type="button" id="multiselect1_rightSelected" class="btn btn-block"><i class="icon-chevron-right"></i></button>
                        <button type="button" id="multiselect1_leftSelected" class="btn btn-block"><i class="icon-chevron-left"></i></button>
                        <button type="button" id="multiselect1_leftAll" class="btn btn-block"><i class="icon-backward"></i></button>
                      </div>
                      
                      <div class="span4">
                      <select name="tomodule[]" id="multiselect1_to" class="form-control" size="8" multiple="multiple">
                        <?php  
                                if($this->rldetails != null){
                                    foreach ($this->rldetails as $act) {
                                        echo '<option value="'.$act['rl_id'].'">'.$act['rl_name'].'('.$act['rl_code'].')'.'</option>';                                    
                                    }  
                                }

                            ?>
                            </select>
                      </div>
                  </div>
              	  
              </div>
              <div class="row-fluid">
                    <div class="form-actions">
                              <div class="span4" >
                              </div>
                              <div class="span6">	             
                                  <button type="submit" class="btn ">Lưu</button>			
                                  <button type="button" class="btn ">Hủy</button>							 
                              </div>
                              <div class="span2" >
                              </div>
                            </div>  
                    </div>
              </div>  
              </form>
            </div>

  
</div>

<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/prettify/r298/prettify.min.js"></script>
<script type="text/javascript" src="<?php echo $this->BaseUrl?>/public/js/multiselect.min.js"></script>
