<script>
$(document).ready(function(){
  window.prettyPrint && prettyPrint();

    $("#search").hide();
    $(".searchfield").hide();

    $('#multiselect1').multiselect();
    $('#multiselect2').multiselect();
    $('#multiselect3').multiselect();


    $("#grantaccess_form").validate({         
          rules:{
            role_name:{
              required:true
            },
            role_code:{
              required:true
            }
          },
          errorClass: "help-inline",
          errorElement: "span",
          highlight:function(element, errorClass, validClass) {
            $(element).parents('.control-group').addClass('error');
          },
          unhighlight: function(element, errorClass, validClass) {
            $(element).parents('.control-group').removeClass('error');
            $(element).parents('.control-group').addClass('success');
          },
          messages: {
            cat_train_quantity: "Vui lòng nhập số giờ giảng dạy của chủ đề",
            cat_train_name: "Vui lòng nhập tên chủ đề !"           
          },
          submitHandler: function(form,e) {
            console.log('Form submitted');
            //alert("test code");
            // var data = {
            //   tomodule : [1,2,3],
            //   testcode :'test'
            // };
            //var testdata = $("#multiselect1_to").val();
            //alert(JSON.stringify(data));
            console.log($('#grantaccess_form').serialize());
            $.ajax({
                  type: "POST",
                  url: "<?php echo $this->BaseUrl?>/admin/action/create/",
                  data: $('#grantaccess_form').serialize() ,
                  //data:data,
                  cache: false,
                  success: function(html)
                  {   
                    alert(html);
                    //$("#message").html(html);
                    // $(".message-success").show();
                    // $("#model-warning").modal("show");                                                   
                  }
            });
            return false;                       
        }
	});



});

   

</script>

<div id="model-warning" class="modal fade"  data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
        
      </div>
        
        <div class="modal-body">
            <p id="message">Bạn đã tạo thành công vai trò mới.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary close-modal" data-dismiss="modal">Đóng</button>
        </div>
      
    </div>
  </div>
</div>

<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i></a> <a href="#" class="current">Tạo mới vai trò</a> </div>
    <!-- <h1>Quản lý luật sư</h1> -->
  </div>
  <div class="container-fluid">
    <!-- <div class="row-fluid">
      <div class="alert alert-success alert-dismissible message-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Thông báo</strong> Bạn đã tạo thành công chủ đề mới..
      </div>	
    </div>  	  -->


    <div class="row-fluid">	  	
      <div class="span12">		 
        <div class="widget-box">
            <div class="widget-title">
              <span class="icon">
                <i class="icon-th-list"></i>
              </span>
              <h5>Tạo mới vai trò</h5>
            </div>
            
            <div class="widget-content nopadding"> 
            <!-- <p>test code </p> -->
              <div class="row-fluid form-horizontal">
                <form id="grantaccess_form" method="post" novalidate="novalidate">
                  <div class="row-fluid">
                    <div class="control-group">
                          <label class="control-label">Tên vai trò </label>
                          <div class="controls">
                              <input type="text" class="span3" name="role_name" id="role_name">
                          </div>
                    </div>
                    <div class="control-group">
                          <label class="control-label">Mã vai trò (Không dấu, không khoảng cách) </label>
                          <div class="controls">
                              <input type="text" class="span3" name="role_code" id="role_code">
                          </div>
                    </div>
                  </div>
                     
                  <div class="row-fluid">
                      <p> Menu</p>
                      <div class="span4">
                        <select id="multiselect1" class="form-control" size="8" multiple="multiple">
                          <?php  
                                if($this->modules != null){
                                    foreach ($this->modules as $act) {
                                        echo '<option value="'.$act['module_id'].'">'.$act['module_name'].' ('.$act['module_type'].')'.'</option>';                                    
                                    }  
                                }

                            ?>
                        </select>
                      </div>
                
                      <div class="span2">
                        <button type="button" id="multiselect1_rightAll" class="btn btn-block"><i class="icon-forward"></i></button>
                        <button type="button" id="multiselect1_rightSelected" class="btn btn-block"><i class="icon-chevron-right"></i></button>
                        <button type="button" id="multiselect1_leftSelected" class="btn btn-block"><i class="icon-chevron-left"></i></button>
                        <button type="button" id="multiselect1_leftAll" class="btn btn-block"><i class="icon-backward"></i></button>
                      </div>
                      
                      <div class="span4">
                      <select name="tomodule[]" id="multiselect1_to" class="form-control" size="8" multiple="multiple"></select>
                      </div>
                  </div>
                  <div class="row-fluid">
                      <p>Action</p>
                      <div class="span4">
                        <select  id="multiselect2" class="form-control" size="8" multiple="multiple">
                            <!-- <option value="1">Item 1</option>
                            <option value="2">Item 5</option>
                            <option value="2">Item 2</option>
                            <option value="2">Item 4</option>
                            <option value="3">Item 3</option> -->
                            <?php  
                                if($this->actions != null){
                                    foreach ($this->actions as $act) {
                                        echo '<option value="'.$act['action_id'].'">'.$act['action_name'].'</option>';                                    
                                    }  
                                }

                            ?>
                        </select>
                      </div>
                
                      <div class="span2"> 
                          <button type="button" id="multiselect2_rightAll" class="btn btn-block"><i class="icon-forward"></i></button>
                          <button type="button" id="multiselect2_rightSelected" class="btn btn-block"><i class="icon-chevron-right"></i></button>
                          <button type="button" id="multiselect2_leftSelected" class="btn btn-block"><i class="icon-chevron-left"></i></button>
                          <button type="button" id="multiselect2_leftAll" class="btn btn-block"><i class="icon-backward"></i></button>
                      </div>
                      
                      <div class="span4">
                      <select name="toaction[]" id="multiselect2_to" class="form-control" size="8" multiple="multiple"></select>
                      </div>
                  </div>
                  <!-- <div class="row-fluid">
                      <p>Chọn Người Dùng</p>
                      <div class="span4">
                          <select id="multiselect3" size="8" multiple="multiple">                             
                              <?php  
                                if($this->users != null){
                                    foreach ($this->users as $act) {
                                        echo '<option value="'.$act['user_id'].'">'.$act['user_username'].'</option>';                                    
                                    }  
                                }

                            ?>
                          </select>
                      </div>
                
                      <div class="span2">
                      <button type="button" id="multiselect3_rightAll" class="btn btn-block"><i class="icon-forward"></i></button>
                          <button type="button" id="multiselect3_rightSelected" class="btn btn-block"><i class="icon-chevron-right"></i></button>
                          <button type="button" id="multiselect3_leftSelected" class="btn btn-block"><i class="icon-chevron-left"></i></button>
                          <button type="button" id="multiselect3_leftAll" class="btn btn-block"><i class="icon-backward"></i></button>
                      </div>
                      
                      <div class="span4">
                          <select  name="touser[]" id="multiselect3_to" class="form-control" size="8" multiple="multiple"></select>
                      </div>
                  </div> -->
                    <div class="span6">
                        <!-- <input type="hidden" id="cus_id" name="cus_id"/> -->
                        <!-- <div class="control-group">
                          <label class="control-label">Số giờ học :</label>
                          <div class="controls">
                              <input type="text" name="cat_train_quantity" id="cat_train_quantity" class="span12" placeholder="Số thời gian học" />
                          </div>
                        </div> -->
                    </div>  
                    <div class="span6">                       
                        <!-- <div class="control-group">
                          <label class="control-label">Tên chủ đề</label>
                          <div class="controls">              
                            <input type="text" name="cat_train_name" id="cat_train_name" class="span8" placeholder="Tên chủ đề" />
                          </div>
                        </div>                  -->
                    </div>  
               	  
              </div>
              <div class="row-fluid">
                    <div class="form-actions">
                              <div class="span4" >
                              </div>
                              <div class="span6">	             
                                  <button type="submit" class="btn ">Lưu</button>			
                                  <button type="button" class="btn ">Hủy</button>							 
                              </div>
                              <div class="span2" >
                              </div>
                            </div>  
                    </div>
              </div>  
              </form>
            </div>

  
</div>

<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/prettify/r298/prettify.min.js"></script>
<script type="text/javascript" src="<?php echo $this->BaseUrl?>/public/js/multiselect.min.js"></script>
