<script>
$(document).ready(function(){
    $("#search").hide();
    $(".searchfield").hide();
});

</script>
<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="#" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i> Trang chủ</a> <a href="#" class="current">Danh sách hành động</a> </div>
    <h1>Danh sách hành động</h1>
  </div>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span12">
        <div class="widget-box">
          <div class="widget-title">
             <span class="icon"><i class="icon-th"></i></span> 
            <h5>Danh sách hành động</h5>
          </div>
          <div class="widget-content nopadding">
            <table class="table table-bordered data-table">
              <thead>
                <tr>
                  <th>Tên phân quyền</th>
                  <th>Tên phân quyền</th>
                  <th>Hành động</th>
                  <th>Mã hành động</th>
                  <th>Module</th> 
                  <th>Controller Module</th> 
                  <th>Trạng thái</th>                  
                </tr>
              </thead>
              <tbody>       
                <?php  
                    if($this->roles != null && sizeof($this->roles)>0){
                        foreach ($this->roles as $act) {
                            $text = 'Ngưng hoạt động';
                            if($act['role_status'] == 1){
                                $text = "Hoạt động";
                            }
                          echo ' <tr class="gradeC">'.
                          '<td>'.$act['role_name'].'</td>'.
                          '<td>'.$act['role_action'].'</td>'.
                          '<td>'.$act['action_name'].'</td>'.
                          '<td>'.$act['action_actname'].'</td>'.
                          '<td>'.$act['module_name'].'</td>'.
                          '<td>'.$act['module_controller_name'].'</td>'.
                          '<td>'.$text.'</td>';                        
                        
                        }  
                    }

                ?>
              </tbody>
            </table>
          </div>
        </div>        
      </div>
    </div>
  </div>
</div>