<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Dashboard</h6>
        </div>

        <div class="card-body">
          Body
        </div>
      </div>
    </div>
  </div>
</div>

<!-- <script src="<?=$this->BaseUrl?>/public/js/customer.js"></script> -->
