<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Danh sách đơn hàng</h6>
        </div>

        <div class="card-body">
          <div class="border-bottom mb-3 pb-3">
            <button type="button" id="btnNewOrder" class="btn btn-primary">
              <i class="fas fa-plus"></i>
              Thêm đơn hàng
            </button>

            <label for="fileUpload" class="btn btn-light btn-outline-secondary ml-1 mb-0">
              <i class="fas fa-upload"></i>
              Import Excel
              <input id="fileUpload" name="fileUpload" type="file" class="d-none" accept="application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">
            </label>

            <button type="button" id="btnRefresh" class="btn btn-light btn-outline-secondary ml-1 mb-0">
              <i class="fas fa-sync-alt"></i>
              Lấy lại danh sách
            </button>
          </div>

          <table id="tblOrder" class="table table-bordered table-striped table-hover data-table">
            <thead></thead>
            <tbody></tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<!--------------------------------------------------------------------------------------->

<!-- Detail dialog -->
<div id="detailDlg" class="modal fade" tabindex="-1">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Thông Tin Chi Tiết Đơn Hàng</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <div class="modal-body px-0">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <label class="mb-1">Khách hàng</label>
              <select id="selCustomer"></select>
              <input type="hidden" id="hidOrderId">
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-12">
              <label class="mb-1">Diễn giải chung</label>
              <input type="text" id="txtOrderDescription" class="form-control">
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-4">
              <label class="mb-1">Ngày chứng từ</label>
              <input id="dpDocumentDate" class="form-control">
            </div>
            <div class="col-md-4">
              <label class="mb-1">Ngày hóa đơn</label>
              <input id="dpInvoiceDate" class="form-control">
            </div>
            <div class="col-md-4">
              <label class="mb-1">Số hóa đơn</label>
              <input type="number" id="txtInvoiceNumber" class="form-control">
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-12">
              <div class="border-bottom mb-3 pb-3">
                <button type="button" id="btnAddProduct" class="btn btn-secondary">
                  <i class="fas fa-plus"></i>
                  Thêm hàng hóa
                </button>

                <button type="button" id="btnRemoveProduct" class="btn btn-light btn-outline-secondary ml-1 mb-0">
                  <i class="fas fa-trash"></i>
                  Xóa hàng hóa
                </button>
              </div>

              <table id="tblProduct" class="table table-bordered table-striped table-hover data-table">
                <thead></thead>
                <tbody></tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <!-- /modal-body -->

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          <i class="fas fa-times"></i>
          Đóng
        </button>
        <button id="btnSaveOrder" type="button" class="btn btn-primary">
          <i class="fas fa-save"></i>
          Lưu
        </button>
      </div>
    </div>
  </div>
</div>
<!-- /Detail dialog -->

<!--------------------------------------------------------------------------------------->

<!-- Import dialog -->
<div id="importDlg" class="modal fade" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Import Excel</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <div class="modal-body">
        <p>
          Bạn đang nhập thông tin đơn hàng từ tập tin
          <br>
          <span id="importDlg-filename" class="d-inline-block font-weight-bold ml-3"></span>
        </p>
        <p>Hãy chắc chắn rằng nội dung tập tin được soạn đúng theo mẫu được cung cấp.</p>
        <p>Tiếp tục thực hiện?</p>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          <i class="fas fa-times"></i>
          Đóng
        </button>
        <button id="btnImportOrder" type="button" class="btn btn-primary">
          <i class="fas fa-file-import"></i>
          Thực hiện
        </button>
      </div>
    </div>
  </div>
</div>
<!-- /Import dialog -->

<!--------------------------------------------------------------------------------------->

<!-- Add product dialog -->
<div id="productDlg" class="modal fade" tabindex="-1">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Thông Tin Hàng Hóa</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <div class="modal-body px-0">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <label class="mb-1">Hàng hóa</label>
              <select id="selProduct"></select>
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-3">
              <label class="mb-1">Đơn vị tính</label>
              <input type="text" id="txtUnitMeasure" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Số lượng bán</label>
              <input type="number" id="txtQuantity" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Đơn giá</label>
              <input type="number" id="txtPrice" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Doanh số bán</label>
              <input type="number" id="txtPreTaxAmount" class="form-control">
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-3">
              <label class="mb-1">Số lượng trả lại</label>
              <input type="text" id="txtReturnQuantity" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Giá trị trả lại</label>
              <input type="number" id="txtReturnAmount" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Thuế GTGT</label>
              <input type="number" id="txtTaxAmount" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Tổng thanh toán</label>
              <input type="number" id="txtTotal" class="form-control">
            </div>
          </div>
        </div>
      </div>
      <!-- /modal-body -->

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          <i class="fas fa-times"></i>
          Đóng
        </button>
        <button id="btnSaveProduct" type="button" class="btn btn-primary">
          <i class="fas fa-check-circle"></i>
          Cập nhật
        </button>
      </div>
    </div>
  </div>
</div>
<!-- /Add product dialog -->

<script src="<?=$this->BaseUrl?>/public/js/order.js"></script>
