<script>
$(document).ready(function(){

    	$('input[type=checkbox],input[type=radio],input[type=file]').uniform();


      $(".message-success").hide();
      
        $("#search").hide();
  $(".searchfield").hide();
      $("#model-warning").modal('hide');  
      
      var date = new Date();
      var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());

      $('.datepicker-start').datepicker({ format: 'dd/mm/yyyy' }); // format to show
      $('.datepicker-start').datepicker('setValue', today);

      $('.datepicker-end').datepicker({ format: 'dd/mm/yyyy' }); // format to show
      $('.datepicker-end').datepicker('setValue', today);

      var searchText = $("#txtsearch").val();

      var endate = $("#enddate").val();

      var startdate = $("#startdate").val();

      var dataString = '?search='+ searchText + '&startdate='+startdate +'&enddate';
      $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/statistic/removelawyername"+dataString);
      var dataTable = $('#employee-grid').DataTable( {
        "language": {
                "lengthMenu": "Hiển thị _MENU_ dòng trên trang",
                "zeroRecords": "Không tìm thấy",
                "info": "Hiển thị trang _PAGE_ of _PAGES_",
                "infoEmpty": "Không có dữ liệu thích hợp",
                "infoFiltered": "(lọc từ _MAX_ tổng số kết quả)",
                "paginate": {
                    "first":      "Đầu",
                    "last":       "Cuối",
                    "next":       "Tới",
                    "previous":   "Sau"
                }
            },
        "processing": true,
        "serverSide": true,
        "searching": false,
        "aLengthMenu": [[10, 50, 75, -1], [10, 50, 75, "All"]],
            "iDisplayLength": 10,
        "ajax":{
          url :"<?php echo $this->BaseUrl?>/default/statistic/listremovelawyernamedatatable"+dataString, // json datasource
          type: "post",  // method  , by default get
          // done:function(){
          //   $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/categorytraining/listtest"+dataString);
          // },
          error: function(){  // error handling
            $(".employee-grid-error").html("");
            $("#employee-grid").append('<tbody class="employee-grid-error"><tr><th colspan="3">Không tìm thấy kết quả</th></tr></tbody>');
            $("#employee-grid_processing").css("display","none");
            
          }
        }
      } );

      $('#filtertable').on('submit', function(e){
          e.preventDefault();
          
          var searchText = $("#txtsearch").val();

          var endate = $("#enddate").val();

          var startdate = $("#startdate").val();

          var dataString = '?search='+ searchText + '&startdate='+startdate +'&enddate';
          $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/statistic/removelawyername"+dataString);
          dataTable.ajax.url( '<?php echo $this->BaseUrl?>/default/statistic/listremovelawyernamedatatable'+dataString).load();
        
        });   
      
});

</script>


<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="#" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i> Trang chủ</a> <a href="#" class="current">Thống kê - Danh sách luật sư rút tên</a> </div>
    <h1>Danh sách luật sư rút tên</h1>
  </div>
  
  <div class="container-fluid">
    <div style="margin-bottom: 4%;">
      <form method="post" id="filtertable" action=""> 
        <table cellpadding="5" cellspacing="0">
          <tbody><tr>
                <td>
                  Từ khóa :
                </td>
                <td>  
                  <input type="text" id="txtsearch" name="txtsearch" placeholder="Vui lòng nhập số thẻ luật sư" value="">  
                </td> 
                <!-- <td>   
                  Trạng thái : 
                </td>
                <td>   
                  <select name="statussearch" style="width: 150px">
                      <option value=""> -- Tất cả --</option>
                      <option value="Chờ">Chờ</option>
                      <option value="Hoàn thành">Hoàn thành</option>
                      <option value="Hủy">Hủy</option>
                  </select>	 
                </td> -->
                <td>
                </td>
                </tr>
                  <tr>
                    <!-- <td>		
                      Tỉnh/Thành Phố :
                    </td>
                    <td>											
                      <select name="sta_id" style="width:150px;" id="sta_id">
                        <option value="0"> -- Tất cả --</option>
                        <option value="67">TP. Hồ Chí Minh</option> 
                        <option value="68">Hà Nội</option> 
                        <option value="69">Bà Rịa Vũng Tàu</option> 
                        <option value="70">Bắc Giang</option> 
                        <option value="71">Bắc Kạn</option> 
                        <option value="72">Bạc Liêu</option> 
                        <option value="73">Bắc Ninh</option> 
                      </select>
                    </td> -->
                    <td>													
                      Thời gian từ ngày: 
                    </td>
                    <td>					 
                      <!-- <select name="timesearch" style="width: 150px">
                          <option value="0"> -- Tất cả --</option>
                          <option value="1">Trong ngày</option>
                          <option value="3">3 ngày</option>
                          <option value="7">7 ngay</option>
                          <option value="30">30 ngày</option>
                      </select>	 		 -->
                      <!-- <div class="control-group">
                            <label class="control-label">Ngày cấp cmnd:</label>
                            <div class="controls"> -->
                              <div id="dpcmnd"  data-date="10/20/2018" class="input-append date datepicker-start">
                              
                                <input id="startdate" name="startdate" type="text" data-date-format="mm-dd-yyyy" class="span2" >
                                <span class="add-on"><i class="icon-th"></i></span>
                              </div>                           
                            <!-- </div>
                          </div>   -->
                    </td>	
                    <td>													
                      Thời gian đến ngày: 
                    </td>
                    <td>					 
                      <!-- <select name="timesearch" style="width: 150px">
                          <option value="0"> -- Tất cả --</option>
                          <option value="1">Trong ngày</option>
                          <option value="3">3 ngày</option>
                          <option value="7">7 ngay</option>
                          <option value="30">30 ngày</option>
                      </select>	 		 -->
                      <!-- <div class="control-group">
                            <label class="control-label">Ngày cấp cmnd:</label>
                            <div class="controls"> -->
                              <div id="dpcmnd"  data-date="10/20/2018" class="input-append date datepicker-end">
                              
                                <input id="enddate" name="enddate" type="text" data-date-format="mm-dd-yyyy" class="span2" >
                                <span class="add-on"><i class="icon-th"></i></span>
                              </div>                           
                            <!-- </div>
                          </div>   -->
                    </td>													
                    <td>
                      <input type="submit" name="sbsearch" value="   Tìm   ">   
                    </td>
                  </tr>								    
          </tbody>
        </table>                 
      </form>
      Xuất file thống kê :<a id="downloadUrl" href=""><img src="<?php echo $this->BaseUrl?>/files/images/ico_excel.gif" border="0"></a>
    </div>
    <!-- <div class="row-fluid">
         <div class="span12">
        <div class="widget-box">
          <div class="widget-title">
             <span class="icon"><i class="icon-th"></i></span> 
            <h5>Danh sách luật sư rút tên</h5>
          </div>
          <div class="widget-content nopadding">
            <table class="table table-bordered data-table">
              <thead>
                <tr>
                  <th>Tên </th>
                  <th>Giới Tính</th>
                  <th>CMND</th>
                  <th>SĐT</th>
                  <th>Só thẻ LS</th>
                  <th>Số chứng chỉ HN</th>
                  <th>Tổ chức</th> 
                  <th>Loại</th>
                  <th>Tình trạng</th>  
                </tr>
              </thead>
              <tbody>  
         
                <?php  
                    if($this->dataactivelawyer != null){
                        foreach ($this->dataactivelawyer as $pay) {           
                            // '<td>'.$pay['payment_lawyer_off_id'].'</td>'.
                            //  $text = ''; 
                            //  if($pay['cus_sex'] == 'nam'){
                            //     $text = '<td>Nam</td>';
                            //  }else{
                            //     $text = '<td>Nữ</td>';  
                            //  }    
                             echo ' <tr class="gradeC">'.
                             '<td>'.$pay['cus_firstname'].' '.$pay['cus_lastname'].'</td>'.
                             '<td>'.$pay['cus_sex'].'</td>'.
                             '<td>'.$pay['cus_identity_card'].'</td>'.
                            //  '<td>'.$pay['law_code'].'</td>'.
                            //  '<td>'.$pay['law_certfication_no'].'</td>'.
                             
                             '<td>'.$pay['cus_cellphone'].'</td>'.
                             '<td>'.$pay['cus_lawyer_number'].'</td>'.
                             '<td>'.$pay['law_certfication_no'].'</td>'.  
                             '<td>'.$pay['organ_name'].'</td>'.
                             '<td>'.$pay['law_type'].'</td>'. 
                             '<td>Rút tên</td>'.                                                           
                        '</tr>';                            
                        }  
                    }
                ?>
              </tbody>
            </table>
          </div>
        </div>        
      </div>
    </div> -->
   
    <div class="row-fluid">
        <div class="span12">
          <table id="employee-grid" class="table table-bordered"  cellpadding="0" cellspacing="0" border="0" class="display" width="100%">
                <thead>
                  <tr>
                      <th>Tên </th>
                      <th>Giới Tính</th>
                      <th>CMND</th>
                      <th>SĐT</th>
                      <th>Số thẻ LS</th>
                      <th>Ngày cấp thẻ LS</th>
                      <th>Số CCHN</th>
                      <th>Ngày cấp CCHN</th>
                      <th>Địa chỉ thường trú</th>
                      <th>Nơi ở hiện tại </th>
                      <th>Tổ chức</th> 
                      <th>Loại</th>
                      <th>Tình trạng</th>  
                  </tr>
                </thead>
          </table>
        </div>
    </div>                      
  </div>
</div>