<script>
$(document).ready(function(){
    $("#search").hide();
  $(".searchfield").hide();
  $(".message-success").hide();

  $("#model-warning").modal('hide');  

  var date = new Date();
  var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
      
  $('.datepicker-start').datepicker('setValue', today);

  $('.datepicker-end').datepicker('setValue', today);

  var searchText = $("#txtsearch").val();

  // var endate = $("#enddate").val();

  // var startdate = $("#startdate").val();

  //$("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/statistic/listlawyer75excel");  
  //var dataString = '?search='+ searchText + '&startdate='+startdate +'&enddate';
  var dataString = '?search='+ searchText ;
  $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/statistic/listlawyer75excel"+dataString);
  var dataTable = $('#employee-grid').DataTable( {
    "language": {
            "lengthMenu": "Hiển thị _MENU_ dòng trên trang",
            "zeroRecords": "Không tìm thấy",
            "info": "Hiển thị trang _PAGE_ of _PAGES_",
            "infoEmpty": "Không có dữ liệu thích hợp",
            "infoFiltered": "(lọc từ _MAX_ tổng số kết quả)",
            "paginate": {
                "first":      "Đầu",
                "last":       "Cuối",
                "next":       "Tới",
                "previous":   "Sau"
            }
        },
    "processing": true,
    "serverSide": true,
    "searching": false,
    "aLengthMenu": [[10, 50, 75, -1], [10, 50, 75, "All"]],
        "iDisplayLength": 10,
    "ajax":{
      url :"<?php echo $this->BaseUrl?>/default/statistic/listlaywer75datatable"+dataString, // json datasource
      type: "post",  // method  , by default get
      // done:function(){
      //   $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/categorytraining/listtest"+dataString);
      // },
      error: function(){  // error handling
        $(".employee-grid-error").html("");
        $("#employee-grid").append('<tbody class="employee-grid-error"><tr><th colspan="3">Không tìm thấy kết quả</th></tr></tbody>');
        $("#employee-grid_processing").css("display","none");
        
      }
    }
  } );

  $('#filtertable').on('submit', function(e){
      e.preventDefault();
      
      var searchText = $("#txtsearch").val();

      // var endate = $("#enddate").val();

      // var startdate = $("#startdate").val();

      //var dataString = '?search='+ searchText + '&startdate='+startdate +'&enddate';
      var dataString = '?search='+ searchText;
      $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/statistic/listlawyer75excel"+dataString);
      dataTable.ajax.url( '<?php echo $this->BaseUrl?>/default/statistic/listlaywer75datatable'+dataString).load();
    
    });  


});
</script>


<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="#" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i> Trang chủ</a> <a href="#" class="current">Thống kê - Danh sách luật sư theo tuổi</a> </div>
    <h1>Danh sách luật sư theo tuổi</h1>
  </div>
  
  <div class="container-fluid">
    <div  style="margin-bottom:4%;">
      <form method="post" id="filtertable" action=""> 
        <table cellpadding="5" cellspacing="0">
          <tbody><tr>
                <td>
                  Từ khóa :
                </td>
                <td>  
                  <input type="text" id="txtsearch" name="txtsearch" placeholder="Vui lòng nhập số tuổi" value="">  
                </td> 
               
                <td>
                </td>
                </tr>
                  <tr>                  
                    <!-- <td>													
                      Thời gian từ ngày: 
                    </td>
                    <td>                 
                          <div id="dpcmnd"  data-date="10/20/2018" class="input-append date datepicker-start">
                          
                            <input id="startdate" name="startdate" type="text" data-date-format="mm-dd-yyyy" class="span2" >
                            <span class="add-on"><i class="icon-th"></i></span>
                          </div>                           
                    
                    </td>	
                    <td>													
                      Thời gian đến ngày: 
                    </td>
                    <td>					 
                                <div id="dpcmnd"  data-date="10/20/2018" class="input-append date datepicker-end">
                              
                                <input id="enddate" name="enddate" type="text" data-date-format="mm-dd-yyyy" class="span2" >
                                <span class="add-on"><i class="icon-th"></i></span>
                              </div>                           
                          
                    </td>													 -->
                    <td>
                      <input type="submit" name="sbsearch" value="   Tìm   ">   
                    </td>
                  </tr>								    
          </tbody>
        </table>                 
      </form>
      Xuất file thống kê :<a id="downloadUrl" href=""><img src="<?php echo $this->BaseUrl?>/files/images/ico_excel.gif" border="0"></a>
    </div>
    <div class="row-fluid">
        <div class="span12">
          <table id="employee-grid" class="table table-bordered"  cellpadding="0" cellspacing="0" border="0" class="display" width="100%">
              <thead>
                <tr>
                    <th>Tên </th>
                    <th>CMND</th>
                    <th>Ngày sinh</th>
                    <th>Số điện thoại</th>                  
                    <th>Số thẻ LS</th>  
                    <th>Ngày cấp thẻ LS</th>  
                    <th>Số chứng chỉ hành nghề</th>
                    <th>Ngày cấp số chứng chỉ hành nghề</th>
                    <th>Đợt gia nhập</th>
                    <th>Số tuổi</th>
                </tr>
              </thead>             
          </table>
        </div>
    </div>   
  </div>
</div>