<script>
$(document).ready(function(){
  
    $("#search").hide();
  $(".searchfield").hide();
  $('select').select2();

  var searchText = $("#organ_detail_id").val();


  var dataString = '?search='+ searchText;
  
  var dataTable = $('#employee-grid').DataTable( {
    "language": {
            "lengthMenu": "Hiển thị _MENU_ dòng trên trang",
            "zeroRecords": "Không tìm thấy",
            "info": "Hiển thị trang _PAGE_ of _PAGES_",
            "infoEmpty": "Không có dữ liệu thích hợp",
            "infoFiltered": "(lọc từ _MAX_ tổng số kết quả)",
            "paginate": {
                "first":      "Đầu",
                "last":       "Cuối",
                "next":       "Tới",
                "previous":   "Sau"
            }
        },
		"processing": true,
    "serverSide": true,
    "searching": false,
    "aLengthMenu": [[10, 50, 75, -1], [10, 50, 75, "All"]],
        "iDisplayLength": 10,
    "ajax":{
      url :"<?php echo $this->BaseUrl?>/default/statistic/listlawyeroforgandatatable"+dataString, // json datasource
      type: "post",  // method  , by default get
      // done:function(){
      //   $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/categorytraining/listtest"+dataString);
      // },
      error: function(){  // error handling
        $(".employee-grid-error").html("");
        $("#employee-grid").append('<tbody class="employee-grid-error"><tr><th colspan="3">Không tìm thấy kết quả</th></tr></tbody>');
        $("#employee-grid_processing").css("display","none");
        
      }
    },
    'columnDefs': [
         {
            'targets': 0,
            'checkboxes': {
               'selectRow': true
            }
         }
      ],
      'select': {
         'style': 'multi'
      },
  } );

  $('.remove').on('click', function(e){

    $("#model-warning").addClass('modal');
    $("#model-warning").modal("show");

    e.preventDefault();

    var form = this;

    var rows_selected = dataTable.column(0).checkboxes.selected();

    // Iterate over all selected checkboxes

    var listIds = [];
    $.each(rows_selected, function(index, rowId){
      listIds.push(rowId);      
    });    
    $("#organ_lid").val(listIds);

    console.log(listIds);
    if(listIds.length <= 0){
          $(".modal-body").text('Bạn phải chọn LS trước khi xóa.');
          $("#model-warning").modal('show');
    }else{
      deleteLS(listIds);
    }  
    });  

  $('#filtertable').on('submit', function(e){
      e.preventDefault();
      
      var searchText = $("#organ_detail_id").val();


      var dataString = '?search='+ searchText;
      dataTable.ajax.url( '<?php echo $this->BaseUrl?>/default/statistic/listlawyeroforgandatatable'+dataString).load();
    
    });   
      
});

function deleteLS($ids){      
      var dataString = '?dsls='+ $ids;
         $.ajax({
              type: "GET",
              url: "<?php echo $this->BaseUrl?>/default/statistic/deletedsls"+dataString ,
              cache: false,
              success: function(html)
              { 
                //alert(html);
                $(".modal-body").text('Bạn đã xóa luật sư ra khỏi TCHN.');
                $("#model-warning").modal('show');
              }
         });  
  }
</script>


<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="#" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i> Trang chủ</a> <a href="#" class="current">Thống kê - Danh sách luật sư của tổ chức</a> </div>
    <h1>Danh sách luật sư của tổ chức</h1>
  </div>
  
  <div class="container-fluid">
    <div  style="margin-bottom:4%;">  
        <form method="post" id="filtertable" action=""> 
          <table cellpadding="5" cellspacing="0">
            <tbody><tr>
                  <td>
                      <label class="control-label">Chọn tổ chức hành nghề *:</label>
                  </td>
                  <td>  
                    <!-- <input type="text" id="txtsearch" name="txtsearch" placeholder="Vui lòng nhập mã luật sư" value="">   -->
                    <div class="control-group">                              
                        <div class="controls">                                
                        <select class="span3" id="organ_detail_id" name="organ_detail_id">
                            <?php  
                                foreach ($this->organizations as $org) {
                                    echo '<option value="'.$org['organ_detail_id'].'" class="span8">'.$org['organ_name'].'</option>';
                                }
                                ?>    
                            </select>
                        </div>
                    </div> 
                  </td>                
                  <td>
                    <button type="submit" class="btn">  Tìm   </button>   
                  </td>
                  </tr>                   
                    <tr>
                          <td>
                          <button class="btn btn-primary remove">Xóa khỏi TCHN</button>
                          </td>
                      </tr>	  							    
            </tbody>
          </table>                 
        </form> 
    </div>
    <div class="row-fluid">
        <div class="span12">
          <table id="employee-grid" class="table table-bordered"  cellpadding="0" cellspacing="0" border="0" class="display" width="100%">
                <thead>
                  <tr>
                      <th></th>
                      <th>Tên </th>
                      <th>CMND </th>
                      <th>Số thẻ LS</th>
                      <th>Ngày cấp thẻ LS</th>
                      <th>Số chứng chỉ hành nghề</th>
                      <th>Ngày cấp chứng chỉ hành nghề</th>
                      <th>Địa chỉ thường trú</th>
                      <th>Nơi ở hiện tại </th>
                      <th>Ngày sinh</th>
                      <th>Quốc tịch</th>
                      <th>TCHN</th>                                           
                  </tr>
                </thead>
          </table>
        </div>
    </div> 
  </div>
</div>

<div id="model-warning" class="modal fade"  data-backdrop="static">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Chỉnh sửa thông tin</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
      </div>
    </div>
  </div>
</div>
