<script>
$(document).ready(function(){
  
    $("#search").hide();
  $(".searchfield").hide();
  $('select').select2();
  // tab 1
  var searchText = $("#year").val();

  var type = $("#type").val();  

  var dataString = '?search='+ searchText+'&type='+ type;
  
  var dataTable = $('#employee-grid').DataTable( {
    "language": {
            "lengthMenu": "Hiển thị _MENU_ dòng trên trang",
            "zeroRecords": "Không tìm thấy",
            "info": "Hiển thị trang _PAGE_ of _PAGES_",
            "infoEmpty": "Không có dữ liệu thích hợp",
            "infoFiltered": "(lọc từ _MAX_ tổng số kết quả)",
            "paginate": {
                "first":      "Đầu",
                "last":       "Cuối",
                "next":       "Tới",
                "previous":   "Sau"
            }
        },
		"processing": true,
    "serverSide": true,
    "searching": false,
    "aLengthMenu": [[10, 50, 75, -1], [10, 50, 75, "All"]],
        "iDisplayLength": 10,
    "ajax":{
      url :"<?php echo $this->BaseUrl?>/default/statistic/reportlawyertrainingdatatable"+dataString, // json datasource
      type: "post",  // method  , by default get
      // done:function(){
      //   $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/categorytraining/listtest"+dataString);
      // },
      error: function(){  // error handling
        $(".employee-grid-error").html("");
        $("#employee-grid").append('<tbody class="employee-grid-error"><tr><th colspan="3">Không tìm thấy kết quả</th></tr></tbody>');
        $("#employee-grid_processing").css("display","none");
        
      }
    }
  } );

  $('#filtertable').on('submit', function(e){
      e.preventDefault();
      
      var searchText = $("#year").val();

      var type = $("#type").val();  

      var dataString = '?search='+ searchText+'&type='+ type;
      dataTable.ajax.url( '<?php echo $this->BaseUrl?>/default/statistic/reportlawyertrainingdatatable'+dataString).load();
    
  });  

  // tab 2
  var searchText1 = $("#year1").val();

  var hours = $("#hours").val();  

  var dataString1 = '?search='+ searchText1+'&hours='+ hours;
  
  var dataTable1 = $('#employee-grid1').DataTable( {
    "language": {
            "lengthMenu": "Hiển thị _MENU_ dòng trên trang",
            "zeroRecords": "Không tìm thấy",
            "info": "Hiển thị trang _PAGE_ of _PAGES_",
            "infoEmpty": "Không có dữ liệu thích hợp",
            "infoFiltered": "(lọc từ _MAX_ tổng số kết quả)",
            "paginate": {
                "first":      "Đầu",
                "last":       "Cuối",
                "next":       "Tới",
                "previous":   "Sau"
            }
        },
		"processing": true,
    "serverSide": true,
    "searching": false,
    "aLengthMenu": [[10, 50, 75, -1], [10, 50, 75, "All"]],
        "iDisplayLength": 10,
    "ajax":{
      url :"<?php echo $this->BaseUrl?>/default/statistic/reportlawyertrainingbyhoursdatatable"+dataString1, // json datasource
      type: "post",  // method  , by default get
      // done:function(){
      //   $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/categorytraining/listtest"+dataString);
      // },
      error: function(){  // error handling
        $(".employee-grid-error1").html("");
        $("#employee-grid1").append('<tbody class="employee-grid-error1"><tr><th colspan="3">Không tìm thấy kết quả</th></tr></tbody>');
        $("#employee-grid_processing1").css("display","none");
        
      }
    }
  } );

  $('#filtertable1').on('submit', function(e){
      e.preventDefault();
      
      var searchText1 = $("#year1").val();

      var hours = $("#hours").val();  

      var dataString1 = '?search='+ searchText1+'&hours='+ hours;
      dataTable1.ajax.url( '<?php echo $this->BaseUrl?>/default/statistic/reportlawyertrainingbyhoursdatatable'+dataString1).load();
    
  });  
      
});
</script>


<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="#" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i> Trang chủ</a> <a href="#" class="current">Thống kê - Danh sách luật sư tham gia bồi dưỡng</a> </div>
    <h1>Danh sách luật sư tham gia bồi dưỡng<h1>
  </div>
  
  <div class="container-fluid">
    <div class="widget-box">
      <div class="widget-title">
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#tab1">Danh sách LS tham gia bồi dưỡng</a></li>
                <li><a data-toggle="tab" href="#tab2">Danh sách LS bồi dưỡng theo số giờ</a></li>
            </ul>
      </div>
      <div class="widget-content tab-content">
          <div id="tab1" class="tab-pane active">
            <div  style="margin-bottom:4%;">  
              <form method="post" id="filtertable" action=""> 
                <table cellpadding="5" cellspacing="0">
                  <tbody><tr>
                      <td>   
                          Hình thức đóng phí : 
                      </td>
                      <td>   
                          <select name="type" id="type" style="width: 150px">
                              <option value="online">Đóng online</option>
                              <option value="offline">Đóng tại đoàn</option>
                              <option value="all">Tất cả</option>                                             
                          </select>	 
                      </td>	
                      <!-- <td>   
                          Số giờ bồi dưỡng : 
                      </td>
                      <td>   
                          <select name="hours" id="hours" style="width: 150px">
                              <option value="8">8</option>
                              <option value="16">16</option>
                              <option value="all">Tất cả</option>                                             
                          </select>	 
                      </td>	   -->
                        <td>
                            <label class="control-label">Chọn năm *:</label>
                        </td>
                        <td>                 
                          <div class="control-group">                              
                              <div class="controls">                                
                                  <select name="year" id="year" style="width: 150px">                            
                                      <option value="2019">2019</option>
                                      <option value="2018">2018</option>
                                      <option value="2017">2017</option>
                                      <option value="2016">2016</option>
                                  </select>	 
                              </div>
                          </div> 
                        </td>                
                        <td>
                        </td>
                        </tr>
                          <tr>                                   												
                            <td>
                              <input type="submit" name="sbsearch" value="   Tìm   ">   
                            </td>
                          </tr>								    
                  </tbody>
                </table>                 
              </form> 
            </div>
            <div class="row-fluid">
                <div class="span12">
                  <table id="employee-grid" class="table table-bordered"  cellpadding="0" cellspacing="0" border="0" class="display" width="100%">
                        <thead>
                          <tr>
                              <th>STT </th>
                              <th>Họ tên</th>
                              <th>CMND</th>
                              <th>Số điện thoại</th>
                              <th>Ngày sinh</th>
                              <th>Số thẻ LS</th>
                              <th>Ngày cấp thẻ LS</th>
                              <th>Địa chỉ thường trú</th>
                              <th>Nơi ở hiện tại </th>
                              <!-- <th>Đợt</th>                       -->
                              <!-- <th>Số mã LS</th>  -->
                              <th>Ngày đóng</th> 
                              <th>Số tiền</th>  
                              <th>Hình thức</th>                   
                          </tr>
                        </thead>
                  </table>
                </div>
            </div> 
          </div>
          <div id="tab2" class="tab-pane">
            <div  style="margin-bottom:4%;">  
              <form method="post" id="filtertable1" action=""> 
                <table cellpadding="5" cellspacing="0">
                  <tbody><tr>
                      <td>   
                          Số giờ bồi dưỡng : 
                      </td>
                      <td>   
                          <select name="hours" id="hours" style="width: 150px">
                              <option value="8">8</option>
                              <option value="16">16</option>
                              <option value="all">Tất cả</option>                                             
                          </select>	 
                      </td>	                     
                        <td>
                            <label class="control-label">Chọn năm *</label>
                        </td>
                        <td>                 
                          <div class="control-group">                              
                              <div class="controls">                                
                                  <select name="year1" id="year1" style="width: 150px">                                            
                                      <option value="2019">2019</option>
                                      <option value="2018">2018</option>
                                      <option value="2017">2017</option>
                                      <option value="2016">2016</option>
                                  </select>	 
                              </div>
                          </div> 
                        </td>                
                        <td>
                        </td>
                        </tr>
                          <tr>                                   												
                            <td>
                              <input type="submit" name="sbsearch" value="   Tìm   ">   
                            </td>
                          </tr>								    
                  </tbody>
                </table>                 
              </form> 
            </div>
            <div class="row-fluid">
                <div class="span12">
                  <table id="employee-grid1" class="table table-bordered"  cellpadding="0" cellspacing="0" border="0" class="display" width="100%">
                        <thead>
                          <tr>
                              <th>STT </th>
                              <th>Họ tên</th>
                              <th>CMND</th>
                              <th>Số điện thoại</th>
                              <th>Ngày sinh</th>
                              <th>Số thẻ LS</th> 
                              <th>Ngày cấp thẻ LS</th>
                              <th>Địa chỉ thường trú</th>
                              <th>Nơi ở hiện tại </th>
                          </tr>
                        </thead>
                  </table>
                </div>
            </div>
          </div>           
      </div>                            
    </div>
  </div>
</div>