<script>
$("#search").hide();
$(".searchfield").hide();
</script>
<div id="content">
    <div id="content-header">
        <div id="breadcrumb">
            <a href="#" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i></a>
            <a href="#" class="current">Gửi tin nhắn</a>
        </div>
    </div>
    <div class="row-fluid">
        <!-- open div general information-->
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title"><span class="icon"> <i class="icon-align-justify"></i> </span>
                    <h5>Thông tin chung</h5>
                </div>
                <div class="widget-content nopadding" id="detail-information">
                    <!--start form-->
                    <form action="" method="post">
                        <div class="row-fluid form-horizontal">
                            <div class="span6">
                                <label class="control-label">Tên nhóm:</label>
                                <div class="controls">
                                    <input type="text" id="group_name" name="group_name" class="span8"
                                           placeholder="Tên nhóm">
                                </div>
                            </div>
                            <div class="span6">
                                <label class="control-label">Trạng thái kích hoạt:</label>
                                <div class="controls">
                                    <div class="span4" style="margin-top: 6px;">
                                        <label>
                                            <div class="radio" id="uniform-undefined">
                                                <span class="checked">
                                                    <div class="radio" id="uniform-undefined">
                                                        <span class="checked">
                                                            <input type="radio" name="group_active" value="1"
                                                                   checked="checked"
                                                                   style="opacity: 0;">
                                                        </span>
                                                    </div>
                                                </span>
                                            </div>
                                            Kích hoạt
                                        </label>
                                    </div>
                                    <div class="span4" style="margin-top: 6px;">
                                        <label>
                                            <div class="radio" id="uniform-undefined">
                                                <span>
                                                    <div class="radio" id="uniform-undefined">
                                                        <span>
                                                            <input type="radio" name="group_active" value="0"
                                                                   style="opacity: 0;">
                                                        </span>
                                                    </div>
                                                </span>
                                            </div>
                                            Không kích hoạt
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="span8 offset2">
                                <label class="control-label">Danh sách luật sư:</label>
                                <div class="controls">
                                    <select name="customers[]" class="select2" multiple>
                                        <?php
                                        foreach ($this->customers as $customer) {
                                            ?>
                                            <option value="<?= $customer->cus_id ?>"><?= $customer->cus_fullname ?>
                                                - <?= $customer->cus_cellphone ?> - <?= $customer->cus_email ?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="row-fluid">
                            <div class="form-actions span12">
                                <div class="pull-right">
                                    <button id="btnAddGroup" class="btn btn-primary">Tạo mới</button>
                                </div>
                            </div>
                        </div>
                        <!-- end form -->
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        $('.select2').select2();
    });
</script>
