
<script>
$(document).ready(function(){

    $("#form-edit").validate({     
            rules:{
                // law_code:{
                // required:true
                // },
                // law_certfication_no:{
                // required:true
                // }
            },
            errorClass: "help-inline",
            errorElement: "span",
            highlight:function(element, errorClass, validClass) {
                $(element).parents('.control-group').addClass('error');
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').removeClass('error');
                $(element).parents('.control-group').addClass('success');
            },
            messages: {
                // //cus_cellphone: "Vui lòng nhập số điện thoại !",
                // // cus_identity_card: "Vui lòng nhập số CMND !",
                // law_code: "Vui lòng nhập mã luật sư !",
                // law_certfication_no: "Vui lòng nhập số chứng chỉ !",
            },
            submitHandler: function(form,e) {
                console.log('Form submitted');
                console.log($('#form-edit').serialize());
                $.ajax({
                      type: "POST",
                      url: "<?php echo $this->BaseUrl?>/default/group/update/",
                      data: $('#form-edit').serialize() ,
                      cache: false,
                      success: function(html)
                      {   
                    
                        $("#message").html("Cập nhật thông tin thành công");
                                                           
                      }
                });
                return false;                       
            }
        });
});  

</script>
<form id="form-edit" class="form-horizontal">
    <p id="message"></p> 
    <input type="hidden" name="group_id" value="<?php echo $this->group['group_id']; ?>" /> 
    <div class="control-group">
        <label class="control-label">Tên nhóm</label>
        <div class="controls">
            <input type="text" class="span2" name="group_name" id="group_name" value="<?php echo $this->group['group_name']; ?>">
        </div>

        <label class="control-label">Danh sách luật sư</label>
        <div class="controls">
            <select name="customers[]" class="select2" multiple>
                <?php
                foreach ($this->customers as $customer) {
                ?>
                   <?php if(in_array($customer->cus_id, $this->existed)){                       
                   ?>
                    <option selected value="<?= $customer->cus_id ?>"><?= $customer->cus_fullname ?>
                        - <?= $customer->cus_cellphone ?> - <?= $customer->cus_email ?></option>
                   <?php }else{ ?>
                    <option value="<?= $customer->cus_id ?>"><?= $customer->cus_fullname ?>
                        - <?= $customer->cus_cellphone ?> - <?= $customer->cus_email ?></option>
                   <?php } ?> 
                <?php } ?>   
            </select>
        </div>
    </div>
    <!-- <div class="form-actions"> -->
    <button style="float: right;" type="submit" class="btn">Save</button>
    <!-- </div> -->
</form>
<script>
    $(document).ready(function(){
        $('.select2').select2();
    });
</script>
         