<script>
$(document).ready(function(){
$("#search").hide();
$(".searchfield").hide();
});

function updateGroup($id){
    var dataString = '?group_id='+ $id;
    $.ajax({
        type: "GET",
        url: "<?php echo $this->BaseUrl?>/default/group/detail"+dataString ,
        cache: false,
        success: function(html)
        { 
            //alert(html);
            $("#message").html(html);
            $("#model-warning").modal('show');
        }
    });       

}
</script>
<div id="model-warning" class="modal fade"  data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
        
      </div>
        
        <div class="modal-body">
            <p id="message"></p>
        </div>
        <div class="modal-footer">
          <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button> -->
          <!-- <button type="submit" class="btn btn-primary save-edit">Lưu</button> -->
        </div>
      
    </div>
  </div>
</div>
<div id="content">
    <div id="content-header">
        <div id="breadcrumb">
            <a href="#" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i></a>
            <a href="#" class="current">Groups</a>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="widget-box">
                <div class="widget-title">
                    <ul class="nav nav-tabs">
                        <li class="active"><a id="internship" data-toggle="tab" href="#tab1">Danh sách nhóm</a></li>
                    </ul>
                </div>
                <div class="widget-content tab-content">
                    <div id="tab1" class="tab-pane active">
                        <div class="row-fluid">
                            <div class="span12">
                                <div class="widget-box">
                                    <div class="widget-title">
                                        <span class="icon"><i class="icon-th"></i></span>
                                        <h5>Danh sách nhóm</h5>
                                    </div>
                                    <div class="widget-content nopadding">
                                        <table class="table table-bordered">
                                            <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>Tên nhóm</th>
                                                <th>Thao tác</th>
                                            </tr>
                                            </thead>
                                            <tbody id="table-lawyer">
                                            <?php                                 
                                                     if($this->groups != null){
                                                         $index = 0;
                                                        foreach ($this->groups as $cat) {   
                                                            $index +=1;                                        
                                                            $text = ''; 
                                                            if($cat['group_active'] == 1){
                                                                $text = '<td>Đang hoạt động</td>';
                                                            }else{
                                                                $text = '<td>Ngưng hoạt động</td>';  
                                                            }    
                                                            echo ' <tr class="gradeC">'.
                                                            '<td>'.$index .'</td>'. 
                                                            '<td>'.$cat['group_name'].'</td>'.                                                                                     
                                                            '<td class="center">'.
                                                                '<button onClick="updateGroup('.$cat['group_id'].');"><i class="icon-pencil"></i></button>'.' '.
                                                                
                                                        '</tr>';                          
                                                        }  
                                                     }
                                            ?> 

                                            </tbody>
                                        </table>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>