<script>
$(document).ready(function(){
  
    $("#search").hide();
  $(".searchfield").hide();

  $('select').select2();

  $('.datepicker-start').datepicker();

  $('.datepicker-end').datepicker();

  $("#model-warning").modal("hide");

  var searchText = $("#category_training_id").val();


  var dataString = '?search='+ searchText;
  
  var dataTable = $('#employee-grid').DataTable( {
    "language": {
            "lengthMenu": "Hiển thị _MENU_ dòng trên trang",
            "zeroRecords": "Không tìm thấy",
            "info": "Hiển thị trang _PAGE_ of _PAGES_",
            "infoEmpty": "Không có dữ liệu thích hợp",
            "infoFiltered": "(lọc từ _MAX_ tổng số kết quả)",
            "paginate": {
                "first":      "Đầu",
                "last":       "Cuối",
                "next":       "Tới",
                "previous":   "Sau"
            }
        },
		"processing": true,
    "serverSide": true,
    "searching": false,
    "aLengthMenu": [[10, 50, 75, -1], [10, 50, 75, "All"]],
        "iDisplayLength": 10,
    "ajax":{
      url :"<?php echo $this->BaseUrl?>/default/trainingmanagement/listtrainedcertificationdatatable"+dataString, // json datasource
      type: "post",  // method  , by default get
      // done:function(){
      //   $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/categorytraining/listtest"+dataString);
      // },
      error: function(){  // error handling
        $(".employee-grid-error").html("");
        $("#employee-grid").append('<tbody class="employee-grid-error"><tr><th colspan="3">Không tìm thấy kết quả</th></tr></tbody>');
        $("#employee-grid_processing").css("display","none");
        
      }
    }    
  } );

  $('#filtertable').on('submit', function(e){
      e.preventDefault();
      
      var searchText = $("#category_training_id").val();


      var dataString = '?search='+ searchText;
      dataTable.ajax.url( '<?php echo $this->BaseUrl?>/default/trainingmanagement/listtrainedcertificationdatatable'+dataString).load();
    
    });   

    // Handle form submission event
  //  $('.checkin').on('click', function(e){
  //     e.preventDefault();
     
  //     var form = this;

  //     var searchText = $("#category_training_id").val();
  //     var dataString = '?search='+ searchText;
  //      createCertificationNumberTraining();
  //      dataTable.ajax.url( '<?php echo $this->BaseUrl?>/default/trainingmanagement/listtrainedcertificationdatatable'+dataString).load();
  //  });

  $('.print').on('click', function(e){

      if(dataTable.rows().count() <= 0){
        //alert("Không có dữ liệu luật sư tham gia bồi dưỡng để in chứng chỉ.");
        $("#model-warning").modal("show");
      }else{
        e.preventDefault();
     
        var form = this;

        var searchText = $("#category_training_id").val();
        var dataString = '?search='+ searchText;
        printCertificationTrainingByCatId(searchText);
        // dataTable.ajax.url( '<?php echo $this->BaseUrl?>/default/trainingmanagement/listtrainedcertificationdatatable'+dataString).load();
      }     
   });
      
});

function printCertificationTrainingByCatId($id){
 
 var dataString = '?category_training_id='+ $id;
      $.ajax({
           type: "GET",
           timeout: 120000,
           async:false,
           dataType : 'html',
           url: "<?php echo $this->BaseUrl?>/default/trainingmanagement/printtraningcattraining"+dataString ,
           cache: false,
           success: function(html)
           {                 
               var mywindow = window.open('', 'Print-Window');

               mywindow.document.write('<html><head><title>' + document.title  + '</title>');
               mywindow.document.write('</head><body >');
               mywindow.document.write('<h1>' + document.title  + '</h1>');
               mywindow.document.write(html);
               mywindow.document.write('</body></html>');

               mywindow.document.close(); // necessary for IE >= 10
               mywindow.focus(); // necessary for IE >= 10*/

               mywindow.print();
               mywindow.close();

           }
     });
}


  // function createCertificationNumberTraining(){
  //         var searchText = $("#category_training_id").val();
  //        $.ajax({
  //             type: "POST",
  //             url: "<?php echo $this->BaseUrl?>/default/trainingmanagement/createcertificationnumber" ,
  //             cache: false,
  //             data:{id:searchText},
  //             success: function(html)
  //             { 
  //               // //alert(html);
  //               // $("#message").html(html);
  //               // $("#model-warning").modal('show');
  //             }
  //        });  

  // }
</script>


<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="#" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i> Trang chủ</a> <a href="#" class="current">Thống kê - Tạo chứng chỉ bồi dưỡng các khóa học</a> </div>
    <h1>Tạo chứng chỉ bồi dưỡng của các khóa</h1>
  </div>
  
  <div class="container-fluid">
    <div  style="margin-bottom:4%;">  
        <form method="post" id="filtertable" action=""> 
          <table cellpadding="5" cellspacing="0">
            <tbody><tr>
                  <td>
                      <label>Chọn đợt bồi dưỡng *:</label>
                  </td>
                  <td>  
                    <!-- <input type="text" id="txtsearch" name="txtsearch" placeholder="Vui lòng nhập mã luật sư" value="">   -->
                    <div class="control-group">
                              
                                <div class="controls">                                
                                  <select style="max-width:200px;" class="span3" id="category_training_id" name="category_training_id">
                                  <?php  
                                       foreach ($this->categoriestrainings as $co) {
                                        //if($cat['category_fee_lawyer_id'] == 1){
                                          echo '<option value="'.$co['cat_train_id'].'" class="span8">'.$co['cat_train_number'].'</option>';
                                        //}                                          
                                    }
                                  ?>    
                                  </select>
                              </div>
                       </div> 
                  </td>     
                  <td style="padding-left: 25px;">
                      <input type="submit" name="sbsearch" value="   Tìm   "> 
                  </td>   
                  </tr>
                    <!-- <tr>                                   												
                      <td>
                        <input type="submit" name="sbsearch" value="   Tìm   ">   
                      </td>
                    </tr>	 -->
                    <!-- <p> **** Lưu ý nếu mã chứng chỉ trống tạo phải tạo mã trước khi In </p> -->
                    <tr>
                        <!-- <td>
                        <button class="btn btn-primary checkin">Tạo chứng chỉ cho khóa học</button>
                        </td> -->
                        <td>
                        <button class="btn btn-primary print">In hàng loạt chứng chỉ cho đợt bồi dưỡng</button>
                        </td>
                    </tr>							    
            </tbody>
          </table>                 
        </form> 
        
    </div>
    <div class="row-fluid">
        <div class="span12">
          <table id="employee-grid" class="table table-bordered"  cellpadding="0" cellspacing="0" border="0" class="display" width="100%">
                <thead>
                  <tr>
                      <!-- <th></th> -->
                      <th>Tên </th>
                      <th>Số thẻ LS</th>
                      <th>Ngày cấp thẻ LS </th>
                      <th>Địa chỉ thường trú</th>
                      <th>Nơi ở hiện tại </th>
                      <th>Số biên nhận</th>
                      <th>Tên khóa học</th>
                      <th>Đợt bồi dưỡng</th>
                      <!-- <th>Điểm danh</th> -->
                      <th>Số chứng chỉ bồi dưỡng</th>
                  </tr>
                </thead>
          </table>
        </div>
    </div> 
  </div>
</div>

<!-- Modal -->
<div id="model-warning" class="modal fade" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <p id="message">Không tồn tại luật sư tham gia đợt bồi dưỡng để in chứng chỉ.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>