<script>
$(document).ready(function(){
  
    $("#search").hide();
  $(".searchfield").hide();

  $('.datepicker-start').datepicker();

  $('.datepicker-end').datepicker();

  var searchText = $("#category_training_id").val();


  var dataString = '?search='+ searchText;
  
  var dataTable = $('#employee-grid').DataTable( {
    "language": {
            "lengthMenu": "Hiển thị _MENU_ dòng trên trang",
            "zeroRecords": "Không tìm thấy",
            "info": "Hiển thị trang _PAGE_ of _PAGES_",
            "infoEmpty": "Không có dự liệu thích hợp",
            "infoFiltered": "(lọc từ _MAX_ tổng số kết quả)",
            "paginate": {
                "first":      "Đầu",
                "last":       "Cuối",
                "next":       "Tới",
                "previous":   "Sau"
            }
        },
		"processing": true,
    "serverSide": true,
    "searching": false,
    "aLengthMenu": [[10, 50, 75, -1], [10, 50, 75, "All"]],
        "iDisplayLength": 10,
    "ajax":{
      url :"<?php echo $this->BaseUrl?>/default/trainingmanagement/listtraineddatatable"+dataString, // json datasource
      type: "post",  // method  , by default get
      // done:function(){
      //   $("#downloadUrl").attr("href", "<?php echo $this->BaseUrl?>/default/categorytraining/listtest"+dataString);
      // },
      error: function(){  // error handling
        $(".employee-grid-error").html("");
        $("#employee-grid").append('<tbody class="employee-grid-error"><tr><th colspan="3">Không tìm thấy kết quả</th></tr></tbody>');
        $("#employee-grid_processing").css("display","none");
        
      }
    },
    'columnDefs': [
         {
            'targets': 0,
            'checkboxes': {
               'selectRow': true
            }
         }
      ],
      'select': {
         'style': 'multi'
      }
  } );

  $('#filtertable').on('submit', function(e){
      e.preventDefault();
      
      var searchText = $("#category_training_id").val();


      var dataString = '?search='+ searchText;
      dataTable.ajax.url( '<?php echo $this->BaseUrl?>/default/trainingmanagement/listtraineddatatable'+dataString).load();
    
    });   

    // Handle form submission event
   $('.checkin').on('click', function(e){
      e.preventDefault();
     
      var form = this;

      var rows_selected = dataTable.column(0).checkboxes.selected();

      // Iterate over all selected checkboxes

      var listIds = [];
      $.each(rows_selected, function(index, rowId){
        //console.log(rowId);
        listIds.push(rowId);
        //updateCheckInOfPaymentTraining();
         // Create a hidden element
        //  $(form).append(
        //      $('<input>')
        //         .attr('type', 'hidden')
        //         .attr('name', 'id[]')
        //         .val(rowId)
        //  );
      });

      var searchText = $("#category_training_id").val();
      var dataString = '?search='+ searchText;
       updateCheckInOfPaymentTraining(listIds);
       dataTable.ajax.url( '<?php echo $this->BaseUrl?>/default/trainingmanagement/listtraineddatatable'+dataString).load();
   });
      
});

  function updateCheckInOfPaymentTraining($data){
     //alert("member status");
    // var dataString = '?payment_lawyer_off_id='+ $id;
         $.ajax({
              type: "POST",
              url: "<?php echo $this->BaseUrl?>/default/trainingmanagement/updatecheckin" ,
              cache: false,
              data:{ids:$data},
              success: function(html)
              { 
                // //alert(html);
                // $("#message").html(html);
                // $("#model-warning").modal('show');
              }
         });  

  }
</script>


<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="#" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i> Trang chủ</a> <a href="#" class="current">Thống kê - Điểm danh luật sư các khóa học</a> </div>
    <h1>Điểm danh luật sư của các khóa</h1>
  </div>
  
  <div class="container-fluid">
    <div  style="margin-bottom:4%;">  
        <form method="post" id="filtertable" action=""> 
          <table cellpadding="5" cellspacing="0">
            <tbody><tr>
                  <td>
                      <label class="control-label">Chọn đợt bồi dưỡng *:</label>
                  </td>
                  <td>  
                    <!-- <input type="text" id="txtsearch" name="txtsearch" placeholder="Vui lòng nhập mã luật sư" value="">   -->
                    <div class="control-group">
                              
                                <div class="controls">                                
                                  <select class="span3" id="category_training_id" name="category_training_id">
                                  <?php  
                                       foreach ($this->categoriestrainings as $co) {
                                        //if($cat['category_fee_lawyer_id'] == 1){
                                          echo '<option value="'.$co['cat_train_id'].'" class="span8">'.$co['cat_train_number'].'</option>';
                                        //}                                          
                                    }
                                  ?>    
                                  </select>
                              </div>
                       </div> 
                  </td>     
                  <td style="padding-bottom: 25px;">
                      <input type="submit" name="sbsearch" value="   Tìm   "> 
                  </td>   
                  </tr>
                    <!-- <tr>                                   												
                      <td>
                        <input type="submit" name="sbsearch" value="   Tìm   ">   
                      </td>
                    </tr>	 -->
                    <tr>
                        <td>
                        <button class="btn btn-primary checkin">Điểm danh</button>
                        </td>
                    </tr>							    
            </tbody>
          </table>                 
        </form> 
        
    </div>
    <div class="row-fluid">
        <div class="span12">
          <table id="employee-grid" class="table table-bordered"  cellpadding="0" cellspacing="0" border="0" class="display" width="100%">
                <thead>
                  <tr>
                      <th></th>
                      <th>Tên </th>
                      <th>Mã luật sư</th>
                      <th>Ngày cấp mã </th>
                      <th>Mã biên nhận</th>
                      <th>Tên khóa học</th>
                      <th>Đợt bồi dưỡng</th>
                      <th>Điểm danh</th>
                      <!-- <th>Số chứng chỉ bồi dưỡng</th>                       -->
                  </tr>
                </thead>
          </table>
        </div>
    </div> 
  </div>
</div>