
<script>
$(document).ready(function(){

    $("#cus_id").prop("disabled",true);

    $(".close-modal").on('click',function(){
       location.reload();
    });

    $("#form-edit").validate({     
            rules:{
                // law_code:{
                // required:true
                // },
                // law_certfication_no:{
                // required:true
                // }
            },
            errorClass: "help-inline",
            errorElement: "span",
            highlight:function(element, errorClass, validClass) {
                $(element).parents('.control-group').addClass('error');
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').removeClass('error');
                $(element).parents('.control-group').addClass('success');
            },
            messages: {
                //cus_cellphone: "Vui lòng nhập số điện thoại !",
                // cus_identity_card: "Vui lòng nhập số CMND !",
                law_code: "Vui lòng nhập mã luật sư !",
                law_certfication_no: "Vui lòng nhập số chứng chỉ !",
            },
            submitHandler: function(form,e) {
                console.log('Form submitted');
                $.ajax({
                      type: "POST",
                      url: "<?php echo $this->BaseUrl?>/default/trainingmanagement/update/",
                      data: $('#form-edit').serialize() ,
                      cache: false,
                      success: function(html)
                      {   
                        $("#message").html("Cập nhật biên nhận bồi dưỡng thành công"); 
                        //$(".close-modal").hide();  
                                                                               
                      }
                });
                return false;                       
            }
        });
});  

function changeLawyer(){
    //alert("testcode");
    $("#cus_id").prop("disabled",false);
    $("#action_type").val("update");
}

</script>

<form id="form-edit" class="form-horizontal">            
              <p id="message"></p>
              <input type="hidden" id="action_type" name="action_type" value=""/> 
              <input type="hidden" name="payment_training_off_id" value="<?php echo $this->paymenttraningofflinedata['payment_training_off_id']; ?>" /> 
              <!-- <div class="control-group">
                    <label class="control-label">Tên LS bồi dưỡng </label>
                    <div class="controls">
                        <input type="text" disabled class="span2" value="<?php echo $this->paymenttraningofflinedata['cus_firstname'].' '.$this->paymenttraningofflinedata['cus_lastname']; ?>">
                    </div>
              </div> -->

                
               <div class="control-group">
                        <label class="control-label">Tên LS bồi dưỡng:</label>
                        <div class="controls change-lawyer"> 
                            <select  class="span3" id="cus_id" name="cus_id">
                            <?php  
                                foreach ($this->lawyers as $law) {
                                    if($this->paymenttraningofflinedata['cus_id'] != $law['cus_id']){
                                        echo '<option value="'.$law['cus_id'].'" class="span3">'.$law['cus_firstname'].' '.$law['cus_lastname'].'- '.$law['cus_identity_card'].'</option>';     
                                    }else{
                                        echo '<option selected value="'.$law['cus_id'].'" class="span3">'.$law['cus_firstname'].' '.$law['cus_lastname'].'- '.$law['cus_identity_card'].'</option>';     
                                    }                                    
                                }
                                ?>    
                            </select>
                            <a onCLick="changeLawyer();">Đổi luật sư:</a>
                        </div>
                </div>                 

              

              <div class="control-group">        
                    <label class="control-label">Mã số biên nhận:</label>
                    <div class="controls">
                    <input type="text" disabled value="<?php echo $this->paymenttraningofflinedata['payment_training_off_code']; ?>" class="span3" placeholder="Vui lòng nhập mã số chứng chỉ" />
                    </div>
                </div> 

             <div class="control-group">        
                <label class="control-label">Ngày đóng phí:</label>
                <div class="controls">
                <input type="text" disabled value="<?php echo ($this->paymenttraningofflinedata['payment_training_off_created_date'] != null && $this->paymenttraningofflinedata['payment_training_off_created_date'] != ''
                && $this->paymenttraningofflinedata['payment_training_off_created_date'] != '1900-01-01 00:00:00') ? date('d/m/Y', strtotime($this->paymenttraningofflinedata['payment_training_off_created_date'])) : '' ; ?>" class="span3" placeholder="Vui lòng nhập mã số chứng chỉ" />
                </div>
            </div>   

            <div class="control-group">        
                    <label class="control-label">Loại phí:</label>
                    <div class="controls">
                    <input type="text" disabled value="<?php echo $this->paymenttraningofflinedata['name']; ?>" class="span3" placeholder="Vui lòng nhập mã số chứng chỉ" />
                    </div>
                </div>

              <!-- <label class="control-label">Trạng thái biên nhận</label>
                <div class="controls">
                    <div class="row-fluid">
                        <div class="span3">
                        <label>                            
                            <input type="radio" name="payment_training_off_status" value="1" <?php echo ($this->paymenttraningofflinedata['payment_training_off_status'] == 1) ? 'checked' :'' ?>/>
                    Đã thanh toán</label>
                        </div>
                        <div class="span6">
                            <label>
                            <input type="radio" name="payment_training_off_status" value="0" <?php echo ($this->paymenttraningofflinedata['payment_training_off_status'] == 0) ? 'checked' :'' ?>/>
                            Chưa thanh toán</label> 
                        </div>
                    </div>                                               
                </div>  -->
             

             
              <!-- <div class="form-actions"> -->
                <button style="float: right;" type="submit" class="btn">Lưu</button>
              <!-- </div> -->
            </form>
         


