<script>
    $(document).ready(function(){

      $("#model-warning").modal("hide");
      $(".message-success").hide(); 
      $('select').select2();
      
      var date = new Date();
      var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());

      $('.datepicker-ngaynop').datepicker({ format: 'dd/mm/yyyy' });
      $('.datepicker-ngaynop').datepicker('setValue', today);
    
    $(".close-modal").on('click',function(){
      location.reload();
    });

    //   $("#notification").html("Thông báo : Số tiền bạn đóng phí thành viên là ")

    $("#search-global").keyup(function(e) {        
        $("#cus_id").val('');
        var key = e.keyCode;

        if (key == 40 || key == 38 || key == 13) {
           return false;
        }   

        var searchbox = $(this).val();
        var dataString = 'searchword='+ searchbox+'&searchfield='+$("#search-field").val();
        searchData(searchbox,dataString);   
    });  

    $('#search').on("keydown", "#search-global", function (e) {
        console.log("event key down");
        var $listItems = $('.display-box-search-result li');
        
        var key = e.keyCode,
        $selected = $listItems.filter('.hovered'),$current;

        var $scrollable = $("#display-content-search-global");
		    var scrollTop = $scrollable.scrollTop();

        if (key != 40 && key != 38 && key != 13)
            return;

        if (key == 40) // Down key
        {
            $listItems.removeClass('hovered');
            if (!$selected.length || $selected.is(':last-child')) {
                $current = $listItems.eq(0);
            } else {
                $current = $selected.next();
            }
            $current.addClass('hovered');
            
        } 
        else if (key == 38) // Up key
        {
            $listItems.removeClass('hovered');
            if (!$selected.length || $selected.is(':first-child')) {
                $current = $listItems.last();
            } else {
                $current = $selected.prev();
            }       
            $current.addClass('hovered');
        } 
        else if (key == 13) // Enter key
        {
            $current = $listItems.filter('.hovered');
            $current.trigger('click');
            return false;
        }

        $("#display-content-search-global").scrollTop(0);//set to top
        $("#display-content-search-global").scrollTop($('.hovered:first').offset().top-$("#display-content-search-global").height());       
        
    });
       

    $("#form-internship").validate({
          rules:{
            course_regis_date:{
              required:true
            },
            amount:{
              required:true
            }
          },
          errorClass: "help-inline",
          errorElement: "span",
          highlight:function(element, errorClass, validClass) {
            $(element).parents('.control-group').addClass('error');
          },
          unhighlight: function(element, errorClass, validClass) {
            $(element).parents('.control-group').removeClass('error');
            $(element).parents('.control-group').addClass('success');
          },
          messages: {
            regis_date: "Chọn ngày đóng phí bồi dưỡng"   ,
            amount:"Vui lòng nhập số tiền"           
          },
          submitHandler: function(form,e) {
            console.log('Form submitted');           
            $.ajax({
                  type: "POST",
                  url: "<?php echo $this->BaseUrl?>/default/trainingmanagement/create/",
                  data: $('#form-internship').serialize() ,
                  cache: false,
                  success: function(html)
                  {   
                    //$(".message-success").show();
                    //alert(html);
                    $("#message").html(html);
                    $("#model-warning").modal("show");
                    loadDataForTab($("#cus_id").val(),"#table-lawyer","lawyer");
                    // $("#display-content-search").html('');
                    // $("#display-content-search").html(html);                  
                  }
            });
            return false;                       
        }
	  });

    $('#display-content-search-global').on('click', function(event) {
      console.log("action event");
      var id = $(event.target).attr('id');
      var dataString = '?searchword='+ id;
       $.ajax({
            type: "GET",
            url: "<?php echo $this->BaseUrl?>/default/customers/detail"+dataString ,
            //data: dataString+'?format=html',
            dataType: 'json',
            cache: false,
            success: function(data)
            {   
 
              if(data.cus_id != null && data.cus_id != undefined){
                     $("#cus_id").val(data.cus_id);
                     $("#law_certification_createdate").val(data.law_certification_createdate);
                     loadDataForTab(data.cus_id,"#table-lawyer","lawyer");
                     $('#display-content-search-global').html('');
                     //$("#search-global").val(data.cus_identity_card);
                     if($("#search-field").val() != null && $("#search-field").val() == "name"){
                      $("#search-global").val(data.cus_fullname);
                     }else if($("#search-field").val() != null && $("#search-field").val() == "lawyer_number"){
                      $("#search-global").val(data.cus_lawyer_number);
                     }else if($("#search-field").val() != null && $("#search-field").val() == "identity_card"){
                      $("#search-global").val(data.cus_identity_card);
                     }else{
                      $("#search-global").val(data.cus_cellphone);
                     }
                     $("#cus_cellphone").val(data.cus_cellphone);
                     $("#cus_firstname").val(data.cus_firstname);
                     $("#cus_lastname").val(data.cus_lastname);
                     $("#cus_identity_card").val(data.cus_identity_card);
                     $("#cus_username").val(data.cus_username);
                     $("#cus_birthday").val(data.cus_birthday);
                     $("#cus_country").val(data.cus_country);

                    console.log($("#amount-year").val());
                     var d = new Date(); // January 1, 2000 
                     var birthdate =  data.cus_birthday;
                     //set ngày sinh
                     var age = parseInt(d.getFullYear()-birthdate.split('/')[2]);
                     if(age >=65 && age<=69){
                      $("#amount").val(parseInt(0.5*$("#amount-year").val()));
                      $("#showAmount").val("125,000");
                      $("#messagesSumMooney").html('Bạn được giảm 50%. Số tiền là : '+ numberWithCommas($("#amount").val()));
                     }else if(age>=70){
                      //$("#amount").val(0);
                      //$("#showAmount").val("0");
                      // $("#messagesSumMooney").html('Bạn được giảm 100%. Bạn phải lập biên nhận để được tạo chứng chỉ.');  
                      //$("#messagesSumMooney").html('Bạn được giảm 100%. Bạn không cần phải lập biên nhận.');  
                      var d = new Date(); // January 1, 2000 
                      var cchn = data.law_certification_createdate;
                      if(cchn != null && cchn != ''){
                        var cchnyear = parseInt(d.getFullYear()-cchn.split('/')[2]);
                        if(cchnyear < 20){
                          $("#amount").val(0);
                          $("#showAmount").val(0);
                          $("#age").val(1);
                          $("#messagesSumMooney").html('Bạn được giảm 100%. Bạn phải lập biên nhận để được tạo chứng chỉ.');                        
                        }else{
                          $("#amount").val(0);
                          $("#showAmount").val("0");  
                          $("#age").val(0);                        
                          $("#messagesSumMooney").html('Bạn được giảm 100%. Bạn không cần phải lập biên nhận.');  
                        }
                      }                      
                      // $("#age").val(age);
                      // $("#amount").val(parseInt($("#amount-year").val()));
                      // $("#showAmount").val(numberWithCommas($("#amount-year").val()));
                      // $("#messagesSumMooney").html(numberWithCommas($("#amount-year").val()));
                     }else{
                      $("#amount").val(parseInt($("#amount-year").val()));
                      $("#messagesSumMooney").html(numberWithCommas($("#amount-year").val()));
                      
                     }

                     
              }
              //console.log(data);             
            }, error: function(msg){               
            }           
            });
    });

 });

  function numberWithCommas(x) {
    return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
  }

  function isNumber(n) {
    return !isNaN(parseFloat(n)) && isFinite(n);
  }

  function printPaymentOfflineTrainingStatus($id){
    var dataString = '?payment_training_off_id='+ $id;
         $.ajax({
              type: "GET",
              timeout: 120000,
              async:false,
              dataType : 'html',
              url: "<?php echo $this->BaseUrl?>/default/trainingmanagement/printtrainingpayment"+dataString ,
              cache: false,
              success: function(html)
              { 
                var mywindow = window.open('', 'Print-Window');

                mywindow.document.write('<html><head><title>' + document.title  + '</title>');
                mywindow.document.write('</head><body >');
                mywindow.document.write('<h1>' + document.title  + '</h1>');
                mywindow.document.write(html);
                mywindow.document.write('</body></html>');

                mywindow.document.close(); // necessary for IE >= 10
                mywindow.focus(); // necessary for IE >= 10*/

                mywindow.print();
                mywindow.close();
              }
         });  

  }

  function loadDataForTab(cus_id,div_content,typetab){ 
      // alert("test code");
        var dataString = '?cus_id='+ cus_id;        
        if(cus_id =='' || cus_id == undefined){
            $("#table-lawyer").html('');
        } else
        {
            var url = "<?php echo $this->BaseUrl?>/default/trainingmanagement/listtraining"+dataString;

            $.ajax({
                type: "GET",
                url: url,
                //data: dataString,
                //dataType: 'json',
                cache: false,
                success: function(html)
                {   
                  // alert(html);
                  $(div_content).html(html);                  
                }
            });
        }
 return false;   
}

  function searchData(searchbox,dataString){
        if(searchbox ==''){
            $("#display-content-search-global").html('');           
        } else
        {
            $.ajax({
                type: "POST",
                url: "<?php echo $this->BaseUrl?>/default/customers/search/",
                data: dataString,
                cache: false,
                success: function(html)
                {               
                  $("#display-content-search-global").html(html);                  
                }
            });           
        }
  }  

</script>

 <div id="content">
    <div id="content-header">
      <div id="breadcrumb"> <a href="" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i></a> <a href="#" class="current">Phí bồi dưỡng</a> </div>
      <!-- <h1>Quản lý luật sư</h1> -->
    </div>
   <div class="container-fluid"> 
   <div class="row-fluid">
      <div class="alert alert-success alert-dismissible message-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <strong>Thông báo</strong> Bạn đã tạo thành công một biên nhận phí bồi dưỡng.
        </div>
    </div>   
    <!-- <h4>Thêm mới luật sư tập sự</h4> -->
    <div class="row-fluid">     
        <!-- open div general information-->
        <div class="span12">          
          <div class="widget-box">
            <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
              <h5>Thông tin chung</h5>
            </div>
            <div class="widget-content nopadding" id="detail-information">
            <!--start form-->              
                <div class="row-fluid form-horizontal">
                  <div class="span6">
                        <label class="control-label">Họ và lót:</label>
                        <div class="controls">
                          <input type="text" disabled id="cus_firstname"  name="cus_firstname" class="span8" placeholder="Họ của luật sư" />
                        </div>  
                        <label class="control-label">Tên :</label>
                        <div class="controls">
                          <input type="text" disabled id="cus_lastname"  name="cus_lastname" class="span8" placeholder="Tên của luật sư" />
                        </div>   
                        <label class="control-label">Ngày sinh :</label>
                        <div class="controls">
                          <input type="text" disabled id="cus_birthday"  name="cus_birthday" class="span8" placeholder="Ngày sinh" />
                        </div>  
                  </div>  
                  <div class="span6">
                      <label class="control-label">Số điện thoại :</label>
                      <div class="controls">
                        <input type="text" disabled disabled id="cus_cellphone"  name="cus_cellphone" class="span8" placeholder="Số điện thoại" />
                      </div> 
                      <label class="control-label">Số chứng minh nhân dân :</label>
                      <div class="controls">
                        <input type="text" disabled id="cus_identity_card"  name="cus_identity_card" class="span8" placeholder="Số chứng minh nhân dân" />
                      </div>  
                      <!-- <label class="control-label">Tỉnh thành :</label>
                      <div class="controls">
                        <input type="text" id="cus_country"  name="cus_country" class="span8" placeholder="Tỉnh thành" />
                      </div>                       -->
                  </div>                  
                </div>            
              <!-- end form -->
            </div>          
          </div>
        </div>   
      </div> 

       <div class="row-fluid">
        <!-- open div general information-->
        <div class="span12">          
          <div class="widget-box">
            <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
              <h5>Thêm mới phí bồi dưỡng</h5>
            </div>
            <div class="widget-content nopadding" id="detail-information">
            <!--start form-->
              <form id="form-internship" class="form-horizontal" novalidate="novalidate">
                <input type="hidden" name="cus_id" id="cus_id" />
                <input type="hidden" name="amount" id="amount" />
                <input type="hidden" name="age" id="age" />
                <input type="hidden" name="law_certification_createdate" id="law_certification_createdate" />
                <input type="hidden" value="<?php echo $this->payment_training_off_code; ?>" name="payment_training_off_code" id="payment_training_off_code" />
                <input type="hidden" value="<?php echo $this->amountYear; ?>" id="amount-year" />
                <div class="row-fluid">
                  <div class="span6">
                      <!-- <label class="control-label">Thông tin khóa học :</label>
                      <div class="controls">
                        <input type="text" id="cus_cellphone"  name="cus_cellphone" class="span8" placeholder="số điện thoại" />
                      </div>  -->
                      <!-- <div class="control-group">
                        <label class="control-label">Chọn ngày nộp phí bồi dưỡng *</label>
                        <div class="controls">                  
                          <div id="dp5" data-date="12-02-2012" class="input-append date datepicker-ngaynop">                    
                            <input name="course_regis_date" data-date-format="mm-dd-yyyy" class="span12" >
                            <span class="add-on"><i class="icon-th"></i></span> </div>
                        </div>
                      </div>   -->
                      <div class="control-group"> 
                        <label class="control-label">Số biên nhận:</label>
                        <div class="controls">
                          <strong><?php echo $this->payment_training_off_code; ?></strong>
                        </div>
                      </div>
                      <div class="control-group">
                              <label class="control-label">Chọn khóa bồi dưỡng *:</label>
                                <div class="controls">                                
                                  <select class="span12" id="category_training_id" name="category_training_id">
                                  <?php  
                                       foreach ($this->categoriestrainings as $co) {
                                        //if($cat['category_fee_lawyer_id'] == 1){
                                          echo '<option value="'.$co['cat_train_id'].'" class="span12">'.$co['cat_train_name'].'</option>';
                                        //}                                          
                                    }
                                  ?>    
                                  </select>
                              </div>
                       </div> 
                  </div>  
                  
                  <div class="span6">
                        <div class="control-group">
                              <label class="control-label">Chọn loại phí *:</label>
                                <div class="controls"> 
                                  <select class="span8" id="category_fee_id" name="category_fee_id">
                                  <?php  
                                      foreach ($this->categoryfee as $cat) {
                                         // if($cat['category_fee_lawyer_id'] == 1){
                                            echo '<option value="'.$cat['category_fee_id'].'" class="span8">'.$cat['name'].'</option>';
                                         // }                                          
                                      }
                                      ?>      
                                  </select>
                              </div>
                        </div>  
                        <div class="control-group">        
                          <label class="control-label">Số tiền:</label>
                          <div class="controls">
                          <input type="text" id="showAmount" disabled value="<?php echo number_format($this->amountYear); ?>" data-type="number" class="span8" placeholder="Vui lòng nhập số tiền" />
                          </div>
                      </div>   
                      <div class="control-group">        
                          <label class="control-label">Tổng tiền phải đóng:</label>
                          <div class="controls">
                            <p id="messagesSumMooney"></p>
                          </div>
                      </div>                                 
                  </div>                  
                </div>             
                <div class="row-fluid">
                    <div class="span2">
                    </div>
                    <div class="span10">
                        <p id="notification"></p>              
                    </div>
                    
                </div>                       
                 <div class="form-actions">                  
                  <button type="submit" class="btn save-internship">Nhập</button>                  
                  <button class="btn">Hủy bỏ</button>
                </div> 
              </form>
              <!-- end form -->
            </div>                      
          </div>
          
            <!--tab-->
            <div class="widget-box">
                <div class="widget-title">
                    <ul class="nav nav-tabs">
                        <li class="active"><a id="internship" data-toggle="tab" href="#tab1">Lịch sử đóng phí bồi dưỡng</a></li>                 
                    </ul>
                </div>
                <div class="widget-content tab-content">
                    <div id="tab1" class="tab-pane active">
                        <div class="row-fluid">
                          <div class="span12">    
                            <div class="widget-box">
                              <div class="widget-title">
                                <span class="icon"><i class="icon-th"></i></span> 
                                <h5>Lịch sử đóng phí bồi dưỡng</h5>
                              </div>
                              <div class="widget-content nopadding">
                              <table class="table table-bordered">
                                  <thead>
                                    <tr>
                                      <th>Tên người đóng phí </th>  
                                      <th>Mã biên nhận </th>                                   
                                      <th>Trạng thái</th>
                                      <th>Ngày đóng phí</th>
                                      <th>Loại</th>
                                      <th>Tổng tiền</th>
                                      <th>Thao tác</th>
                                    </tr>
                                  </thead>
                                  <tbody id="table-lawyer">                                 
                            
                                  </tbody>
                                </table>                            
                              </div>
                            </div>
                                    
                          </div>          
                        </div>         
                    </div>
                   
      </div>     
    </div>    
    </div>
      <!--end div-->   
      <!--open div--> 
   
    </div>  
  </div>
  
 
<!-- </div> -->

<!-- Modal -->
<div id="model-warning" class="modal fade" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <p id="message">Bạn đã tạo thành công phí bồi dưỡng cho luật sư.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>