<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1">
<style>
body {
    margin: 0;
    padding: 0;
    background-color: #FAFAFA;
    font: 10pt "Tahoma";
    line-height:100%;
}
* {
    box-sizing: border-box;
    -moz-box-sizing: border-box;
}
/* .content strong{
    text-decoration: underline;
    line-height:80%;
    padding : 0 15px 0 0;
	
} */
.page {
    /* width: 14cm; */
    width: 21cm;
    overflow:hidden;
    /* max-height:116.5mm; */
    max-height:148.5mm;
    padding: 1.5cm;
    margin-left:auto;
    margin-right:auto;
    background: white;
    box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
}
.subpage {
    padding: 1cm;
    border: 5px red solid;
    height: 257mm;
    outline: 2cm #FFEAEA solid;
}

 @page {
 size: A5 landscape;
 margin: 10%;
}

button {
    width:100px;
    height: 24px;
}
.header {
    overflow:hidden;
}
.logo {
    /*background-color:#FFFFFF;*/
    text-align:center;
    float:left;
}
.company {
    /*padding-top:24px;*/
    /* text-transform:uppercase; */
    background-color:#FFFFFF;
    text-align:right;
    float:right;
    padding-right:30px;
    font-size:13px;
}
.title {
    text-align:center;
    position:relative;
    color:#0000FF;
    font-size: 16px;
    top:1px;
}
.footer-left {
    text-align:center;
    text-transform:uppercase;
    padding-top:24px;
    position:relative;
    height: 150px;
    width:50%;
    color:#000;
    float:left;
    font-size: 12px;
    bottom:1px;
}
.footer-right {
    text-align:center;
    text-transform:uppercase;
    padding-top:24px;
    position:relative;
    height: 150px;
    width:50%;
    color:#000;
    font-size: 12px;
    float:right;
    bottom:1px;
}
@media print {
 @page {
 margin: 0;
 border: initial;
 border-radius: initial;
 width: initial;
 min-height: initial;
 box-shadow: initial;
 background: initial;
 page-break-after: always;
}
}

</style>
<body onload="window.print();">
<div id="page" class="page">
    <div class="header">
        <div class="logo"><strong>ĐOÀN LUẬT SƯ</strong> <br/>
        <strong> THÀNH PHỐ HỒ CHÍ MINH</strong><br/>
         ----oOo----
         </div>
        <div class="company">Số : <span style="font-style: italic;font-weight:bold"><?php echo $this->paymentlawyertrainingofflinedata['payment_training_off_code']; ?> </span></div>
    </div>
  <div class="title">
       <strong> BIÊN NHẬN</strong>
        <br/>
        *****
<br><br>
  </div>
  <div class="content">
    <p>Nhận của : <span style="font-style: italic;"><strong>Luật Sư <span style="text-transform: uppercase;"><?php echo $this->paymentlawyertrainingofflinedata['cus_firstname'].' '.$this->paymentlawyertrainingofflinedata['cus_lastname'] ?></span></strong><span style="font-style: italic;"></p>
    <p>Năm sinh : <span style="font-style: italic;"><strong><span style="text-transform: uppercase;"><?php echo date('Y', strtotime($this->paymentlawyertrainingofflinedata['cus_birthday'])); ?><span></strong> </span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Số thẻ :  <span style="font-style: italic;"><strong><?php echo $this->paymentlawyertrainingofflinedata['cus_lawyer_number'] ?></strong> </span> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ngày cấp : <span style="font-style: italic;"><strong><span style="text-transform: uppercase;"><?php echo date('d/m/Y', strtotime($this->paymentlawyertrainingofflinedata['cus_date_lawyer_number']));  ?><span></strong></span></p>
    <p>Lý do thu : <span style="font-style: italic;"><!--<?php echo $this->paymentlawyertrainingofflinedata['cat_train_name']; ?>-->Đăng ký lớp bồi dưỡng chuyên môn, nghiệp vụ LS  <?php echo $this->paymentlawyertrainingofflinedata['cat_train_number']; ?> , <span style="text-decoration: underline;">ngày <?php echo date('d/m/Y', strtotime($this->paymentlawyertrainingofflinedata['cat_train_fromdate'])) ?></span></span></p>
    <p>Số tiền : <span style="font-style: italic;"><strong><?php echo number_format($this->paymentlawyertrainingofflinedata['amount']); ?></strong></span></p>
    <p><span style="font-style: italic;">(Bằng chữ : <strong><?php echo $this->paymentlawyertrainingofflinedata['amount_word']; ?> đồng )</strong></span></p>

  </div>
  
  <div class="footer-left"> <br/>
    Người nộp </div>
  <div class="footer-right"> TP Hồ Chí Minh, Ngày <?php echo date('d', strtotime($this->paymentlawyertrainingofflinedata['payment_training_off_created_date'])) ?> tháng <?php echo date('m', strtotime($this->paymentlawyertrainingofflinedata['payment_training_off_created_date'])) ?> năm <?php echo date('Y', strtotime($this->paymentlawyertrainingofflinedata['payment_training_off_created_date'])) ?><br/>
    Người nhận 
    <br/>
    <br/>
    <br/>
    <br/><br/><br/>
<br/>
    Lê Thị Hòa  </div>
    <br/>  
    <p><span style="text-decoration: underline;"> Thời gian :</span> <?php echo date('d/m/Y', strtotime($this->paymentlawyertrainingofflinedata['cat_train_fromdate'])); ?> </p>
    <p><span style="font-style: italic;"><span style="text-decoration: underline;">Địa điểm: </span> <?php echo $this->paymentlawyertrainingofflinedata['cat_train_address']; ?></span></p>
</div>

</body>

</head>



