<script>
  $(document).ready(function(){
    $("#search").hide();
    $(".searchfield").hide();    
  });
</script>
<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="#" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i> Trang chủ</a> <a href="#" class="current"></a> </div>
  </div>
  <div class="container-fluid">
    <div class="row-fluid">     
      <!-- <div class="span2">
      </div> 
      <div class="span8"> -->          
          <h3> <?php echo $this->contentdata['title'];?></h3>
      <!-- </div>    
      <div class="span2">
      </div>      -->
    </div>
    <div class="widget-box widget-plain">
        <?php echo $this->contentdata['description'];?>
    </div>

  </div> 
</div>

<script src="<?php echo $this->BaseUrl?>/public/js/excanvas.min.js"></script> 
<script src="<?php echo $this->BaseUrl?>/public/js/jquery.flot.min.js"></script> 
<script src="<?php echo $this->BaseUrl?>/public/js/jquery.flot.resize.min.js"></script> 
<script src="<?php echo $this->BaseUrl?>/public/js/jquery.peity.min.js"></script> 
<script src="<?php echo $this->BaseUrl?>/public/js/maruti.dashboard.js"></script> 
