<div class="container-fluid">
  <!-- <div class="widget-box widget-plain">
    <div class="center">
      <ul class="stat-boxes">
        <li>
          <div class="left peity_bar_neutral">
            <span style="display: none;">2,4,9,7,12,10,12</span>
            <canvas width="50" height="24"></canvas>
          </div>
        </li>
        <li>
          <div class="left peity_bar_bad">
            <span style="display: none;">3,5,6,16,8,10,6</span>
            <canvas width="50" height="24"></canvas>
          </div>
        </li>
        <li>
          <div class="left peity_line_good">
            <span style="display: none;">12,6,9,23,14,10,17</span>
            <canvas width="50" height="24"></canvas>
          </div>
        </li>
      </ul>
    </div>
  </div> -->
</div>

<!-- <script src="<?=$this->BaseUrl?>/public/js/excanvas.min.js"></script>
<script src="<?=$this->BaseUrl?>/public/js/jquery.flot.min.js"></script>
<script src="<?=$this->BaseUrl?>/public/js/jquery.flot.resize.min.js"></script>
<script src="<?=$this->BaseUrl?>/public/js/jquery.peity.min.js"></script> -->
