<script>
$(document).ready(function(){
    
    $('input[type=checkbox],input[type=radio],input[type=file]').uniform();
  
    $("#search").hide();
    $(".searchfield").hide();
      $(".message-success").hide();
  
      $("#model-warning").modal('hide');   
  
      $(".close-modal").on('click',function(){
        location.reload();
      });
         
  
    function isNumber(n) {
      return !isNaN(parseFloat(n)) && isFinite(n);
    }  
  
  
  });

    function updatePaymentOfflineMemberStatus($id){
      //alert("member status");
        var dataString = '?payment_lawyer_off_id='+ $id +'&type=confirm';
         $.ajax({
              type: "GET",
              url: "<?php echo $this->BaseUrl?>/default/fee/detailmemberpayment"+dataString ,
              cache: false,
              success: function(html)
              { 
                //alert(html);
                $("#message").html(html);
                $("#model-warning").modal('show');
              }
         });  
    }

    function updatePaymentOfflineStatus($id){
      var dataString = '?payment_id='+ $id +'&type=confirm';
         $.ajax({
              type: "GET",
              url: "<?php echo $this->BaseUrl?>/default/fee/detaildifferentpayment"+dataString ,
              cache: false,
              success: function(html)
              { 
                //alert(html);
                $("#message").html(html);
                $("#model-warning").modal('show');
              }
         });  
    }

  function printPaymentOffline($id){
      var dataString = '?payment_id='+ $id;
         $.ajax({
              type: "GET",
              timeout: 120000,
              url: "<?php echo $this->BaseUrl?>/default/fee/printdifferentfee"+dataString ,
              cache: false,
              async:false,
              dataType : 'html',
              success: function(html)
              { 
                var mywindow = window.open('', 'Print-Window');

                mywindow.document.write('<html><head><title>' + document.title  + '</title>');
                mywindow.document.write('</head><body >');
                mywindow.document.write('<h1>' + document.title  + '</h1>');
                mywindow.document.write(html);
                mywindow.document.write('</body></html>');

                mywindow.document.close(); // necessary for IE >= 10
                mywindow.focus(); // necessary for IE >= 10*/

                mywindow.print();
                mywindow.close();
              }
         }); 
    }

    // function printPaymentOfflineMemberStatus($id){
    //   //var dataHTML = '';      
    // }

    // function printPaymentOfflineJoiningStatus($id){
    //   var dataString = '?payment_joining_off_id='+ $id;
    //      $.ajax({
    //           type: "GET",
    //           timeout: 120000,
    //           url: "<?php echo $this->BaseUrl?>/default/fee/printjoiningfee"+dataString ,
    //           cache: false,
    //           async:false,
    //           dataType : 'html',
    //           success: function(html)
    //           { 
    //             var mywindow = window.open('', 'Print-Window');

    //             mywindow.document.write('<html><head><title>' + document.title  + '</title>');
    //             mywindow.document.write('</head><body >');
    //             mywindow.document.write('<h1>' + document.title  + '</h1>');
    //             mywindow.document.write(html);
    //             mywindow.document.write('</body></html>');

    //             mywindow.document.close(); // necessary for IE >= 10
    //             mywindow.focus(); // necessary for IE >= 10*/

    //             mywindow.print();
    //             mywindow.close();
    //           }
    //      }); 
    // }
    
    function updatePaymentOfflineJoiningStatus($id){
      //alert("joining status");
      var dataString = '?payment_joining_off_id='+ $id +'&type=confirm';
         $.ajax({
              type: "GET",
              url: "<?php echo $this->BaseUrl?>/default/fee/detailjoiningpayment"+dataString ,
              cache: false,
              success: function(html)
              { 
                //alert(html);
                $("#message").html(html);
                $("#model-warning").modal('show');
              }
         });  
    }

    // function printPaymentOfflineIntershipStatus($id){
    //   var dataString = '?payment_inter_off_id='+ $id;
    //      $.ajax({
    //           type: "GET",
    //           timeout: 120000,
    //           async:false,
    //           dataType : 'html',
    //           url: "<?php echo $this->BaseUrl?>/default/fee/printintershipfee"+dataString ,
    //           cache: false,
    //           success: function(html)
    //           { 
    //             var mywindow = window.open('', 'Print-Window');

    //             mywindow.document.write('<html><head><title>' + document.title  + '</title>');
    //             mywindow.document.write('</head><body >');
    //             mywindow.document.write('<h1>' + document.title  + '</h1>');
    //             mywindow.document.write(html);
    //             mywindow.document.write('</body></html>');

    //             mywindow.document.close(); // necessary for IE >= 10
    //             mywindow.focus(); // necessary for IE >= 10*/

    //             mywindow.print();
    //             mywindow.close();
    //           }
    //      });  

    // }

    function updatePaymentOfflineIntershipStatus($id){      
      var dataString = '?payment_inter_off_id='+ $id +'&type=confirm';
         $.ajax({
              type: "GET",
              url: "<?php echo $this->BaseUrl?>/default/fee/detailintershippayment"+dataString ,
              cache: false,
              success: function(html)
              { 
                //alert(html);
                $("#message").html(html);
                $("#model-warning").modal('show');
              }
         });  
    }
  

</script>

<div id="model-warning" class="modal fade"  data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
        
      </div>
        
        <div class="modal-body">
            <p id="message">Bạn đã cập nhật thành công.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary close-modal" data-dismiss="modal">Đóng</button>
        </div>
      
    </div>
  </div>
</div>

<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="#" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i> Trang chủ</a> <a href="#" class="current">Xác nhận thu tiền</a> </div>
    <h1>Xác nhận thu tiền</h1>
  </div>
  <div class="container-fluid">
      <div class="widget-box">
          <div class="widget-title">
              <ul class="nav nav-tabs">
                  <li class="active"><a data-toggle="tab" href="#tab1">Xác nhận thu tiền phí thành viên</a></li>
                  <li><a data-toggle="tab" href="#tab2">Xác nhận thu tiền phí gia nhập</a></li>
                  <li><a data-toggle="tab" href="#tab3">Xác nhận thu tiền phí tập sự</a></li>
                  <li><a data-toggle="tab" href="#tab4">Xác nhận thu tiền phí khác</a></li>
              </ul>
          </div>
          <div class="widget-content tab-content">
              <div id="tab1" class="tab-pane active">
                <div class="row-fluid">
                  <div class="span12">
                    <div class="widget-box">
                      <div class="widget-title">
                        <span class="icon"><i class="icon-th"></i></span> 
                        <h5>Xác nhận thu tiền phí thành viên</h5>
                      </div>
                      <div class="widget-content nopadding">
                        <table class="table table-bordered data-table">
                          <thead>
                            <tr>
                                <th>Tên người đóng phí </th>
                                <!-- <th>Mã luật sư </th>
                                <th>Mã chứng chỉ hành nghề </th> -->
                                <th>Mã biên nhận </th>
                                <th>Trạng thái</th>                                
                                <th>Loại</th>
                                <th>Ngày đóng phí</th>
                                <th>Hình thức</th>
                                <th>Tổng tiền</th>
                                <th>Thời gian (tháng)</th> 
                                <th>Thao tác</p>              
                            </tr>
                          </thead>
                          <tbody>       
                            <?php  
                                if($this->paymentofflines != null){
                                    foreach ($this->paymentofflines as $pay) {  
                                      if($pay['payment_type'] == 'offline'){         
                                        // '<td>'.$pay['payment_lawyer_off_id'].'</td>'.
                                        $payment_type = '';
                                        if($pay['payment_type'] == 'offline'){
                                          $payment_type = '<td>Tại đoàn</td>';
                                        }else{
                                          $payment_type = '<td>Qua mạng</td>';
                                        }
                                        
                                        $text = ''; 
                                        if($pay['payment_lawyer_off_status'] == 1){
                                            $text = '<td>Đã thanh toán</td>';
                                        }else{
                                            $text = '<td>Chưa thanh toán</td>';  
                                        }    

                                        $payment_lawyer_off_created_date = ($pay['payment_lawyer_off_created_date'] != null && $pay['payment_lawyer_off_created_date'] != ''
                                        && $pay['payment_lawyer_off_created_date'] != '1900-01-01 00:00:00') ? date('d/m/Y', strtotime($pay['payment_lawyer_off_created_date'])) : '';    

                                        echo ' <tr class="gradeC">'.
                                        '<td>'.$pay['cus_firstname'].' '.$pay['cus_lastname'].'</td>'.
                                        //  '<td>'.$pay['law_code'].'</td>'.
                                        //  '<td>'.$pay['law_certfication_no'].'</td>'.
                                        '<td>'.$pay['payment_lawyer_off_code'].'</td>'.
                                        $text.
                                        $payment_type.
                                        '<td>'.$payment_lawyer_off_created_date
                                        .'</td>'.
                                        '<td>'.$pay['name'].'</td>'.
                                        '<td>'.number_format($pay['amount']).'</td>'.  
                                        '<td>'.$pay['month'].'</td>'.
                                        '<td class="center">'.
                                              '<button onClick="updatePaymentOfflineMemberStatus('.$pay['payment_lawyer_off_id'].');"><i class="icon-pencil"></i></button>'.' '.
                                              // '<button onClick="printPaymentOfflineMemberStatus('.$pay['payment_lawyer_off_id'].');"><i class="icon-print"></i></button>'.
                                              
                                    '</tr>';                            
                                    } 
                                  }   
                                }

                            ?>
                          </tbody>
                        </table>
                      </div>
                    </div>        
                  </div>
                </div>
              </div>
              <div id="tab2" class="tab-pane">
               <!-- phí gia nhập-->
                <div class="row-fluid">
                  <div class="span12">
                    <div class="widget-box">
                      <div class="widget-title">
                        <span class="icon"><i class="icon-th"></i></span> 
                        <h5>Xác nhận thu tiền phí gia nhập</h5>
                      </div>
                      <div class="widget-content nopadding">
                        <table class="table table-bordered data-table">
                          <thead>
                            <tr>
                                <th>Tên người đóng phí </th>
                                <!-- <th>Mã luật sư </th>
                                <th>Mã chứng chỉ hành nghề </th> -->
                                <th>Mã biên nhận </th>
                                <th>Trạng thái</th>
                                <th>Ngày đóng phí</th>
                                <th>Loại</th>
                                <th>Tổng tiền</th>
                                <!-- <th>Thời gian (tháng)</th>  -->
                                <th>Thao tác</p>              
                            </tr>
                          </thead>
                          <tbody>       
                            <?php  
                                if($this->paymentjoiningofflines != null){
                                    foreach ($this->paymentjoiningofflines as $pay) {           
                                        // '<td>'.$pay['payment_lawyer_off_id'].'</td>'.
                                        $text = ''; 
                                        if($pay['payment_joining_off_status'] == 1){
                                            $text = '<td>Đã thanh toán</td>';
                                        }else{
                                            $text = '<td>Chưa thanh toán</td>';  
                                        }    

                                        $payment_joining_off_created_date = ($pay['payment_joining_off_created_date'] != null && $pay['payment_joining_off_created_date'] != ''
                                        && $pay['payment_joining_off_created_date'] != '1900-01-01 00:00:00') ? date('d/m/Y', strtotime($pay['payment_joining_off_created_date'])) : '';    


                                        echo ' <tr class="gradeC">'.
                                        '<td>'.$pay['cus_firstname'].' '.$pay['cus_lastname'].'</td>'.
                                        //  '<td>'.$pay['law_code'].'</td>'.
                                        //  '<td>'.$pay['law_certfication_no'].'</td>'.
                                        '<td>'.$pay['payment_joining_off_code'].'</td>'.
                                        $text.
                                        '<td>'.$payment_joining_off_created_date
                                        .'</td>'.
                                        '<td>'.$pay['name'].'</td>'.
                                        '<td>'.number_format($pay['amount']).'</td>'.  
                                        //  '<td>'.$pay['month'].'</td>'.
                                        '<td class="center">'.
                                              '<button onClick="updatePaymentOfflineJoiningStatus('.$pay['payment_joining_off_id'].');"><i class="icon-pencil"></i></button>'.' '.
                                              // '<button onClick="printPaymentOfflineJoiningStatus('.$pay['payment_joining_off_id'].');"><i class="icon-print"></i></button>'.
                                    '</tr>';                            
                                    }  
                                }else{
                                   // echo " Không có dữ liệu đóng phí thành viên.";
                                }

                            ?>
                          </tbody>
                        </table>
                      </div>
                    </div>        
                  </div>
                </div>                                
              </div>
              <div id="tab3" class="tab-pane">
                <div class="row-fluid">
                  <div class="span12">
                    <div class="widget-box">
                      <div class="widget-title">
                        <span class="icon"><i class="icon-th"></i></span> 
                        <h5>Xác nhận thu tiền phí tập sự</h5>
                      </div>
                      <div class="widget-content nopadding">
                        <table class="table table-bordered data-table">
                          <thead>
                            <tr>
                                <th>Tên người đóng phí </th>
                                <!-- <th>Mã luật sư </th>
                                <th>Mã chứng chỉ hành nghề </th> -->
                                <th>Mã biên nhận </th>
                                <th>Trạng thái</th>
                                <th>Ngày đóng phí</th>
                                <th>Loại</th>
                                <th>Tổng tiền</th>                   
                                <th>Thao tác</p>              
                            </tr>
                          </thead>
                          <tbody>       
                            <?php  
                                if($this->paymentintershipofflines != null){
                                    foreach ($this->paymentintershipofflines as $pay) {           
                                        // '<td>'.$pay['payment_lawyer_off_id'].'</td>'.
                                        $text = ''; 
                                        if($pay['payment_inter_off_status'] == 1){
                                            $text = '<td>Đã thanh toán</td>';
                                        }else{
                                            $text = '<td>Chưa thanh toán</td>';  
                                        }    

                                        $payment_inter_off_created_date = ($pay['payment_inter_off_created_date'] != null && $pay['payment_inter_off_created_date'] != ''
                                        && $pay['payment_inter_off_created_date'] != '1900-01-01 00:00:00') ? date('d/m/Y', strtotime($pay['payment_inter_off_created_date'])) : '';    

                                        echo ' <tr class="gradeC">'.
                                        '<td>'.$pay['cus_firstname'].' '.$pay['cus_lastname'].'</td>'.
                                        //  '<td>'.$pay['law_code'].'</td>'.
                                        //  '<td>'.$pay['law_certfication_no'].'</td>'.
                                        '<td>'.$pay['payment_inter_off_code'].'</td>'.
                                        $text.
                                        '<td>'.$payment_inter_off_created_date
                                        .'</td>'.
                                        '<td>'.$pay['name'].'</td>'.
                                        '<td>'.number_format($pay['amount']).'</td>'.                               
                                        '<td class="center">'.                            
                                              '<button onClick="updatePaymentOfflineIntershipStatus('.$pay['payment_inter_off_id'].');"><i class="icon-pencil"></i></button>'.' '.
                                              // '<button onClick="printPaymentOfflineIntershipStatus('.$pay['payment_inter_off_id'].');" ><i class="icon-print"></i></button>'.
                                    '</tr>';                            
                                    }  
                                }

                            ?>
                          </tbody>
                        </table>
                      </div>
                    </div>        
                  </div>
                </div>              
              </div>
              <div id="tab4" class="tab-pane">
                <div class="row-fluid">
                  <div class="span12">
                    <div class="widget-box">
                      <div class="widget-title">
                        <span class="icon"><i class="icon-th"></i></span> 
                        <h5>Xác nhận thu tiền phí khác</h5>
                      </div>
                      <div class="widget-content nopadding">
                        <table class="table table-bordered data-table">
                          <thead>
                            <tr>
                                <th>Người/Tổ chức đóng phí </th>                               
                                <th>Mã biên nhận </th>
                                <th>Trạng thái</th>
                                <th>Ngày đóng phí</th>                                
                                <th>Tổng tiền</th>       
                                <th>Loại hình</th>  
                                <th>Hình thức </th>          
                                <th>Thao tác</th>              
                            </tr>
                          </thead>
                          <tbody>       
                            <?php  
                                if($this->paymentOfflines != null){
                                    foreach ($this->paymentOfflines as $pay) {  
                                      if($pay['payment_type'] == 'offline'){         
                                        // '<td>'.$pay['payment_lawyer_off_id'].'</td>'.
                                        $text = ''; 
                                        if($pay['payment_off_status'] == 1){
                                            $text = '<td>Đã thanh toán</td>';
                                        }else{
                                            $text = '<td>Chưa thanh toán</td>';  
                                        }    

                                        $payment_type = '';
                                        if($pay['payment_type'] == 'offline'){
                                          $payment_type = '<td>Tại đoàn</td>';
                                        }else{
                                          $payment_type = '<td>Qua mạng</td>';
                                        }

                                        $name = '';
                                        $hinhthuc = '';
                                        if($pay['community'] != null){
                                            $name =  '<td>'.$pay['community'].'</td>';
                                            $hinhthuc = '<td>'.'Cá nhân tổ chức bên ngoài'.'</td>';
                                        }else{
                                            $name = '<td>'.$pay['cus_firstname'].' '.$pay['cus_lastname'].'</td>';
                                            $hinhthuc = '<td>'.'Cá nhân thuộc Đoàn'.'</td>';
                                        }

                                        $payment_off_created_date = ($pay['payment_off_created_date'] != null && $pay['payment_off_created_date'] != ''
                                        && $pay['payment_off_created_date'] != '1900-01-01 00:00:00') ? date('d/m/Y', strtotime($pay['payment_off_created_date'])) : '';    


                                        echo ' <tr class="gradeC">'.
                                        $name.                                       
                                        '<td>'.$pay['payment_off_code'].'</td>'.
                                        $text.
                                        '<td>'.$payment_off_created_date
                                        .'</td>'.                                        
                                        '<td>'.number_format($pay['amount']).'</td>'. 
                                        $hinhthuc.    
                                        $payment_type.                            
                                        '<td class="center">'.                                                        
                                              '<button onClick="updatePaymentOfflineStatus('.$pay['payment_id'].');"><i class="icon-pencil"></i></button>'.' '.
                                              '<button onClick="printPaymentOffline('.$pay['payment_id'].');" ><i class="icon-print"></i></button>'.
                                    '</tr>';                            
                                    }
                                  }    
                                }

                            ?>
                          </tbody>
                        </table>
                      </div>
                    </div>        
                  </div>
                </div>              
              </div>
          </div>                            
      </div>   
  </div>
</div>