
<script>
$(document).ready(function(){

    $(".close-modal").on('click',function(){
       location.reload();
    });

    $("#form-edit").validate({     
            rules:{
                // law_code:{
                // required:true
                // },
                // law_certfication_no:{
                // required:true
                // }
            },
            errorClass: "help-inline",
            errorElement: "span",
            highlight:function(element, errorClass, validClass) {
                $(element).parents('.control-group').addClass('error');
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').removeClass('error');
                $(element).parents('.control-group').addClass('success');
            },
            messages: {
                //cus_cellphone: "Vui lòng nhập số điện thoại !",
                // cus_identity_card: "Vui lòng nhập số CMND !",
                // law_code: "Vui lòng nhập mã luật sư !",
                // law_certfication_no: "Vui lòng nhập số chứng chỉ !",
            },
            submitHandler: function(form,e) {
                console.log('Form submitted');
                $.ajax({
                      type: "POST",
                      url: "<?php echo $this->BaseUrl?>/default/fee/updatedifferentpayment/",
                      data: $('#form-edit').serialize() ,
                      cache: false,
                      success: function(html)
                      {   
                        $("#message").html("Cập nhật biên nhận thành công"); 
                        //$(".close-modal").hide();  
                                                                               
                      }
                });
                return false;                       
            }
        });
});  

</script>

<form id="form-edit" class="form-horizontal">
    <h4> Chỉnh sửa trạng thái phí khác </h3>
    <p id="message"></p>
    <input type="hidden" name="payment_id" value="<?php echo $this->differentpayment['payment_id']; ?>" /> 

    <div class="control-group">        
        <label class="control-label">Mã số biên nhận:</label>
        <div class="controls">
        <input type="text" disabled value="<?php echo $this->differentpayment['payment_off_code']; ?>" class="span3" placeholder="Vui lòng nhập mã số chứng chỉ" />
        </div>
    </div> 

        <div class="control-group">        
    <label class="control-label">Ngày đóng phí:</label>
    <div class="controls">
    <input type="text" disabled value="<?php echo ($this->differentpayment['payment_off_created_date'] != null && $this->differentpayment['payment_off_created_date'] != '1900-01-01 00:00:00' && $this->differentpayment['payment_off_created_date'] != '') ? date('d/m/Y', strtotime($this->differentpayment['payment_off_created_date'])) : ''; ?>" class="span3" placeholder="Vui lòng nhập mã số chứng chỉ" />
    </div>
    </div>   

    <label class="control-label">Trạng thái biên nhận: </label>
    <div class="controls">
        <div class="row-fluid">
            <div class="span3">
            <label>                            
                <input type="radio" name="payment_off_status" value="1" <?php echo ($this->differentpayment['payment_off_status'] == 1) ? 'checked' :'' ?>/>
        Đã thanh toán</label>
            </div>
            <div class="span6">
                <label>
                <input type="radio" name="payment_off_status" value="0" <?php echo ($this->differentpayment['payment_off_status'] == 0) ? 'checked' :'' ?>/>
                Chưa thanh toán</label> 
            </div>
        </div>                                               
    </div> 



    <!-- <div class="form-actions"> -->
    <button style="float: right;" type="submit" class="btn">Lưu</button>
    <!-- </div> -->
</form>
         


