<script>
$(document).ready(function(){
    
	$('input[type=checkbox],input[type=radio],input[type=file]').uniform();
  $("#search").hide();
  $(".searchfield").hide();

  $('select').select2();

    $(".message-success").hide();

    $("#model-warning").modal('hide');   

    $(".close-modal").on('click',function(){
      location.reload();
    });

    var date = new Date();
    var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
    $('.datepicker-ngaydong').datepicker({ format: 'dd/mm/yyyy' });
    $('.datepicker-ngaydong').datepicker('setValue', today);

    $("#community").attr("disabled",true);
    $(".community-type input[name='community_type']").click(function(){
      if($('input:radio[name=community_type]:checked').val() == "person"){
        $("#community").attr("disabled",true);
        $("#law-donggop").show();
      }else{
        $("#law-donggop").hide();
        $("#community").attr("disabled",false);
      }
    });  
      
   $("#categorytranining_form").validate({     
          rules:{
            reason:{
              required:true
            },
            community:{
              required:true
            },
            amount:{
              required:true
            }
          },
          errorClass: "help-inline",
          errorElement: "span",
          highlight:function(element, errorClass, validClass) {
            $(element).parents('.control-group').addClass('error');
          },
          unhighlight: function(element, errorClass, validClass) {
            $(element).parents('.control-group').removeClass('error');
            $(element).parents('.control-group').addClass('success');
          },
          messages: {
            reason: "Vui lòng nhập nội dung đóng góp !",
            community: "Vui lòng nhập cá nhân hoặc tổ chức đóng góp !",
            amount : "Vui lòng nhập số tiền đóng góp !"           
          },
          submitHandler: function(form,e) {
             console.log('Form submitted');
             console.log($('#categorytranining_form').serialize());
            $.ajax({
                  type: "POST",
                  url: "<?php echo $this->BaseUrl?>/default/fee/createfeedifferent/",
                  data: $('#categorytranining_form').serialize() ,
                  cache: false,
                  success: function(html)
                  {   
                    //$("#message").html(html);
                    $(".message-success").show();
                    $("#model-warning").modal("show");                                                   
                  }
            });
            return false;                       
        }
	});


  function isNumber(n) {
    return !isNaN(parseFloat(n)) && isFinite(n);
  }



});

  function updateCategoryStatus($cat_id){
    // alert("test code law");
     console.log($cat_id);

      var dataString = '?cat_id='+ $cat_id;
       $.ajax({
            type: "GET",
            url: "<?php echo $this->BaseUrl?>/default/categorytraining/detail"+dataString ,
            //data: dataString+'?format=html',
            //dataType: 'json',
            cache: false,
            success: function(html)
            { 
              //alert(html);
              $("#message").html(html);
              $("#model-warning").modal('show');
            }
       });       


    
    
  }

   

</script>

<div id="model-warning" class="modal fade"  data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
        
      </div>
        
        <div class="modal-body">
            <p id="message">Bạn đã tạo thành công phí khác.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary close-modal" data-dismiss="modal">Đóng</button>
        </div>
      
    </div>
  </div>
</div>

<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i></a> <a href="#" class="current">Nhập mới đóng góp</a> </div>
    <!-- <h1>Quản lý luật sư</h1> -->
  </div>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="alert alert-success alert-dismissible message-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Thông báo</strong> Bạn đã tạo phí khác (phí đóng góp) thành công..
      </div>	
    </div>  	 

    <div class="row-fluid">	  	
      <div class="span12">		 
        <div class="widget-box">
            <div class="widget-title">
              <span class="icon">
                <i class="icon-th-list"></i>
              </span>
              <h5>Nhập mới đóng góp</h5>
            </div>
            
            <div class="widget-content nopadding"> 
            <!-- <p>test code </p> -->
              <div class="row-fluid form-horizontal">
                <form id="categorytranining_form" novalidate="novalidate">
                    <div class="span6">
                        <!-- <input type="hidden" id="cus_id" name="cus_id"/> -->
                        <input type="hidden" name="payment_different_off_code" id="payment_different_off_code" value="<?php echo $this->payment_different_off_code; ?>"/>
                        <div class="control-group"> 
                          <label class="control-label">Số biên nhận:</label>
                          <div class="controls">
                            <strong><?php echo $this->payment_different_off_code; ?></strong>
                          </div>
                        </div>
                        
                        <label class="control-label">Chọn hình thức đóng góp *:</label>
                        <div class="controls">
                          <div class="row-fluid community-type">
                              <div class="span3">
                                <label>
                                    <input type="radio" name="community_type" value="person" checked/>
                            LS tại đoàn </label>
                              </div>
                              <div class="span6">
                                    <label>
                                  <input type="radio"  name="community_type" value="community"/>
                            Khác</label> 
                              </div>
                          </div>                                               
                        </div> 

                        <div  id="persontext" class="control-group">
                          <label class="control-label">Tên cá nhân hoặc tổ chức đóng góp *:</label>
                          <div class="controls">
                              <input type="text" name="community" id="community" class="span12" placeholder="Vui lòng nhập cá nhân hoặc tổ chức đóng góp " />
                          </div>
                        </div>

                        <div id="law-donggop" class="control-group">
                              <label class="control-label">Chọn luật sư đóng góp:</label>
                              <div class="controls"> 
                                  <select class="span12" id="law_id" name="law_id">
                                  <?php  
                                      foreach ($this->lawyers as $law) {
                                          echo '<option value="'.$law['law_id'].'" class="span8">'.$law['cus_firstname'].' '.$law['cus_lastname'].' - '.$law['cus_identity_card'].'</option>';
                                      }
                                      ?>    
                                  </select>
                              </div>
                        </div>                      

                        <!-- <div class="control-group">
                              <label class="control-label">Hình thức đóng góp *</label>
                                <div class="controls"> 
                                  <select class="span12" id="category_fee_lawyer_id" name="category_fee_lawyer_id">
                                  <?php                                    
                                      foreach ($this->categoryfee as $cat) {                                       
                                          // if($cat['category_fee_lawyer_id'] == 1){
                                            echo '<option value="'.$cat['category_fee_lawyer_id'].'" class="span8">'.$cat['name'].'</option>';
                                          //}                                          
                                      }
                                      ?>    
                                  </select>
                              </div>
                        </div>   -->
                       
                         
                    </div>  
                    <div class="span6">                       
                        <!-- <div class="control-group">
                          <label class="control-label">Địa điểm : *</label>
                          <div class="controls">              
                            <input type="text" name="cat_train_address" id="cat_train_address" class="span12" placeholder="Vui lòng nhập địa điểm" />
                          </div>
                        </div>    -->

                        <div  id="communitytext" class="control-group">
                          <label class="control-label">Nội dung đóng góp : *</label>
                          <div class="controls">
                              <input type="text" name="reason" id="reason" class="span10" placeholder="Vui lòng nhập nội dung đóng góp" />
                          </div>
                        </div>
                        <div class="control-group">
                          <label class="control-label">Số tiền đóng góp : *</label>
                          <div class="controls">
                              <input type="text" name="amount" id="amount" class="span10" placeholder="Vui lòng nhập số tiền đóng góp" />
                          </div>
                        </div>

                        <div class="control-group">
                              <label class="control-label">Lý do đóng góp *</label>
                              <div class="controls"> 
                                      <textarea class="span12" name="reason_method" cols='5' >
                                      </textarea>
                              </div>
                        </div>

                        <!-- <div class="control-group">
                        <label class="control-label">Chọn ngày đóng góp : *</label>
                        <div class="controls">                  
                          <div id="dp5" data-date="" class="input-append date datepicker-ngaydong">                    
                            <input name="regis_date" data-date-format="mm-dd-yyyy" class="span12" >
                            <span class="add-on"><i class="icon-th"></i></span> </div>
                        </div> -->
                      </div>                
                    </div>  
                    
               	  
              </div>
              <div class="row-fluid">
                    <div class="form-actions">
                              <div class="span4" >
                              </div>
                              <div class="span6">	             
                                  <button type="submit" class="btn ">Lưu</button>			
                                  <button type="button" class="btn ">Hủy</button>							 
                              </div>
                              <div class="span2" >
                              </div>
                            </div>  
                    </div>
              </div>  
              </form>
            </div>

            <!--tab-->
            <!-- <div class="widget-box">
                <div class="widget-title">
                    <ul class="nav nav-tabs">
                        <li class="active"><a id="internship" data-toggle="tab" href="#tab1">Danh sách chủ đề</a></li>
                                                
                    </ul>
                </div>
                <div class="widget-content tab-content">
                    <div id="tab1" class="tab-pane active">
                        <div class="row-fluid">
                          <div class="span12">    
                            <div class="widget-box">
                              <div class="widget-title">
                                <span class="icon"><i class="icon-th"></i></span> 
                                <h5>Danh sách nội dung bồi dưỡng</h5>
                              </div>
                              <div class="widget-content nopadding">
                              <table class="table table-bordered data-table">
                                  <thead>
                                    <tr>
                                      <th>Đợt bồi dưỡng</th>
                                      <th>Tên nội dung bồi dưỡng</th>
                                      <th>Địa điểm</th>                                      
                                      <th>Trạng thái</th>
                                      <th>Hành động</th>
                                    </tr>
                                  </thead>
                                  <tbody id="table-lawyer">   
                                  <?php  
                                        if($this->categories != null){
                                            foreach ($this->categories as $cat) {                                           
                                                $text = ''; 
                                                if($cat['cat_train_active'] == 1){
                                                    $text = '<td>Đang hoạt động</td>';
                                                }else{
                                                    $text = '<td>Ngưng hoạt động</td>';  
                                                }    
                                                echo ' <tr class="gradeC">'.
                                                '<td>'.$cat['cat_train_number'].'</td>'.
                                                '<td>'.$cat['cat_train_name'].'</td>'.
                                                '<td>'.$cat['cat_train_address'].'</td>'.
                                                $text.                                               
                                                '<td class="center">'.
                                                    '<button onClick="updateCategoryStatus('.$cat['cat_train_id'].');"><i class="icon-pencil"></i></button>'.' '.
                                                    
                                            '</tr>';                          
                                            }  
                                        }
                                    ?>                             
                            
                                  </tbody>
                                </table>                            
                              </div>
                            </div>
                                    
                          </div>          
                        </div>         
                    </div>                   -->
        
    </div>
  </div>  
</div>

