<script>
    $(document).ready(function(){

      $("#model-warning").modal("hide");
      $(".message-success").hide(); 
      $('select').select2();

      $("input[data-type='number']").keyup(function(event){
          // skip for arrow keys
          if(event.which >= 37 && event.which <= 40){
              event.preventDefault();
          }
          var $this = $(this);
          var num = $this.val().replace(/,/gi, "");
          var num2 = num.split(/(?=(?:\d{3})+$)/).join(",");
          // console.log(num2);
          // the following line has been simplified. Revision history contains original.
          $this.val(num2);
      });

      var date = new Date();
      var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
      $('.datepicker-nopphi').datepicker({ format: 'dd/mm/yyyy' }); 
      $('.datepicker-nopphi').datepicker('setValue', today);
       


    //   $("#notification").html("Thông báo : Số tiền bạn đóng phí thành viên là ")

      var regis_date = '';

      $('#dp5').datepicker()
      .on('changeDate', function(ev){
          regis_date = ev.date.valueOf();        
      });    


    $("#search-global").keyup(function(e) {        
        $("#cus_id").val('');
        var key = e.keyCode;

        if (key == 40 || key == 38 || key == 13) {
          return false;
        }   
        var searchbox = $(this).val();
        var dataString = 'searchword='+ searchbox + '&searchfield='+$("#search-field").val();
        searchData(searchbox,dataString);
        
    });  

    
    $('#search').on("keydown", "#search-global", function (e) {
        console.log("event key down");
        var $listItems = $('.display-box-search-result li');
        //console.log($listItems);
        var key = e.keyCode,
        $selected = $listItems.filter('.hovered'),$current;

        var $scrollable = $("#display-content-search-global");
		    var scrollTop = $scrollable.scrollTop();

        //console.log(scrollTop);

        if (key != 40 && key != 38 && key != 13)
            return;

        //$listItems.removeClass('selected');

        if (key == 40) // Down key
        {
            $listItems.removeClass('hovered');
            if (!$selected.length || $selected.is(':last-child')) {
                $current = $listItems.eq(0);
            } else {
                $current = $selected.next();
            }
            $current.addClass('hovered');
            //console.log("Current : "+$current);
            //console.log($current);
            //$scrollable.scrollTop(scrollTop + 10);
        } 
        else if (key == 38) // Up key
        {
            $listItems.removeClass('hovered');
            if (!$selected.length || $selected.is(':first-child')) {
                $current = $listItems.last();
            } else {
                $current = $selected.prev();
            }       
            $current.addClass('hovered');
            //console.log($('.display-box-search-result li').length);
            //$scrollable.scrollTop(scrollTop - 10);

        } 
        else if (key == 13) // Enter key
        {
            $current = $listItems.filter('.hovered');
            $current.trigger('click');
            return false;
        }

        $("#display-content-search-global").scrollTop(0);//set to top
        $("#display-content-search-global").scrollTop($('.hovered:first').offset().top-$("#display-content-search-global").height());       
        
    });
       

    $("#form-internship").validate({
          rules:{
            // regis_date:{
            //   required:true
            // },
            // lawyer_guide:{
            //   required:true
            // }
            // ,
            // amount:{
            //   required:true
            // }
          },
          errorClass: "help-inline",
          errorElement: "span",
          highlight:function(element, errorClass, validClass) {
            $(element).parents('.control-group').addClass('error');
          },
          unhighlight: function(element, errorClass, validClass) {
            $(element).parents('.control-group').removeClass('error');
            $(element).parents('.control-group').addClass('success');
          },
          messages: {
            // regis_date: "Chọn ngày đóng phí thành viên !!!",
            // lawyer_guide:"Chọn luật sư hướng dẫn" ,
            // amount:"Vui lòng nhập số tiền"  
          },
          submitHandler: function(form,e) {
            console.log('Form submitted');
            var data = {
              cus_id : $("#cus_id").val(),
              category_fee_id : $("#category_fee_id").val(),
              payment_inter_off_code :$('#payment_inter_off_code').val()
              // ,
              // regis_date : regis_date
              // ,
              // amount: $("#amount").val()
            }
            $.ajax({
                  type: "POST",
                  url: "<?php echo $this->BaseUrl?>/default/fee/createfeeintership/",
                  data: data ,
                  cache: false,
                  success: function(html)
                  {   
                    //$(".message-success").show();
                    //alert(html);
                    $("#message").html(html);
                    $("#model-warning").modal("show");   
                    loadDataForTab($("#cus_id").val(),"#table-lawyer","lawyer");                           
                  }
            });
            return false;                       
        }
	  });

    $('#display-content-search-global').on('click', function(event) {
      console.log("action event");
      var id = $(event.target).attr('id');
      //var value = $("#"+id).val();
      var dataString = '?searchword='+ id;
       $.ajax({
            type: "GET",
            url: "<?php echo $this->BaseUrl?>/default/customers/detail"+dataString ,
            //data: dataString+'?format=html',
            dataType: 'json',
            cache: false,
            success: function(data)
            {   
 
              if(data.cus_id != null && data.cus_id != undefined){
                     $("#cus_id").val(data.cus_id);
                     loadDataForTab(data.cus_id,"#table-lawyer","lawyer");
                     $('#display-content-search-global').html('');
                     //$("#search-global").val(data.cus_identity_card);
                     if($("#search-field").val() != null && $("#search-field").val() == "name"){
                      $("#search-global").val(data.cus_fullname);
                     }else if($("#search-field").val() != null && $("#search-field").val() == "lawyer_number"){
                      $("#search-global").val(data.cus_lawyer_number);
                     }else if($("#search-field").val() != null && $("#search-field").val() == "identity_card"){
                      $("#search-global").val(data.cus_identity_card);
                     }else{
                      $("#search-global").val(data.cus_cellphone);
                     }
                     $("#cus_cellphone").val(data.cus_cellphone);
                     $("#cus_firstname").val(data.cus_firstname);
                     $("#cus_lastname").val(data.cus_lastname);
                     $("#cus_identity_card").val(data.cus_identity_card);
                     $("#cus_username").val(data.cus_username);
                     $("#cus_birthday").val(data.cus_birthday);
                     $("#cus_country").val(data.cus_country);
                     $("#cus_id").val(data.cus_id);  
              }
              //console.log(data);             
            }, error: function(msg){               
            }           
            });
    });

 });

 function searchData(searchbox,dataString){
    if(searchbox ==''){
            $("#display-content-search-global").html('');
            //load = true;
        } else
        {
            $.ajax({
                type: "POST",
                url: "<?php echo $this->BaseUrl?>/default/customers/search/",
                data: dataString,
                cache: false,
                success: function(html)
                {   
                  //$("#display-content-search-global").html('');
                  //console.log(html.length);
                  $("#display-content-search-global").html(html);                  
                }
            });
            //load = true
        }
  }  

  function isNumber(n) {
    return !isNaN(parseFloat(n)) && isFinite(n);
  }

   function printPaymentOfflineIntershipStatus($id){
      var dataString = '?payment_inter_off_id='+ $id;
         $.ajax({
              type: "GET",
              timeout: 120000,
              async:false,
              dataType : 'html',
              url: "<?php echo $this->BaseUrl?>/default/fee/printintershipfee"+dataString ,
              cache: false,
              success: function(html)
              { 
                var mywindow = window.open('', 'Print-Window');

                mywindow.document.write('<html><head><title>' + document.title  + '</title>');
                mywindow.document.write('</head><body >');
                mywindow.document.write('<h1>' + document.title  + '</h1>');
                mywindow.document.write(html);
                mywindow.document.write('</body></html>');

                mywindow.document.close(); // necessary for IE >= 10
                mywindow.focus(); // necessary for IE >= 10*/

                mywindow.print();
                mywindow.close();
              }
         });  

    }

  function loadDataForTab(cus_id,div_content,typetab){ 
        var dataString = '?cus_id='+ cus_id;        
        if(cus_id =='' || cus_id == undefined){
            $("#table-lawyer").html('');
        } else
        {
            var url = "<?php echo $this->BaseUrl?>/default/fee/listintership"+dataString;

            $.ajax({
                type: "GET",
                url: url,
                //data: dataString,
                //dataType: 'json',
                cache: false,
                success: function(html)
                {   
                  //alert(html);
                  $(div_content).html(html);                  
                }
            });
        }
 return false;   
}

</script>

 <div id="content">
    <div id="content-header">
      <div id="breadcrumb"> <a href="" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i></a> <a href="#" class="current">Thêm mới biên nhận phí tập sự</a> </div>
      <!-- <h1>Quản lý luật sư</h1> -->
    </div>
   <div class="container-fluid"> 
   <div class="row-fluid">
      <div class="alert alert-success alert-dismissible message-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <strong>Thông báo</strong> Bạn đã tạo thành công một biên nhận phí tập sự.
        </div>
    </div>   
    <!-- <h4>Thêm mới luật sư tập sự</h4> -->
    <div class="row-fluid">     
        <!-- open div general information-->
        <div class="span12">          
          <div class="widget-box">
            <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
              <h5>Thông tin chung</h5>
            </div>
            <div class="widget-content nopadding" id="detail-information">
            <!--start form-->              
                <div class="row-fluid form-horizontal">
                  <div class="span6">
                      <label class="control-label">Họ và lót :</label>
                        <div class="controls">
                          <input type="text" disabled id="cus_firstname"  name="cus_firstname" class="span8" placeholder="Họ của luật sư" />
                        </div>  
                        <label class="control-label">Tên :</label>
                        <div class="controls">
                          <input type="text" disabled id="cus_lastname"  name="cus_lastname" class="span8" placeholder="Tên của luật sư" />
                        </div>   
                        <label class="control-label">Ngày sinh :</label>
                        <div class="controls">
                          <input type="text" disabled id="cus_birthday"  name="cus_birthday" class="span8" placeholder="Ngày sinh" />
                        </div>  
                      
                      <!-- <label class="control-label">Tên đăng nhập:</label>
                        <div class="controls">
                          <input type="text" id="cus_username"  name="cus_username" class="span8" placeholder="Nhập số điện thoại để tìm luật sư" />
                      </div>                                      -->
                  </div>  
                  <div class="span6">
                    <label class="control-label">Số điện thoại :</label>
                      <div class="controls">
                        <input type="text" disabled id="cus_cellphone"  name="cus_cellphone" class="span8" placeholder="Số điện thoại" />
                      </div> 
                      <label class="control-label">Số chứng minh nhân dân :</label>
                      <div class="controls">
                        <input type="text" disabled id="cus_identity_card"  name="cus_identity_card" class="span8" placeholder="Số chứng minh nhân dân" />
                      </div>  
                      <!-- <label class="control-label">Tỉnh thành :</label>
                      <div class="controls">
                        <input type="text" id="cus_country"  name="cus_country" class="span8" placeholder="Tỉnh thành" />
                      </div>                   -->
                  </div>                  
                </div>            
              <!-- end form -->
            </div>          
          </div>
        </div>   
      </div> 

       <div class="row-fluid">
        <!-- open div general information-->
        <div class="span12">          
          <div class="widget-box">
            <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
              <h5>Thêm mới phí tập sự</h5>
            </div>
            <div class="widget-content nopadding" id="detail-information">
            <!--start form-->
              <form id="form-internship" class="form-horizontal" novalidate="novalidate">
                <input type="hidden" name="cus_id" id="cus_id" />
                <input type="hidden" name="payment_inter_off_code" id="payment_inter_off_code" value="<?php echo $this->payment_inter_off_code; ?>"/>
                <div class="row-fluid">
                  <div class="span6">
                      <!-- <label class="control-label">Thông tin khóa học :</label>
                      <div class="controls">
                        <input type="text" id="cus_cellphone"  name="cus_cellphone" class="span8" placeholder="số điện thoại" />
                      </div>  -->
                      <div class="control-group"> 
                        <label class="control-label">Số biên nhận:</label>
                        <div class="controls">
                          <strong><?php echo $this->payment_inter_off_code; ?></strong>
                        </div>
                      </div>

                      <!-- <div class="control-group">
                              <label class="control-label">Chọn đợt tập sự *</label>
                              <div class="controls"> 
                                  <select class="span8" id="intership_number" name="intership_number">
                                  <?php  
                                       foreach ($this->intershipdata as $join) {                        
                                          
                                          echo '<option value="'.$join['intership_number_id'].'" class="span8">'.$join['intership_number_name'].'</option>';
                                       }
                                      ?>    
                                  </select>
                              </div>
                      </div>  -->
                  </div>  
                  <div class="span6">                            
                        <!-- <div class="control-group">
                              <label class="control-label">Chọn loại phí *:</label>
                                <div class="controls"> 
                                  <select class="span10" id="category_fee_id" name="category_fee_id">
                                  <?php  
                                      foreach ($this->categoryfee as $cat) {                                          
                                            echo '<option value="'.$cat['category_fee_id'].'" class="span8">'.$cat['name'].'</option>';
                                      }
                                      ?>    
                                  </select>
                              </div>
                        </div>  -->

                        <div class="control-group">        
                            <label class="control-label">Số tiền:</label>
                            <!-- <div class="controls">
                            <input type="text" id="amount"  name="amount" disabled value="<?php echo number_format($this->amountYear);?>" data-type="number" class="span8" placeholder="Vui lòng nhập số tiền" />
                            </div> -->
                            <div class="controls"> 
                                <select class="span10" id="category_fee_id" name="category_fee_id">
                                <?php  
                                    foreach ($this->categoryfee as $cat) {                                          
                                          $mooney = number_format($cat['mooney']);
                                          echo '<option value="'.$cat['category_fee_id'].'" class="span8">'.$cat['name'].' - '.$mooney.'</option>';
                                    }
                                    ?>    
                                </select>
                            </div>
                        </div>                                   
                  </div>   

                

                </div>             
                <div class="row-fluid">
                    <div class="span2">
                    </div>
                    <div class="span10">
                        <p id="notification"></p>              
                    </div>
                    
                </div>                       
                 <div class="form-actions">                  
                  <button type="submit" class="btn save-internship">Nhập</button>                  
                  <button class="btn">Hủy bỏ</button>
                </div> 
              </form>
              <!-- end form -->
            </div>                      
          </div>
          
            <!--tab-->
            <div class="widget-box">
                <div class="widget-title">
                    <ul class="nav nav-tabs">
                        <li class="active"><a id="internship" data-toggle="tab" href="#tab1">Lịch sử đóng phí tập sự</a></li>                 
                    </ul>
                </div>
                <div class="widget-content tab-content">
                    <div id="tab1" class="tab-pane active">
                        <div class="row-fluid">
                          <div class="span12">    
                            <div class="widget-box">
                              <div class="widget-title">
                                <span class="icon"><i class="icon-th"></i></span> 
                                <h5>Lịch sử đóng phí tập sự</h5>
                              </div>
                              <div class="widget-content nopadding">
                              <table class="table table-bordered">
                                  <thead>
                                    <tr>
                                      <th>Tên người đóng phí </th>
                                      <th>Trạng thái</th>
                                      <th>Ngày đóng phí</th>
                                      <th>Loại</th>
                                      <th>Tổng tiền</th>
                                      <th>Thao tác</th>
                                    </tr>
                                  </thead>
                                  <tbody id="table-lawyer">                                 
                            
                                  </tbody>
                                </table>                            
                              </div>
                            </div>
                                    
                          </div>          
                        </div>         
                    </div>
                   
      </div>     
    </div>    
    </div>
      <!--end div-->   
      <!--open div--> 
   
    </div>  
  </div>
  
 
<!-- </div> -->

<!-- Modal -->
<div id="model-warning" class="modal fade" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <p id="message">Trong hệ thống đã tồn tại luật sư,hệ thống sẽ tải thông tin để bạn đăng kí tập sự.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>