<?php  
    if($this->paymentofflines != null){
        foreach ($this->paymentofflines as $pay) {           
            // '<td>'.$pay['payment_lawyer_off_id'].'</td>'.
             $print = '';
             if($pay['payment_lawyer_off_status'] != 1){               
                $print = '<td><button onClick="printPaymentMember('.$pay['payment_lawyer_off_id'].');"><i class="icon-print" ></i></button></td>';  
             }else{
                // $print = '<td></td>';
                $print = '<td><button onClick="printPaymentMember('.$pay['payment_lawyer_off_id'].');"><i class="icon-print" ></i></button></td>';  
             }       

             $text = ''; 
             if($pay['payment_lawyer_off_status'] == 1){
                $text = '<td>Đã thanh toán</td>';
             }else{
                $text = '<td>Chưa thanh toán</td>';  
             }    

             $payment_lawyer_off_created_date = ($pay['payment_lawyer_off_created_date'] != null && $pay['payment_lawyer_off_created_date'] != ''
             && $pay['payment_lawyer_off_created_date'] != '1900-01-01 00:00:00') ? date('d/m/Y', strtotime($pay['payment_lawyer_off_created_date'])) : '';    

             echo ' <tr class="gradeC">'.
             '<td>'.$pay['cus_firstname'].' '.$pay['cus_lastname'].'</td>'.
             '<td>'.$pay['cus_lawyer_number'].'</td>'.
             '<td>'.$pay['law_certfication_no'].'</td>'.
             $text.
             '<td>'.$payment_lawyer_off_created_date.'</td>'.
             '<td>'.$pay['name'].'</td>'.
             '<td>'.number_format($pay['amount']).'</td>'.  
             '<td>'.$pay['month'].'</td>'.
             '<td>'.$pay['startedmonth'].'</td>'.
             '<td>'.$pay['endmonth'].'</td>'.
            //  '<td>'.
            //  '<button onClick="printPaymentMember('.$pay['payment_lawyer_off_id'].');"><i class="icon-print"></i></button>'.
            //  '</td>'.
             $print.
        '</tr>';                            
        }  
    }else{
        echo " Không có dữ liệu đóng phí thành viên.";
    }

?>   
                            
                               