<script>
    $(document).ready(function(){
      
      $(".dropdown-menu").hide();
      $("#model-warning").modal("hide");
      $(".message-success").hide(); 
      $('select').select2();

      $("input[data-type='number']").keyup(function(event){
          // skip for arrow keys
          if(event.which >= 37 && event.which <= 40){
              event.preventDefault();
          }
          var $this = $(this);
          var num = $this.val().replace(/,/gi, "");
          var num2 = num.split(/(?=(?:\d{3})+$)/).join(",");
          // console.log(num2);
          // the following line has been simplified. Revision history contains original.
          $this.val(num2);
      });  

      var date = new Date();
      // var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
      // $('.datepicker-ngaynop').datepicker({ format: 'dd/mm/yyyy' });
      // $('.datepicker-ngaynop').datepicker('setValue', today);
      $("#year").val(date.getFullYear());

    //   $("#notification").html("Thông báo : Số tiền bạn đóng phí thành viên là ")

    // $(".close-modal").on('click',function(){
    //   location.reload();
    // });

      // var regis_date = '';

      // $('#dp5').datepicker()
      // .on('changeDate', function(ev){
      //     regis_date = ev.date.valueOf();        
      // });    


      $("#search-global").keyup(function(e) {  
        //console.log("test code");      
        $("#cus_id").val('');    
        var key = e.keyCode;

        if (key == 40 || key == 38 || key == 13) {
          return false;
        }     
        var searchbox = $(this).val();
        var dataString = 'searchword='+ searchbox+'&searchfield='+$("#search-field").val();
        searchData(searchbox,dataString);   
    });  

      $("#month").click(function(){      
      var total = parseInt($("#amount").val()*$("#month").val());
      $("#messagesSumMooney").html('Tổng số tiền : '+ numberWithCommas(parseInt(total)));
    });

    $("#form-internship").validate({
          rules:{
            regis_date:{
              required:true
            },
            lawyer_guide:{
              required:true
            },
            amount:{
              required:true
            }
          },
          errorClass: "help-inline",
          errorElement: "span",
          highlight:function(element, errorClass, validClass) {
            $(element).parents('.control-group').addClass('error');
          },
          unhighlight: function(element, errorClass, validClass) {
            $(element).parents('.control-group').removeClass('error');
            $(element).parents('.control-group').addClass('success');
          },
          messages: {
            regis_date: "Chọn ngày đóng phí thành viên !!!",
            lawyer_guide:"Chọn luật sư hướng dẫn" ,
            amount:"Vui lòng nhập số tiền"  
          },
          submitHandler: function(form,e) {
            console.log('Form submitted');
            var data = {
              month :  $("#month").val(),
              cus_id : $("#cus_id").val(),
              category_fee_id : $("#category_fee_lawyer_id").val(),
              amount : $("#amount").val(),
              startmonth : $("#startmonth").val(),
              cus_age : $("#cus_age").val(),
              cus_member : $("#cus_member").val(),
              type : $("#type").val(),
              payment_lawyer_off_code :$("#payment_lawyer_off_code").val(),
              category_fee_id : $("#category_fee_id").val(),
              cus_age_year : $("#cus_age_year").val()
            }

            $.ajax({
                  type: "POST",
                  url: "<?php echo $this->BaseUrl?>/default/fee/create/",
                  data: data ,
                  cache: false,
                  // beforeSend: function(){
                  //   $("#wait").css("display", "block");
                  // },
                  // complete: function(){
                  //   $("#wait").css("display", "none");
                  // },
                  success: function(html)
                  {   
                    //$(".message-success").show();
                    //alert(html);
                    $("#message").html(html);
                    $("#model-warning").modal("show");
                    if($("#cus_id").val() != null && $("#cus_id").val() != undefined){
                      loadDataForTab($("#cus_id").val(),"#table-lawyer","lawyer");
                    }                   
                    // $("#display-content-search").html('');
                    // $("#display-content-search").html(html);                  
                  }
            });
            return false;                       
        }
	  });

    $('#search').on("keydown", "#search-global", function (e) {
        console.log("event key down");
        var $listItems = $('.display-box-search-result li');
        //console.log($listItems);
        var key = e.keyCode,
        $selected = $listItems.filter('.hovered'),$current;

        var $scrollable = $("#display-content-search-global");
		    var scrollTop = $scrollable.scrollTop();

        //console.log(scrollTop);

        if (key != 40 && key != 38 && key != 13)
            return;

        //$listItems.removeClass('selected');

        if (key == 40) // Down key
        {
            $listItems.removeClass('hovered');
            if (!$selected.length || $selected.is(':last-child')) {
                $current = $listItems.eq(0);
            } else {
                $current = $selected.next();
            }
            $current.addClass('hovered');
            //console.log("Current : "+$current);
            //console.log($current);
            //$scrollable.scrollTop(scrollTop + 10);
        } 
        else if (key == 38) // Up key
        {
            $listItems.removeClass('hovered');
            if (!$selected.length || $selected.is(':first-child')) {
                $current = $listItems.last();
            } else {
                $current = $selected.prev();
            }       
            $current.addClass('hovered');
            //console.log($('.display-box-search-result li').length);
            //$scrollable.scrollTop(scrollTop - 10);

        } 
        else if (key == 13) // Enter key
        {
            $current = $listItems.filter('.hovered');
            $current.trigger('click');
            return false;
        }

        $("#display-content-search-global").scrollTop(0);//set to top
        $("#display-content-search-global").scrollTop($('.hovered:first').offset().top-$("#display-content-search-global").height());       
        
    });

    $('#display-content-search-global').on('click', function(event) {
      console.log("action event");
      var id = $(event.target).attr('id');
      // console.log(id);
      var value = $("#"+id).val();
      // console.log(value.split('-')[1]);
      
      var dataString = '?searchword='+ id;
      // console.log(dataString);
       $.ajax({
            type: "GET",
            url: "<?php echo $this->BaseUrl?>/default/customers/detail"+dataString ,
            //data: dataString+'?format=html',
            dataType: 'json',
            cache: false,
            success: function(data)
            {   
              //console.log(data);
              if(data.cus_id != null && data.cus_id != undefined){
                     $("#cus_id").val(data.cus_id);
                     loadDataForTab(data.cus_id,"#table-lawyer","lawyer");
                     $('#display-content-search-global').html('');
                    //  console.log(data);
                    //  console.log($("#search-field").val());
                     if($("#search-field").val() != null && $("#search-field").val() == "name"){
                      $("#search-global").val(data.cus_fullname);
                     }else if($("#search-field").val() != null && $("#search-field").val() == "lawyer_number"){
                      $("#search-global").val(data.cus_lawyer_number);
                     }else if($("#search-field").val() != null && $("#search-field").val() == "identity_card"){
                      $("#search-global").val(data.cus_identity_card);
                     }else{
                      $("#search-global").val(data.cus_cellphone);
                     }
                    //  $("#search-global").val(data.cus_identity_card);
                     $("#cus_cellphone").val(data.cus_cellphone);
                     $("#cus_firstname").val(data.cus_firstname);
                     $("#cus_lastname").val(data.cus_lastname);
                     $("#cus_identity_card").val(data.cus_identity_card);
                     $("#cus_username").val(data.cus_username);
                     $("#cus_birthday").val(data.cus_birthday);
                     $("#cus_country").val(data.cus_country);
                     //$("#endmonth").val(data.endmonth);                     

                     var d = new Date(); // January 1, 2000 
                     var birthdate =  data.cus_birthday;
                     //set ngày sinh
                     $("#cus_age").val(parseInt(d.getFullYear()-birthdate.split('/')[2]));
                     //$("#cus_age_year").val(birthdate.split('/')[2]);
                     // bắt đầu đóng tiền từ tháng
                     $("#cus_member").val(data.cus_member);
                     $("#cus_age_year").val(0);
                     
                     
                     var endMonth = data.endmonth; 
                     console.log(endMonth);   
                     if(endMonth == null){
                        var date = new Date();
                        // var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
                        console.log(date.getMonth());
                        var month = '';
                        if(date.getMonth()<10){
                          month  = '0'+(date.getMonth()+1);
                        }
                        $("#startmonth").val(month+'/'+date.getFullYear()); 
                     }else{
                        console.log(endMonth.split('/')[0]);
                        console.log(parseInt(endMonth.split('/')[1])+1);
                        if(endMonth.split('/')[0] == '01'){
                        $("#startmonth").val('02/'+endMonth.split('/')[1]);
                        }else if(endMonth.split('/')[0] == '02'){
                          $("#startmonth").val('03/'+endMonth.split('/')[1]);  
                        }else if(endMonth.split('/')[0] == '03'){
                          $("#startmonth").val('04/'+endMonth.split('/')[1]);  
                        }else if(endMonth.split('/')[0] == '04'){
                          $("#startmonth").val('05/'+endMonth.split('/')[1]);  
                        }else if(endMonth.split('/')[0] == '05'){
                          $("#startmonth").val('06/'+endMonth.split('/')[1]);  
                        }else if(endMonth.split('/')[0] == '06'){
                          $("#startmonth").val('07/'+endMonth.split('/')[1]);  
                        }else if(endMonth.split('/')[0] == '07'){
                          $("#startmonth").val('08/'+endMonth.split('/')[1]);  
                        }else if(endMonth.split('/')[0] == '08'){
                          $("#startmonth").val('09/'+endMonth.split('/')[1]);  
                        }else if(endMonth.split('/')[0] == '09'){
                          $("#startmonth").val('10/'+endMonth.split('/')[1]);  
                        }else if(endMonth.split('/')[0] == '10'){
                          $("#startmonth").val('11/'+endMonth.split('/')[1]);  
                        }else if(endMonth.split('/')[0] == '11'){
                          $("#startmonth").val('12/'+endMonth.split('/')[1]);  
                        }else if(endMonth.split('/')[0] == '12'){
                          $("#startmonth").val('01/'+(parseInt(endMonth.split('/')[1])+1));  
                        }

                        //case 75 tuoi
                        if(parseInt(d.getFullYear()-birthdate.split('/')[2]) >= 75){
                          $endyearpayment = parseInt(birthdate.split('/')[2]) + parseInt(75);
                          $endmonthpayment = '';
                          if( parseInt(endMonth.split('/')[1])+1 < parseInt($endyearpayment)){
                            if(endMonth.split('/')[0] == '01'){
                              //$("#startmonth").val('02/'+$endyearpayment);
                              $endmonthpayment = '02';
                            }else if(endMonth.split('/')[0] == '02'){
                              //$("#startmonth").val('03/'+$endyearpayment);  
                              $endmonthpayment = '03';
                            }else if(endMonth.split('/')[0] == '03'){
                              //$("#startmonth").val('04/'+$endyearpayment);  
                              $endmonthpayment = '04';
                            }else if(endMonth.split('/')[0] == '04'){
                              //$("#startmonth").val('05/'+$endyearpayment);  
                              $endmonthpayment = '05';
                            }else if(endMonth.split('/')[0] == '05'){
                              //$("#startmonth").val('06/'+$endyearpayment);  
                              $endmonthpayment = '06';
                            }else if(endMonth.split('/')[0] == '06'){
                              //$("#startmonth").val('07/'+$endyearpayment);  
                              $endmonthpayment = '07';
                            }else if(endMonth.split('/')[0] == '07'){
                              //$("#startmonth").val('08/'+$endyearpayment); 
                              $endmonthpayment = '08'; 
                            }else if(endMonth.split('/')[0] == '08'){
                              //$("#startmonth").val('09/'+$endyearpayment);  
                              $endmonthpayment = '09';
                            }else if(endMonth.split('/')[0] == '09'){
                              //$("#startmonth").val('10/'+$endyearpayment);  
                              $endmonthpayment = '10';
                            }else if(endMonth.split('/')[0] == '10'){
                              //$("#startmonth").val('11/'+$endyearpayment); 
                              $endmonthpayment = '11'; 
                            }else if(endMonth.split('/')[0] == '11'){
                              //$("#startmonth").val('12/'+$endyearpayment);  
                              $endmonthpayment = '12';
                            }else if(endMonth.split('/')[0] == '12'){
                              //$("#startmonth").val('01/'+(parseInt($endyearpayment)));  
                              $endmonthpayment = '01';
                            }
                            //console.log("test code "+$("#startmonth").val());
                            
                            //console.log("test code "+endMonth.split('/')[0]);
                            if(endMonth.split('/')[0] >= $endmonthpayment && endMonth.split('/')[1] >= $endyearpayment){
                              //console.log("Khong dong nua");
                              $("#cus_age_year").val(1);
                            }
                          }
                        }
                     }   
              
              }
              //console.log(data);             
            }, error: function(msg){               
            }           
            });
    });
 
});

  function searchData(searchbox,dataString){
    if(searchbox ==''){
            $("#display-content-search-global").html('');
            //load = true;
        } else
        {
            $.ajax({
                type: "POST",
                url: "<?php echo $this->BaseUrl?>/default/customers/search/",
                data: dataString,
                cache: false,
                success: function(html)
                {   
                  //$("#display-content-search-global").html('');
                  //console.log(html.length);
                  $("#display-content-search-global").html(html);                  
                }
            });
            //load = true
        }
  }  

 function numberWithCommas(x) {
    return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
 }

  function isNumber(n) {
    return !isNaN(parseFloat(n)) && isFinite(n);
  }

  function loadDataForTab(cus_id,div_content,typetab){ 
        var dataString = '?cus_id='+ cus_id;        
        if(cus_id =='' || cus_id == undefined){
            $("#table-lawyer").html('');
        } else
        {
            var url = "<?php echo $this->BaseUrl?>/default/fee/list"+dataString;

            $.ajax({
                type: "GET",
                url: url,
                //data: dataString,
                //dataType: 'json',
                cache: false,
                success: function(html)
                {   
                  //alert(html);
                  $(div_content).html(html);                  
                }
            });
        }
        return false;   
  }

  function printPaymentMember($id){
    var dataString = '?payment_lawyer_off_id='+ $id;
         $.ajax({
              type: "GET",
              timeout: 120000,
              url: "<?php echo $this->BaseUrl?>/default/fee/printlawyerfee"+dataString ,
              cache: false,
              async:false,
              dataType : 'html',
              success: function(html)
              {                
   
                var mywindow = window.open('', 'Print-Window');

                mywindow.document.write('<html><head><title>' + document.title  + '</title>');
                mywindow.document.write('</head><body >');
                mywindow.document.write('<h1>' + document.title  + '</h1>');
                mywindow.document.write(html);
                mywindow.document.write('</body></html>');

                mywindow.document.close(); // necessary for IE >= 10
                mywindow.focus(); // necessary for IE >= 10*/

                mywindow.print();
                mywindow.close();
              }
         });  

    }

</script>

    <!-- <div id="wait" style="width:69px;height:89px;position:absolute;top:50%;left:50%;padding:2px;"><img src='<?php echo $this->BaseUrl?>/files/images/demo_wait.gif' width="64" height="64" /><br>Đang tải..</div>     -->
 <div id="content">    
    <div id="content-header">
      <div id="breadcrumb"> <a href="" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i></a> <a href="#" class="current">Thêm mới biên nhận thành viên</a> </div>
      <!-- <h1>Quản lý luật sư</h1> -->
    </div>
   <div class="container-fluid"> 
   <div class="row-fluid">
      <div class="alert alert-success alert-dismissible message-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <strong>Thông báo</strong> Bạn đã tạo thành công một biên nhận phí thành viên.
        </div>
    </div>   
    <!-- <h4>Thêm mới luật sư tập sự</h4> -->
    <div class="row-fluid">                       
        <!-- open div general information-->
        <div class="span12">          
          <div class="widget-box">
            <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
              <h5>Thông tin chung</h5>
            </div>
            <div class="widget-content nopadding" id="detail-information">
            <!--start form-->              
                <div class="row-fluid form-horizontal">
                  <div class="span6">
                      <label class="control-label">Họ và lót:</label>
                      <div class="controls">
                        <input type="text" disabled id="cus_firstname"  name="cus_firstname" class="span8" placeholder="Họ của luật sư" />
                      </div>  
                      <label class="control-label">Tên :</label>
                      <div class="controls">
                        <input type="text" disabled id="cus_lastname"  name="cus_lastname" class="span8" placeholder="Tên của luật sư" />
                      </div>
                      <label class="control-label">Ngày sinh :</label>
                      <div class="controls">
                        <input type="text" disabled  id="cus_birthday"  name="cus_birthday" class="span8" placeholder="Ngày sinh" />
                      </div>  
                     
                      <!-- <label class="control-label">Tên đăng nhập:</label>
                        <div class="controls">
                          <input type="text" id="cus_username"  name="cus_username" class="span8" placeholder="Nhập số điện thoại để tìm luật sư" />
                      </div>                                      -->
                  </div>  
                  <div class="span6">
                      <label class="control-label">Số điện thoại :</label>
                      <div class="controls">
                        <input type="text" disabled id="cus_cellphone"  name="cus_cellphone" class="span8" placeholder="Số điện thoại" />
                      </div> 
                      <label class="control-label">Số chứng minh nhân dân :</label>
                      <div class="controls">
                        <input type="text" disabled id="cus_identity_card"  name="cus_identity_card" class="span8" placeholder="Số chứng minh nhân dân" />
                      </div> 
                      <!-- <label class="control-label">Tỉnh thành :</label>
                      <div class="controls">
                        <input type="text" id="cus_country"  name="cus_country" class="span8" placeholder="Tỉnh thành" />
                      </div>     -->

                  </div>                  
                </div>            
              <!-- end form -->
            </div>          
          </div>
        </div>   
      </div> 

       <div class="row-fluid">
        <!-- open div general information-->
        <div class="span12">          
          <div class="widget-box">
            <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
              <h5>Thêm mới phí thành viên</h5>
            </div>
            <div class="widget-content nopadding" id="detail-information">
            <!--start form-->
              <form id="form-internship" class="form-horizontal" novalidate="novalidate">
                <input type="hidden" name="cus_id" id="cus_id" />
                <input type="hidden" name="cus_age" id="cus_age" />
                <input type="hidden" name="cus_age_year" id="cus_age_year" />
                <input type="hidden" name="cus_member" id="cus_member" />
                <input type="hidden" name="type" id="type" value="offline" />
                <input type="hidden" value="<?php echo $this->amountYear; ?>" name="amount" id="amount" />
                <input type="hidden" value="<?php echo $this->payment_lawyer_off_code; ?>" name="payment_lawyer_off_code" id="payment_lawyer_off_code" />
                <div class="row-fluid">
                  <div class="span6">
                      <div class="control-group"> 
                        <label class="control-label">Số biên nhận:</label>
                        <div class="controls">
                          <strong><?php echo $this->payment_lawyer_off_code; ?></strong>
                      </div>
                      </div> 
                      <div class="control-group">        
                          <label class="control-label">Số tiền mỗi tháng:</label>
                          <div class="controls">
                          <input type="text" disabled value="<?php echo number_format($this->amountYear); ?>" data-type="number" class="span8" placeholder="Vui lòng nhập số tiền" />
                          </div>
                      </div>

                      <!-- <div class="control-group">        
                          <label class="control-label">Đã đóng tiền đến tháng:</label>
                          <div class="controls">
                          <input type="text" disabled id="endmonth"  name="endmonth"  class="span8"  />
                          </div>
                      </div>  -->
                      <div class="control-group">        
                          <label class="control-label">Đóng từ tháng:</label>
                          <div class="controls">
                          <input type="text" disabled id="startmonth"  name="startmonth"  class="span8"  />
                          </div>
                      </div>  
                      <div class="control-group">
                        <div class="controls">
                          <p id="messagesSumMooney"></p>
                        </div>
                      </div>

                  </div>  
                  <div class="span6">
                            <div class="control-group">
                              <label class="control-label">Chọn số tháng đóng *:</label>
                                <div class="controls">                                
                                  <select class="span3" id="month" name="month">
                                  <?php  
                                      for ($month = 1; $month<=48 ; $month++) {
                                        echo '<option value="'.$month.'" class="span8">'.$month.'</option>';
                                      }
                                      ?>    
                                  </select>
                              </div>
                        </div>   
                        <div class="control-group">
                              <label class="control-label">Chọn loại phí *:</label>
                                <div class="controls"> 
                                  <select class="span8" id="category_fee_id" name="category_fee_id">
                                  <?php  
                                      foreach ($this->categoryfee as $cat) {
                                         // if($cat['category_fee_lawyer_id'] == 1){
                                            echo '<option value="'.$cat['category_fee_id'].'" class="span8">'.$cat['name'].'</option>';
                                         // }                                          
                                      }
                                      ?>    
                                  </select>
                              </div>
                        </div>                                                   
                  </div>                  
                </div>             
                <div class="row-fluid">
                    <div class="span2">
                    </div>
                    <div class="span10">
                        <p id="notification"></p>              
                    </div>
                    
                </div>                       
                 <div class="form-actions">                  
                  <button type="submit" class="btn save-internship">Nhập</button>                  
                  <button class="btn">Hủy bỏ</button>
                </div> 
              </form>
              <!-- end form -->
            </div>                      
          </div>
          
            <!--tab-->
             <div class="widget-box">                                    
                <div class="widget-title">
                    <ul class="nav nav-tabs">
                        <li class="active"><a id="internship" data-toggle="tab" href="#tab1">Lịch sử đóng phí thành viên</a></li>                 
                    </ul>
                </div>
                <div class="widget-content tab-content">                
                    <div id="tab1" class="tab-pane active">
                        <div class="row-fluid">
                          <div class="span12">    
                            <div class="widget-box">
                              <div class="widget-title">
                                <span class="icon"><i class="icon-th"></i></span> 
                                <h5>Lịch sử đóng phí thành viên</h5>
                              </div>
                              <div class="widget-content nopadding">
                              <table class="table table-bordered">
                                  <thead>
                                    <tr>
                                      <th>Tên người đóng phí </th>
                                      <th>Số thẻ luật sư </th>
                                      <th>Số chứng chỉ hành nghề </th>
                                      <th>Trạng thái</th>
                                      <th>Ngày đóng phí</th>
                                      <th>Loại</th>
                                      <th>Tổng tiền</th>
                                      <th>Thời gian (tháng)</th>
                                      <th>Tháng bắt đầu</th>
                                      <th>Tháng kết thúc</th>
                                      <th>Thao tác</th>
                                    </tr>
                                  </thead>
                                  <tbody id="table-lawyer">                                 
                            
                                  </tbody>
                                </table>                            
                              </div>
                            </div>
                                    
                          </div>          
                        </div>         
                    </div>
                    
      </div>     
    </div>    
    </div>
      <!--end div-->   
      <!--open div--> 
   
    </div>  
  </div>
  
 
<!-- </div> -->

<!-- Modal -->
<div id="model-warning" class="modal fade" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <p id="message">Trong hệ thống đã tồn tại luật sư,hệ thống sẽ tải thông tin để bạn đăng kí tập sự.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary close-modal" data-dismiss="modal">Đóng</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>