<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1">
<style>
body {
    margin: 0;
    padding: 0;
    background-color: #FAFAFA;
    font: 10pt "Tahoma";
    line-height:100%;
}
* {
    box-sizing: border-box;
    -moz-box-sizing: border-box;
}
/* .content strong{
    text-decoration: underline;
} */
.page {
    width: 21cm;
    overflow:hidden;
    max-height:148.5mm;
    padding: 1.5cm;
    margin-left:auto;
    margin-right:auto;
    background: white;
    box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
}
.subpage {
    padding: 1cm;
    border: 5px red solid;
    height: 237mm;
    outline: 2cm #FFEAEA solid;
}
 @page {
 size: A5 landscape;
 margin: 10%;
}
button {
    width:100px;
    height: 24px;
}
.header {
    overflow:hidden;
}
.logo {
    /*background-color:#FFFFFF;*/
    text-align:center;
    float:left;
}
.company {
    /*padding-top:24px;*/
    background-color:#FFFFFF;
    text-align:right;
    float:right;
    padding-right:30px;
    font-size:13px;
}
.title {
    text-align:center;
    position:relative;
    color:#0000FF;
    font-size: 16px;
    top:1px;
}
.footer-left {
    text-align:center;
    /* text-transform:uppercase; */
    /* padding-top:24px; */
    padding-top:15px;
    position:relative;
    height: 90px;
    width:25%;
    color:#000;
    float:left;
    font-size: 12px;
    bottom:1px;
}
.footer-mid {
    text-align:center;
    /* text-transform:uppercase; */
    padding-top:15px;
    position:relative;
    height: 90px;
    width:30%;
    color:#000;
    float:left;
    font-size: 12px;
    bottom:1px;
}
.footer-right {
    text-align:center;
    /* text-transform:uppercase; */
    padding-top:0px;
    position:relative;
    height: 90px;
    width:45%;
    color:#000;
    font-size: 12px;
    float:right;
    bottom:1px;
}
.note{
	padding-top:35px;
	text-align: center;
	 font-size: 11px;
}
.clear {
    clear: both;

}

@media print {
 @page {
 margin: 0;
 border: initial;
 border-radius: initial;
 width: initial;
 min-height: initial;
 box-shadow: initial;
 background: initial;
 page-break-after: always;
}
}
</style>
<body onload="window.print();">
<div id="page" class="page">
    <div class="header">
        <div class="logo">ĐOÀN LUẬT SƯ <br/>
         THÀNH PHỐ HỒ CHÍ MINH<br/>
         ----oOo----
         </div>
        <div class="company">Số : <?php echo $this->differentpayment['payment_off_code']; ?> </div>
    </div>
  <div class="title">
        BIÊN NHẬN
        <br/>
        *****
  </div>
  <div class="content">
    <p>Nhận của &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: 
        <strong>Luật Sư/ Tổ chức: <span style="text-transform: uppercase;"><?php echo $this->differentpayment['cus_firstname'].' '.$this->differentpayment['cus_lastname'].' '.$this->differentpayment['community'] ?></span></strong>
    </p>
    <p>Lý do thu &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <strong><span><?php echo $this->differentpayment['reason']; ?></span></strong>
    </p>
    <p>
       Ngày thu &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <strong><span><?php echo ($this->differentpayment['payment_off_created_date'] != null && 
       $this->differentpayment['payment_off_created_date'] != '' && $this->differentpayment['payment_off_created_date'] != '1900-01-01 00:00:00')  ? date('d/m/Y', strtotime($this->differentpayment['payment_off_created_date'])) : ''; ?></span></strong>
    </p>
    <p>Số tiền : <strong><span style="font-style: italic;"><?php echo number_format($this->differentpayment['amount']); ?></span></strong></p>
    <!-- <p>(Bằng chữ : <strong>hai trăm năm mươi ngàn đồng.)</strong></p> -->
  </div>  
     <div class="footer-left"> 
    Người nộp </div>
  <div class="footer-mid"> 
    Người lập phiếu
    <br/>
    <br/>
    <br/>
    <br/>
	<br/>
<br/>
	<br/>    
    <strong> LS Lê Thị Hòa</strong></div>  
    <div class="footer-right"> TP Hồ Chí Minh, Ngày <?php echo date('d', strtotime($this->differentpayment['payment_off_created_date'])) ?> tháng <?php echo date('m', strtotime($this->differentpayment['payment_off_created_date'])) ?> năm <?php echo date('Y', strtotime($this->differentpayment['payment_off_created_date'])) ?><br>
    Người nhận
    <br/>
	<br/>
    <br/>
    <br/>
    <br/>     <br/>
    <br/>
    <strong>LS Kỷ Minh Đức</strong> </div> 
    <div class="clear"></div>
    <div class="note">	  
    <!-- <span style="font-size:12px;font-style: italic;">Ghi chú: Đề nghị luật sư, luật sư tập sự lưu giữ biên nhận để tiện đối chiếu</span> -->
	</div>
</div>
</body>

</head>

