<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Danh sách khách hàng</h6>
        </div>

        <div class="card-body">
          <div class="border-bottom mb-3 pb-3">
            <button type="button" id="btnThemKH" class="btn btn-primary">
              <i class="fas fa-plus"></i>
              Thêm khách hàng
            </button>

            <label for="fileUpload" class="btn btn-light btn-outline-secondary ml-1 mb-0">
              <i class="fas fa-upload"></i>
              Import Excel
              <input id="fileUpload" name="fileUpload" type="file" class="d-none" accept="application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">
            </label>
          </div>

          <table id="tblCustomer" class="table table-bordered table-striped table-hover data-table responsive">
            <thead></thead>
            <tbody></tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<!--------------------------------------------------------------------------------------->

<!-- Detail dialog -->
<div id="detailDlg" class="modal fade" tabindex="-1">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Thông Tin Chi Tiết Khách Hàng</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <div class="modal-body px-0">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-3">
              <label class="mb-1">Mã khách hàng</label>
              <input type="text" id="txtMaKH" class="form-control">
              <input type="hidden" id="hidCusId">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Tên khách hàng</label>
              <input type="text" id="txtTenKH" class="form-control">
            </div>
            <div class="col-md-6">
              <label class="mb-1">Địa chỉ</label>
              <input type="text" id="txtDiaChi" class="form-control">
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-6">
              <label class="mb-1">Nhóm KH, NCC</label>
              <select multiple id="selNhomKH"></select>
            </div>
            <div class="col-md-3">
            <label class="mb-1">Mã số thuế</label>
              <input type="number" id="txtMST" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Điện thoại</label>
              <input type="text" id="txtDienThoai" class="form-control">
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-3">
              <label class="mb-1">ĐT di động</label>
              <input type="text" id="txtDiDong" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Fax</label>
              <input type="text" id="txtFax" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Email</label>
              <input type="email" id="txtEmail" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Website</label>
              <input type="url" id="txtWebsite" class="form-control">
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-3">
              <label class="mb-1">CMND / CCCD</label>
              <input type="number" id="txtCMND" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Ngày cấp</label>
              <input id="dpNgayCap" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Nơi cấp</label>
              <input type="text" id="txtNoiCap" class="form-control">
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-6">
              <label class="mb-1">Điều khoản TT</label>
              <input type="text" id="txtDieuKhoanTT" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Số ngày được nợ</label>
              <input type="number" id="txtSoNgayDuocNo" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Số nợ tối đa</label>
              <input type="number" id="txtNoToiDa" class="form-control">
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-3">
              <label class="mb-1">Nhân viên</label>
              <input type="text" id="txtNhanVien" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Tên nhân viên</label>
              <input type="text" id="txtTenNhanVien" class="form-control">
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-3">
              <label class="mb-1">TK ngân hàng</label>
              <input type="text" id="txtTKNH" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Tên ngân hàng</label>
              <input type="text" id="txtTenNganHang" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Chi nhánh ngân hàng</label>
              <input type="text" id="txtChiNhanhNH" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Tỉnh/TP TK ngân hàng</label>
              <select id="selTinhTKNganHang"></select>
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-3">
              <label class="mb-1">Quốc gia</label>
              <select id="selQuocGia"></select>
            </div>
            <div class="col-md-3">
              <label class="mb-1">Tỉnh / TP</label>
              <select id="selTinhTP"></select>
            </div>
            <div class="col-md-3">
              <label class="mb-1">Quận/Huyện</label>
              <select id="selQuan"></select>
            </div>
            <div class="col-md-3">
              <label class="mb-1">Phường/Xã</label>
              <select id="selPhuong"></select>
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-3">
              <label class="mb-1">Xưng hô</label>
              <input type="text" id="txtXungHo" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Người liên hệ</label>
              <input type="text" id="txtNguoiLienHe" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Chức danh</label>
              <input type="text" id="txtChucDanh" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">ĐT di động</label>
              <input type="text" id="txtDTDiDong" class="form-control">
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-3">
              <label class="mb-1">ĐTDĐ khác</label>
              <input type="text" id="txtDTDDKhac" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">ĐT cố định</label>
              <input type="text" id="txtDTCoDinh" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Email</label>
              <input type="text" id="txtEmailNguoiLienHe" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1">Địa chỉ</label>
              <input type="text" id="txtDiaChiNguoiLienHe" class="form-control">
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-3">
              <label class="mb-1">Địa điểm giao hàng</label>
              <input type="text" id="txtDiaDiemGH" class="form-control">
            </div>
            <div class="col-md-3">
              <label class="mb-1"> </label>
              <div class="mt-2 pt-1">
                <div class="form-check d-inline-block">
                  <input class="form-check-input" type="radio" name="tochuc-canhan" id="radToChuc">
                  <label class="form-check-label" for="radToChuc">
                    Tổ chức
                  </label>
                </div>
                <div class="form-check d-inline-block ml-3">
                  <input class="form-check-input" type="radio" name="tochuc-canhan" id="radCaNhan">
                  <label class="form-check-label" for="radCaNhan">
                    Cá nhân
                  </label>
                </div>
              </div>
            </div>
            <div class="col-md-3">
              <label class="mb-1"> </label>
              <div class="mt-2 pt-1">
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" id="chkNhaCC">
                  <label class="form-check-label" for="chkNhaCC">
                    Là nhà cung cấp
                  </label>
                </div>
              </div>
            </div>
            <div class="col-md-3">
              <label class="mb-1"> </label>
              <div class="mt-2 pt-1">
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" id="chkNgungTheoDoi">
                  <label class="form-check-label" for="chkNgungTheoDoi">
                    Ngừng theo dõi
                  </label>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /modal-body -->

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          <i class="fas fa-times"></i>
          Đóng
        </button>
        <button id="btnSaveCustomer" type="button" class="btn btn-primary">
          <i class="fas fa-save"></i>
          Lưu
        </button>
      </div>
    </div>
  </div>
</div>
<!-- /Detail dialog -->

<!--------------------------------------------------------------------------------------->

<!-- Import dialog -->
<div id="importDlg" class="modal fade" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Import Excel</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <div class="modal-body">
        <p>
          Bạn đang import thông tin khách hàng từ tập tin
          <br>
          <span id="importDlg-filename" class="d-inline-block font-weight-bold ml-3"></span>
        </p>
        <p>Hãy chắc chắn rằng nội dung tập tin được soạn đúng theo mẫu được cung cấp.</p>
        <p>Tiếp tục import?</p>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          <i class="fas fa-times"></i>
          Đóng
        </button>
        <button id="btnImportCustomer" type="button" class="btn btn-primary">
          <i class="fas fa-file-import"></i>
          Import
        </button>
      </div>
    </div>
  </div>
</div>
<!-- /Import dialog -->

<script src="<?=$this->BaseUrl?>/public/js/customer.js"></script>
