<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Danh sách khách hàng</h6>
        </div>

        <div class="card-body">
          <div class="border-bottom mb-3 pb-3">
            <button type="button" data-target="#detailDlg" data-toggle="modal" class="btn btn-primary">
              <i class="fas fa-plus"></i>
              Thêm khách hàng
            </button>
            <button type="button" data-target="#importDlg" data-toggle="modal" class="btn btn-light btn-outline-secondary ml-1">
              <i class="fas fa-upload"></i>
              Import
            </button>
          </div>

          <table id="tblCustomer" class="table table-bordered table-striped data-table">
            <thead>
              <tr>
                <th>Mã khách hàng</th>
                <th>Tên khách hàng</th>
                <th>Địa chỉ</th>
                <th>Mã số thuế</th>
                <th>Điện thoại</th>
                <th>ĐT di động</th>
                <th>Nhóm KH, NCC</th>
                <th>Fax</th>
                <th>Email</th>
                <th>Website</th>
                <th>Số CMND</th>
                <th>Ngày cấp</th>
                <th>Nơi cấp</th>
                <th>Điều khoản TT</th>
                <th>Số ngày được nợ</th>
                <th>Số nợ tối đa</th>
                <th>Nhân viên</th>
                <th>Tên nhân viên</th>
                <th>TK ngân hàng</th>
                <th>Tên ngân hàng</th>
                <th>Chi nhánh TK ngân hàng</th>
                <th>Tỉnh/TP TK ngân hàng</th>
                <th>Quốc gia</th>
                <th>Tỉnh/TP</th>
                <th>Quận/Huyện</th>
                <th>Phường/Xã</th>
                <th>Xưng hô</th>
                <th>Người liên hệ</th>
                <th>Chức danh</th>
                <th>ĐT di động</th>
                <th>ĐTDĐ khác</th>
                <th>ĐT cố định</th>
                <th>Email</th>
                <th>Địa chỉ</th>
                <th>Địa điểm giao hàng</th>
                <th>Tổ chức/Cá nhân</th>
                <th>Là nhà cung cấp</th>
                <th>Trạng thái</th>
              </tr>
            </thead>
            <tbody>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<!--------------------------------------------------------------------------------------->

<!-- Detail dialog -->
<div id="detailDlg" class="modal" tabindex="-1">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Thông Tin Chi Tiết Khách Hàng</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <div class="modal-body">
        <div class="container-fluid">
          <div class="row">
            <div class="span4">
              <label>Mã khách hàng</label>
              <input type="text" id="txtMaKH" class="w-100">
            </div>
            <div class="span4">
              <label>Tên khách hàng</label>
              <input type="text" id="txtTenKH" class="w-100">
            </div>
            <div class="span4">
              <label>Địa chỉ</label>
              <input type="text" id="txtDiaChi" class="w-100">
            </div>
          </div>
          <div class="row">
            <div class="span4">
              <label>Mã số thuế</label>
              <input type="text" id="txtMST" class="w-100">
            </div>
            <div class="span4">
              <label>Điện thoại</label>
              <input type="text" id="txtDienThoai" class="w-100">
            </div>
            <div class="span4">
              <label>ĐT di động</label>
              <input type="text" id="txtDiDong" class="w-100">
            </div>
          </div>
          <div class="row">
            <div class="span4">
              <label>Nhóm KH, NCC</label>
              <input type="text" autocomplete="off" class="select2-input" tabindex="0" style="width: 10px;">
              <select multiple id="selNhomKH">
                <?php
                  foreach ($this->customerTypes as $cusType) {
                    echo '<option value="' . $cusType['customer_type_name'] . '">' . $cusType['customer_type_name'] . '</option>';
                  }
                ?>
              </select>
            </div>
            <div class="span4">
              <label></label>
              <input type="text" id="txt" class="w-100">
            </div>
            <div class="span4">
              <label></label>
              <input type="text" id="txt" class="w-100">
            </div>
          </div>
          <div class="row">
            <div class="span4">
              <label></label>
              <input type="text" id="txt" class="w-100">
            </div>
            <div class="span4">
              <label></label>
              <input type="text" id="txt" class="w-100">
            </div>
            <div class="span4">
              <label></label>
              <input type="text" id="txt" class="w-100">
            </div>
          </div>
          <div class="row">
            <div class="span4">
              <label></label>
              <input type="text" id="txt" class="w-100">
            </div>
            <div class="span4">
              <label></label>
              <input type="text" id="txt" class="w-100">
            </div>
            <div class="span4">
              <label></label>
              <input type="text" id="txt" class="w-100">
            </div>
          </div>
          <div class="row">
            <div class="span4">
              <label></label>
              <input type="text" id="txt" class="w-100">
            </div>
            <div class="span4">
              <label></label>
              <input type="text" id="txt" class="w-100">
            </div>
            <div class="span4">
              <label></label>
              <input type="text" id="txt" class="w-100">
            </div>
          </div>
          <div class="row">
            <div class="span4">
              <label></label>
              <input type="text" id="txt" class="w-100">
            </div>
            <div class="span4">
              <label></label>
              <input type="text" id="txt" class="w-100">
            </div>
            <div class="span4">
              <label></label>
              <input type="text" id="txt" class="w-100">
            </div>
          </div>
        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          <i class="fas fa-times"></i>
          Đóng
        </button>
        <button id="btnSaveCustomer" type="button" class="btn btn-primary">
          <i class="fas fa-save"></i>
          Lưu
        </button>
      </div>
    </div>
  </div>
</div>
<!-- /Detail dialog -->

<!--------------------------------------------------------------------------------------->

<!-- Import dialog -->
<div id="importDlg" class="modal" tabindex="-1">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Import Excel</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <div class="modal-body">
        <label class="control-label">Chọn file Excel</label>
        <input type="file" name="importExcel" />
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          <i class="fas fa-times"></i>
          Đóng
        </button>
        <button id="btnImportCustomer" type="button" class="btn btn-primary">
          <i class="fas fa-file-import"></i>
          Import
        </button>
      </div>
    </div>
  </div>
</div>
<!-- /Import dialog -->

<script src="<?=$this->BaseUrl?>/public/js/customer.js"></script>
