<script>
$(document).ready(function(){
    
	$('input[type=checkbox],input[type=radio],input[type=file]').uniform();
  $("#search").hide();
  $(".searchfield").hide();

    $(".message-success").hide();

    $("#model-warning").modal('hide');   

    $(".close-modal").on('click',function(){
      location.reload();
    });

    var date = new Date();
    var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
    console.log("<?php echo $this->data['activationdate']; ?>");
    $('.datepicker-activationdate').datepicker({ format: 'dd/mm/yyyy' });
    $('.datepicker-activationdate').datepicker('setValue', "<?php echo $this->data['activationdate']; ?>");

      $('.datepicker-expiredate').datepicker({ format: 'dd/mm/yyyy' });
    $('.datepicker-expiredate').datepicker('setValue', "<?php echo $this->data['expiredate']; ?>");
      
   $("#categorytranining_form").validate({     
          rules:{
            title:{
              required:true
            },
            description:{
              required:true
            }
          },
          errorClass: "help-inline",
          errorElement: "span",
          highlight:function(element, errorClass, validClass) {
            $(element).parents('.control-group').addClass('error');
          },
          unhighlight: function(element, errorClass, validClass) {
            $(element).parents('.control-group').removeClass('error');
            $(element).parents('.control-group').addClass('success');
          },
          messages: {
            title: "Vui lòng nhập tên thông báo !",
            description: "Vui lòng nhập tên nội dung thông báo !"
                      
          },
          submitHandler: function(form,e) {
             console.log('Form submitted');
             console.log($('#categorytranining_form').serialize());
            $.ajax({
                  type: "POST",
                  url: "<?php echo $this->BaseUrl?>/default/notification/update/",
                  data: $('#categorytranining_form').serialize() ,
                  cache: false,
                  success: function(html)
                  {   
                    //$("#message").html(html);
                    $(".message-success").show();
                    $("#model-warning").modal("show");                                                   
                  }
            });
            return false;                       
        }
	});


  function isNumber(n) {
    return !isNaN(parseFloat(n)) && isFinite(n);
  }

});

  function updateCategoryStatus($cat_id){
    // alert("test code law");
     console.log($cat_id);

      var dataString = '?cat_id='+ $cat_id;
       $.ajax({
            type: "GET",
            url: "<?php echo $this->BaseUrl?>/default/categorytraining/detail"+dataString ,
            //data: dataString+'?format=html',
            //dataType: 'json',
            cache: false,
            success: function(html)
            { 
              //alert(html);
              $("#message").html(html);
              $("#model-warning").modal('show');
            }
       }); 
  }

  function editNotification(id){
    window.location.href = '<?php echo $this->BaseUrl?>/default/notification/editnotificationpage?id='+id;
  }

   

</script>

<div id="model-warning" class="modal fade"  data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
        
      </div>
        
        <div class="modal-body">
            <p id="message">Bạn đã cập nhật thành công chủ đề mới.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary close-modal" data-dismiss="modal">Đóng</button>
        </div>
      
    </div>
  </div>
</div>

<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="" title="Chỉnh sửa thông báo" class="tip-bottom"><i class="icon-home"></i></a><a href="<?php echo $this->BaseUrl?>/default/notification" class="current">Danh sách thông báo</a> <a href="#" class="current">Chỉnh sửa thông báo</a> </div>
    <!-- <h1>Quản lý luật sư</h1> -->
  </div>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="alert alert-success alert-dismissible message-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Thông báo</strong> Bạn đã cập nhật thành công thông báo
      </div>	
    </div>  	 

    <div class="row-fluid">	  	
      <div class="span12">		 
        <div class="widget-box">
            <div class="widget-title">
              <span class="icon">
                <i class="icon-th-list"></i>
              </span>
              <h5>Chỉnh sửa thông táo</h5>
            </div>
            
            <div class="widget-content nopadding"> 
            <!-- <p>test code </p> -->
              <div class="row-fluid form-horizontal">
                <form id="categorytranining_form" novalidate="novalidate">
                    <div class="span6">
                        <input type="hidden" id="notification_id" name="notification_id" value="<?php echo $this->data['notification_id']; ?>"/>
                        <div class="control-group">
                          <label class="control-label">Tên thông báo *:</label>
                          <div class="controls">
                              <input type="text" name="title" id="title" value="<?php echo $this->data['title']; ?>" class="span12" placeholder="Vui lòng nhập tên thông báo " />
                          </div>
                        </div>
                        <div class="control-group">
                          <label class="control-label">Nội dung thông báo *:</label>
                          <div class="controls">
                              <textarea name="description" id="description" class="span12" 
                              placeholder="Vui lòng nhập nội dung thông báo" rows="4"><?php echo $this->data['description']; ?></textarea>
                          </div>
                        </div>
                    </div>  
                    <div class="span6">      

                        <div class="control-group">
                            <label class="control-label">Chọn ngày bắt đầu thông báo *:</label>
                            <div class="controls">                  
                            <div id="dp5" data-date="" class="input-append date datepicker-activationdate">                    
                                <input name="activationdate" data-date-format="mm-dd-yyyy" class="span12" >
                                <span class="add-on"><i class="icon-th"></i></span> </div>
                            </div>
                        </div> 

                        <div class="control-group">
                            <label class="control-label">Chọn ngày kết thúc thông báo *:</label>
                            <div class="controls">                  
                            <div id="dp5" data-date="" class="input-append date datepicker-expiredate">                    
                                <input name="expiredate" data-date-format="mm-dd-yyyy" class="span12" >
                                <span class="add-on"><i class="icon-th"></i></span> </div>
                            </div>
                        </div>                
                    </div>  
                    
               	  
              </div>
              <div class="row-fluid">
                    <div class="form-actions">
                              <div class="span4" >
                              </div>
                              <div class="span6">	             
                                  <button type="submit" class="btn ">Lưu</button>			
                                  <button type="button" class="btn ">Hủy</button>							 
                              </div>
                              <div class="span2" >
                              </div>
                            </div>  
                    </div>
              </div>  
              </form>
            </div>

            <!--tab-->
        </div>
  </div>  
</div>

