<script>
$(document).ready(function(){
    
	$('input[type=checkbox],input[type=radio],input[type=file]').uniform();
  $("#search").hide();
  $(".searchfield").hide();

    $(".message-success").hide();

    $("#model-warning").modal('hide');   

    $(".close-modal").on('click',function(){
      location.reload();
    });

    var date = new Date();
    var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());

    $('.datepicker-activationdate').datepicker({ format: 'dd/mm/yyyy' });
    $('.datepicker-activationdate').datepicker('setValue', today);

      $('.datepicker-expiredate').datepicker({ format: 'dd/mm/yyyy' });
    $('.datepicker-expiredate').datepicker('setValue', today);
      
   $("#categorytranining_form").validate({     
          rules:{
            title:{
              required:true
            },
            description:{
              required:true
            }
          },
          errorClass: "help-inline",
          errorElement: "span",
          highlight:function(element, errorClass, validClass) {
            $(element).parents('.control-group').addClass('error');
          },
          unhighlight: function(element, errorClass, validClass) {
            $(element).parents('.control-group').removeClass('error');
            $(element).parents('.control-group').addClass('success');
          },
          messages: {
            title: "Vui lòng nhập tên thông báo !",
            description: "Vui lòng nhập tên nội dung thông báo !"
                      
          },
          submitHandler: function(form,e) {
             console.log('Form submitted');
             console.log($('#categorytranining_form').serialize());
            $.ajax({
                  type: "POST",
                  url: "<?php echo $this->BaseUrl?>/default/notification/create/",
                  data: $('#categorytranining_form').serialize() ,
                  cache: false,
                  success: function(html)
                  {   
                    //$("#message").html(html);
                    $(".message-success").show();
                    $("#model-warning").modal("show");                                                   
                  }
            });
            return false;                       
        }
	});


  function isNumber(n) {
    return !isNaN(parseFloat(n)) && isFinite(n);
  }



});

  function updateCategoryStatus($cat_id){
    // alert("test code law");
     console.log($cat_id);

      var dataString = '?cat_id='+ $cat_id;
       $.ajax({
            type: "GET",
            url: "<?php echo $this->BaseUrl?>/default/categorytraining/detail"+dataString ,
            //data: dataString+'?format=html',
            //dataType: 'json',
            cache: false,
            success: function(html)
            { 
              //alert(html);
              $("#message").html(html);
              $("#model-warning").modal('show');
            }
       }); 
  }

  function editNotification(id){
    window.location.href = '<?php echo $this->BaseUrl?>/default/notification/editnotificationpage?id='+id;
  }

   

</script>

<div id="model-warning" class="modal fade"  data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
        
      </div>
        
        <div class="modal-body">
            <p id="message">Bạn đã tạo thành công chủ đề mới.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary close-modal" data-dismiss="modal">Đóng</button>
        </div>
      
    </div>
  </div>
</div>

<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i></a> <a href="#" class="current">Nhập mới thông báo</a> </div>
    <!-- <h1>Quản lý luật sư</h1> -->
  </div>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="alert alert-success alert-dismissible message-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Thông báo</strong> Bạn đã tạo thành công thông báo
      </div>	
    </div>  	 

    <div class="row-fluid">	  	
      <div class="span12">		 
        <div class="widget-box">
            <div class="widget-title">
              <span class="icon">
                <i class="icon-th-list"></i>
              </span>
              <h5>Nhập mới thông táo</h5>
            </div>
            
            <div class="widget-content nopadding"> 
            <!-- <p>test code </p> -->
              <div class="row-fluid form-horizontal">
                <form id="categorytranining_form" novalidate="novalidate">
                    <div class="span6">
                        <!-- <input type="hidden" id="cus_id" name="cus_id"/> -->
                        <div class="control-group">
                          <label class="control-label">Tên thông báo *:</label>
                          <div class="controls">
                              <input type="text" name="title" id="title" class="span12" placeholder="Vui lòng nhập tên thông báo " />
                          </div>
                        </div>
                        <div class="control-group">
                          <label class="control-label">Nội dung thông báo *:</label>
                          <div class="controls">
                              <textarea name="description" id="description" class="span12" 
                              placeholder="Vui lòng nhập nội dung thông báo" rows="4"></textarea>
                          </div>
                        </div>
                    </div>  
                    <div class="span6">      

                        <div class="control-group">
                            <label class="control-label">Chọn ngày bắt đầu thông báo *:</label>
                            <div class="controls">                  
                            <div id="dp5" data-date="" class="input-append date datepicker-activationdate">                    
                                <input name="activationdate" data-date-format="mm-dd-yyyy" class="span12" >
                                <span class="add-on"><i class="icon-th"></i></span> </div>
                            </div>
                        </div> 

                        <div class="control-group">
                            <label class="control-label">Chọn ngày kết thúc thông báo *:</label>
                            <div class="controls">                  
                            <div id="dp5" data-date="" class="input-append date datepicker-expiredate">                    
                                <input name="expiredate" data-date-format="mm-dd-yyyy" class="span12" >
                                <span class="add-on"><i class="icon-th"></i></span> </div>
                            </div>
                        </div>                
                    </div>  
                    
               	  
              </div>
              <div class="row-fluid">
                    <div class="form-actions">
                              <div class="span4" >
                              </div>
                              <div class="span6">	             
                                  <button type="submit" class="btn ">Lưu</button>			
                                  <button type="button" class="btn ">Hủy</button>							 
                              </div>
                              <div class="span2" >
                              </div>
                            </div>  
                    </div>
              </div>  
              </form>
            </div>

            <!--tab-->
            <div class="widget-box">
                <div class="widget-title">
                    <ul class="nav nav-tabs">
                        <li class="active"><a id="internship" data-toggle="tab" href="#tab1">Danh sách thông báo</a></li>
                                                
                    </ul>
                </div>
                <div class="widget-content tab-content">
                    <div id="tab1" class="tab-pane active">
                        <div class="row-fluid">
                          <div class="span12">    
                            <div class="widget-box">
                              <div class="widget-title">
                                <span class="icon"><i class="icon-th"></i></span> 
                                <h5>Danh sách nội dung thông báo</h5>
                              </div>
                              <div class="widget-content nopadding">
                              <table class="table table-bordered data-table">
                                  <thead>
                                    <tr>
                                      <th>STT</th>
                                      <th>Tên thông báo</th>
                                      <th>Nội dung thông báo</th>
                                      <th>Ngày bắt đầu</th>                                      
                                      <th>Ngày kết thúc</th>
                                      <th>Hành động</th>
                                    </tr>
                                  </thead>
                                  <tbody id="table-lawyer">   
                                  <?php  
                                        if($this->notifications != null){
                                            $index = 0;
                                            foreach ($this->notifications as $cat) {                                           
                                                // $text = ''; 
                                                // if($cat['status'] == 1){
                                                //     $text = '<td>Đang hoạt động</td>';
                                                // }else{
                                                //     $text = '<td>Ngưng hoạt động</td>';  
                                                // }  

                                                $activationdate = ($cat['activationdate'] != null && $cat['activationdate'] != ''
                                                && $cat['activationdate'] != '1900-01-01 00:00:00') ? date('d/m/Y', strtotime($cat['activationdate'])) : '';    

                                                $expiredate = ($cat['expiredate'] != null && $cat['expiredate'] != ''
                                                && $cat['expiredate'] != '1900-01-01 00:00:00') ? date('d/m/Y', strtotime($cat['expiredate'])) : '';    


                                                $index +=1; 
                                                echo ' <tr class="gradeC">'.
                                                '<td>'.$index.'</td>'.
                                                '<td>'.$cat['title'].'</td>'.
                                                '<td>'.$cat['description'].'</td>'.
                                                '<td>'.$activationdate
                                                .'</td>'.
                                                '<td>'.$expiredate
                                                .'</td>'.  
                                                '<td>'.'<button data-toggle="tooltip" title="Chỉnh sửa" onClick="editNotification('.$cat['notification_id'].');"><i class="icon-pencil"></i></button>'.'</td>'.                                            
                                            '</tr>';                          
                                            }  
                                        }
                                    ?>                             
                            
                                  </tbody>
                                </table>                            
                              </div>
                            </div>
                                    
                          </div>          
                        </div>         
                    </div>                  
        
    </div>
  </div>  
</div>

