
<script>
$(document).ready(function(){

    $("#form-edit").validate({     
            rules:{
                // law_code:{
                // required:true
                // },
                // law_certfication_no:{
                // required:true
                // }
            },
            errorClass: "help-inline",
            errorElement: "span",
            highlight:function(element, errorClass, validClass) {
                $(element).parents('.control-group').addClass('error');
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').removeClass('error');
                $(element).parents('.control-group').addClass('success');
            },
            messages: {
                //cus_cellphone: "Vui lòng nhập số điện thoại !",
                // cus_identity_card: "Vui lòng nhập số CMND !",
                // law_code: "Vui lòng nhập mã luật sư !",
                // law_certfication_no: "Vui lòng nhập số chứng chỉ !",
            },
            submitHandler: function(form,e) {
                console.log('Form submitted');
                console.log($('#form-edit').serialize());
                $.ajax({
                      type: "POST",
                      url: "<?php echo $this->BaseUrl?>/default/customersreward/update/",
                      data: $('#form-edit').serialize() ,
                      cache: false,
                      success: function(html)
                      {   
                        //alert("Cập nhật luật sư thành công");
                        //$(".message-success").show();
                        $("#message").html("Cập nhật thông tin thành công");
                        // $("#model-warning").modal("show");                                    
                      }
                });
                return false;                       
            }
        });
});  

</script>
<form id="form-edit" class="form-horizontal">
    <p id="message"></p> 
    <input type="hidden" name="id" value="<?php echo $this->detailReward['id']; ?>" /> 
    <div class="row-fluid">
        <div class="span10"> 
            <label class="control-label">Hình thức:</label>
            <div class="controls">
                <div class="row-fluid">
                    <div class="span3">
                    <label>
                        <input type="radio" name="cus_reward_discipline" value="khenthuong"   <?php echo $this->detailReward['type'] == 'Khen thưởng' ? 'checked':''; ?> /> 
                Khen thưởng</label>
                    </div>
                    <div class="span6">
                        <label>
                        <input type="radio" name="cus_reward_discipline" value="kyluat" <?php echo $this->detailReward['type'] == 'Kỷ luật' ? 'checked' : ''?> />
                        Kỉ luật</label> 
                    </div>
                </div>                                               
            </div>
            <label class="control-label">Lý do * :</label>
            <div class="controls">
            <textarea id="cus_reason" name="cus_reason" value="<?php echo $this->detailReward['type'] == 'Kỷ luật' ? $this->detailReward['discipline_reason'] : $this->detailReward['reward_reason']?>;" class="span11"  placeholder="Vui lòng nhập lý do" ></textarea>
            </div>  
        </div> 
    </div>      
    <!-- <div class="form-actions"> -->
    <button style="float: right;" type="submit" class="btn">Save</button>
    <!-- </div> -->
</form>