<script>
$(document).ready(function(){
    
	$('input[type=checkbox],input[type=radio],input[type=file]').uniform();

  $("#search").hide();
  $(".searchfield").hide();

  $('.datepicker-startdate').datepicker();

  $('.datepicker-enddate').datepicker();

    $(".message-success").hide();

    $("#model-warning").modal('hide');   

    $(".close-modal").on('click',function(){
      location.reload();
    });
      
   $("#course_form").validate({     
          rules:{
            cat_train_id:{
              required:true
            },
            course_name:{
              required:true
            },
            course_startdate:{
              required:true
            },
            course_enddate:{
              required:true
            }
          },
          errorClass: "help-inline",
          errorElement: "span",
          highlight:function(element, errorClass, validClass) {
            $(element).parents('.control-group').addClass('error');
          },
          unhighlight: function(element, errorClass, validClass) {
            $(element).parents('.control-group').removeClass('error');
            $(element).parents('.control-group').addClass('success');
          },
          messages: {
            course_startdate: "Vui lòng nhập ngày bắt đầu khóa học",
            course_enddate: "Vui lòng nhập ngày kết thúc khóa học",
            course_name: "Vui lòng nhập tên khóa học !"           
          },
          submitHandler: function(form,e) {
             console.log('Form submitted');
            $.ajax({
                  type: "POST",
                  url: "<?php echo $this->BaseUrl?>/default/course/create/",
                  data: $('#course_form').serialize() ,
                  cache: false,
                  success: function(html)
                  {   
                    //$("#message").html(html);
                    $(".message-success").show();
                    $("#model-warning").modal("show");                                                   
                  }
            });
            return false;                       
        }
	});


  function isNumber(n) {
    return !isNaN(parseFloat(n)) && isFinite(n);
  }



});

  function updateCourseStatus($course_id){
    // alert("test code law");
     console.log($course_id);

      var dataString = '?course_id='+ $course_id;
       $.ajax({
            type: "GET",
            url: "<?php echo $this->BaseUrl?>/default/course/detail"+dataString ,
            //data: dataString+'?format=html',
            //dataType: 'json',
            cache: false,
            success: function(html)
            { 
              //alert(html);
              $("#message").html(html);
              $("#model-warning").modal('show');
            }
       });       


    
    
  }

   

</script>

<div id="model-warning" class="modal fade"  data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
        
      </div>
        
        <div class="modal-body">
            <p id="message">Bạn đã tạo thành công chủ đề mới.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary close-modal" data-dismiss="modal">Đóng</button>
        </div>
      
    </div>
  </div>
</div>

<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i></a> <a href="#" class="current">Nhập mới chủ đề bồi dưỡng</a> </div>
    <!-- <h1>Quản lý luật sư</h1> -->
  </div>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="alert alert-success alert-dismissible message-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Thông báo</strong> Bạn đã tạo thành công khóa học..
      </div>	
    </div>  	 

    <div class="row-fluid">	  	
      <div class="span12">		 
        <div class="widget-box">
            <div class="widget-title">
              <span class="icon">
                <i class="icon-th-list"></i>
              </span>
              <h5>Nhập mới khóa bồi dưỡng</h5>
            </div>
            
            <div class="widget-content nopadding"> 
            <!-- <p>test code </p> -->
              <div class="row-fluid form-horizontal">
                <form id="course_form" novalidate="novalidate">
                    <div class="span6">
                        <div class="control-group">
                          <label class="control-label">Tên khóa học</label>
                          <div class="controls">              
                            <input type="text" name="course_name" id="course_name" class="span8" placeholder="Tên khóa học" />
                          </div>
                        </div> 

                        <div class="control-group">
                              <label class="control-label">Chọn chủ đề</label>
                              <div class="controls">
                                <select class="span12" name="cat_train_id">
                                <?php  
                                    foreach ($this->categories as $cat) {
                                      if($cat['cat_train_active'] == 1){
                                        echo '<option value="'.$cat['cat_train_id'].'" class="span8">'.$cat['cat_train_name'].'</option>';
                                      }                                        
                                    }
                                    ?>    
                                </select>
                              </div>  
                        </div>   
                  
                    </div>  
                    <div class="span6">                       
          
                        <div class="control-group">
                          <label class="control-label">Ngày bắt đầu:</label>
                          <div class="controls">
                            <div id="dpcmnd"  data-date="10/20/2018" class="input-append date datepicker-startdate">
                             
                              <input id="course_startdate" name="course_startdate" type="text" value="10/20/2018"  data-date-format="mm-dd-yyyy" class="span11" >
                              <span class="add-on"><i class="icon-th"></i></span>
                            </div>                           
                          </div>
                        </div>

                        <div class="control-group">
                          <label class="control-label">Ngày kết thúc:</label>
                          <div class="controls">
                            <div id="dpcmnd"  data-date="10/20/2018" class="input-append date datepicker-enddate">
                             
                              <input id="course_enddate" name="course_enddate" type="text" value="10/20/2018"  data-date-format="mm-dd-yyyy" class="span11" >
                              <span class="add-on"><i class="icon-th"></i></span>
                            </div>                           
                          </div>
                        </div>
                
                    </div>  
               	  
              </div>
              <div class="row-fluid">
                    <div class="form-actions">
                              <div class="span4" >
                              </div>
                              <div class="span6">	             
                                  <button type="submit" class="btn ">Lưu</button>			
                                  <button type="button" class="btn ">Hủy</button>							 
                              </div>
                              <div class="span2" >
                              </div>
                            </div>  
                    </div>
              </div>  
              </form>
            </div>

            <!--tab-->
            <div class="widget-box">
                <div class="widget-title">
                    <ul class="nav nav-tabs">
                        <li class="active"><a id="internship" data-toggle="tab" href="#tab1">Danh sách chủ đề</a></li>
                                                
                    </ul>
                </div>
                <div class="widget-content tab-content">
                    <div id="tab1" class="tab-pane active">
                        <div class="row-fluid">
                          <div class="span12">    
                            <div class="widget-box">
                              <div class="widget-title">
                                <span class="icon"><i class="icon-th"></i></span> 
                                <h5>Danh sách chủ đề</h5>
                              </div>
                              <div class="widget-content nopadding">
                              <table class="table table-bordered data-table">
                                  <thead>
                                    <tr>
                                      <th>Tên khóa học</th>
                                      <th>Ngày bắt đầu</th> 
                                      <th>Ngày kết thúc</th> 
                                      <th>Nội dung bồi dưỡng</th>                                     
                                      <th>Trạng thái</th>
                                      <th>Hành động</th> 
                                    </tr>
                                  </thead>
                                  <tbody id="table-lawyer">   
      
                                  <?php  
                                        if($this->courses != null){
                                            foreach ($this->courses as $course) {                                           
                                                $text = ''; 
                                                if($course['course_status'] == 1){
                                                    $text = '<td>Đang hoạt động</td>';
                                                }else{
                                                    $text = '<td>Ngưng hoạt động</td>';  
                                                }    
                                                echo ' <tr class="gradeC">'.
                                                '<td>'.$course['course_name'].'</td>'.
                                                '<td>'.$course['course_startdate'].'</td>'.
                                                '<td>'.$course['course_enddate'].'</td>'.
                                                '<td>'.$course['cat_train_name'].'</td>'.                                                
                                                $text.                                               
                                                '<td class="center">'.
                                                    '<button onClick="updateCourseStatus('.$course['course_id'].');"><i class="icon-pencil"></i></button>'.' '.
                                                    
                                            '</tr>';                          
                                            }  
                                        }

                                    ?>                             
                            
                                  </tbody>
                                </table>                            
                              </div>
                            </div>
                                    
                          </div>          
                        </div>         
                    </div>                  
        
    </div>
  </div>  
</div>

