<script>
$(document).ready(function(){
    
	$('input[type=checkbox],input[type=radio],input[type=file]').uniform();

      $("#search").hide();
  $(".searchfield").hide();

    $(".message-success").hide();

    $("#model-warning").modal('hide');   

    $(".close-modal").on('click',function(){
      location.reload();
    });

        
    $('input[type=checkbox],input[type=radio],input[type=file]').uniform();

    $('.datepicker-startdate').datepicker();
    $('.datepicker-enddate').datepicker();

   $("#categorytranining_form").validate({     
          rules:{
            joining_name:{
              required:true
            }
          },
          errorClass: "help-inline",
          errorElement: "span",
          highlight:function(element, errorClass, validClass) {
            $(element).parents('.control-group').addClass('error');
          },
          unhighlight: function(element, errorClass, validClass) {
            $(element).parents('.control-group').removeClass('error');
            $(element).parents('.control-group').addClass('success');
          },
          messages: {            
            joining_name: "Vui lòng nhập tên đơt gia nhập !"           
          },
          submitHandler: function(form,e) {
             console.log('Form submitted');
            $.ajax({
                  type: "POST",
                  url: "<?php echo $this->BaseUrl?>/default/joining/create/",
                  data: $('#categorytranining_form').serialize() ,
                  cache: false,
                  success: function(html)
                  {   
                    //alert(html);
                    $(".message-success").show();
                    $("#model-warning").modal("show");                                                   
                  }
            });
            return false;                       
        }
	});


  function isNumber(n) {
    return !isNaN(parseFloat(n)) && isFinite(n);
  }



});

  function updateCategoryStatus($cat_id){
    // alert("test code law");
     console.log($cat_id);

      var dataString = '?joining_id='+ $cat_id;
       $.ajax({
            type: "GET",
            url: "<?php echo $this->BaseUrl?>/default/joining/detail"+dataString ,
            //data: dataString+'?format=html',
            //dataType: 'json',
            cache: false,
            success: function(html)
            { 
              //alert(html);
              $("#message").html(html);
              $("#model-warning").modal('show');
            }
       });       


    
    
  }

   

</script>

<div id="model-warning" class="modal fade"  data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
        
      </div>
        
        <div class="modal-body">
            <p id="message">Bạn đã tạo thành công đợt gia nhập mới.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary close-modal" data-dismiss="modal">Đóng</button>
        </div>
      
    </div>
  </div>
</div>

<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i></a> <a href="#" class="current">Nhập mới đợt gia nhập</a> </div>
    <!-- <h1>Quản lý luật sư</h1> -->
  </div>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="alert alert-success alert-dismissible message-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Thông báo</strong> Bạn đã tạo thành công đợt gia nhập mới..
      </div>	
    </div>  	 

    <div class="row-fluid">	  	
      <div class="span12">		 
        <div class="widget-box">
            <div class="widget-title">
              <span class="icon">
                <i class="icon-th-list"></i>
              </span>
              <h5>Nhập mới đợt gia nhập</h5>
            </div>
            
            <div class="widget-content nopadding"> 
            <!-- <p>test code </p> -->
              <div class="row-fluid form-horizontal">
                <form id="categorytranining_form" novalidate="novalidate">
                    <div class="span6">
                        <!-- <input type="hidden" id="cus_id" name="cus_id"/> -->
                        <!-- <div class="control-group">
                          <label class="control-label">Số giờ học :</label>
                          <div class="controls">
                              <input type="text" name="cat_train_quantity" id="cat_train_quantity" class="span8" placeholder="Số lượng học viên" />
                          </div>
                        </div> -->
                        <div class="control-group">
                          <label class="control-label">Tên đợt gia nhập</label>
                          <div class="controls">              
                            <input type="text" name="joining_name" id="joining_name" class="span8" placeholder="Tên đợt gia nhập" />
                          </div>
                        </div>   
                        <div class="control-group">
                          <label class="control-label">Ngày bắt đầu:</label>
                          <div class="controls">
                            <div id="dpcmnd"  data-date="10/20/2018" class="input-append date datepicker-startdate">
                             
                              <input id="joining_startdate" name="joining_startdate" type="text" value="10/20/2018"  data-date-format="mm-dd-yyyy" class="span11" >
                              <span class="add-on"><i class="icon-th"></i></span>
                            </div>                           
                          </div>
                        </div>   

                    </div>  
                    <div class="span6">                       
                        
                        
                    <div class="control-group">
                          <label class="control-label">Ngày kết thúc:</label>
                          <div class="controls">
                            <div id="dpcmnd"  data-date="10/20/2018" class="input-append date datepicker-enddate">
                             
                              <input id="joining_enddate" name="joining_enddate" type="text" value="10/20/2018"  data-date-format="mm-dd-yyyy" class="span11" >
                              <span class="add-on"><i class="icon-th"></i></span>
                            </div>                           
                          </div>
                        </div>                 
                    </div>  
               	  
              </div>
              <div class="row-fluid">
                    <div class="form-actions">
                              <div class="span4" >
                              </div>
                              <div class="span6">	             
                                  <button type="submit" class="btn ">Lưu</button>			
                                  <button type="button" class="btn ">Hủy</button>							 
                              </div>
                              <div class="span2" >
                              </div>
                            </div>  
                    </div>
              </div>  
              </form>
            </div>

            <!--tab-->
            <div class="widget-box">
                <div class="widget-title">
                    <ul class="nav nav-tabs">
                        <li class="active"><a id="internship" data-toggle="tab" href="#tab1">Danh sách đợt gia nhập</a></li>
                                                
                    </ul>
                </div>
                <div class="widget-content tab-content">
                    <div id="tab1" class="tab-pane active">
                        <div class="row-fluid">
                          <div class="span12">    
                            <div class="widget-box">
                              <div class="widget-title">
                                <span class="icon"><i class="icon-th"></i></span> 
                                <h5>Danh sách đợt gia nhập</h5>
                              </div>
                              <div class="widget-content nopadding">
                              <table class="table table-bordered data-table">
                                  <thead>
                                    <tr>
                                      <th>Tên đợt gia nhập</th>
                                      <th>Ngày bắt đầu</th>
                                      <th>Ngày kết thúc</th>                                                                    
                                      <th>Trạng thái</th>
                                      <th>Hành động</th>
                                    </tr>
                                  </thead>
                                  <tbody id="table-lawyer">   
                                  <?php  
                                        if($this->joinings != null){
                                            foreach ($this->joinings as $join) {                                           
                                                $text = ''; 
                                                if($join['joining_status'] == 1){
                                                    $text = '<td>Đang hoạt động</td>';
                                                }else{
                                                    $text = '<td>Ngưng hoạt động</td>';  
                                                }    
                                                echo ' <tr class="gradeC">'.
                                                '<td>'.$join['joining_name'].'</td>'.
                                                '<td>'.$join['joining_startdate'].'</td>'.
                                                '<td>'.$join['joining_enddate'].'</td>'.
                                                $text.                                               
                                                '<td class="center">'.
                                                    '<button onClick="updateCategoryStatus('.$join['joining_id'].');" ><i class="icon-pencil"></i></button>'.' '.
                                                    
                                            '</tr>';                          
                                            }  
                                        }
                                    ?>                             
                            
                                  </tbody>
                                </table>                            
                              </div>
                            </div>
                                    
                          </div>          
                        </div>         
                    </div>                  
        
    </div>
  </div>  
</div>

