

<div id="model-warning" class="modal fade"  data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>

      </div>
        
        <div class="modal-body">
            <p id="message">Bạn đã cập nhật thành công.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary close-modal" data-dismiss="modal">Đóng</button>
        </div>
      
    </div>
  </div>
</div>

<div id="content">
    <div id="content-header">
        <div id="breadcrumb">
            <a href="#" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i></a>
            <a href="<?php echo $this->BaseUrl?>/admin/contentpages/index" class="current">Quản lý nội dung</a>
            <a href="#" class="current">Chỉnh sửa nội dung</a>
        </div>
    </div>
    <div class="row-fluid">
        <!-- open div general information-->
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title"><span class="icon"> <i class="icon-align-justify"></i> </span>
                    <h5>Chỉnh sửa nội dung</h5>
                </div>
                <div class="widget-content nopadding" id="detail-information">
                    <!--start form-->
                    <form  id="form_edit" action="" method="post">
                        <input type="hidden" id="content_id" name="content_id"  value="<?php echo $this->contentdata['content_id'];?>"/>
                        <div class="row-fluid form-horizontal">
                            <div class="span6">
                                <label class="control-label">Trạng thái </label>
                                <div class="controls">
                                    <div class="row-fluid">
                                        <div class="span3">
                                        <label>                            
                                            <input type="radio" name="status" value="1" <?php echo ($this->contentdata['status'] == 1) ? 'checked' :'' ?>/>
                                    Hoạt động</label>
                                        </div>
                                        <div class="span6">
                                            <label>
                                            <input type="radio" name="status" value="0" <?php echo ($this->contentdata['status'] == 0) ? 'checked' :'' ?>/>
                                            Ngưng hoạt động</label> 
                                        </div>
                                    </div>                                               
                                </div> 
                            </div>
                            <div class="span6">
                                <label class="control-label">Tiêu đề</label>
                                <div class="controls">
                                    <input type="text" id="title" name="title" class="span8"
                                    value="<?php echo $this->contentdata['title'];?>"   placeholder="Tiêu đề" required>
                                </div>
                            </div>
                        </div>
                        <div class="row-fluid form-horizontal">
                            <div class="span12">
                                <label class="control-label">Nội dung</label>
                                <div class="controls">
                                <textarea id="description" name="description"><?php echo $this->contentdata['description'];?></textarea>

                                <!-- creating a CKEditor instance called myeditor -->
                                <script type="text/javascript">
                                    CKEDITOR.replace('description');
                                </script>
                                    
                                </div>
                            </div>
                        </div>
                        <!-- <input type="hidden" value="send_group" name="type_mail"> -->
                        <div class="row-fluid">
                            <div class="form-actions span12">
                                <div class="pull-right">
                                    <button type="submit" id="btnSendGroup" class="btn btn-primary">Lưu</button>
                                </div>
                            </div>
                        </div>
                        <!-- end form -->
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- <script>
    $(document).ready(function(){
        $('.select2').select2();
    });
</script> -->
<script type="text/javascript" src="<?php echo $this->BaseUrl?>/public/js/jquery.validate.js"></script>
<script>

$(document).ready(function(){
    $("#search").hide();
    $(".searchfield").hide();

    $("#form_edit").validate({     
          rules:{
            title:{
              required:true
            }       
          },
          errorClass: "help-inline",
          errorElement: "span",
          highlight:function(element, errorClass, validClass) {
            $(element).parents('.control-group').addClass('error');
          },
          unhighlight: function(element, errorClass, validClass) {
            $(element).parents('.control-group').removeClass('error');
            $(element).parents('.control-group').addClass('success');
          },
          messages: {
            title: "Vui lòng nhập tiêu đề !"
            // cat_train_name: "Vui lòng nhập tên nội dung bồi dưỡng !",
            // cat_train_address : "Vui lòng nhập địa điểm bồi dưỡng !"           
          },
          submitHandler: function(form,e) {
           console.log("call ajax");
           CKEDITOR.instances.description.updateElement();
            $.ajax({
                  type: "POST",
                  url: "<?php echo $this->BaseUrl?>/admin/contentpages/update/",
                  data: $('#form_edit').serialize() ,
                  cache: false,
                  success: function(html)
                  {   
                    //$("#message").html(html);
                    $(".message-success").show();
                    $("#model-warning").modal("show");                                                   
                  }
            });
            return false;                       
        }
	});
});
</script>
