
<script>
$(document).ready(function(){

    $(".close-modal").on('click',function(){
       location.reload();
    });

    $("#form-edit").validate({     
            rules:{
                year:{
                required:true
                },
                name:{
                required:true
                }
            },
            errorClass: "help-inline",
            errorElement: "span",
            highlight:function(element, errorClass, validClass) {
                $(element).parents('.control-group').addClass('error');
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').removeClass('error');
                $(element).parents('.control-group').addClass('success');
            },
            messages: {
                //cus_cellphone: "Vui lòng nhập số điện thoại !",
                // cus_identity_card: "Vui lòng nhập số CMND !",
                year: "Vui lòng nhập năm !",
                name: "Vui lòng nhập tên phí !",
            },
            submitHandler: function(form,e) {
                console.log('Form submitted');
                $.ajax({
                      type: "POST",
                      url: "<?php echo $this->BaseUrl?>/admin/categoryfee/update/",
                      data: $('#form-edit').serialize() ,
                      cache: false,
                      success: function(html)
                      {   
                        $("#form-edit").html('');
                        $("#message").html("Cập nhật thành công"); 
                        
                        //$(".close-modal").hide();  
                                                                               
                      }
                });
                return false;                       
            }
        });
});  

</script>


<form id="form-edit" class="form-horizontal">
              <p id="message"></p>
              <input type="hidden" name="category_fee_id" id="category_fee_id" value="<?php echo $this->categoryfee['category_fee_id']; ?>" />
              
              <div class="control-group">
                    <label class="control-label">Tên phí</label>
                    <div class="controls">
                        <input type="text" name="name" id="name" class="span3" value="<?php echo $this->categoryfee['name']; ?>">
                    </div>
              </div> 

              <div class="control-group">        
                    <label class="control-label">Năm:</label>
                    <div class="controls">
                    <input type="number" name="year" id="year" value="<?php echo $this->categoryfee['year']; ?>" class="span3" placeholder="Vui lòng nhập năm" />
                    </div>
                </div>

            <div class="control-group">        
                <label class="control-label">Dựa trên số thông báo:</label>
                <div class="controls">
                <input type="text" name="baseondocument" id="baseondocument" value="<?php echo $this->categoryfee['baseondocument']; ?>" class="span3" placeholder="Vui lòng nhập số văn bản" />
                </div>
            </div>   

            <label class="control-label">Trạng thái phí</label>
                <div class="controls">
                    <div class="row-fluid">
                        <div class="span3">
                        <label>                            
                            <input type="radio" name="status" value="1" <?php echo ($this->categoryfee['status'] == 1) ? 'checked' :'' ?>/>
                    Hoạt động</label>
                        </div>
                        <div class="span6">
                            <label>
                            <input type="radio" name="status" value="0" <?php echo ($this->categoryfee['status'] == 0) ? 'checked' :'' ?>/>
                            Ngưng hoạt động</label> 
                        </div>
                    </div>                                               
                </div> 
             

             
              <!-- <div class="form-actions"> -->
                <button style="float: right;" type="submit" class="btn">Lưu</button>
              <!-- </div> -->
            </form>
         


