
<script>
$(document).ready(function(){
  $("#search").hide();
  $(".searchfield").hide();

  $(".close-modal").on('click',function(){
    location.reload();
  });

  $("#form-edit-lock").validate({            
      submitHandler: function(form,e) {
          console.log('Form submitted');
          $.ajax({
                type: "POST",
                url: "<?php echo $this->BaseUrl?>/default/useradmin/updatestatus/",
                data: $('#form-edit-lock').serialize() ,
                cache: false,
                success: function(html)
                {   
                  //alert(html);
                  $(".modal-body").html(html);
                  $("#model-warning").modal('show');
                  //$("#message").html("Đổi mật khẩu thành công"); 
                  //$(".close-modal").hide();  
                                                                          
                }
          });
          return false;                       
      }
  });

 $("#form-edit").validate({     
            rules:{
                password:{
                  required:true
                },
                password2: {
                  equalTo: "#password"
                }
            },
            errorClass: "help-inline",
            errorElement: "span",
            highlight:function(element, errorClass, validClass) {
                $(element).parents('.control-group').addClass('error');
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').removeClass('error');
                $(element).parents('.control-group').addClass('success');
            },
            messages: {
                password: "Vui lòng nhập mật khẩu mới",
				        password2: { equalTo: "Mật khẩu không khớp" },
            },
            submitHandler: function(form,e) {
                console.log('Form submitted');
                $.ajax({
                      type: "POST",
                      url: "<?php echo $this->BaseUrl?>/default/useradmin/updatenewpassword/",
                      data: $('#form-edit').serialize() ,
                      cache: false,
                      success: function(html)
                      {   
                        //alert(html);
                        $(".modal-body").html(html);
                        $("#model-warning").modal('show');
                        //$("#message").html("Đổi mật khẩu thành công"); 
                        //$(".close-modal").hide();  
                                                                               
                      }
                });
                return false;                       
            }
        });
});

 function changePass(id){
      $("#message").hide();
      $("#user_id").val(id);
      $("#form-edit-lock").hide();
      $("#form-edit").show();
      $("#model-warning").modal('show');
 }

 
function editCategoryFee($id){
      //alert("member status");
    var dataString = '?category_fee_id='+ $id;
      $.ajax({
          type: "GET",
          url: "<?php echo $this->BaseUrl?>/admin/categoryfee/detail"+dataString ,
          cache: false,
          success: function(html)
          { 
            //alert(html);
            $(".modal-body").html(html);
            $("#model-warning").modal('show');
          }
      });  
}

 function lockUser(id){
      $("#message").hide();
      $("#user_id_lock").val(id);
      $("#form-edit").hide();
      $("#form-edit-lock").show();
      $("#model-warning").modal('show');
 }  
</script>
<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="#" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i> Trang chủ</a> <a href="#" class="current">Danh sách các loại phí trong hệ thống</a> </div>
    <h1>Danh sách các loại phí trong hệ thống</h1>
  </div>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span12">
        <div class="widget-box">
          <div class="widget-title">
             <span class="icon"><i class="icon-th"></i></span> 
            <h5>Danh sách các loại phí trong hệ thống</h5>
          </div>
          <div class="widget-content nopadding">
            <table class="table table-bordered data-table">
              <thead>
                <tr>
                  <th>Tên</th>
                  <th>Số tiền</th>
                  <th>Năm áp dụng</th>
                  <th>Dựa trên thông báo</th>
                  <th>Loại</th>
                  <th>Trạng thái</th>    
                  <th>Hành động</th>              
                </tr>
              </thead>
              <tbody>       
                <?php  
                      if($this->data != null && sizeof($this->data)>0){
                          foreach ($this->data as $fee) {

                            $status = '';
                            if($fee['status'] == 0){
                                $status = '<td>Ngưng hoạt động</td>';
                            }else{
                                $status = '<td>Hoạt động</td>';  
                            }

                            echo ' <tr class="gradeC">'.
                            '<td>'.$fee['name'].'</td>'.
                            '<td>'.$fee['mooney'].'</td>'.
                            '<td>'.$fee['year'].'</td>'.
                            '<td>'.$fee['baseondocument'].'</td>'.
                            '<td>'.$fee['type'].'</td>'.
                             $status.
                             '<td>'.'<button data-toggle="tooltip" title="Chỉnh sửa" onClick="editCategoryFee('.$fee['category_fee_id'].');"><i class="icon-pencil"></i></button>'.' '. 
                            //  '<button data-toggle="tooltip" title="Khóa tài tài khoản" onClick="lockUser('.$user['user_id'].');"><i class="icon-lock"></i></button>'.               
                             '</tr>';                          
                          
                          }  
                      }

                  ?>
              </tbody>
            </table>
          </div>
        </div>        
      </div>
    </div>
  </div>
</div>

<div id="model-warning" class="modal fade"  data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="exampleModalLabel">Chỉnh sửa</h5>
        
      </div>
        
        <div class="modal-body">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary close-modal" data-dismiss="modal">Đóng</button>
        </div>
      
    </div>
  </div>
</div>