<div id="loginbox">            
    <form id="loginform" method="post" class="form-vertical" action="">
            <div class="control-group normal_text"> <h3>Đoàn Luật Sư TP Hồ Chí Minh</h3></div>
        <div class="control-group">
            <div class="controls">
                <div class="main_input_box">
                    <i style="margin-right: 4%;" class="icon-user"></i><input type="text" name="username" placeholder="Tài khoản" />
                </div>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <div class="main_input_box">
                    <i style="margin-right: 4%;" class="icon-lock"></i><input type="password" name="password" placeholder="Mật khẩu" />
                </div>
            </div>
        </div>
        
        <div class="bg_error">
                <?php
                    echo $this->note;
                ?>
        </div>
        
        
        <div class="form-actions">
            <!-- <span class="pull-left"><a href="#" class="flip-link btn btn-inverse" id="to-recover">Lost password?</a></span> -->
            <span class="pull-right"><input type="submit" class="btn btn-success" value="Đăng nhập" /></span>
        </div>
    </form>
    <form id="recoverform" action="#" class="form-vertical">
        <p class="normal_text">Enter your e-mail address below and we will send you instructions how to recover a password.</p>
        
            <div class="controls">
                <div class="main_input_box">
                    <span class="add-on"><i class="icon-envelope"></i></span><input type="text" placeholder="E-mail address" />
                </div>
            </div>
        
        <div class="form-actions">
            <span class="pull-left"><a href="#" class="flip-link btn btn-inverse" id="to-login">&laquo; Back to login</a></span>
            <span class="pull-right"><input type="submit" class="btn btn-info" value="Recover" /></span>
        </div>
    </form>
</div>

<script type="text/javascript" src="<?php echo $this->BaseUrl?>/public/js/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo $this->BaseUrl?>/public/js/maruti.login.js"></script>        
