<form method="post" class="user">
  <div class="form-group input-group">
    <div class="input-group-prepend">
      <div class="input-group-text" id="btnGroupAddon"><i class="fas fa-user"></i></div>
    </div>
    <input name="username"
      type="text" class="form-control"
      placeholder="Tài khoản"
      aria-label="Tài khoản"
      aria-describedby="btnGroupAddon"
      value="admin">
  </div>

  <div class="form-group input-group">
    <div class="input-group-prepend">
      <div class="input-group-text" id="btnGroupAddon"><i class="fas fa-key"></i></div>
    </div>
    <input name="password"
      type="password" class="form-control"
      placeholder="Mật khẩu"
      aria-label="Mật khẩu"
      aria-describedby="btnGroupAddon"
      value="1">
  </div>

  <div class="form-group">
    <button type="submit" class="btn btn-primary btn-user btn-block">
      <i class="fas fa-sign-in-alt"></i>
      Đăng nhập
    </button>
  </div>

  <hr>

  <div class="text-center">
    <a href="<?=$this->BaseUrl?>/forgot-password">Quên mật khẩu?</a>
  </div>

  <hr>

  <div id="lblNote" class="form-group invisible text-danger text-center">
    &nbsp;<?=$this->note?>
  </div>
</form>
