<!DOCTYPE html>

<html>

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><?=$this->escape($this->pageTitle)?></title>

    <link rel="shortcut icon" href="<?=$this->BaseUrl?>/public/img/logo.png">

    <link rel="stylesheet" href="<?=$this->BaseUrl?>/public/css/bootstrap.min.css" />
    <link rel="stylesheet" href="<?=$this->BaseUrl?>/public/css/bootstrap-responsive.min.css" />
    <link rel="stylesheet" href="<?=$this->BaseUrl?>/public/css/maruti-login.css" />
    <link rel="stylesheet" href="<?=$this->BaseUrl?>/public/css/bootstrap-4-polyfill.css" />
</head>

<body>
    <?=$this->layout()->content?>
</body>

</html>