<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<link rel="stylesheet" href="<?php echo $this->BaseUrl?>/public/css/bootstrap.min.css" />
<link rel="stylesheet" href="<?php echo $this->BaseUrl?>/public/css/bootstrap-responsive.min.css" />
<link rel="stylesheet" href="<?php echo $this->BaseUrl?>/public/css/fullcalendar.css" />
<link rel="stylesheet" href="<?php echo $this->BaseUrl?>/public/css/maruti-style.css" />
<link rel="stylesheet" href="<?php echo $this->BaseUrl?>/public/css/maruti-media.css" class="skin-color" />
<link rel="stylesheet" href="<?php echo $this->BaseUrl?>/public/css/maruti-login.css" />
<title><?php echo $this->escape($this->pageTitle); ?></title>


</head>

<body>

<?php 
    echo $this->layout()->content;
?>

</body>

</html>