<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><?=$this->escape($this->pageTitle)?></title>

    <link rel="shortcut icon" href="<?=$this->BaseUrl?>/public/img/logo.png">

    <link rel="stylesheet" type="text/css" href="<?=$this->BaseUrl?>/public/css/nunito.css" />
    <link rel="stylesheet" type="text/css" href="<?=$this->BaseUrl?>/public/css/sb-admin-2.min.css" />
    <link rel="stylesheet" type="text/css" href="<?=$this->BaseUrl?>/public/css/sb-admin-2-override.css" />
    <link rel="stylesheet" type="text/css" href="<?=$this->BaseUrl?>/public/vendor/fontawesome-free/all.min.css" />

    <style type="text/css">
        .login-box {
            width: 360px;
        }

        .card {
            margin-top: 100px;
        }

        .input-group-text {
            border-bottom-left-radius: 22px;
            border-top-left-radius: 22px;
            justify-content: center;
            width: 44px;
        }

        .form-control {
            border-bottom-right-radius: 22px;
            border-top-right-radius: 22px;
            height: 44px;
        }

        form.user .btn-user {
            font-size: inherit;
        }
    </style>
</head>

<body class="bg-gradient-primary">
    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">
            <div class="login-box">
                <div class="card o-hidden border-0 shadow-lg">
                    <div class="card-body p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">ĐĂNG NHẬP</h1>
                        </div>
                        <?=$this->layout()->content?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="<?=$this->BaseUrl?>/public/vendor/jquery/jquery.min.js"></script>
    <script src="<?=$this->BaseUrl?>/public/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="<?=$this->BaseUrl?>/public/vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="<?=$this->BaseUrl?>/public/js/sb-admin-2.min.js"></script>
    <script src="<?=$this->BaseUrl?>/public/js/login.js"></script>
</body>

</html>