<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
      <i class="fa fa-bars"></i>
  </button>

  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">

    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline"><?=$this->display_name?></span>
        <i class="fas fa-user-circle"></i>
      </a>

      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <?php
          if (strpos($_SERVER['REQUEST_URI'], 'admin') === false) {
            echo '<a class="dropdown-item" href="' . $this->BaseUrl . '/user-info">';
            echo '<i class="fas fa-user fa-fw mr-2"></i>Thông tin người dùng</a>';
            echo '<div class="dropdown-divider"></div>';
          }
        ?>
        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
          <i class="fas fa-sign-out-alt fa-fw mr-2"></i>
          Thoát
        </a>
      </div>
    </li>

  </ul>

</nav>
