<div id="header">
  <a href="<?=$this->BaseUrl?>" title="Trang chủ">
    <img src="<?=$this->BaseUrl?>/public/img/logo.png" alt="logo-phu-gia">
    <span class="title">Phần Mềm Quản Trị Nhân Viên Kinh Doanh CCRM - Phú Gia</span>
  </a>
</div>

<!--top-Header-menu-->
<div id="user-nav" class="navbar navbar-inverse">
  <ul class="nav">
    <li><span class="login-name text">Xin chào <?=$_SESSION['username']?></span></li>
    <li>
      <a href="<?=$this->BaseUrl?>/header/logout">
        <i class="icon icon-remove-circle"></i>
        <span class="text">Thoát</span>
      </a>
    </li>
  </ul>
</div>

<div id="search" class="d-none">
  <input type="text" id="search-global" placeholder="Nhập số điện thoại hoặc CMND ..." onfocus="this.placeholder = ''" onblur="this.placeholder = 'Nhập số điện thoại hoặc CMND ...'" style="width:275px;"/>
  <button type="submit" class="tip-left" title="Search"><i class="icon-search icon-white"></i></button>
  <div id="display-content-search-global"></div>
</div>

<div class="searchfield d-none mr-0 mt-1" id="search" style="width: 20%">
  <span>
    <select id="search-field">
      <option value="name">Tìm theo tên Luật Sư</option>
      <option value="cellphone">Tìm theo SĐT Di Động</option>
      <option value="identity_card">Tìm theo CMND</option>
      <option value="lawyer_number">Tìm theo Số thẻ Luật Sư</option>
    </select>
  </span>
</div>
<!--close-top-Header-menu-->

<div id="sidebar">
  <a href="<?=$this->BaseUrl?>" class="visible-phone"><i class="icon icon-home"></i></a>
  <ul>
    <li class="active"><a href="<?=$this->BaseUrl?>" title="Trang chủ"><i class="icon icon-home"></i></a></li>
    <?=$this->menuHtml?>
  </ul>
</div>