<?php
  if ($this->data['user_image']) {
    $userImage = $this->data['user_image'];
  } else {
    $userImage = $this->BaseUrl . '/public/images/default-user.png';
  }
?>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Thông tin người dùng</h6>
        </div>

        <div class="card-body">
          <div class="row">
            <div class="col-md-4 col-xl-3 mb-3">
              <div class="bg-light border p-3 text-center">
                <img src="<?=$userImage?>" alt="user image" width="90%">
                <label for="fileUpload" class="btn btn-link mt-2">
                  Đổi ảnh đại diện
                  <input id="fileUpload" name="fileUpload" type="file" class="d-none" accept="image/gif,image/jpeg,image/pjpeg,image/png">
                </label>
              </div>
            </div>
            <div class="col-md-8 col-xl-9">
              <div class="row">
                <div class="col-md-12">
                  <label class="mb-1">Họ và tên</label>
                  <input type="text" class="form-control" readonly value="<?=$this->data['user_fullname']?>">
                </div>
              </div>

              <div class="row mt-3">
                <div class="col-md-12">
                  <label class="mb-1">Tên hiển thị</label>
                  <input type="text" class="form-control" readonly value="<?=$this->data['user_display_name']?>">
                </div>
              </div>

              <div class="row mt-3">
                <div class="col-md-12">
                  <label class="mb-1">Tên đăng nhập</label>
                  <input type="text" class="form-control" readonly value="<?=$this->data['user_username']?>">
                </div>
              </div>

              <div class="row mt-3">
                <div class="col-md-12">
                  <label class="mb-1">Mật khẩu</label>
                  <input type="text" class="form-control" readonly value="(Đã mã hóa)">
                </div>
              </div>

              <div class="row mt-3">
                <div class="col-md-12">
                  <label class="mb-1">Phòng</label>
                  <input type="text" class="form-control" readonly value="<?=$this->data['user_department']?>">
                </div>
              </div>

              <div class="row mt-3">
                <div class="col-md-12 text-center">
                  <button type="button" id="btnSua" class="btn btn-light border border-dark">
                    <i class="fas fa-edit"></i>
                    Sửa thông tin
                  </button>
                  <button type="button" id="btnDoiPass" class="btn btn-light border border-dark ml-2" data-toggle="modal" data-target="#changePassModal">
                    <i class="fas fa-key"></i>
                    Đổi mật khẩu
                  </button>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!--------------------------------------------------------------------------------------->

<!-- Change pass dialog -->
<div id="changePassModal" class="modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Đổi Mật Khẩu</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <div class="modal-body">
        <label>Mật khẩu cũ</label>
        <input id="txtOldPass" type="password" class="form-control">
        <label class="mt-3">Mật khẩu mới</label>
        <input id="txtNewPass" type="password" class="form-control">
        <label class="mt-3">Nhập lại mật khẩu mới</label>
        <input id="txtConfirmNewPass" type="password" class="form-control">
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          <i class="fas fa-times"></i>
          Đóng
        </button>
        <button id="btnChangePass" type="button" class="btn btn-primary">
          <i class="fas fa-save"></i>
          Cập nhật
        </button>
      </div>
    </div>
  </div>
</div>
<!-- /Change pass dialog -->
