<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><?php echo $this->escape($this->pageTitle); ?></title>

    <link rel="shortcut icon" href="<?=$this->BaseUrl?>/public/img/logo.png">

    <link rel="stylesheet" type="text/css" href="<?=$this->BaseUrl?>/public/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="<?=$this->BaseUrl?>/public/css/bootstrap-responsive.min.css" />
    <link rel="stylesheet" type="text/css" href="<?=$this->BaseUrl?>/public/css/fullcalendar.css" />
    <link rel="stylesheet" type="text/css" href="<?=$this->BaseUrl?>/public/css/datepicker.css">
    <link rel="stylesheet" type="text/css" href="<?=$this->BaseUrl?>/public/css/uniform.css">
    <link rel="stylesheet" type="text/css" href="<?=$this->BaseUrl?>/public/css/select2.css">
    <link rel="stylesheet" type="text/css" href="<?=$this->BaseUrl?>/public/css/maruti-style.css" />
    <link rel="stylesheet" type="text/css" href="<?=$this->BaseUrl?>/public/css/maruti-media.css" class="skin-color" />
    <link rel="stylesheet" type="text/css" href="<?=$this->BaseUrl?>/public/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="<?=$this->BaseUrl?>/public/css/dataTables.checkboxes.css" />
    <link rel="stylesheet" type="text/css" href="<?=$this->BaseUrl?>/public/css/bootstrap-4-polyfill.css" />

    <script src="<?=$this->BaseUrl?>/library/ckeditor/ckeditor.js"></script>
    <script src="<?=$this->BaseUrl?>/public/js/jquery.min.js"></script>
    <script src="<?=$this->BaseUrl?>/public/js/jquery.ui.custom.js"></script>
    <script src="<?=$this->BaseUrl?>/public/js/bootstrap.min.js"></script>
    <script src="<?=$this->BaseUrl?>/public/js/jquery.dataTables.min.js"></script>
    <script src="<?=$this->BaseUrl?>/public/js/dataTables.checkboxes.min.js"></script>

    <style type="text/css">
        ::-webkit-scrollbar {
            width: 10px;
        }

        ::-webkit-scrollbar-track {
            background: #f1f1f1;
        }

        ::-webkit-scrollbar-thumb {
            background: #888;
        }

        ::-webkit-scrollbar-thumb:hover {
            background: #555;
        }
    </style>
</head>

<body>
    <?php
        if (strpos($_SERVER['REQUEST_URI'], 'admin') > 0) {
            $module = 'admin';
        } else {
            $module = 'default';
        }
    ?>

    <?=$this->action('index', 'header', $module)?>

    <div id="content" class="bg-white p-2">
        <?=$this->layout()->content?>
    </div>

    <?=$this->action('index', 'footer', $module)?>

    <script src="<?=$this->BaseUrl?>/public/js/bootstrap-colorpicker.js"></script>
    <script src="<?=$this->BaseUrl?>/public/js/bootstrap-datepicker.js"></script>
    <script src="<?=$this->BaseUrl?>/public/js/jquery.uniform.js"></script>
    <script src="<?=$this->BaseUrl?>/public/js/select2.min.js"></script>
    <script src="<?=$this->BaseUrl?>/public/js/jquery.validate.js"></script>
    <script src="<?=$this->BaseUrl?>/public/js/maruti.js"></script>
    <script src="<?=$this->BaseUrl?>/public/js/maruti.tables.js"></script>
</body>

</html>