<script>
    $(document).ready(function(){
      
       $('input[type=checkbox],input[type=radio],input[type=file]').uniform();

       $('select').select2();

       $(".close-modal").on('click',function(){
        //location.reload();
            window.location.href = '<?php echo $this->BaseUrl?>/default/customers/details';
        });

        $(".cancel").on('click',function(){
        //location.reload();
            window.location.href = '<?php echo $this->BaseUrl?>/default/customers/details';
        });

       $("#model-warning").modal("hide");
       $("#search").hide();
       $(".searchfield").hide();
      var date = new Date();
      var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
	
      $(".message-success").hide(); 

      $('.datepicker-capthe').datepicker({ format: 'dd/mm/yyyy' }); 
      $('.datepicker-capthe').datepicker(
        'setValue', "<?php echo $this->customerdata['cus_date_lawyer_number']; ?>"
      );

      $('.datepicker-capthe-khac').datepicker({ format: 'dd/mm/yyyy' }); 
      $('.datepicker-capthe-khac').datepicker(
        'setValue', today
      );
      
      $('.datepicker-capchungchi').datepicker({ format: 'dd/mm/yyyy' }); 
      $('.datepicker-capchungchi').datepicker(
        'setValue', "<?php echo $this->lawyerdata['law_certification_createdate']; ?>"
      );



      // var inter_regis_date = '';

      // $('#dp5').datepicker()
      // .on('changeDate', function(ev){
      //   console.log("tesst code");
      //     console.log(ev.date.valueOf());
      //     console.log($("#dp5").val());
      //     inter_regis_date = ev.date.valueOf();        
      // });    

  $("#law_organ_old").attr("disabled",true);
  $("#inline_content input[name='joiningvalue']").click(function(){
    if($('input:radio[name=joiningvalue]:checked').val() == "notorgan"){
      //$("#law_organ_old").attr("disabled",false);
      //$("#law_joining_number").attr("disabled",true);
    }else{
      //$("#law_organ_old").attr("disabled",true);
      //$("#law_joining_number").attr("disabled",false);
    }
  });



  $("#search-global").keyup(function(e) {        
      $("#cus_id").val('');
      var key = e.keyCode;

      if (key == 40 || key == 38 || key == 13) {
          return false;
      }   
      var searchbox = $(this).val();
      var dataString = 'searchword='+ searchbox + '&searchfield='+$("#search-field").val();
      searchData(searchbox,dataString);
      
  });  

  $('#search').on("keydown", "#search-global", function (e) {
        console.log("event key down");
        var $listItems = $('.display-box-search-result li');
        //console.log($listItems);
        var key = e.keyCode,
        $selected = $listItems.filter('.hovered'),$current;

        var $scrollable = $("#display-content-search-global");
		    var scrollTop = $scrollable.scrollTop();

        //console.log(scrollTop);

        if (key != 40 && key != 38 && key != 13)
            return;

        //$listItems.removeClass('selected');

        if (key == 40) // Down key
        {
            $listItems.removeClass('hovered');
            if (!$selected.length || $selected.is(':last-child')) {
                $current = $listItems.eq(0);
            } else {
                $current = $selected.next();
            }
            $current.addClass('hovered');
            //console.log("Current : "+$current);
            //console.log($current);
            //$scrollable.scrollTop(scrollTop + 10);
        } 
        else if (key == 38) // Up key
        {
            $listItems.removeClass('hovered');
            if (!$selected.length || $selected.is(':first-child')) {
                $current = $listItems.last();
            } else {
                $current = $selected.prev();
            }       
            $current.addClass('hovered');
            //console.log($('.display-box-search-result li').length);
            //$scrollable.scrollTop(scrollTop - 10);

        } 
        else if (key == 13) // Enter key
        {
            $current = $listItems.filter('.hovered');
            $current.trigger('click');
            return false;
        }

        $("#display-content-search-global").scrollTop(0);//set to top
        $("#display-content-search-global").scrollTop($('.hovered:first').offset().top-$("#display-content-search-global").height());       
        
  });

  $('#display-content-search-global').on('click', function(event) {
    console.log("action event");
    var id = $(event.target).attr('id');
    var value = $("#"+id).val();
    var dataString = '?searchword='+ id;
      $.ajax({
          type: "GET",
          url: "<?php echo $this->BaseUrl?>/default/customers/detail"+dataString ,
          //data: dataString+'?format=html',
          dataType: 'json',
          cache: false,
          success: function(data)
          {   

            if(data.cus_id != null && data.cus_id != undefined){
                    $("#cus_id").val(data.cus_id);
                    $('#display-content-search-global').html('');
                    //$("#search-global").val(data.cus_identity_card);
                    if($("#search-field").val() != null && $("#search-field").val() == "name"){
                      $("#search-global").val(data.cus_fullname);
                     }else if($("#search-field").val() != null && $("#search-field").val() == "lawyer_number"){
                      $("#search-global").val(data.cus_lawyer_number);
                     }else if($("#search-field").val() != null && $("#search-field").val() == "identity_card"){
                      $("#search-global").val(data.cus_identity_card);
                     }else{
                      $("#search-global").val(data.cus_cellphone);
                     }
                    $("#cus_cellphone").val(data.cus_cellphone);
                    $("#cus_firstname").val(data.cus_firstname);
                    $("#cus_lastname").val(data.cus_lastname);
                    $("#cus_identity_card").val(data.cus_identity_card);
                    $("#cus_username").val(data.cus_username);
                    $("#cus_birthday").val(data.cus_birthday);
                    $("#cus_country").val(data.cus_country);

                    $("#cus_member").val(data.cus_member);
                    $("#law_code").val(data.cus_lawyer_number);
                    $("#law_certfication_no").val(data.law_certfication_no);
                    $("#law_joining_number").val(data.inter_number_name);

            }
            //console.log(data);             
          }, error: function(msg){               
          }           
          });
  });


    $("#form-lawyer").validate({
          rules:{
            law_code:{
              required:true
            },
            law_code_createdate:{
              required:true
            },
            law_certfication_no:{
              required:true
            },
            law_certification_createdate:{
              required:true
            }
            // ,
            // law_organ_address:{
            //   required:true
            // },
            // law_organ_phone:{
            //   required:true
            // }
          },
          errorClass: "help-inline",
          errorElement: "span",
          highlight:function(element, errorClass, validClass) {
            $(element).parents('.control-group').addClass('error');
          },
          unhighlight: function(element, errorClass, validClass) {
            $(element).parents('.control-group').removeClass('error');
            $(element).parents('.control-group').addClass('success');
          },
          messages: {            
            law_code: "Vui lòng nhập số thẻ luật sư",
            // lawyer_guide:"Chọn luật sư hướng dẫn",
            law_certfication_no:"Vui lòng nhập số chứng chỉ hành nghề" ,
            law_certification_createdate : " Vui lòng chọn ngày cấp chứng chỉ hành nghề"  ,
            // law_organ_address :"Nhập địa chỉ tổ chức hành nghề luật sư",
            // law_organ_phone : "Nhập số điện thoại văn phòng"
          },
          submitHandler: function(form,e) {
           //console.log($('#form-lawyer').serialize());
            $.ajax({
                  type: "POST",
                  url: "<?php echo $this->BaseUrl?>/default/lawyer/create/",
                  data: $('#form-lawyer').serialize() ,
                  cache: false,
                  success: function(html)
                  {   
                    //alert(html);
                    $("#message").html("Bạn đã chỉnh sửa thành công thông tin luật sư chính thức");
                    $("#model-warning").modal("show");
                                
                  }
            });
            return false;                       
        }
	  });


});

function searchData(searchbox,dataString){
    if(searchbox ==''){
            $("#display-content-search-global").html('');
            //load = true;
        } else
        {
            $.ajax({
                type: "POST",
                url: "<?php echo $this->BaseUrl?>/default/customers/search/",
                data: dataString,
                cache: false,
                success: function(html)
                {   
                  //$("#display-content-search-global").html('');
                  //console.log(html.length);
                  $("#display-content-search-global").html(html);                  
                }
            });
            //load = true
        }
  }  
  
  function isNumber(n) {
    return !isNaN(parseFloat(n)) && isFinite(n);
  }
</script>

 <div id="content">
    <div id="content-header">
      <div id="breadcrumb"> <a href="" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i></a> <a href="#" class="current">Chỉnh sửa thông tin luật sư chính thức</a> </div>
      <!-- <h1>Quản lý luật sư</h1> -->
    </div>
   <div class="container-fluid"> 
 
   <div class="row-fluid">
      <div class="alert alert-success alert-dismissible message-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <strong>Thông báo!</strong> Bạn đã tạo mới thành công luật sư tập sự.
        </div>        
  </div>   
    <!-- <h4>Thêm mới luật sư tập sự</h4> -->
    <div class="row-fluid">     
        <!-- open div general information-->
        <div class="span12">          
          <div class="widget-box">
            <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
              <h5>Thông tin chung</h5>
            </div>
            <div class="widget-content nopadding" id="detail-information">
            <!--start form-->              
                <div class="row-fluid form-horizontal">
                  <div class="span6">
                      <label class="control-label">Họ và lót:</label>
                      <div class="controls">
                        <input type="text" disabled id="cus_firstname" value="<?php echo $this->customerdata['cus_firstname'];?>" name="cus_firstname" class="span8" placeholder="Nhập số điện thoại để tìm luật sư" />
                      </div>  
                      <label class="control-label">Tên :</label>
                      <div class="controls">
                        <input type="text" disabled id="cus_lastname" value="<?php echo $this->customerdata['cus_lastname'];?>"  name="cus_lastname" class="span8" placeholder="Nhập số điện thoại để tìm luật sư" />
                      </div>      
                      <label class="control-label">Ngày sinh :</label>
                      <div class="controls">
                        <input type="text" disabled id="cus_birthday" value="<?php echo date("d/m/Y",strtotime($this->customerdata['cus_birthday']));?>" name="cus_birthday" class="span8" placeholder="Ngày sinh" />
                      </div>                
                                   
                  </div>  
                  <div class="span6">
                      <label class="control-label">Số điện thoại :</label>
                      <div class="controls">
                        <input type="text" disabled id="cus_cellphone" value="<?php echo $this->customerdata['cus_cellphone'];?>" name="cus_cellphone" class="span8" placeholder="số điện thoại" />
                      </div> 
                      <label class="control-label">Số chứng minh nhân dân :</label>
                      <div class="controls">
                        <input type="text" disabled id="cus_identity_card" value="<?php echo $this->customerdata['cus_identity_card'];?>"   name="cus_identity_card" class="span8" placeholder="Nhập số điện thoại để tìm luật sư" />
                      </div> 
                      <!-- <label class="control-label">Số thẻ LS :</label>
                      <div class="controls">
                        <input type="text" id="cus_lawyer_number" value="<?php echo $this->customerdata['cus_lawyer_number'];?>"  name="cus_lawyer_number" class="span8" placeholder="Số thẻ LS" />
                      </div>   -->
      
                      <!-- <label class="control-label">Tên đăng nhập:</label>
                      <div class="controls">
                        <input type="text" id="cus_username"  name="cus_username" class="span8" placeholder="Nhập số điện thoại để tìm luật sư" />
                      </div>     -->
                  </div>                  
                </div>            
              <!-- end form -->
            </div>          
          </div>
        </div>   
      </div> 

       <div class="row-fluid">
        <!-- open div general information-->
        <div class="span12">          
          <div class="widget-box">
            <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
              <h5>Chỉnh sửa thông tin luật sư chính thức</h5>
            </div>
            <div class="widget-content nopadding" id="detail-information">
            <!--start form-->
              <form id="form-lawyer" class="form-horizontal" novalidate="novalidate">
                <input type="hidden" name="cus_id" id="cus_id" value="<?php echo $this->customerdata['cus_id'];?>" />
                <input type="hidden" name="law_id" value="<?php echo $this->lawyerdata['law_id']; ?>" />
                <input type="hidden" name="crudation" value="update" />
             
                <input type="hidden" name="cus_member" id="cus_member" />
                <div class="row-fluid">
                  <div class="span6">

                      <div class="control-group">
                        <label class="control-label">Số thẻ luật sư * :</label>
                        <div class="controls">
                          <input id="law_code" type="number"  name="law_code"  value="<?php echo $this->customerdata['cus_lawyer_number']; ?>" class="span8" placeholder="Vui lòng nhập mã số luật sư" />
                        </div> 
                      </div>   

                      <div class="control-group">
                        <label class="control-label">Ngày cấp số thẻ luật sư * :</label>
                        <div class="controls">                            
                            <div  data-date="12-02-2012" class="input-append date datepicker-capthe">
                              <input type="text"  id="law_code_createdate" name="law_code_createdate" data-date-format="dd-mm-yyyy" class="span11" placeholder="Vui lòng chọn ngày cấp" >
                              <span class="add-on"><i class="icon-th"></i></span> 
                            </div>
                        </div>
                      </div>  

                      <div class="control-group">        
                              <label class="control-label">Ngày cấp số thẻ luật sư khác:</label>
                              <div class="controls">
                                  <!-- <input type="text" class="span8" id="cus_identity_date" name="cus_identity_date" placeholder="Company name" /> -->
                                  <div  data-date="12-02-2012" class="input-append date datepicker-capthe-khac">
                                    <input type="text" id="law_code_createdate_different" name="law_code_createdate_different" data-date-format="dd-mm-yyyy" class="span11" placeholder="Vui lòng chọn ngày cấp" >
                                    <span class="add-on"><i class="icon-th"></i></span> 
                                  </div>
                              </div>   
                            </div>                                  

                      <label class="control-label">Chọn gia nhập *:</label>
                        <div class="controls">
                          <div id="inline_content" class="row-fluid">
                              <div class="span6">
                                <label>
                                    <input type="radio" name="joiningvalue" value="organ" checked/>
                            Tập sự tại đoàn</label>
                              </div>
                              <div class="span6">
                                    <label>
                                  <input type="radio" name="joiningvalue" value="notorgan" />
                                 Khác</label> 
                              </div>
                          </div>                                               
                        </div>  

                      <div class="control-group">        
                        <label class="control-label">Đợt gia nhập *:</label>
                        <div class="controls">
                          <input type="text" id="law_joining_number" value="<?php echo $this->lawyerdata['law_joining_number']; ?>"  name="law_joining_number" class="span8" placeholder="Vui lòng nhập đợt gia nhập" />
                        </div>
                      </div>   

                      <!-- <div class="control-group">        
                        <label class="control-label">Ghi chú * ( Trường hợp khác):</label>
                        <div class="controls">
                          <textarea cols="6" type="text" id="law_organ_old"  name="law_organ_old" class="span8" placeholder="Vui lòng nhập ghi chú"></textarea>
                        </div>
                      </div> -->

                       

                  </div>  
                  <div class="span6">
                            <div class="control-group">        
                              <label class="control-label">Số chứng chỉ hành nghề*:</label>
                              <div class="controls">
                                <input id="law_certfication_no" type="number" name="law_certfication_no" value="<?php echo $this->lawyerdata['law_certfication_no']; ?>" class="span8" placeholder="Vui lòng nhập mã số chứng chỉ" />
                              </div>
                            </div>   

                            <div class="control-group">        
                              <label class="control-label">Ngày cấp chứng chỉ hành nghề *:</label>
                              <div class="controls">
                                  <!-- <input type="text" class="span8" id="cus_identity_date" name="cus_identity_date" placeholder="Company name" /> -->
                                  <div  data-date="12-02-2012" class="input-append date datepicker-capchungchi">
                                    <input type="text" id="law_certification_createdate" name="law_certification_createdate" data-date-format="dd-mm-yyyy" class="span11" placeholder="Vui lòng chọn ngày cấp" >
                                    <span class="add-on"><i class="icon-th"></i></span> 
                                  </div>
                              </div>   
                            </div>

                             <!-- <div class="control-group">
                              <label class="control-label">Chọn hình thức hành nghề</label>                      
                              <div class="controls">
                                    <select class="span8" id="act_id" name="act_id">
                                    <?php  
                                        foreach ($this->activitys_data as $act) {
                                            echo '<option value="'.$act['act_id'].'" class="span8">'.$act['act_name'].'</option>';
                                        }
                                        ?>    
                                    </select>
                              </div>
                            </div>                              -->

                            <div class="control-group">
                              <label class="control-label" >Chọn tổ chức hành nghề đang làm việc:</label>                      
                              <div class="controls">
                                    <select class="span8" id="organ_lid" name="organ_lid">
                                      <option value="0" class="span8">Không tham gia TCHN</option>
                                    <?php  
                                          
                                      foreach ($this->organizations as $org) {
                                          echo '<option value="'.$org['organ_detail_id'].'" class="span8">'.$org['organ_name'].'</option>';
                                      }
                                      ?>                                        
                                    </select>
                              </div>  
                            </div>   

                            <!-- <div class="control-group">        
                              <label class="control-label">Địa chỉ tổ chức hành nghề *:</label>
                              <div class="controls">
                                <textarea type="text" id="law_organ_address"  name="law_organ_address" class="span8" placeholder="Vui lòng nhập địa chỉ tổ chức hành nghề"></textarea>
                              </div>
                            </div>    -->

                             <!-- <div class="control-group">        
                              <label class="control-label">Quận/Huyện *:</label>
                              <div class="controls">
                                  <select name="district" style="width: 150px">                                     
                                      <option value="Quận 1">Quận 1</option>
                                      <option value="Quận 2">Quận 2</option> 
                                      <option value="Quận 3">Quận 3</option>
                                      <option value="Quận 4">Quận 4</option>
                                      <option value="Quận 5">Quận 5</option>
                                      <option value="Quận 6">Quận 6</option>
                                      <option value="Quận 7">Quận 7</option>
                                      <option value="Quận 8">Quận 8</option>
                                      <option value="Quận 9">Quận 9</option>
                                      <option value="Quận 10">Quận 10</option>
                                      <option value="Quận 11">Quận 11</option>
                                      <option value="Quận 12">Quận 12</option>
                                      <option value="Quận Thử Đức">Quận Thủ Đức</option>
                                      <option value="Quận Bình Thạnh">Quận Bình Thạn</option>
                                      <option value="Quận Gò Vấp">Quận Gò Vấp</option>
                                      <option value="Quận Phú Nhuận">Quận Phú Nhuận</option>
                                      <option value="Quận Tân Phú">Quận Tân Phú</option>
                                      <option value="Quận Bình Tân">Quận Bình Tân</option>
                                      <option value="Quận Tân Bình">Quận Tân Bình</option>
                                      <option value="Huyện Nhà Bè">Huyện Nhà Bè</option>
                                      <option value="Huyện Bình Chánh">Huyện Bình Chánh</option>
                                      <option value="Huyện Hóc Môn">Huyện Hóc Môn</option>
                                      <option value="Huyện Củ Chi">Huyện Củ Chi</option>
                                      <option value="Huyện Cần Giờ">Huyện Cần Giờ</option>
                                      <option value="Khác">Khác</option>                                   
                                  </select>	
                              </div>
                            </div>  -->

                            <!-- <div class="control-group">        
                              <label class="control-label">Điện thoại văn phòng *:</label>
                              <div class="controls">
                                <input type="text" id="law_organ_phone"  name="law_organ_phone" class="span8" placeholder="Vui lòng nhập điện thoại văn phòng" />
                              </div>
                            </div>                     
                             -->
                            <div class="control-group">
                              <label class="control-label">Chọn trạng thái luật sư:</label>                      
                              <div class="controls">
                                    <select class="span8" id="lawstatus_id" name="lawstatus_id">
                                    <?php  
                                        foreach ($this->status as $stt) {
                                            if($stt['lawstatus_id'] == $this->lawyerdata['lawstatus_id'] ){
                                                echo '<option selected value="'.$stt['lawstatus_id'].'" class="span8">'.$stt['lawstatus_name'].'</option>';
                                            }else{
                                                echo '<option value="'.$stt['lawstatus_id'].'" class="span8">'.$stt['lawstatus_name'].'</option>';    
                                            }    
                                            //echo '<option value="'.$stt['lawstatus_id'].'" class="span8">'.$stt['lawstatus_name'].'</option>';
                                        }
                                        ?>    
                                    </select>
                              </div>
                            </div>     

                          <div class="control-group">        
                            <label class="control-label">Ghi chú * :</label>
                            <div class="controls">
                              <textarea cols="6" type="text" id="law_organ_note"  name="law_organ_note" class="span8" placeholder="Vui lòng nhập ghi chú"><?php echo $this->lawyerdata['law_organ_note']; ?></textarea>
                            </div>
                          </div>                 
                      
                  </div>                  
                </div>              
                   <div class="form-actions">                  
                    <button type="submit" class="btn">Lưu</button>    
                    <a href="<?php echo $this->BaseUrl?>/default/customers/details" class="btn" >Hủy bỏ</a>              
                    <!-- <button class="btn cancel">Hủy bỏ</button> -->
                  </div> 
              </form>
              <!-- end form -->
            </div>          
          </div>
        </div>   
      </div>     
    </div>    
    </div>
      <!--end div-->   
      <!--open div--> 
   
    </div>  
  </div>
  
 
<!-- </div> -->

<!-- Modal -->
<div id="model-warning" class="modal fade" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Thông báo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <p id="message">Trong hệ thống đã tồn tại luật sư,hệ thống sẽ tải thông tin để bạn đăng kí tập sự.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>