
<script>
$(document).ready(function(){

    $("#form-edit").validate({     
            rules:{
                // law_code:{
                // required:true
                // },
                // law_certfication_no:{
                // required:true
                // }
            },
            errorClass: "help-inline",
            errorElement: "span",
            highlight:function(element, errorClass, validClass) {
                $(element).parents('.control-group').addClass('error');
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').removeClass('error');
                $(element).parents('.control-group').addClass('success');
            },
            messages: {
                //cus_cellphone: "Vui lòng nhập số điện thoại !",
                // cus_identity_card: "Vui lòng nhập số CMND !",
                law_code: "Vui lòng nhập mã luật sư !",
                law_certfication_no: "Vui lòng nhập số chứng chỉ !",
            },
            submitHandler: function(form,e) {
                console.log('Form submitted');
                console.log($('#form-edit').serialize());
                $.ajax({
                      type: "POST",
                      url: "<?php echo $this->BaseUrl?>/default/lawyer/updatehistory/",
                      data: $('#form-edit').serialize() ,
                      cache: false,
                      success: function(html)
                      {   
                        //alert(html);
                        //alert("Cập nhật luật sư thành công");
                        //$(".message-success").show();
                        $("#message").html("Cập nhật thông tin đợt gia nhập thành công");
                        // $("#model-warning").modal("show");                                    
                      }
                });
                return false;                       
            }
        });
});  

</script>
<form id="form-edit" class="form-horizontal">
    <p id="message"></p> 
    <input type="hidden" name="history_joining_id" value="<?php echo $this->historydata['history_joining_id']; ?>" /> 
    <div class="control-group">
        <label class="control-label">Tên đợt gia nhập: </label>
        <div class="controls">
            <input type="text" class="span3" name="law_joining_number" id="law_joining_number" value="<?php echo $this->historydata['law_joining_number']; ?>">
        </div>
    </div>    
    <!-- <label class="control-label">Trạng thái đợt tập sư:</label>
    <div class="controls">
        <div class="row-fluid">                        
               
                <div class="span6">
                    <label>
                    <input type="radio" name="payment_inter_status" value="2" />
                     Bỏ đợt tập sự</label> 
                </div>              
        </div>                                               
    </div>  -->
    <div class="control-group">
        <label class="control-label">Ghi chú: </label>
        <div class="controls">
            <input type="text" class="span3" name="law_joining_note" id="law_joining_note" value="<?php echo $this->historydata['law_joining_note']; ?>">
        </div>
    </div>           
    <!-- <div class="form-actions"> -->
    <button style="float: right;" type="submit" class="btn">Lưu</button>
    <!-- </div> -->
</form>
         