<?php  
    if($this->histories != null){
        foreach ($this->histories as $inter) {
            $edit = '<td class="center">'.
            '<input type="button" class=button value="Chỉnh sửa" onClick="updateHistoryJoining('.$inter['history_joining_id'].');" />'.
        '</td>';

            // if($inter['cus_id'] != null){
            //     $edit = '<td>Không chỉnh sửa. </th>';
            // }

            if($inter['payment_joining_status'] == 1){
                $edit = '<td>Không chỉnh sửa.</th>';
            }

            $inter_regis_date = ($inter['createddate'] != null && $inter['createddate'] != ''
                && $inter['createddate'] != '1900-01-01 00:00:00') ? date('d/m/Y', strtotime($inter['createddate'])) : '';    
        
            echo ' <tr class="gradeC">'.
            '<td>'.$inter_regis_date.'</td>'.
            '<td>'.$inter['law_joining_number'].'</td>'.  
            '<td>'.$inter['law_joining_note'].'</td>'.          
            $edit.               
        '</tr>';                            
        }  
    }

?>   
                            
                               