
<script>
$(document).ready(function(){

    $(".close-modal").on('click',function(){
       location.reload();
    });

    $("#form-edit").validate({     
            rules:{
                answer:{
                    required:true
                }
            },
            errorClass: "help-inline",
            errorElement: "span",
            highlight:function(element, errorClass, validClass) {
                $(element).parents('.control-group').addClass('error');
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').removeClass('error');
                $(element).parents('.control-group').addClass('success');
            },
            messages: {
                answer: "Vui lòng nhập nội dung câu trả lời !"               
            },
            submitHandler: function(form,e) {
                console.log('Form submitted');
                $.ajax({
                      type: "POST",
                      url: "<?php echo $this->BaseUrl?>/default/questionanswer/create/",
                      data: $('#form-edit').serialize() ,
                      cache: false,
                      success: function(html)
                      {   
                        $("#message").html("Trả lời câu hỏi thành công"); 
                        //$(".close-modal").hide();  
                                                                               
                      }
                });
                return false;                       
            }
        });
});  

</script>

<form id="form-edit" class="form-horizontal">
    <!-- <h4> Trả lời câu hỏi của luật sư </h3> -->
        <p id="message"></p>
        <input type="hidden" name="question_id" value="<?php echo $this->question['question_id']; ?>" /> 
        <div class="control-group">
            <label class="control-label">Nội dung câu hỏi:</label>
            <div class="controls">
                <textarea rows="5" disabled class="span3">
                    <?php echo $this->question['question_content']; ?>
                </textarea>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Trả lời câu hỏi:</label>
            <div class="controls">
                <textarea name="answer" rows="5" class="span3">
                    
                </textarea>
            </div>
        </div>      
        <!-- <div class="form-actions"> -->
        <button style="float: right;" type="submit" class="btn">Lưu</button>
        <!-- </div> -->
</form>
         


