<h2>Công Ty TNHH Thương Mại Y Tế Phú Gia</h2>
<p>Xin chào <?= $this->name ?>,</p>
<p>Bạn nhận được email này là do bạn hoặc nhân viên quản trị hệ thống đã thiết lập lại mật khẩu cho tài khoản của bạn.</p>
<p>Mật khẩu mới của bạn là <strong><?= $this->password ?></strong></p>
<p>Bạn vui lòng đăng nhập hệ thống bằng mật khẩu này và tiến hành đổi mật khẩu ngay sau khi đăng nhập thành công.</p>
<p>Vui lòng không trả lời email này. Đây là email do hệ thống gửi tự động.</p>
<p>Nếu bạn có bất kỳ thắc mắc nào, vui lòng liên hệ nhân viên quản trị hệ thống của công ty.</p>
<p>Thân mến./.</p>