<script type="text/javascript">
  $("#search").hide();
  $(".searchfield").hide();

</script>
<div id="content">
    <div id="content-header">
        <div id="breadcrumb">
            <a href="#" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i></a>
            <a href="#" class="current">Gửi email</a>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="widget-box">
                <div class="widget-title">
                    <ul class="nav nav-tabs">
                        <li class="active"><a data-toggle="tab" href="#tab1">Gửi email theo nhóm</a></li>
                        <li><a data-toggle="tab" href="#tab2">Gửi theo địa chỉ email</a></li>
                        <!-- <li><a data-toggle="tab" href="#tab3">Tab3</a></li> -->
                    </ul>
                </div>
                <div class="widget-content tab-content">
                    <div id="tab1" class="tab-pane active">
                        <div class="widget-title"><span class="icon"> <i class="icon-align-justify"></i> </span>
                            <h5>Gửi email theo nhóm</h5>
                        </div>
                        <div class="widget-content nopadding" id="detail-information">
                            <!--start form-->
                            <form action="" method="post">
                                <div class="row-fluid form-horizontal">
                                    <div class="span6">
                                        <label class="control-label">Chọn nhóm</label>
                                        <div class="controls">
                                            <select name="group_id" class="select2 span8" required>
                                                <?php
                                                foreach ($this->groups as $group) {
                                                    ?>
                                                    <option value="<?= $group->group_id ?>"><?= $group->group_name ?></option>
                                                <?php } ?>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="span6">
                                        <label class="control-label">Tiêu đề</label>
                                        <div class="controls">
                                            <input type="text" id="mail_subject" name="mail_subject" class="span8"
                                                placeholder="Tiêu đề" required>
                                        </div>
                                    </div>
                                </div>
                                <div class="row-fluid form-horizontal">
                                    <div class="span12">
                                        <label class="control-label">Nội dung</label>
                                        <div class="controls">
                                            <!-- creating a text area for my editor in the form -->
<textarea id="myeditor" name="mail_content" id="myeditor"></textarea>

<!-- creating a CKEditor instance called myeditor -->
<script type="text/javascript">
    CKEDITOR.replace('myeditor');
</script>
                                        <!--    <textarea name="mail_content" rows="8" class="span8" style="margin: 0px; width: 997px; height: 159px;" required></textarea>-->
                                        </div>
                                    </div>
                                </div>
                                <input type="hidden" value="send_group" name="type_mail">
                                <div class="row-fluid">
                                    <div class="form-actions span12">
                                        <div class="pull-right">
                                            <button id="btnSendGroup" class="btn btn-primary">Gửi</button>
                                        </div>
                                    </div>
                                </div>
                            <!-- end form -->
                            </form>
                        </div>
                    </div>
                    <div id="tab2" class="tab-pane">
                        <div class="widget-title"><span class="icon"> <i class="icon-align-justify"></i> </span>
                            <h5>Gửi theo địa chỉ email</h5>
                        </div>
                        <div class="widget-content nopadding" id="detail-information">
                            <!--start form-->
                            <form action="" method="post">
                                <div class="row-fluid form-horizontal">
                                    <div class="span6">
                                        <label class="control-label">Địa chỉ email</label>
                                        <div class="controls">
                                            <input type="email" id="person_email" name="person_email" class="span8"
                                                placeholder="Địa chỉ email" required>
                                        </div>
                                    </div>
                                    <div class="span6">
                                        <label class="control-label">Tiêu đề</label>
                                        <div class="controls">
                                            <input type="text" id="mail_subject" name="mail_subject" class="span8"
                                                placeholder="Tiêu đề" required>
                                        </div>
                                    </div>
                                </div>
                                <div class="row-fluid form-horizontal">
                                    <div class="span12">
                                        <label class="control-label">Nội dung</label>
                                        <div class="controls">
                                        <!-- creating a text area for my editor in the form -->
<textarea id="myeditor1" name="mail_content"></textarea>

<!-- creating a CKEditor instance called myeditor -->
<script type="text/javascript">
    CKEDITOR.replace('myeditor1');
</script>
                                       <!-- <textarea name="mail_content" rows="8" class="span8" style="margin: 0px; width: 997px; height: 159px;" required></textarea>-->
                                        </div>
                                    </div>
                                </div>
                                <input type="hidden" value="send_email" name="type_mail">
                                <div class="row-fluid">
                                    <div class="form-actions span12">
                                        <div class="pull-right">
                                            <button id="btnSendMail" class="btn btn-success">Gửi</button>
                                        </div>
                                    </div>
                                </div>
                                <!-- end form -->
                            </form>
                        </div>
                    </div>
                    <div id="tab3" class="tab-pane">                       
        
                    </div>
                </div>                            
            </div>
        </div>
    </div>    
</div>
<script>
    $(document).ready(function(){
        $('.select2').select2();
    });
</script>

