<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Danh sách vật tư, hàng hóa</h6>
        </div>

        <div class="card-body">
          <div class="border-bottom mb-3 pb-3">
            <button type="button" id="btnThemVT" class="btn btn-primary">
              <i class="fas fa-plus"></i>
              Thêm vật tư
            </button>

            <label for="fileUpload" class="btn btn-light btn-outline-secondary ml-1 mb-0">
              <i class="fas fa-upload"></i>
              Import Excel
              <input id="fileUpload" name="fileUpload" type="file" class="d-none" accept="application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">
            </label>
          </div>

          <table id="tblProduct" class="table table-bordered table-striped table-hover data-table">
            <thead></thead>
            <tbody></tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<!--------------------------------------------------------------------------------------->

<!-- Detail dialog -->
<div id="detailDlg" class="modal fade" tabindex="-1">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Thông Tin Chi Tiết Vật Tư</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <div class="modal-body px-0">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-6">
              <label class="mb-1">Mã vật tư</label>
              <input type="text" id="txtMaVT" class="form-control">
              <input type="hidden" id="hidPrdId">
            </div>
            <div class="col-md-6">
              <label class="mb-1">Tên vật tư</label>
              <input type="text" id="txtTenVT" class="form-control">
            </div>
          </div>

          <div class="row mt-3">
            <div class="col-md-6">
              <label class="mb-1">Đơn vị tính</label>
              <input type="text" id="txtDonViTinh" class="form-control">
            </div>
            <div class="col-md-6">
              <label class="mb-1">Hãng sản xuất</label>
              <input type="text" id="txtHangSX" class="form-control">
            </div>
          </div>
        </div>
      </div>
      <!-- /modal-body -->

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          <i class="fas fa-times"></i>
          Đóng
        </button>
        <button id="btnSaveProduct" type="button" class="btn btn-primary">
          <i class="fas fa-save"></i>
          Lưu
        </button>
      </div>
    </div>
  </div>
</div>
<!-- /Detail dialog -->

<!--------------------------------------------------------------------------------------->

<!-- Import dialog -->
<div id="importDlg" class="modal fade" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Import Excel</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <div class="modal-body">
        <p>
          Bạn đang nhập thông tin vật tư từ tập tin
          <br>
          <span id="importDlg-filename" class="d-inline-block font-weight-bold ml-3"></span>
        </p>
        <p>Hãy chắc chắn rằng nội dung tập tin được soạn đúng theo mẫu được cung cấp.</p>
        <p>Tiếp tục thực hiện?</p>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          <i class="fas fa-times"></i>
          Đóng
        </button>
        <button id="btnImportProduct" type="button" class="btn btn-primary">
          <i class="fas fa-file-import"></i>
          Thực hiện
        </button>
      </div>
    </div>
  </div>
</div>
<!-- /Import dialog -->

<script src="<?=$this->BaseUrl?>/public/js/product.js"></script>
