
<script>
$(document).ready(function(){
  $("#search").hide();
  $(".searchfield").hide();

    $(".close-modal").on('click',function(){
    location.reload();
  });

  $("#form-edit-lock").validate({            
      submitHandler: function(form,e) {
          console.log('Form submitted');
          $.ajax({
                type: "POST",
                url: "<?php echo $this->BaseUrl?>/default/useradmin/updatestatus/",
                data: $('#form-edit-lock').serialize() ,
                cache: false,
                success: function(html)
                {   
                  //alert(html);
                  $(".modal-body").html(html);
                  $("#model-warning").modal('show');
                  //$("#message").html("Đổi mật khẩu thành công"); 
                  //$(".close-modal").hide();  
                                                                          
                }
          });
          return false;                       
      }
  });

 $("#form-edit").validate({     
            rules:{
                password:{
                  required:true
                },
                password2: {
                  equalTo: "#password"
                }
            },
            errorClass: "help-inline",
            errorElement: "span",
            highlight:function(element, errorClass, validClass) {
                $(element).parents('.control-group').addClass('error');
            },
            unhighlight: function(element, errorClass, validClass) {
                $(element).parents('.control-group').removeClass('error');
                $(element).parents('.control-group').addClass('success');
            },
            messages: {
                password: "Vui lòng nhập mật khẩu mới",
				        password2: { equalTo: "Mật khẩu không khớp" },
            },
            submitHandler: function(form,e) {
                console.log('Form submitted');
                $.ajax({
                      type: "POST",
                      url: "<?php echo $this->BaseUrl?>/default/useradmin/updatenewpassword/",
                      data: $('#form-edit').serialize() ,
                      cache: false,
                      success: function(html)
                      {   
                        //alert(html);
                        $(".modal-body").html(html);
                        $("#model-warning").modal('show');
                        //$("#message").html("Đổi mật khẩu thành công"); 
                        //$(".close-modal").hide();  
                                                                               
                      }
                });
                return false;                       
            }
        });
});

function assignRole(id){
  window.location.href = '<?php echo $this->BaseUrl?>/admin/action/assignrole?userid='+id;
}

 function changePass(id){
      $("#message").hide();
      $("#user_id").val(id);
      $("#form-edit-lock").hide();
      $("#form-edit").show();
      $("#model-warning").modal('show');
 }

 function lockUser(id){
      $("#message").hide();
      $("#user_id_lock").val(id);
      $("#form-edit").hide();
      $("#form-edit-lock").show();
      $("#model-warning").modal('show');
 }  
</script>
<div id="content">
  <div id="content-header">
    <div id="breadcrumb"> <a href="#" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i> Trang chủ</a> <a href="#" class="current">Danh sách người dùng</a> </div>
    <h1>Danh sách người dùng</h1>
  </div>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span12">
        <div class="widget-box">
          <div class="widget-title">
             <span class="icon"><i class="icon-th"></i></span> 
            <h5>Danh sách người dùng</h5>
          </div>
          <div class="widget-content nopadding">
            <table class="table table-bordered data-table">
              <thead>
                <tr>
                  <th>Tên</th>
                  <th>Tên Đăng Nhập</th>
                  <th>Trạng thái</th>    
                  <th>Hành động</th>              
                </tr>
              </thead>
              <tbody>       
                <?php  
                      if($this->list != null){
                          foreach ($this->list as $user) {

                            $status = '';
                            if($user['user_status'] == 0){
                                $status = '<td>Ngưng hoạt động</td>';
                             }else{
                                $status = '<td>Hoạt động</td>';  
                             }    

  
                            echo ' <tr class="gradeC">'.
                            '<td>'.$user['user_name'].'</td>'.
                            '<td>'.$user['user_username'].'</td>'.
                             $status.
                             '<td>'.'<button data-toggle="tooltip" title="Gắn vai trò " onClick="assignRole('.$user['user_id'].');"><i class="icon-pencil"></i></button>'.' '
                             .'<button data-toggle="tooltip" title="Đổi mật khẩu" onClick="changePass('.$user['user_id'].');"><i class="icon-refresh"></i></button>'.' '. 
                             '<button data-toggle="tooltip" title="Khóa tài tài khoản" onClick="lockUser('.$user['user_id'].');"><i class="icon-lock"></i></button>'.               
                             '</tr>';                          
                          
                          }  
                      }

                  ?>
              </tbody>
            </table>
          </div>
        </div>        
      </div>
    </div>
  </div>
</div>

<div id="model-warning" class="modal fade"  data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="exampleModalLabel">Cập nhật mật khẩu</h5>
        
      </div>
        
        <div class="modal-body">
            <p id="message">Bạn đã cập nhật thành công.</p>
            <form id="form-edit" class="form-horizontal">
                   <input type="hidden" name="user_id" id="user_id" />                       

                    <div class="control-group">        
                          <label class="control-label">Nhập mật khẩu mới:</label>
                          <div class="controls">
                            <input id="password" type="password" name="password" />
                          </div>
                      </div> 

                    <div class="control-group">        
                        <label class="control-label">Xác nhận mật khẩu mới:</label>
                        <div class="controls">
                        <input id="password2" type="password" name="password2" />
                        </div>
                    </div> 
                              
                    <!-- <div class="form-actions"> -->
                      <button style="float: right;" type="submit" class="btn">Lưu</button>
                    <!-- </div> -->
                  </form>

                  <form id="form-edit-lock" class="form-horizontal">
                   <input type="hidden" name="user_id_lock" id="user_id_lock" />                       

                     <label class="control-label">Trạng thái tài khoản</label>
                        <div class="controls">
                          <div class="row-fluid">
                              <div class="span3">
                                <label>
                                    <input type="radio" name="user_status" value="active" checked/>
                            Hoạt động</label>
                              </div>
                              <div class="span6">
                                    <label>
                                  <input type="radio" name="user_status" value="inactive"/>
                                  Ngưng hoạt động</label> 
                              </div>
                          </div>                                               
                        </div>    
                              
                    <!-- <div class="form-actions"> -->
                      <button style="float: right;" type="submit" class="btn">Lưu</button>
                    <!-- </div> -->
                  </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary close-modal" data-dismiss="modal">Đóng</button>
        </div>
      
    </div>
  </div>
</div>