<script>

$(document).ready(function(){
    $('select').select2();

     $("#search-global").keyup(function(e) {        
        $("#cus_id").val('');
        var key = e.keyCode;

        if (key == 40 || key == 38 || key == 13) {
            return false;
        }   
        var searchbox = $(this).val();
        var dataString = 'searchword='+ searchbox + '&searchfield='+$("#search-field").val();
        searchData(searchbox,dataString); 
        
    });  

    $("#organ_name").hide();

    $('#search').on("keydown", "#search-global", function (e) {
        console.log("event key down");
        var $listItems = $('.display-box-search-result li');
        //console.log($listItems);
        var key = e.keyCode,
        $selected = $listItems.filter('.hovered'),$current;

        var $scrollable = $("#display-content-search-global");
		 var scrollTop = $scrollable.scrollTop();

        //console.log(scrollTop);

        if (key != 40 && key != 38 && key != 13)
            return;

        //$listItems.removeClass('selected');

        if (key == 40) // Down key
        {
            $listItems.removeClass('hovered');
            if (!$selected.length || $selected.is(':last-child')) {
                $current = $listItems.eq(0);
            } else {
                $current = $selected.next();
            }
            $current.addClass('hovered');
            //console.log("Current : "+$current);
            //console.log($current);
            //$scrollable.scrollTop(scrollTop + 10);
        } 
        else if (key == 38) // Up key
        {
            $listItems.removeClass('hovered');
            if (!$selected.length || $selected.is(':first-child')) {
                $current = $listItems.last();
            } else {
                $current = $selected.prev();
            }       
            $current.addClass('hovered');
            //console.log($('.display-box-search-result li').length);
            //$scrollable.scrollTop(scrollTop - 10);

        } 
        else if (key == 13) // Enter key
        {
            $current = $listItems.filter('.hovered');
            $current.trigger('click');
            return false;
        }

        $("#display-content-search-global").scrollTop(0);//set to top
        $("#display-content-search-global").scrollTop($('.hovered:first').offset().top-$("#display-content-search-global").height());       
        
    });

    $('#display-content-search-global').on('click', function(event) {
      console.log("action event");
      var id = $(event.target).attr('id');
      var value = $("#"+id).val();
      // console.log(value.split('_')[2]);
      var dataString = '?searchword='+ id;
       $.ajax({
            type: "GET",
            url: "<?php echo $this->BaseUrl?>/default/customers/detail"+dataString ,
            //data: dataString+'?format=html',
            dataType: 'json',
            cache: false,
            success: function(data)
            {   
 
              if(data.cus_id != null && data.cus_id != undefined){

                     //$("#cus_id").val(data.cus_id);
                      //$("#lawyer").click();
                     //$("#internship").click();

                     loadDataForTab(data.cus_id,"#table-intership","intership");
                     loadDataForTab(data.cus_id,"#table-lawyer","lawyer");
                     loadDataForTab(data.cus_id,"#table-training","training");
                     loadDataForTab(data.cus_id,"#table-reward","reward");
                     loadDataForTab(data.cus_id,"#table-member","member");

                     $('#display-content-search-global').html('');
                     //$("#search-global").val(data.cus_identity_card);
                     if($("#search-field").val() != null && $("#search-field").val() == "name"){
                      $("#search-global").val(data.cus_fullname);
                     }else if($("#search-field").val() != null && $("#search-field").val() == "lawyer_number"){
                      $("#search-global").val(data.cus_lawyer_number);
                     }else if($("#search-field").val() != null && $("#search-field").val() == "identity_card"){
                      $("#search-global").val(data.cus_identity_card);
                     }else{
                      $("#search-global").val(data.cus_cellphone);
                     }
                     $("#cus_cellphone").html(data.cus_cellphone);
                     $("#cus_firstname").html(data.cus_fullname);
                     $("#cus_username").html(data.cus_username);
                     $("#cus_lastname").html(data.cus_lastname);
                     $("#cus_identity_card").html(data.cus_identity_card);
                     $("#cus_identity_place").html(data.cus_identity_place);
                     $("#cus_identity_date").html(data.cus_identity_date);
                     $("#cus_birthday").html(data.cus_birthday);
                     $("#cus_birthplace").html(data.cus_birthplace);
                     $("#city_name").html(data.city_name);
                     $("#cus_country").html(data.cus_country);
                     $("#cus_nation").html(data.cus_nation);
                     $("#cus_address_resident").html(data.cus_address_resident);
                     $("#cus_address_resident_now").html(data.cus_address_resident_now);
                     $("#cus_sex").html(data.cus_sex); 
                     $("#cus_homephone").html(data.cus_homephone); 
                     //$("#cus_passport_card").html(data.cus_passport_card); 
                     //$("#cus_passport_place").html(data.cus_passport_place); 
                     //$("#cus_passport_date").html(data.cus_passport_date); 
                     $("#cus_educations").html(data.cus_educations);
                     //$("#cus_language_level").html(data.cus_language_level);
                     $("#cus_joining_communist_youth").html(data.cus_joining_communist_youth);
                     $("#cus_joining_communist_prepare").html(data.cus_joining_communist_prepare);
                     $("#cus_joining_communist").html(data.cus_joining_communist); 
                     $("#cus_language_level").html(data.language_name);
                     $("#cus_homephone").html(data.cus_homephone);
                     $("#cus_religion").html(data.cus_religion);
               
                     if(data.type_image != undefined){
                        if(data.attachment_name_image != null){
                            if(data.attachment_name_image != ''){
                               $('#image-review').attr('src', data.attachment_name_image);
                            }  
                        }                        
                      
                      //$("#message-image").show(); 
                     }else{
                        $('#image-review').attr('src', "<?php echo $this->BaseUrl?>/files/images/photo.jpg");
                     } 

                              
                     //$("#cus_lawyer_hcm").val(data.cus_lawyer_hcm); 
                     //$('#image-review').attr('src',data.);
                     //console.log(data.cus_lawyer_hcm);
                     $("#cus_email").html(data.cus_email);

                     if(data.cus_member == 1){
                         $("#cus_member").html('Hiện đang là luật sư của Đoàn Luật Sư Hồ Chí Minh');
                        $("#organ_name").show();
                     }else{
                        $("#cus_member").html('Hiện không phải là luật sư của Đoàn Luật Sư Hồ Chí Minh');
                     }
    
              }
              //console.log(data);             
            }, error: function(msg){               
            }           
            });
    });
});

  function loadDataForTab(cus_id,div_content,typetab){
 
    var dataString = '?cus_id='+ cus_id;        
    if(cus_id !='' &&  cus_id != null){ 
        var url = '';
        if(typetab != '' && typetab == 'intership'){
        url = "<?php echo $this->BaseUrl?>/default/intership/listdata"+dataString;
        }else if(typetab != '' && typetab == 'lawyer' ){
        url = "<?php echo $this->BaseUrl?>/default/lawyer/listdata"+dataString;
        }else if(typetab != '' && typetab == 'reward'){
        url = "<?php echo $this->BaseUrl?>/default/customersreward/listdata"+dataString;
        }else if(typetab != '' && typetab == 'member'){
        url = "<?php echo $this->BaseUrl?>/default/fee/listdata"+dataString;
        }else if(typetab != '' && typetab == 'training'){
        url = "<?php echo $this->BaseUrl?>/default/trainingmanagement/listdata"+dataString;
        }
        $.ajax({
            type: "GET",
            url: url,
            //data: dataString,
            dataType: 'json',
            cache: false,
            success: function(html)
            {   
                if(typetab != '' && typetab == 'intership'){
                    var result ='';
                    for(var i = 0; i < html.length; i++) {
                        var obj = html[i]; 
                        var dottapsu = obj.inter_number_name != null ? obj.inter_number_name : '';                      
                        result+='<div class="row-fluid"><div class="span6"> Ngày đăng ký tập sự: '+obj.inter_regis_date+'</div><div class="span6">Đợt tập sự: '+dottapsu+'</div></div>';
                        result+='<div class="row-fluid"><div class="span6"> Thời gian tập sự (tháng): '+obj.duration+'</div><div class="span6">Địa điểm tập sự: '+obj.intership_address+'</div></div>';
                        result+='<div class="row-fluid"><div class="span6"> TCHN Tập Sự (nếu có): '+obj.organ_name+'</div></div>';
                   
                    }
                    $(".intership").empty();
                    $(".intership").append(result);
                   
                }else if(typetab != '' && typetab == 'lawyer' ){
                    for(var i = 0; i < html.length; i++) {
                        var obj = html[i];
                        $("#cus_lawyer_number").html(obj.cus_lawyer_number);
                        $("#cus_date_lawyer_number").html(obj.cus_date_lawyer_number);
                        $("#law_certfication_no").html(obj.law_certfication_no);
                        $("#law_certification_createdate").html(obj.law_certification_createdate);                        
                        $("#law_joining_number").html(obj.law_joining_number);
                        $("#act_name").html(obj.act_name);                        
                    }
                   

                }else if(typetab != '' && typetab == 'reward'){
                        
                    var result ='';
                    for(var i = 0; i < html.length; i++) {
                        var obj = html[i];               
                        if(obj.type == "Kỷ luật") {
                            result+='<div class="row-fluid">'+
                             '<div class="span4">'+
                                 'Ngày kỉ luật: '+obj.discipline_date+
                             '</div>'+
                           '<div class="span4">'+
                                'Hình thức: '+ 'Kỉ luật' + 
                            '</div>'+
                            '<div class="span4">'+
                               'Lý do:'+obj.discipline_reason+
                            '</div>'+
                        '</div>';  
                        }else{
                            result+='<div class="row-fluid">'+
                             '<div class="span4">'+
                                 'Ngày khen thưởng: '+ obj.reward_date +
                             '</div>'+
                           '<div class="span4">'+
                                'Hình thức: '+ 'Khen thưởng' + 
                            '</div>'+
                            '<div class="span4">'+
                               'Lý do:'+ obj.reward_reason +
                            '</div>'+
                        '</div>';  
                        }  
                     
                    
                    }
                    $(".reward").empty();
                    $(".reward").append(result);                 
                }else if(typetab != '' && typetab == 'member'){
                    var result ='';
                    for(var i = 0; i < html.length; i++) {
                        var obj = html[i]; 
                        //var dottapsu = obj.inter_number_name != null ? obj.inter_number_name : '';                      
                        result+='<div class="row-fluid"><div class="span6"> Ngày đóng phí thành viên: '+obj.payment_lawyer_off_created_date+'</div><div class="span6">Số biên nhận: '+obj.payment_lawyer_off_code+'</div></div>';
                        result+='<div class="row-fluid"><div class="span6"> Tháng bắt đầu : '+obj.startedmonth+'</div><div class="span6">Tháng kết thúc : '+obj.endmonth+'</div></div>';
                        result+='<div class="row-fluid"><div class="span6"> Tổng số tháng : '+obj.month+'</div></div>';
                   
                    }
                    $(".member").empty();
                    $(".member").append(result);
                   
                }else if(typetab != '' && typetab == 'training'){
                    var result ='';
                    for(var i = 0; i < html.length; i++) {
                        var obj = html[i]; 
                        //var dottapsu = obj.inter_number_name != null ? obj.inter_number_name : '';                      
                        //result+='<div class="row-fluid"><div class="span6"> Ngày :'+obj.inter_regis_date+'</div><div class="span6">Đợt tập sự:'+dottapsu+'</div></div>';
                        result+='<div class="row-fluid"><div class="span6"> Tham gia bồi dưỡng đợt: '+obj.cat_train_number+'</div><div class="span6">Địa điểm bồi dưỡng: '+obj.cat_train_address+'</div></div>';
                        //result+='<div class="row-fluid"><div class="span6"> TCHN Tập Sự (nếu có):'+obj.organ_name+'</div></div>';
                   
                    }
                    $(".training").empty();
                    $(".training").append(result);
                   
                }                
            }
        });
    }
    return false;   
}

function searchData(searchbox,dataString){
    if(searchbox ==''){
            $("#display-content-search-global").html('');
            //load = true;
        } else
        {
            $.ajax({
                type: "POST",
                url: "<?php echo $this->BaseUrl?>/default/customers/search/",
                data: dataString,
                cache: false,
                success: function(html)
                {   
                  //$("#display-content-search-global").html('');
                  //console.log(html.length);
                  $("#display-content-search-global").html(html);                  
                }
            });
            //load = true
        }
  }  
</script>

<div id="content">
    <div id="content-header">
        <div id="breadcrumb"> <a href="" title="Trang chủ" class="tip-bottom"><i class="icon-home"></i></a> <a href="#" class="current">Lý lịch luật sư</a> </div>
  
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <div class="widget-box">
                    <div class="widget-title">
                        <span class="icon">
                            <i class="icon-th-list"></i>
                        </span>
                        <h5>Lý lịch luật sư</h5>
                    </div>
                    <div class="widget-content">
                        <div class="row-fluid">
                            <div class="span6">
                                <div class="control-group">
                                    <div class="controls">
                                        Họ và tên: <span id="cus_firstname"></span>
                                    </div>
                                </div>
                                
                                <!-- <div class="control-group">
                                    <div class="controls">
                                        Tên: <span id="cus_lastname"></span>
                                    </div>
                                </div>                                 -->
                                <div class="control-group">
                                    <div class="controls">
                                        Tên thường gọi:
                                    </div>    
                                </div>   
                                <div class="control-group">
                                    <div class="controls">
                                        Sinh ngày: <span id="cus_birthday"></span>
                                    </div>
                                </div>
                                <div class="control-group">    
                                    <div class="span6">
                                        Nơi Sinh: <span id="city_name"></span>
                                    </div>
                                </div>  
                                <!-- <div class="control-group">
                                    <div class="span6">
                                        Nam/Nữ: <span id="cus_sex"></span>
                                    </div>
                                </div>                     -->
                            </div>
                            <div class="span6">
                                <div style="margin-left:33%;">                                  
                                    <img id="image-review" src="<?php echo $this->BaseUrl?>/files/images/photo.jpg" class="img-thumbnail img-responsive" width="120" height="336">
                                </div>                               
                            </div>
                        </div>                

                        <div class="row-fluid">
                            <div class="span6">
                                Chứng minh nhân dân số: <span id="cus_identity_card"></span>
                            </div>
                            <div class="span6">
                                Tên đăng nhập: <span id="cus_username"></span>
                            </div>
                        </div> 

                         <div class="row-fluid">
                            <div class="span6">
                                Nơi cấp: <span id="cus_identity_place"></span>
                            </div>
                            <div class="span6">
                                Dân tộc: <span id="cus_nation"></span>
                            </div>
                        </div>                          

                        <div class="row-fluid">
                            <div class="span6">                           
                                Ngày cấp CMND: <span id="cus_identity_date"></span>
                            </div>
                            <div class="span6">
                                Tôn giáo: <span id="cus_religion"></span>
                            </div>
                        </div> 

                        <div class="row-fluid">
                            <div class="span6">                           
                                Giới tính: <span id="cus_sex"></span>
                            </div>
                            <div class="span6">
                                Trình độ học vấn: <span id="cus_educations"></span>
                            </div>
                        </div> 

                        <div class="row-fluid">
                            <div class="span6">                           
                                Email: <span id="cus_email"></span>
                            </div>
                            <div class="span6">
                                Trình độ ngoại ngữ: <span id="cus_language_level"></span>
                            </div>
                        </div> 

                         <div class="row-fluid">
                            <div class="span6">
                            Số điện thoại (di động): <span id="cus_cellphone"></span>
                            </div>
                            <div class="span6">
                                Số điện thoại nhà riêng: <span id="cus_homephone"></span>
                            </div>
                        </div>       

                         <div class="row-fluid">
                            <div class="span12">
                            Địa chỉ thường trú: <span id="cus_address_resident"></span>
                            </div>
                        </div>  

                        <div class="row-fluid">
                            <div class="span12">
                            Nơi ở hiện tại: <span id="cus_address_resident_now"></span>
                            </div>
                        </div>             
                        
                        <div class="row-fluid">
                            <div class="span12">
                            Ngày vào Đoàn Thanh Niên Cộng sản Việt Nam ( dự bị): <span id="cus_joining_communist_youth"></span>
                            </div>
                        </div>  

                        <div class="row-fluid">
                            <div class="span12">
                            Ngày kết nạp và Đảng Cộng sản Việt Nam ( dự bị): <span id="cus_joining_communist_prepare"></span>
                            </div>
                        </div>   

                        <div class="row-fluid">
                            <div class="span12">
                            Ngày kết nạp và Đảng Cộng sản Việt Nam (chính thức): <span id="cus_joining_communist"></span>
                            </div>
                        </div>     

                        <div class="row-fluid">
                            <div class="span12">
                                <span id="cus_member"></span>
                            </div>
                        </div>            

                    </div>
                </div>
            </div>
        </div>
       
        <div class="row-fluid">
            <div class="span12">
                <div class="widget-box">
                    <div class="widget-title">
                        <span class="icon">
                            <i class="icon-th-list"></i>
                        </span>
                        <h5>Thông tin gia nhập</h5>
                    </div>
                    <div class="widget-content">
                        <div class="row-fluid">
                            <div class="span6">
                                Số thẻ luật sư: <span id="cus_lawyer_number"></span>
                            </div>
                            <div class="span6">
                                Ngày cấp thẻ LS: <span id="cus_date_lawyer_number"></span>
                            </div>
                        </div>  

                        <div class="row-fluid">
                            <div class="span6">
                                Số chứng chỉ hành nghề: <span id="law_certfication_no"></span>
                            </div>
                            <div class="span6">
                               Ngày cấp CCHN: <span id="law_certification_createdate"></span>
                            </div>
                        </div>  

                        <div class="row-fluid">
                            <div class="span6">
                                Đợt gia nhập: <span id="law_joining_number"></span>
                            </div>
                            <div class="span6">
                               Tổ chức: <span id="organ_name"> Đoàn Luật Sư Thành Phố Hồ Chí Minh</span>
                            </div>
                            <!-- <div class="span6">
                               Tổ chức ĐLS Tỉnh: <span id="organ_name"> Đoàn Luật Sư Thành Phố Hồ Chí Minh</span>
                            </div> -->
                        </div>            
                      
                    </div>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <div class="widget-box">
                    <div class="widget-title">
                        <span class="icon">
                            <i class="icon-th-list"></i>
                        </span>
                        <h5>Thông tin tập sự</h5>
                    </div>
                    <div class="widget-content intership">
                            <!-- Content intership-->                                   
                    </div>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <div class="widget-box">
                    <div class="widget-title">
                        <span class="icon">
                            <i class="icon-th-list"></i>
                        </span>
                        <h5>Thông tin tham gia bồi dưỡng</h5>
                    </div>
                    <div class="widget-content training">
                       
                    </div>
                </div>
            </div>
        </div> 
        <div class="row-fluid">
            <div class="span12">
                <div class="widget-box">
                    <div class="widget-title">
                        <span class="icon">
                            <i class="icon-th-list"></i>
                        </span>
                        <h5>Thông tin khen thưởng kỷ luật</h5>
                    </div>
                    <div class="widget-content reward">
                       
                    </div>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <div class="widget-box">
                    <div class="widget-title">
                        <span class="icon">
                            <i class="icon-th-list"></i>
                        </span>
                        <h5>Thông tin đóng phí thành viên</h5>
                    </div>
                    <div class="widget-content member">
                       
                    </div>
                </div>
            </div>
        </div>               
    </div>  
</div>    