<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1">
<style>
body {
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
    background-color: #FAFAFA;
    font: 12pt "Tahoma";
}
* {
    box-sizing: border-box;
    -moz-box-sizing: border-box;
}
.page {
    width: 210mm;
    min-height: 297mm;
    padding: 20mm;
    margin: 10mm auto;
    border: 1px #D3D3D3 solid;
    border-radius: 5px;
    background: white;
    box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
}
.subpage {
    padding: 1cm;
    border: 5px red solid;
    height: 257mm;
    outline: 2cm #FFEAEA solid;
}

@page {
    size: A4;
    margin: 0;
}
@media print {
    html, body {
        width: 210mm;
        height: 297mm;        
    }
    .page {
        margin: 0;
        border: initial;
        border-radius: initial;
        width: initial;
        min-height: initial;
        box-shadow: initial;
        background: initial;
        page-break-after: always;
    }
}

button {
    width:100px;
    height: 24px;
}
.header {
    overflow:hidden;
}
.logo {
    /*background-color:#FFFFFF;*/
    text-align:center;
    float:left;
}
.company {
    /*padding-top:24px;*/
    text-transform:uppercase;
    background-color:#FFFFFF;
    text-align:right;
    float:right;
    font-size:16px;
}
.title {
    text-align:center;
    position:relative;
    color:#0000FF;
    font-size: 24px;
    top:1px;
}
.footer-left {
    text-align:center;
    text-transform:uppercase;
    padding-top:24px;
    position:relative;
    height: 150px;
    width:50%;
    color:#000;
    float:left;
    font-size: 12px;
    bottom:1px;
}
.footer-right {
    text-align:center;
    text-transform:uppercase;
    padding-top:24px;
    position:relative;
    height: 150px;
    width:50%;
    color:#000;
    font-size: 12px;
    float:right;
    bottom:1px;
}


</style>
<body >
<div id="page" class="page">
    <div class="header">
        <div class="logo">ĐOÀN LUẬT SƯ <br/>
         THÀNH PHỐ HỒ CHÍ MINH<br/>
         ----oOo----
         </div>
        <div class="company">Số : <?php echo $this->paymentlawyertrainingofflinedata['payment_training_off_code']; ?> </div>
    </div>
  <br/>
  <div class="title">
        BIÊN NHẬN
        <br/>
        *****
  </div>
  <br/>
  <div class="content">
    <p>Nhận của : <strong>Luật Sư <span style="text-transform: uppercase;"><?php echo $this->paymentlawyertrainingofflinedata['cus_lastname'].' '.$this->paymentlawyertrainingofflinedata['cus_firstname'] ?></span></strong></p>
    <p>Năm sinh : <strong><span style="text-transform: uppercase;"><?php echo date('Y', strtotime($this->paymentlawyertrainingofflinedata['cus_birthday'])); ?><span></strong> Số thẻ <strong><?php echo $this->paymentlawyertrainingofflinedata['cus_lawyer_number'] ?></strong> Ngày cấp : <strong><span style="text-transform: uppercase;"><?php echo date('d/m/y', strtotime($this->paymentlawyertrainingofflinedata['law_code_createdate']));  ?><span></strong></p>
    <p>Lý do thu : <?php echo $this->paymentlawyertrainingofflinedata['cat_train_name']; ?>, <?php echo $this->paymentlawyertrainingofflinedata['cat_train_number']; ?> , <span style="text-decoration: underline;"><?php echo $this->paymentlawyertrainingofflinedata['name'].' '.date('d/m/y', strtotime($this->paymentlawyertrainingofflinedata['payment_training_off_created_date'])) ?></span></p>
    <p>Số tiền : <strong><?php echo $this->paymentlawyertrainingofflinedata['amount']; ?></strong></p>
    <!-- <p>(Bằng chữ : <strong>hai trăm năm mươi ngàn đồng.)</strong></p> -->

  </div>
  
  <div class="footer-left"> <br/>
    Người nộp </div>
  <div class="footer-right"> TP Hồ Chí Minh, Ngày <?php echo date('d', strtotime($this->paymentlawyertrainingofflinedata['payment_training_off_created_date'])) ?> tháng <?php echo date('m', strtotime($this->paymentlawyertrainingofflinedata['payment_training_off_created_date'])) ?> năm <?php echo date('Y', strtotime($this->paymentlawyertrainingofflinedata['payment_training_off_created_date'])) ?><br/>
    Người nhận 
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    Lê Thị Hòa  </div>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <p><span style="text-decoration: underline;"> Thời gian :</span> <?php echo $this->paymentlawyertrainingofflinedata['cat_train_fromdate']; ?> </p>
    <p><span style="text-decoration: underline;">Địa điểm: </span> <?php echo $this->paymentlawyertrainingofflinedata['cat_train_address']; ?></p>
</div>

</body>

</head>



